### ISSUE TITLE
Makefile missing uninstall

### ISSUE THREAD

**Issue by forthrin** [htacg/tidy-html5#100]
There is no "uninstall" target in the Makefile.

Particularly annoying because installation fails on OS X (see previous Issue), scattering partially installed files in /usr/local which I now have to clean up by hand.

**Comment by aristidesfl** [comment]
+1

**Comment by geoffmcl** [comment]
As you may know the current development branch is develop-500
$ git checkout develop-500
and all issues can only be against this branch for the moment...

It uses cmake for configuration and generate the Makefile files... 

And adding an uninstall target is certainly still on the list of things to be done...

**Comment by eric-brechemier** [comment]
+1

For reference:

Can I do "make uninstall" with CMake?
http://www.cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F

There is a step by step explanation on how to include the uninstall target in the project, and a turnaround for users when the uninstall target is not provided:

`xargs rm < install_manifest.txt`

**Comment by geoffmcl** [comment]
@forthrin, @LudovicRousseau, @aristidesfl, @eric-brechemier have looked carefully at the Wiki/CMake_FAQ, but it does seem a lot for little gain ;=().

First as pointed out, building and installing from source has a simple way to achieve this, namely the `xargs rm < install_manifest.txt` for unix/MAC systems. And for windows, if an install is done, then again this files lists what needs to be deleted.

Second, others who install tidy using the DEB/RPM packages have dpkg -r or -P package, or selection in say the Synaptic Package Manager. And using the EXE/MSI windows installer, does include an uninstall, as normal, in Control Panel - Programs and Features...

So it seems unnecessary to provide a 'make uninstall' target. And hope any build/install problems mentioned in Issue #99 have now been fixed.

Also note the latest code is now in the master branch, the default, as we head towards a 5.0.0 release - `$ git checkout master; $ git pull`

I'll close this issue for now, but feel free to re-open, or open other issues. Thanks for reporting...
