### ISSUE TITLE
Build and install depency list

### ISSUE THREAD

**Issue by korjavin** [htacg/tidy-html5#101]
Looks like package xsltproc is needed for installation.

**Comment by geoffmcl** [comment]
As you may know the current development branch is develop-500
$ git checkout develop-500
and issue can only be against this branch...

This branch has a dependency on cmake, and little else at present... Try it out...

**Comment by balthisar** [comment]
I will close this as cmake definitely isn't using xsltproc, although I still wonder how the man pages are being generated....

**Comment by eric-brechemier** [comment]
xsltproc is used in the script `build/documentation/build_docs.sh` to generate quickref.html and tidy.1 (man) from the XML output of `tidy5 -xml-config` and `tidy5 -xml-help`.

**Comment by balthisar** [comment]
And it will probably go back into cmake, too. We'll look at a solution that allows it to work (without the xslt) if xsltproc isn't found.

I'll re-open this and tag it.

**Comment by geoffmcl** [comment]
@korjavin, @baptistelabat, @eric-brechemier, this has now been fully added to the cmake process, and only if xsltproc is found will the man page be generated. And cmake will issue a WARNING if in UNIX and xsltproc is NOT found. Without it no man page can be generated.

Widows on the other hand uses a completely different set of tools, sources, and output to generate 'help' files, but these are usually only for GUI apps, not command line tools, so nothing to do for windows a this time.

And note the current stable source is in the master branch, as we head towards a 5.0.0 release - `$ git checkout master; $ git pull`.

So I'll close this for now, but feel free to re-open, or open other issues. Thanks for reporting...
