### ISSUE TITLE
The type attribute of the ol element is allowed in the actual HTML, but tidy-html5 does not allow it

### ISSUE THREAD

**Issue by ncaq** [htacg/tidy-html5#1012]
If the ol element has a type attribute, tidy-html5 will issue a warning.

~~~html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <title>ol</title>
  </head>
  <body>
    <ol type="i">
      <li>hoge</li>
    </ol>
  </body>
</html>
~~~

~~~console
$ tidy ol-type.html
line 8 column 5 - Warning: <ol> attribute "type" not allowed for HTML5
Info: Document content looks like HTML5
Tidy found 1 warning and 0 errors!

<!DOCTYPE html>
<html lang="ja">
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Linux version 5.8.0">
<meta charset="utf-8">
<title>ol</title>
</head>
<body>
<ol type="i">
<li>hoge</li>
</ol>
</body>
</html>

About HTML Tidy: https://github.com/htacg/tidy-html5
Bug reports and comments: https://github.com/htacg/tidy-html5/issues
Official mailing list: https://lists.w3.org/Archives/Public/public-htacg/
Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
Validate your HTML documents: http://validator.w3.org/nu/
Lobby your company to join the W3C: http://www.w3.org/Consortium

Do you speak a language other than English, or a different variant of
English? Consider helping us to localize HTML Tidy. For details please see
https://github.com/htacg/tidy-html5/blob/master/README/LOCALIZE.md
~~~

~~~console
$ tidy --version
HTML Tidy for Linux version 5.8.0
~~~

I checked and found that the source code defines that the type attribute does not exist in HTML5.

<https://github.com/htacg/tidy-html5/blob/2d15699ccf1564d11e764fb955e83c64d963d5ad/src/attrdict.c#L2300>

However, I actually consulted the HTML standards document and found that the ol element does have a type attribute.

<https://html.spec.whatwg.org/multipage/grouping-content.html#the-ol-element>

The type attribute of the ol element seems to have been restored as follows.

* [9798 – The type attribute on `<ol>` and `<ul>` is semantic and should be permitted](https://www.w3.org/Bugs/Public/show_bug.cgi?id=9798)
* [[ac] (2) Reintroduce `<ol type>` as conforming. · whatwg/html@4e3753d](https://github.com/whatwg/html/commit/4e3753d88a09243914e190e81036e12e6a1495b4)

Is this a bug?

Even if it is not a bug, I would like to optionally disable this warning only because Pandoc outputs HTML of this format.

**Comment by ip1981** [comment]
Workaround might be using `--mute MISMATCHED_ATTRIBUTE_WARN`

P. S. Plus testing exit code: 1 for warnings, 2 for errors

**Comment by ncaq** [comment]
Yes, I can use `--mute MISMATCHED_ATTRIBUTE_WARN`.
Thank you.
However, I want to leave the warnings for the other attributes checked and have it work correctly.

**Comment by oalders** [comment]
Would it be possible to get a new release which includes this change?

**Comment by balthisar** [comment]
Sorry, with Geoff’s absence, it’s been hard to keep up. Give me a couple of weeks, and I’ll see if I can consolidate the current PR’s and generate a formal release.

**Comment by oalders** [comment]
Thank you so much @balthisar and no hurry on my end. I imagine there's a lot of work involved. It's very much appreciated. 😄

**Comment by jidanni** [comment]
Well, with the last release of tidy being in 2021, no wonder bug reports will never cease despite the problem being fixed upstream.

https://github.com/jgm/pandoc/issues/11324#event-21388299669
