### ISSUE TITLE
“Warning: trimming empty <dd>” results in invalid output

### ISSUE THREAD

**Issue by andersk** [htacg/tidy-html5#103]
When given a document with an empty `<dd></dd>` element, tidy-html5 reports:
`line 9 column 1 - Warning: trimming empty <dd>`
and removes the `<dd></dd>`.  This causes a validation error on other validators, because HTML5 requires each `<dt>` to be followed by at least one `<dd>`.

Test case:

``` html
<!DOCTYPE html>
<html>
<head>
<title>Test</title>
</head>
<body>
<dl>
<dt>foo</dt>
<dd></dd>
</dl>
</body>
</html>
```

**Comment by balthisar** [comment]
@nickbuddendotcom, it looks like the develop-500 branch has solved this issue. If that's not the case, would you please open a separate issue?

@andersk, I'll tag this for 5.0.0 and see if I can't get to the bottom of it in time for release.

**Comment by balthisar** [comment]
Fixed in develop-500. I will close this. Please re-open it if troubles persist.
