### ISSUE TITLE
Issue with =

### ISSUE THREAD

**Issue by jonathan-s** [htacg/tidy-html5#105]
`<div ="nav nav-tabs"></div>`

HTML Tidy turned this into `<div nav=""></div>` 
If it should turn anything to something default it should be `<div class="nav nav-tabs"></div> `

**Comment by geoffmcl** [comment]
Thanks for the post. Researched quite deeply into this... naturally in the develop-500 branch...

On finding '=' while searching for div attributes tidy clearly indicates this with the warning -
Warning: <div> unexpected "=", expected attribute name

And the next thing found is the '"', and again tidy squawks
Warning: <div> unexpected or duplicate quote mark

So even IF tidy remembered it got an '="', which could be taken as an indication the the attribute name was missing, div supports some 16 global attributes, one of which is class, and perhaps some 80 others attributes... 

How could tidy 'decide' that the html writer meant class in this case, as opposed to the some 95 others??? Even as a default choice...

And what happens afterwards in this BAD case in anyone's guess... and while I too may not like the fix-ups and output after this mistake, I do not see anything I can do about that!

To me Tidy does some great fix-ups, but can not read minds ;=))

No, I think we have to reject this as a feature request... just too impossible for tidy to GUESS... and do not think it is a bug!

Will leave it open for a while in case others want to try something... Maybe need another label like 'Feature Rejected', always meaning 'at least for now' ;=))

Regards,
Geoff.

**Comment by balthisar** [comment]
I agree that the warning is enough. Since no one else agreed to take it, I'll close this issue now.
