### ISSUE TITLE
Wrong version information and lack of version tag on repository

### ISSUE THREAD

**Issue by marcinant** [htacg/tidy-html5#106]
Could you please provide some proper versioning system on tidy?

Currently tidy -version returns:
```
HTML Tidy for HTML5 (experimental) for Linux https://github.com/w3c/tidy-html5/tree/c63cc39
```
This is not compatible with any versioning system.
It's impossible to detect which tidy is new and which is an old one.

Although I understand that this repository is experimental, it could be nice to put some intial tag on repo which could allow to download tidy sources as tar.gz or zip

**Comment by geoffmcl** [comment]
Please checkout develop-500 branch, and build, test if you get a chance...
Does this now 'conform' reasonably well with the usual --version output?
When this branch is 'tested' it will eventually be merged into the master branch, and of course the word 'experimental' will be dropped...

**Comment by balthisar** [comment]
I will close this. I know that my #148 duped it, but there's some other discussion there.
