### ISSUE TITLE
Hardcoded gcc in makefiles fails when no gcc installed

### ISSUE THREAD

**Issue by apeiron** [htacg/tidy-html5#116]
Just tried building tidy-html5 on FreeBSD 10 (which ships clang, not gcc) and it fails because the makefile is hardcoded to assume gcc is installed. The POSIX standard says that systems must ship `cc`, so the correct approach is to call `cc` and let the OS call the correct compiler with that.

**Comment by geoffmcl** [comment]
The latest development branch, develop-500, no longer has any hardcoded make files... it uses cmake to generate the Makefile...
It would be appreciated if you could checkout develop-500 branch, build and test, and hopefully confirm this issue can be closed... Thanks...

**Comment by apeiron** [comment]
The build now uses the POSIX standard `cc`, thank you!

**Comment by geoffmcl** [comment]
Glad it worked out for you... and thanks for closing this...

Hope you get a chance to STRONGLY test Tidy5, and report any BUGS... We do want to head for a new release soonest... Thanks...
