### ISSUE TITLE
Tidy doesn't support macros; garbage output when recording macro

### ISSUE THREAD

**Issue by Acecool** [htacg/tidy-html5#124]
Record macro, choose tidy config 1, stop recording, playback. GARBAGE.

Nothing I change works. I need to use a macro, or not use this at all because of this garbage: "Tidy never outputs tabs. "

**Comment by balthisar** [comment]
What is your environment? Tidy has no macro features. What is your OS and what are you using for macros?

**Comment by Acecool** [comment]
Notepad++ has macro features to combine common patterns into one tool / button which is what I used to "record the macro" and "play the macro" of me clicking tidy config 1.

Windows 7 64, 8gb, 3TB

**Comment by geoffmcl** [comment]
So this seems a bug in Notepad++, which I use a lot in the same OS, but have not tried the macro function...
I think you are right that tidy never outputs tabs, and has always been like this...
You will need to explain more what is the potential BUG in develop-500 branch of tidy5...
