### ISSUE TITLE
Does not properly indent <style> / CSS area

### ISSUE THREAD

**Issue by Acecool** [htacg/tidy-html5#126]
It properly indents everything, except the CSS style area, they need to be tabbed in 3 times for the page to line up properly.

I've looked through ALL of the settings, modified the config; no go.

**Comment by geoffmcl** [comment]
You mentioned this in #127...
Can you supply a small html test sample that demonstrates the problem against the develop-500 branch... Thanks...

**Comment by balthisar** [comment]
Same as #127, it seems. When setting indent to auto, result is:
~~~~~
<!DOCTYPE html>

<html>
<head>

  <style type="text/css">
p { font-size: 12pt; }
  </style>

  <title>Test</title>
  <style type="text/css">
div.c2 {text-align: center}
  p.c1 {color: red}
  </style>
</head>

<body>
  <p class="c1">Hello, world.</p>

  <div class="c2">
    I'm in the middle
  </div>
</body>
</html>
~~~~~

Given the input #27:
~~~
<!DOCTYPE html>
<html>
<head>
<style type="text/css">
p { font-size: 12pt; }
</style>
<title>Test</title>
</head>
<body>
<p style="color: red">Hello, world.</p>
<center>I'm in the middle</center>
</body>
</html>
~~~

**Comment by geoffmcl** [comment]
Found a FIX, but it seems it undoes what is stated in the comments -
    /* use zero indent here, see http://tidy.sf.net/bug/729972 */

The little fix - changing
   TY_(PFlushLine)(doc, 0);
to
   TY_(PFlushLine)(doc, indent);

As this issue states, using a config -c --indent yes, the previous output 1 was -
````
  <style type="text/css">
p { font-size: 12pt; }
  </style>
````

Now the output 2 is -
````
  <style type="text/css">
  p { font-size: 12pt; }
  </style>
````

Looking carefully at the bug 728872, it seems tidy did at some time indent it per the above output 2, 
but then some time later, by the 2009 release, had reverted to output 1!

Anyway now NOT entirely fixed to my satisfaction, perhaps it should add one more indent, but hopefully an improvement.

As usual bumped the version point to 6 for this fix.

**Comment by balthisar** [comment]
Since you say it's an improvement but aren't entirely satisfied I'll leave this open as a feature request for the future.

**Comment by geoffmcl** [comment]
Have experimented some more but can not get the indent increased at this time.

But am now satisfied that the current indent lines up correctly, so closing for now... to be opened again if someone find a fuller fix...
