### ISSUE TITLE
parallel make fails with mkdir: ./obj: File exists

### ISSUE THREAD

**Issue by LudovicRousseau** [htacg/tidy-html5#134]
I have a multicore processor so I use ``make -j9`` to benefit from GNU make parallelism.
But that fails with:
```
$ make -j2
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C build/gmake
if [ ! -d ./obj ]; then mkdir ./obj; fi
if [ ! -d ./obj ]; then mkdir ./obj; fi
mkdir: ./obj: File exists
gcc -g -pedantic -Wall -I ../../include -Wunused-parameter  -D_DEBUG=1 -D_MSC_VER=1400 -o obj/access.o -c ../../src/access.c
make[1]: *** [obj/attrs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [bin/tidy] Error 2
```

The problem is that the Makefile tries to create a ``obj`` directory before each compilation.

Using autoconf + automake would solve that problem and also https://github.com/w3c/tidy-html5/issues/61, https://github.com/w3c/tidy-html5/issues/79, https://github.com/w3c/tidy-html5/issues/100, https://github.com/w3c/tidy-html5/issues/116

**Comment by apeiron** [comment]
Can we please not use @ to hide the build commands? It makes it really difficult to understand what's going on when the build fails, which is the only time you're going to be paying attention anyway.

**Comment by geoffmcl** [comment]
The latest development branch, develop-500 now only uses cmake...
$ git pull and git checkout develop-500
Would really appreciate you building this branch, and reporting any problems...

**Comment by LudovicRousseau** [comment]
develop-500: The build works for me on Mac OS X 10.9.

**Comment by geoffmcl** [comment]
Thank you for your quick test and report... Can we close this issue?

**Comment by balthisar** [comment]
Close, now using cmake in develop-500.
