### ISSUE TITLE
Announce: HTML Tidy Advocacy Community Group

### ISSUE THREAD

**Issue by balthisar** [htacg/tidy-html5#137]
Fellow HTML Tidy developers and implementors,

I've setup a [W3C Community Group](http://www.w3.org/community/about/) at W3C which is currently undergoing moderation before being enabled. I'd like to gage interest and solicit candidates for leadership roles for those that are interested.

Titled "HTML Tidy Advocacy Community Group" ("HTACG"; I suppose we could pronounce it "H-TASK"), once it passes moderation it requires the votes of four additional people to become active. In order to vote one requires a free account at W3C.

This is the description of the group that I have created:

> The HTML Tidy Advocacy Community Group ("HTACG") is dedicated to the continued support, development, and evolution of the HTML Tidy command line application and library.

>The Community in cooperation with the W3C aims to become the canonical release group for HTML Tidy, which has been without a stable, public release since 2008. The Community aspires to achieve the agreement and support of the original and current developers to this end.

>The Community will continue to develop HTML Tidy to adapt it to modern standards; to implement testing systems; and to implement robust build systems. The Community will also promote the continued relevance of HTML Tidy in modern software systems.

W3C indicates that the group would have access to W3C resources such as a repository, mailing list, blogspace, etc., but further indicates that we might have a githhub repository under the /w3c namespace which adds a lot of credibility.

Importantly the [FAQ](http://www.w3.org/community/about/faq/) indicates that the group gains credibility by being able to claim, "work happening at W3C."

If the group passes moderation and enough of us approve the Group then it will become active and we can decide on specific next steps.

In general some next steps that I could foresee:

- Develop a group charter (probably in a repo).
- Decide on commit/merge access.
- Determine a good code-base to start from.
- Determine just "who" is "who".

I'll edit this post when the proposed group exits moderation.

Although I've taken the initiative to start this group, I'm disclaiming all "ownership" over this group, and am not campaigning for the eventual "chairmanship" of the group.

I'm simply trying to promote a response to the current "this project is dead" way of life. HTML Tidy is only dead if there's no community to keep it alive. We should admit that the private forks, lack of response from this repository's owner, and relative obscurity of this particular repository in the entirely of the internet doesn't provide adequate tools to keep the project alive.

As such it's my hope that working with W3C provides a new legitimacy to the project that attracts added attention and relevancy.

* * *

Any thoughts?

* * *

Edit: link, so you don't have to find it buried in the thread: http://www.w3.org/community/groups/proposed/#htacg

**Comment by skynet** [comment]
Good luck! How do we join this group at W3C? Thanks.

**Comment by balthisar** [comment]
As soon as they release it from quarantine, I'll post it back on this thread.

In the meantime you can follow one of the links and register an account.

Hey, don't wish _me_ luck. Wish _us_ luck, because it seems we all have to do this together.

**Comment by petdance** [comment]
I'm interested in helping out, but don't understand the W3C ins & outs.  I'm glad to contribute time & code as soon as there's some direction.

**Comment by balthisar** [comment]
It looks like the proposed group is out of moderation and people can vote to approve the new group.

- http://www.w3.org/community/groups/proposed/#htacg

You don't have to understand W3C ins and outs; simply create a user account at W3C and then vote.

@petdance, I don't understand the ins and outs either, and it took quite a bit of research to discover and propose this (potential) solution. Luckily as a "community group" we'll be insulated from most of the internal workings of the W3C aside from the exposure and affiliation. There's still a lot to read up on, and I'm hoping there are enough of us (and attract more) so that we can gain some traction.

I want to reiterate that my objective is that this is not **my** project but becomes **our** project. If you want to read between the lines, I mean that I hope that I don't have to run the whole show, although I'm willing to commit extra-ordinary effort at the beginning (full time extra-ordinary effort isn't sustainable, I'm afraid).

**Comment by skynet** [comment]
Voted. "Once 5 or more people support the group it will be created."

**Comment by balthisar** [comment]
Update:
- I've reached out to @sideshowbarker via email in order to get his support.
- I've reached out Dave Raggett in an attempt to get his endorsement.

@skynet, even if we don't get this repo, I seem to think that we can get another repo in /w3c. We might start considering names. What happens if html6 ever reaches a draft stage? :-)

**Comment by jay** [comment]
I voted for this as well. sideshowbarker seems like the right guy to reach out to. Good luck guys.

**Comment by skynet** [comment]
@balthisar, I would make all possible attempts to wake up W3C. There are way too many support tickets opened here. This project needs to be brought back to life.

**Comment by sideshowbarker** [comment]
I suggest what'd be best at this point is for @balthisar or somebody to take the initiative of creating a new github org, called `tidy-html` or whatever. Then after that's been created, I can transfer the ownership of this repo over to that org. As far as I understand things, that will preserve the issues list, PRs, the Watch/Star/Forks info and of course the history for the repo.

**Comment by balthisar** [comment]
@sideshowbarker, did you receive an email from me today at your @w3.org address?

**Comment by sideshowbarker** [comment]
in reply to @balthisar 
> @sideshowbarker, did you receive an email from me today at your @w3.org address?

yeah I did, and I plan to respond, but my response is going be basically the same as what I just said here

**Comment by balthisar** [comment]
@sideshowbarker, thanks @skynet beat me to it, but I'm okay with that.
https://github.com/tidy-html

**Comment by skynet** [comment]
Or, even better: https://github.com/htacg/tidy-html
@balthisar - Feel free to take over either of these.

**Comment by balthisar** [comment]
Oh, yeah, that's a better idea (you're _fast_). It will fit in better with our W3C project. Let's use that one, especially in case we add side projects or something.

@sideshowbarker, I suggest that if you're available tomorrow night at this time, we can execute a transfer of ownership then. I'd rather assume any type of control until someone has a chance to object.

**Comment by sideshowbarker** [comment]
@balthisar I'll be around. Just ping me any time.

I'm happy to transfer ownership to whatever other github org—e.g., https://github.com/tidy-html or https://github.com/htacg. But to be clear there doesn't need to be a forked repo such as https://github.com/htacg/tidy-html existing under that org already. In fact there shouldn't be. Because the idea is what we move (transfer, not fork) this entire (upstream) repo/project over to that new org.

**Comment by skynet** [comment]
@sideshowbarker - removed forked repo. https://github.com/htacg

**Comment by balthisar** [comment]
@sideshowbarker, well, it's been about 24 hours and no one has objected. If you want to transfer ownership to me, I think it's fine. No hurry, it's about bedtime in these parts.

**Comment by sideshowbarker** [comment]
@balthisar The way github works, this repo needs to be transferred to another github org, not an individual. So please just let me know what org. https://github.com/htacg? And I need to (temporarily) be an admin of the receiving org in order for github to let me transfer the repo to it.

**Comment by balthisar** [comment]
Done, and at the correct repo. Thanks.

**Comment by sideshowbarker** [comment]
I'm getting an error message saying I don't have admin perms to the htacg org

**Comment by balthisar** [comment]
It shows as your invitation still pending -- did you accept it? You're assigned to the Owners group once accepted.

**Comment by sideshowbarker** [comment]
@balthisar I see that I could instead actually transfer it directly to you, except that you have a html5-tidy fork already, and it can't overwrite that.

**Comment by balthisar** [comment]
@sideshowbarker, I renamed it -- maybe that's enough.
You can either try to transfer it to me again or see if the htacg invitation worked.

**Comment by sideshowbarker** [comment]
Ok, done now. Please go ahead and remove me from the org. Then if anything further comes up that I can help with, please feel free to ping me and let me know.

**Comment by balthisar** [comment]
I don't think anyone would mind you staying on. You're a link in Tidy's history, after all.

Thanks for all your help, @sideshowbarker.

**Comment by skynet** [comment]
Good job, now let's start to address those 64 pending issues and 14 pull requests. Good luck, everyone!

**Comment by petdance** [comment]
1) Where is the new repo?  I can't tell from the thread where it is now.

2) Perhaps an overview of what needs to be done, other than "fix bugs", would be helpful to people who want to get involved.

**Comment by skynet** [comment]
You are already on it - check url above.

**Comment by sideshowbarker** [comment]
> Good job, now let's start to address those 64 pending issues and 14 pull requests. Good luck, everyone!

People might also want to look back at the list of bugs at http://sourceforge.net/p/tidy/bugs/?limit=250 and  feature requests at http://sourceforge.net/p/tidy/feature-requests/?limit=250

At the time back when I originally set up the github, I couldn't figure out any way to import any of those sourceforge issues into the github issue tracker. But maybe there's some tool around now to do it.

**Comment by petdance** [comment]
I converted from RT to GitHub a few years ago: http://perlbuzz.com/2012/01/parrot-tickets-now-converted-to-github.html  Transfering from one bug tracker to another is not just a simple "convert this to that".  There are undoubtedly impedance mismatches between SourceForge's data points and GitHub's.

**Comment by skynet** [comment]
There are only 141 such items on SF. We can try to close some of them in place, and manually transfer those that need further investigation and testing. More important is to actually address those tickets.

**Comment by skynet** [comment]
Actually, there's more to it ( on http://sourceforge.net/p/tidy/ )

- [ ] 222 feature requests
- [ ] 141 bugs
- [ ] 33 patches
- [ ] 22 user contributions
- [ ] 12 support requests

**Comment by skynet** [comment]
And we also need to address this pretty quick  - we just killed the documentation page: http://w3c.github.io/tidy-html5/

**Comment by skynet** [comment]
At least the repo links get "301 Moved Permanently" redirected from https://github.com/w3c/tidy-html5 to https://github.com/htacg/tidy-html5. Does anyone know how to redirect http://w3c.github.io/tidy-html5/ to htacg.github.io/tidy-html5/ ?

**Comment by sideshowbarker** [comment]
> Does anyone know how to redirect http://w3c.github.io/tidy-html5/ to htacg.github.io/tidy-html5/ 

I doubt there's any way to do it other than raising a github support request to ask if a github admin can do it.

**Comment by skynet** [comment]
I just did. Thank you.

**Comment by balthisar** [comment]
**everyone** and @sideshowbarker (by name), thank you all so much for your support in this.

There's still a lot to do. Even though this change brings us commit access, we still need one more vote to legitimize the project with the W3C. Please **register** (quick, free, and no spam) and then **vote** for the [W3C project](http://www.w3.org/community/groups/proposed/#htacg).

**Comment by balthisar** [comment]
I should create a wiki or something, but this thread still has a lot of attention, so I'll use it for now. If we get the HTACG W3C group approved, that will offer tools for discussion, too.
* * * *
As for the PR requests we should ensure that we use the regression testing scheme that's already in the library, or improve it before we willy-nilly before accepting PRs. We don't have to be in a hurry, and it's still possible to clone the project as-is and merge in individual PRs.

In fact, I've done this for a lot of the PR's already: https://github.com/balthisar/tidy-html5/tree/geoffmcl-restart

This actually involved a **lot** of manual work, so some of the PR commit history is lost, although I did specify the issue numbers in each commit. The problem is that so many people have issued PR's against the current base, the diffs keep accumulating making it impossible to auto-merge without all of the manual work.

My branch is @geoffmcl's as of November, with several PRs already merged in and commented. @geoffmcl made several changes without posting a PR, which is why I based off of his fork.

After testing the current master versus my fork, my I suggest rebasing the current master to my fork? This will make future PRs much more successful. (I'll also clean up some of the output strings that are specific to my use before adding).

I would also like to eliminate all of those trailing spaces. There are a few PRs where someone's editor stripped them all away making the diff absolutely huge. If we're going to rebase, now's a good time to nip that in the bud.

**Comment by balthisar** [comment]
> I just did (send a support request). Thank you.

@skynet, if that doesn't work, we could very kindly ask @sideshowbarker to re-create an empty project with that name, and a simple HTML meta redirect in the gh-pages. More ambitiously I suppose I could use the current gh-pages and generate a meta redirect from ALL of the old pages, but only 200 instead of 301.

**Comment by skynet** [comment]
I would probably build a new website + documentation.

**Comment by skynet** [comment]
Here's the answer from Github:

> GitHub Pages doesn't currently offer redirection from one subdomain to another. If you'd like to redirect from https://w3c.github.io/tidy-html5/ to your new site, the only way of doing this would be to add a `tidy-html5` directory inside the current `w3c.github.io` repo, containing an index.html file that does a redirect with either a meta tag or using JavaScript.

**Comment by petdance** [comment]
Seems that when the repo got moved, my push rights went away.  Don't know if this was intentional or not.

**Comment by skynet** [comment]
You got it, sorry for that! Permissions are not carried over from one organization to another when moving a repo.

**Comment by petdance** [comment]
I'm still not able to push: 

```
ERROR: Permission to htacg/tidy-html5.git denied to petdance.
fatal: Could not read from remote repository.

$ git info
origin  git@github.com:htacg/tidy-html5.git (fetch)
origin  git@github.com:htacg/tidy-html5.git (push)
```

**Comment by sideshowbarker** [comment]
> Here's the answer from Github:
> 
> GitHub Pages doesn't currently offer redirection from one subdomain to another. If you'd like to redirect from https://w3c.github.io/tidy-html5/ to your new site, the only way of doing this would be to add a tidy-html5 directory inside the current w3c.github.io repo, containing an index.html file that does a redirect with either a meta tag or using JavaScript.

Cool, thanks—I've gone ahead and set up the redirect: https://w3c.github.io/tidy-html5 and http://w3c.github.io/tidy-html5 now redirect to https://htacg.github.io/tidy-html5/

**Comment by skynet** [comment]
Thanks, @sideshowbarker 

@petdance - please check your keys. what are you trying to push.

**Comment by petdance** [comment]
I'll check later.  I'm starting a combination design doc and FAQ.

**Comment by balthisar** [comment]
@petdance, did you get anywhere on those? And how's your access?

I've created a /community repo. If you're willing to commit any in-progress docs there, myself and others are certainly willing to help out. I created it for that purpose and W3C HTAGC, too.

It might serve the secondary purpose of letting others know that the community is making some sort of progress.
