### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by gordio** [htacg/tidy-html5#139]
Before we start, need choice code style. I propose [Linux Coding Style](http://www.makelinux.net/books/lkd2/ch20lev1sec2)
But with exceptions. Line length in 80 symbols looks weird in 2015 with big displays. What you think?

I propose this style:
`astyle --mode=c --style=linux --indent=spaces=4 --unpad-paren --pad-header --pad-oper --suffix=none ./**/*.c ./**/*.h`

**Comment by skynet** [comment]
How does your suggestion aligns with existing coding style?

**Comment by geoffmcl** [comment]
Have replied to this at -
https://lists.w3.org/Archives/Public/public-htacg-contrib/2015Jan/0002.html
which is where I think this important discussion belongs... and hope we can close here...
Sorry for my first VERY LONG post...

**Comment by skynet** [comment]
Ok, will close. Thank you.
