### ISSUE TITLE
Add an option to preserve existing line breaks.

### ISSUE THREAD

**Issue by jyasskin** [htacg/tidy-html5#143]
I'm maintaining a document formatted approximately like:
```html
<p>
  Here is a sentence.
  Here is another sentence.
  Here is a long sentence with multiple clauses
  that doesn't fit in 100 columns.
</p>
```
I break lines at sentence boundaries to make the diff easier to read when I edit a sentence and change its length.

I'd like to run tidy-html5 on this document, but any option for `wrap` throws away the existing newlines and re-wraps the text (or joins it into a single line per element for `wrap==0`). It'd be nice to have some way to keep the existing line-breaking choices while still using tidy on the rest of the document.

**Comment by geoffmcl** [comment]
As you can read here -
http://www.htacg.org/tidy-html5/#preserve-indenting
this would be a tall order ;=))

Although I have often thought about this, I am afraid such a 'feature' is probably way into the future, if at all... but you never know...

**Comment by geoffmcl** [comment]
Since no more comments for over a month, am closing this for now...

But feel free to re-open, or open another issue... thanks...
