### ISSUE TITLE
Remove build date support in favor of semantic versioning

### ISSUE THREAD

**Issue by balthisar** [htacg/tidy-html5#148]
Remove build date support in favor of versioning.

**Comment by balthisar** [comment]
I made the changes and pushed this. `tidyReleaseDate()` is marked in comments as deprecated which should be picked up by doxygen. I didn't include a compiler attribute to flag warnings in the interests of compatibility with non-GCC-style compilers.

Also reverted `CMakeLists.txt` and removed the date macro. `version.h` still supports the macro in case we want to revert this behavior, but I've set the default date to Unix epoch for lack of a better idea. People that are counting on `tidyReleaseDate()` should be able to see that something is wrong when they see the date.

An alternative would be to use `tidyReleaseDate()` as an alias for `tidyLibraryVersion()` but I don't know if any current users have a use case for parsing dates that might be broken by returning a version string instead of a formatted date.

Forgot to mention in the comments that I cleaned up some strings while I was at it to avoid mentions of "experimental" and "this fork", etc., as we near 5.0.0.

I'll leave this issue open for discussion re: what to return from `tidyReleaseDate()`.

**Comment by balthisar** [comment]
If no one cares what `tidyReleaseDate()` returns (currently Unix epoch), then I will assume everyone is satisfied and close this issue.

I'll leave it open for a few more days and cross-post to the three lists...

Oh, I suggest that we add a deprecated flag to `tidyReleaseDate()`. This is simple for GCC-like compilers, but I'm unfamiliar with other compilers -- is there a generally recognized, cross-compiler flag available for this?

**Comment by geoffmcl** [comment]
@balthisar have never tried it myself but found this reference
http://stackoverflow.com/questions/295120/c-mark-as-deprecated

Will get around to trying it in MSVC and see what happens ;=))

````
#ifdef __GNUC__
#define DEPRECATED(func) func __attribute__ ((deprecated))
#elif defined(_MSC_VER)
#define DEPRECATED(func) __declspec(deprecated) func
#else
#pragma message("WARNING: You need to implement DEPRECATED for this compiler")
#define DEPRECATED(func) func
#endif
...
//don't use me any more
DEPRECATED(void OldFunc(int a, float b));
//use me instead
void NewFunc(int a, double b);
````

**Comment by geoffmcl** [comment]
See Issue #190 for comments on why this reversion to continuing support for `tidyReleaseDate()`

**Comment by geoffmcl** [comment]
For now continuing support for both version and date, although console tidy continues to only show only the version. Maybe the date could now also be added.

But no further comments for a few weeks so closing this for now...

Feel free to re-open, or post a new issue.
