### ISSUE TITLE
crash on inferred attribute value

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#149]
Testing a simple fragment case
````
<form name>
````
got a crash - segfault - config
show-body-only:yes
show-input:no
tidy-mark:no
show-info:no

**Comment by geoffmcl** [comment]
fixed in version 4.9.8

**Comment by balthisar** [comment]
Uh, oh, we'll have to use 4.9.9.1, 4.9.9.2, etc.

**Comment by geoffmcl** [comment]
You are kidding right?

You will note I am now at 4.9.10 ;=))
