### ISSUE TITLE
Support "picture" element

### ISSUE THREAD

**Issue by AlbertWiersch** [htacg/tidy-html5#151]
Would like to see support for picture element:
https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element
http://www.w3.org/html/wg/drafts/html/master/embedded-content.html#the-picture-element

Now it generates these warnings:
Warning: &lt;picture&gt; is not approved by W3C
Warning: missing &lt;/picture&gt; before &lt;source&gt;
Warning: inserting implicit &lt;picture&gt;

Example HTML:
&lt;picture&gt;
 &lt;source srcset="pear-desktop.jpeg" media="(min-width: 1281px)"&gt;
 &lt;source srcset="pear-tablet.jpeg" media="(min-width: 721px)"&gt;
 &lt;img src="pear-mobile.jpeg" alt="The pear is juicy."&gt;
&lt;/picture&gt;

**Comment by geoffmcl** [comment]
Thanks for the input, sample html, and links.

Seems tidy5 should support the picture element, and will see what can be done.

**Comment by geoffmcl** [comment]
@AlbertWiersch - Have added initial support for the picture element. Tidy now issues no warnings for the above html sample, as do the validators.

Also no warnings for #152, adding the srcset attribute to both picture and source. Also added the sizes attribute to picture.

TODO:
1. Check, verify the picture attribute list.
2. pprint to get closer to the above input lining.
3. check the VERS_ELEM_PICTURE. Is this element supported in more than html5?

Please pull develop-500 branch, version 4.9.12+, and if you get a chance, test and close these two issues. Thanks...

**Comment by AlbertWiersch** [comment]
Thanks! A quick test seems to indicate this issue is no more.
