### ISSUE TITLE
Support "srcset" attribute

### ISSUE THREAD

**Issue by AlbertWiersch** [htacg/tidy-html5#152]
Support "srcset" attribute, like for "source" element when used in "picture" and for "img" elements:
http://www.w3.org/html/wg/drafts/html/master/embedded-content.html#the-source-element-when-used-with-the-picture-element
http://www.w3.org/html/wg/drafts/html/master/embedded-content.html#attr-picture-source-srcset
https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element-when-used-with-the-picture-element
https://html.spec.whatwg.org/multipage/embedded-content.html#attr-picture-source-srcset

Tidy generates these messages:
Warning: &lt;img&gt; proprietary attribute "srcset"
Warning: &lt;source&gt; proprietary attribute "srcset"

Example HTML:
&lt;img class="maintitle" src="https://www.htmlvalidator.com/png/html-validator.png" srcset="https://www.htmlvalidator.com/png/html-validator-2x.png 2x" alt="Home" title="CSE HTML Validator at www.htmlvalidator.com" width="475" height="100"&gt;

&lt;picture&gt;
 &lt;source srcset="pear-desktop.jpeg" media="(min-width: 1281px)"&gt;
 &lt;source srcset="pear-tablet.jpeg" media="(min-width: 721px)"&gt;
 &lt;img src="pear-mobile.jpeg" alt="The pear is juicy."&gt;
&lt;/picture&gt;

**Comment by geoffmcl** [comment]
Thanks for the input, sample html, and links.

Certainly seems an img element should allow a srcset attribute. Will see what can be done.

**Comment by geoffmcl** [comment]
Have implemented initial support for 'srcset', and threw in 'sizes', attributes on the img element...

Please pull version 4.9.11, or later, from the develop-500 branch, and if you get a chance, test and report...

Thanks.

**Comment by AlbertWiersch** [comment]
Thanks! A quick test seems to indicate this issue is no more.
