### ISSUE TITLE
PageSpeed vs tidy-html5

### ISSUE THREAD

**Issue by skynet** [htacg/tidy-html5#157]
It would be interesting to position tidy-html5 in rapport to PageSpeed:

https://developers.google.com/speed/pagespeed/module

it is clear that for various other uses PageSpeed is not an option, but for HTML delivery using Nginx or Apache the only feature that I don't see is pretty printing HTML.

**Comment by balthisar** [comment]
It looks interesting, but without having to become a PageSpeed expert, what is it you're proposing here? Use Tidy as an output filter in order to pretty print?

**Comment by skynet** [comment]
What I suggested was to compare tidy-html5 to PageSpeed. What are some use-cases for tidy-html5? When you develop a product you need to have in mind a real specific need for your product, right?

**Comment by balthisar** [comment]
That's actually an excellent point. A lot of people have a lot of different use cases. In my case, for example, I use TidyLib in a GUI application that that adds a _lot_ of use cases beyond what Tidy was intended for.

We can start a use cases document in the community/ repo. I can probably roll it into the new webpage when it's ready.

**Comment by skynet** [comment]
Sounds like a plan, thank you!
