### ISSUE TITLE
building/installing develop-500 branch (ubuntu)

### ISSUE THREAD

**Issue by dkebler** [htacg/tidy-html5#159]
Anyone help me out?

Since master is now quite behind compiling/installing develop-500 branch seems necessary.  

I found this bash script (for ubuntu) in a gist and it made doing so for master branch trivial but it's not helpful for develop-500 as in there is no gnuauto folder within /build in this branch.

I need help with the line indicated ????
Will simply bringing across the complete /build folder from master solve this??? 
or need to use make use of /cmake which is in this branch.  In which case what is the equivalent call(s)

Wish I knew enough to do this myself without extensive time/learning....but alas no....just a lowly sass/html web designer trying to lint his htm5 :-(.

Once done this would be a very helpful gist in htacg account.

````
#!/bin/bash
# Check if user is root
if [ $(id -u) != "0" ]; then
    echo "Error: You must be root to run this script, please use root to install the software."
    exit 1
fi

# uncomment if not yet removed and/or installed
# apt-get remove libtidy-0.99-0 tidy 
# apt-get install git-core automake libtool checkinstall

mkdir /tmp/htmltidy
cd /tmp/htmltidy
# master branch
# git clone https://github.com/htacg/tidy-html5.git
#development branch
git clone -b develop-500 https://github.com/htacg/tidy-html5.git
cd tidy-html5

#This works for master branch
# sh build/gnuauto/setup.sh && ./configure --prefix=/usr && make
# This works for develop-500 branch
????????????????

checkinstall --pkgversion $(date +"%Y%m%dcvs-1")

#  if you don't want the debian, etc package afterinstall then uncomment
# rm /tmp/htmltidy -rf
`````

**Comment by geoffmcl** [comment]
Yes, the current development is ONLY in the develop-500 branch. We hope ot move this to master soon, but for the moment you MUST only be in the develop-500 branch.
$ git checkout develop-500

Now ALL build starts with cmake. Do you have cmake installed?
$ sudo apt-get install cmake

Now there is only a little step before building -
$ cd tidy-html5
$ git branch # just to check you are really in the develop-500 branch
$ cd build/cmake # get into the building directory
$ cmake ../.. # config and generate the native build files
after that you are back to the simple automake mantra ;=))
$ make
$ [sudo] make install (if desired)

After install tidy5 should be available to run from anywhere...

Advise if you have any trouble...

**Comment by geoffmcl** [comment]
@dkebler PS: That build ifnormation is in the README.md AFTER you switch to the develop-500 branch...

Like I say, we hope that will all be in the master brnach SOON...

**Comment by balthisar** [comment]
@dkebler, can you point out the gist to us? I will notify the gist owner that the instruction is soon to be invalid. He or she can change it, I hope.

**Comment by geoffmcl** [comment]
@dkebler, in the develop-500 branch, have removed some development stuff from build/cmake/build-me.sh, so you can use that if you prefer a script, but it will still not do the install. That must be done manually.

$ cd build/cmake
$ ./build-me.sh
$ [sudo] make install (if desired)

By default will install in /usr/local/bin, the cmake default binary install location...

If you want to install it in say /usr/bin use - note the 'bin' is not added -
$ ./build-me.sh -DCMAKE_INSTALL_PREFIX=/usr
$ [sudo] make install

Advise any problems...

HTH.

**Comment by dkebler** [comment]
https://gist.github.com/tacone/6082520

Nice thing about the script is it makes a deb package that can be put in a
ppa or other repo so others like me can just grab the latest.

Best would be your repo to maintain this gist and point to such in the
readme.md file.

On Thu, Feb 12, 2015 at 4:08 AM, Jim Derry <notifications@github.com> wrote:

> @dkebler <https://github.com/dkebler>, can you point out the gist to us?
> I will notify the gist owner that the instruction is soon to be invalid. He
> or she can change it, I hope.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/htacg/tidy-html5/issues/159#issuecomment-74060934>.
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by balthisar** [comment]
@dkebler, our plan is to release to all of those repos. Hopefully in Universe, so no having to add custom ppa's, etc.
