### ISSUE TITLE
Remove deprecated code

### ISSUE THREAD

**Issue by balthisar** [htacg/tidy-html5#160]
Inspecting the newest generated API docs (http://www.html-tidy.org/tidylib_api/deprecated.html) there are some deprecated functions. 5.0.0 might be a good milestone for removing them.

**Comment by geoffmcl** [comment]
@balthisar feel the next release of tidy after such a long time should be as binary compatible to the last as possible...

Maybe a good idea for a 5.1, 5.2, ...

ps: The above link is now broken...

**Comment by balthisar** [comment]
Fixed link. Agreed.

**Comment by geoffmcl** [comment]
@balthisar has the time for this `beast` at hand?

**Comment by geoffmcl** [comment]
Maybe for release 5.2, or later... for now closing this...
