### ISSUE TITLE
<main> is not recognized

### ISSUE THREAD

**Issue by michaeljwilliams** [htacg/tidy-html5#164]
Tidy does not like the main element, which is newish but officially in the HTML5 spec. When this issue is fixed, also keep in mind that only 1 main element is allowed per page, and it should not be a child of sectioning tags (article, header, footer, et al).

<a href="http://www.w3.org/TR/2012/WD-html-main-element-20121217/">w3c main</a>

"Authors MUST NOT include more than one main element in a document.

Authors MUST NOT include the main element as a child of an article, aside, footer, header or nav element."

I think this can be fixed by editing the /src/tags.c file..? I'd fix it myself but I don't understand what's going on with the ASCII strings.

**Comment by geoffmcl** [comment]
@michaeljwilliams thanks for adding this issue...

But as far as I can see tidy already has a TidyTag_MAIN and W3CAttrsFor_MAIN... You mean something is not working right?

Maybe you could construct a simple 'sample' html file that demonstrated the problem. Maybe the current implementation needs fixing or extending,,,

It presently uses the generic TY_(ParseBlock) parser. Maybe it needs it own specific parser, like say TY_(ParseMain). And maybe specific 'checking' code, like that for a table, CheckTABLE, or a link, CheckLINK, etc...

**Comment by michaeljwilliams** [comment]
Hi Geoff, you might be right, but as far as I saw in the file I mentioned previously, there was no main element present. I don't really know anything about Tidy's structure so that probably has nothing to do with this, but anyway something is wrong. I made an example html file and took a screenshot of the tidy output. FYI I compiled Tidy from the source in the master branch just a few days ago.

example.html: https://github.com/michaeljwilliams/michaeljwilliams.github.io/blob/master/example.html

![image](https://cloud.githubusercontent.com/assets/10594600/6320282/3421841a-ba8e-11e4-8438-0da000d5e48b.png)

**Comment by balthisar** [comment]
@michaeljwilliams, I apologize for the inconvenience. You're using the "master" branch, whereas the "develop-500" branch should be working. We'll resolve this shortly, as it's confusing.

Would you please confirm that the develop-500 branch works for you properly?

**Comment by michaeljwilliams** [comment]
@balthisar ah, yes, confusing. I would think the stable branch to be the one that works. Another thing that is confusing is the need for CMake to compile and install the develop-500 branch. I'd like to confirm that the develop branch supports the main element, but I haven't been able to compile and install it. I suppose CMake is to add Windows compatibility? But it seems to me to be at the expense of Unix (or at least OS X) users.

Firstly, Tidy's instructions do not say that this program is required prior to compilation. After getting CLI errors when trying to follow the instructions, I found and installed CMake and tried to get it working. I was unable to compile Tidy using the CMake GUI and the program refused to install the CLI tools, throwing errors at me at every turn for both attempts. What happened to the good ol' makefile?

Also the QT interface in CMake is non-retina and thus quite unsightly, but that's unrelated.

**Comment by balthisar** [comment]
I've made develop-500 the default branch now, temporarily, until it's rolled into master again.

Actually I was afraid of cmake at first, but I've come around to it. It is exceptionally flexible. Just today I learned how easy it is to create Mac OS X disk images with signed installer packages in them.

In any case, for 5.0.0 we do plan to offer binaries because we certainly don't expect end users to build all of their own software.

What version of Mac OS X are you on? For the initial install did you try running the bootstrap script for the initial install? It's also possible that you'll have to use `sudo make install`, although cmake's documentation doesn't mention it.

I didn't know cmake had a GUI, but like I mentioned, I'm still getting used to it.

Let me update my personal website with a current build, and I'll report back to this thread when it's up. It's something I do anyway, but it's still using an old build from a private fork, so time to update it.

**Comment by michaeljwilliams** [comment]
You must have installed CMake some other way than I. Perhaps through Homebrew? I got it through their website. I'm sure the CLI tools, once installed, function respectably. I'm on Mavericks (10.9.5).

I did not try running the bootstrap script and I don't know what that means. I just tried to follow the instructions haha. I appreciate the attention you've given this matter.

**Comment by balthisar** [comment]
@michaeljwilliams, try [this](http://www.balthisar.com/files/TidyCommandLine.dmg). It's a disk image containing a developer-ID-signed installer with today's most up to date develop-500 build for Mac OS X 10.8 and above. Maybe works on earlier 10.8, but I don't have the ability to test earlier than that.

**Comment by balthisar** [comment]
I used the version from their website. Because you don't have cmake already installed, the bootstrap script is the only way to install cmake the first time. That's for the command line version, though. I don't know the requirements for the GUI version.

**Comment by michaeljwilliams** [comment]
Thanks @balthisar. I installed from that dmg and ran the example.html again and Tidy gave no errors. That's good in that the main element is recognized, and also bad in that Tidy does not care that there are two main elements. I don't know if you're going that deep into semantics, but it would be a nice feature.

Consider the bug closed, but please leave open under feature label if you plan on implementing that.

**Comment by balthisar** [comment]
@michaeljwilliams, would you kindly file a new issue? Just plainly state that the current build allows two main elements when it shouldn't. If I don't see it in the couple of days, I'll add it myself.

I'll close this issue for now, though.
