### ISSUE TITLE
Anchor duplication - block-level anchor issue?

### ISSUE THREAD

**Issue by jacksonp** [htacg/tidy-html5#167]
Input:
```html
<!DOCTYPE html>
<title>Test</title>
<a id="Section" href="#Section"><h1>Section</h1></a>
```
Output of tidy5 -indent:
```html
<!DOCTYPE html>

<html>
<head>
  <meta name="generator" content=
  "HTML Tidy for HTML5 for Linux version 4.9.17">

  <title>Test</title>
</head>

<body>
  <a id="Section" href="#Section">
  <h1><a id="Section" href="#Section">Section</a></h1></a>
</body>
</html>
```
Note the two anchor tags with id "Section" in the output.

**Comment by geoffmcl** [comment]
@jacksonp yes, somehow this anchor tag got block and mixed added. Putting it back to just inline give the previous output...

**Comment by geoffmcl** [comment]
@jacksonp please pull version 4.9.18 if you get a chance, and re-test... thanks...

**Comment by jacksonp** [comment]
@geoffmcl Thanks, that does stop the duplication issue, I now get this output:
````html
<!DOCTYPE html>

<html>
<head>
  <meta name="generator" content=
  "HTML Tidy for HTML5 for Linux version 4.9.18">

  <title>Test</title>
</head>

<body>
  <h1><a id="Section" href="#Section">Section</a></h1>
</body>
</html>
````

But anchor tags can go around block-level elements in html5, so I guess I should have said I was expecting the output to be the same as the input, so:
````html
<a id="Section" href="#Section"><h1>Section</h1></a>
````

**Comment by geoffmcl** [comment]
@jacksonp yes I reverted the behaviour because the duplication of the anchor looked very bad! Will now look for a way to allow the anchor to be around the block if html5... thanks for the quick testing and report...

**Comment by geoffmcl** [comment]
@jacksonp see issue #169 for hopefully a solution to this...

**Comment by jacksonp** [comment]
@geoffmcl With that fix I get this output:
````html
<body>
  <a id="Section" href="#Section" name="Section">
  <h1>Section</h1></a>
</body>
````
It seems to now add a name attribute, which isn't supported in html5.

**Comment by geoffmcl** [comment]
@jacksonp some further fixes on doctype and version... hope for some good news...

**Comment by jacksonp** [comment]
That's great, the tags are now perfect. The indentation seems a bit off tho, here's the output I get with
`tidy5 -indent -wrap 400 test.html`:
````html
<body>
  <a id="Section" href="#Section">
  <h1>Section</h1></a>
</body>
````
I think the anchor block should all be one line in this case (same as the input)?

**Comment by geoffmcl** [comment]
@jacksonp just glad the tags are right!

To me there is a **LOT** wrong with the pprint.c module, especially when to, and to not add a new line... there is even a feature request to try and keep the current indents, lines, etc... very difficult...

But for now I am only concentrating on html tag bugs... Would appreciate you opening a new issue for the pprint output which I think will be attacked after we have 5.0.0 out the door... probably a 5.1 target, unless you, or others, can offer easy PR or diffs... dig into it...

Thanks for the quick testing and report...

**Comment by jacksonp** [comment]
@geoffmcl I've added a new issue for the pprint output (#179).

I hit this issue straight away when trying tidy-html5 for the first time, haven't have a chance to see what it can do yet!
