### ISSUE TITLE
no command line manual page

### ISSUE THREAD

**Issue by anEffingChamp** [htacg/tidy-html5#177]
At least for my sake `tidy` could benefit from a manual page, such than `man tidy` would render some thing. It could even just start as the same output as `tidy -?`, but it is another common path to exploring command line options.

**Comment by geoffmcl** [comment]
@anEffingChamp as mentioned in #178 we are certainly working towards bringing this back... the previous man tidy pages were generated using xsltproc which is not a very crossplatform way... any help appreciated...

**Comment by pedromorgan** [comment]
An observation re packaging

This is what cpack currently includes in the deb, missing is the man file ```tidy.1```
```
./usr/bin/tidy5
./usr/include/buffio.h
./usr/include/platform.h
./usr/include/tidy.h
./usr/include/tidyenum.h
./usr/lib/libtidy5.a
```

So the snag is that ```tidy.1``` needs to be included 

`tidy.1` is created with the `build_docs.sh` and requires  xsltproc
```
$TIDY_PATH -xml-help > "tidy-help.xml"
xsltproc "tidy1.xsl" "$tidy-help.xml" > "$OUTP_DIR/tidy.1"
```

So this is a bit chicken and egg in that..
1. tidy needs to be compiled, to output the `tidy-help.xml`
2. xml is then processed into man page

So the sequence needs to be..
1. build tidy
2. generate man page
3. run cpack and include man page for install

**Comment by pedromorgan** [comment]
http://stackoverflow.com/questions/3375341/man-page-generation-packaging-installation-with-cmake

**Comment by geoffmcl** [comment]
@pedromorgan Thanks Pete. As the link you gave points out this can **ALL** be done in CMakeLists.txt, which is where is SHOULD be done, NOT as a separate process, including -

  1. finding if xsltproc is installed
  2. running the just built tidy executable to generate the tidy-help.xml and tidy-config.xml
  3. running xsltproc to generate the tidy.1 and quickref.html
  4. installing tidy.1 and quickref.html appropriately along with the rest
  5. then cpack would pick them up and include them in the deb and rpm

As a quick guess that would be something like, added after the exe builds, before the cpack stuff, but this is obviously untested -

````
if (UNIX)
    find_program( XSLTPROC_FOUND NAME xsltproc )
    if (XSLTPROC_FOUND)
        set(TIDY1XSL /path/to/tidy1.xsl)
        set(TIDYHELP ${CMAKE_BINARY_DIR}/tidy-help.xml)
        add_custom_target(man ALL)
        # run built EXE to generate output
        add_custom_command(
            OUTPUT ${TIDYHELP}
            COMMAND tidy5 -xml-help > ${TIDYHELP}
            COMMENT "Generate ${TIDYHELP}"
            VERBATIM
            )
        # repeated for tidy-config.xml
        # run xsltproc to generate the install files..
        add_custom_command(
            TARGET man
            SOURCE ${TIDYHELP}
            COMMAND xsltproc ARGS ${TIDY1XSL} ${TIDYHELP} > ${CMAKE_BINARY_DIR}/tidy.1
            OUTPUTS ${CMAKE_BINARY_DIR}/tidy.1
            )
        add_custom_command(
            TARGET man
            SOURCE man
            DEPENDS ${CMAKE_BINARY_DIR}/tidy.1
        )
        # repeated for quikcref.html - may need different targets...
        install(FILES ${CMAKE_BINARY_DIR}/tidy.1 DESTINATION man/man1)
        # add the quickref.html install
    endif ()
endif ()
````

And another small point, I would like to remove this root/build/documentation folder, maybe just in root/documentation, or something. I want to simplify the actual build to -
```` $ cd build
$ cmake ..
$ make 
$ [sudo] make install ````

Needs some experimentation... I will get around to this eventually... but any help **ADDING** this capability to CMakeLists.txt, testing and fixing, would be **MOST** appreciated...

**Comment by geoffmcl** [comment]
Of course this ONLY addresses UNIX man page... and maybe OS X? But still to give some thought to something similar for Windows...

**Comment by pedromorgan** [comment]
Would make sense to move 
```
build/documentation/
``` 
to
```
docs/
```
and something I considered but didnt to as not to upset apples in cart

**Comment by pedromorgan** [comment]
This can be closed as its fixed here..

https://github.com/htacg/tidy-html5/commit/08d037b6af630b40c4c9df7569a9a30a56d7c332

**Comment by balthisar** [comment]
Seem confirmed on multiple versions of Cmake, and I can confirm Mac OS X. Will close.

**Comment by balthisar** [comment]
@pedromorgan said:

> Would make sense to move

Soon. I'm planning to remove the build_docs script and add its functions to cmake as another target, which will allow some cleanup and moving out of `build`.

**Comment by geoffmcl** [comment]
@anEffingChamp, just to clarify this, even though closed... 

In unix systems, if xlsproc is installed, then the man page is auto generated, and thus will get installed on `[sudo] make install`...

And further at this time, until 5.0.0 is released, tidy is generated as tidy5, thus the man page will be `tidy5.1`, and can be seen by `man tidy5`...

Works great in my Ubuntu ;=))
