### ISSUE TITLE
stdout missing file name identification

### ISSUE THREAD

**Issue by anEffingChamp** [htacg/tidy-html5#178]
Currently when linting a document with `tidy5 -e foo.html` the program will lint the pages for errors. However when linting multiple documents with `tidy5 -e *html` the program will output information on all documents in succession without any indication of what the documents are. This makes correcting issues much more difficult, and could easily be fixed by prepending the file name to any related output.

**Comment by geoffmcl** [comment]
@anEffingChamp have you tried the --gnu-emacs yes option?

I thought this output the usual `file-name:rr:cc:` in front of each warning, error...

**Comment by anEffingChamp** [comment]
You are right, it does. Documentation for that option is just missing
from the `tidy -h` help screen.

**Comment by geoffmcl** [comment]
@anEffingChamp yes -h is only a quite minimal screen... try -help-config for the **BIG** list.

And we are working on more documentation, like <a href="http://www.html-tidy.org/documentation">here</a>, and as suggested in your #177 also a man tidy page... slowly moving forward... any help would be appreciated...
