### ISSUE TITLE
Treat elements ids as case-sensitive

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#185]
<a href="https://github.com/eksperimental"><img src="https://avatars.githubusercontent.com/u/9133420?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eksperimental](https://github.com/eksperimental)**
_Wednesday Dec 31, 2014 at 03:21 GMT_
_Originally opened as https://github.com/geoffmcl/tidy-fork/issues/7_

----

````
<span id="test"></span>
<span id="Test"></span>
<span id="TEST"></span>
````
gives a warning:
````
line 74 column 1 - Warning: <span> anchor "Test" already defined
line 75 column 1 - Warning: <span> anchor "TEST" already defined
````

that's ok for html4, but it is not the case in html5, as they are considered different elements
http://www.w3.org/TR/html5/disabled-elements.html#case-sensitivity

**Comment by geoffmcl** [comment]
<a href="https://github.com/geoffmcl"><img src="https://avatars.githubusercontent.com/u/1333435?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geoffmcl](https://github.com/geoffmcl)**
_Sunday Jan 18, 2015 at 19:10 GMT_

----

Hi eksperimental,

Thank you for the report, and sorry about the
delay in my response...

Hmmm, this is QUITE difficult ;=((

As you point out, for html4 (and less), ids 'test',
'Test' and 'TEST' are the same, thus the warning.

So how to keep this behaviour if the documents is
html4, while at the same time treat them differently
for html5???

This check is done AFTER the parsing of the whole
document, so could possibly 'guess' if it looks
like htm5 and act differently...

Or it could be based on say the --doctype html5
user config input. If this doctype is given, only
then treat it as html5...

Need to think and consult on this... Will be back
soonest...

Regards,
Geoff.

**Comment by geoffmcl** [comment]
<a href="https://github.com/subhaze"><img src="https://avatars.githubusercontent.com/u/141903?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [subhaze](https://github.com/subhaze)**
_Tuesday Jan 20, 2015 at 01:54 GMT_

----

Just jumping in with a thought. Would it be a bad thing if tidy-html5 only focused on html5 and allowed the existing tidy be the go to for html4?

**Comment by geoffmcl** [comment]
<a href="https://github.com/eksperimental"><img src="https://avatars.githubusercontent.com/u/9133420?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eksperimental](https://github.com/eksperimental)**
_Tuesday Jan 20, 2015 at 05:51 GMT_

----

@subhaze oh really, I thought tidy-html5 was a fork of tidy(-html4) that focused only on html5.
@geoffmcl if the document doesn't explicitly say it's html4, i think tidy-HTML5 should treat it as html5.

what you guys think?

**Comment by geoffmcl** [comment]
<a href="https://github.com/subhaze"><img src="https://avatars.githubusercontent.com/u/141903?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [subhaze](https://github.com/subhaze)**
_Tuesday Jan 20, 2015 at 12:26 GMT_

----

@eksperimental you are right, it's a fork to add additional support. I was just throwing out a thought on if things begin to be very difficult on keeping BC, potentially moving to just HTML5.

**Comment by geoffmcl** [comment]
<a href="https://github.com/geoffmcl"><img src="https://avatars.githubusercontent.com/u/1333435?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geoffmcl](https://github.com/geoffmcl)**
_Tuesday Jan 20, 2015 at 12:36 GMT_

----

Hi,

While I agree life would be MUCH easier if
we just separated the two - leave tidy to do
html4 and earlier, and have tidy5 treat everything
as html5, that has /NEVER/ been the aim!

And such a library separation also represents
additional maintenance, like when a bug is
reported that applies to both... two sources,
or a very messy macro switched source... UGH!

At present tidy5 tries to guess what type of
document it is... if it finds tags, attributes,
features, etc only in html5, then it chooses
html5... And likewise for html4, or earlier...

Also there is a --doctype html5 command that
indicates to tidy5 that you want the output with
a html5 doctype...

The options for doctype are html5, omit, auto,
strict, transitional, and user, with auto
being the default.

So far this has been quite successful... and
for the present will continue to try to have
full functionality in the next release of
tidy[5] ;=))

And you will note the W3C validator is now trying
to do the same... so this is a push for the
single, very intelligent, tidy[5]...

Regards,
Geoff.

**Comment by geoffmcl** [comment]
<a href="https://github.com/subhaze"><img src="https://avatars.githubusercontent.com/u/141903?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [subhaze](https://github.com/subhaze)**
_Tuesday Jan 20, 2015 at 12:55 GMT_

----

Geoff, thanks for the details. I'm glad to see you're up for the task on
keeping everything supported :)

And again, many thanks for putting life back into this tool.

**Comment by geoffmcl** [comment]
@subhaze moved this issue to here where the current development of tidy is taking place...

For now we are continuing with a single tidy, which defaults to html5 mode unless it finds a DOCTYPE of html4 or earlier, so should now be able to address this issue here...

**Comment by eksperimental** [comment]
thans for the heads-up @geoffmcl

**Comment by geoffmcl** [comment]
@eksperimental, have pushed hopefully a fix for this...

If you get a chance pull version 4.9.21++ and test again... thanks...

**Comment by geoffmcl** [comment]
@eksperimental since no further comments for nearly a month, assume this is 'fixed'.

Accordingly am closing this for now... feel free to re-open, or open other issues... thanks...
