### ISSUE TITLE
Can't we make include/platform.h configurable with CMake?

### ISSUE THREAD

**Issue by bdheeman** [htacg/tidy-html5#188]
Why do we need to edit include/platform.h manually?

    diff --git a/include/platform.h b/include/platform.h
    index 3b60114..7d0029c 100644
    --- a/include/platform.h
    +++ b/include/platform.h
    @@ -18,7 +18,7 @@ extern "C" {
    */
    
    /* #define TIDY_CONFIG_FILE "/etc/tidy_config.txt" */ /bin /boot /dev /etc /home /initrd.img /lib /lost+found /media /mnt /opt /proc /root /run /sbin /srv /sys /tmp /usr /var /vmlinuz original */
    -/* #define TIDY_CONFIG_FILE "/etc/tidyrc" */
    +#define TIDY_CONFIG_FILE "/etc/tidyrc"
    /* #define TIDY_CONFIG_FILE "/etc/tidy.conf" */
    
    /*
    @@ -27,7 +27,7 @@ extern "C" {
    It enables tidy to find config files named ~/.tidyrc if
    the HTML_TIDY environment variable is not set.
    */
    -/* #define TIDY_USER_CONFIG_FILE "~/.tidyrc" */
    +#define TIDY_USER_CONFIG_FILE "~/.tidyrc"
    
    /*
    Uncomment the following #define if your
    @@ -42,7 +42,7 @@ extern "C" {
    Contributed by Todd Lewis.
    */
    
    -/* #define SUPPORT_GETPWNAM */
    +#define SUPPORT_GETPWNAM
    
     /* Enable/disable support for Big5 and Shift_JIS character encodings */

**Comment by geoffmcl** [comment]
@bdheeman, agreed, should not need to...

Have modified CMakeLists.txt to accomodate 3 user additions when running cmake

 1. -DTIDY_CONFIG_FILE="/path/to/config"
 2. -DTIDY_USER_CONFIG_FILE="/path/to/config"
 3. -DSUPPORT_GETPWNAM=1

Please pull 4.9.22 or later, and test... Thanks for reporting...

**Comment by geoffmcl** [comment]
@bdheeman no response for over a month so assume 'fixed' so closing...

Feel free to re-open if still a problem, or open a new issue... thanks..
