### ISSUE TITLE
Double lines with vertical spacing

### ISSUE THREAD

**Issue by Zackio** [htacg/tidy-html5#189]
I think that the line spacing was removed so that it only has vertical spacing if vertical spacing is set to on. However when I enable vertical spacing I get double line breaks, is this a bug?

On the branch: https://github.com/htacg/tidy-html5/commit/66a597f5b7a131f1a4b7e60b82bb4532dc489117

I get a single newline as expected, turning on vertical space creates single new lines.

With vertical spacing (now and before)
```HTML
              <ul class="menu">
                <li>
                  <a href="./services1.html">Services 1</a>
                </li>


                <li>
                  <a href="./services2.html">Services 2</a>
                </li>
              </ul>
              <!-- End .menu -->

```

Without vertical spacing before the code change related to issue #180
```HTML
            <ul class="menu">
                <li>
                  <a href="./services1.html">Services 1</a>
                </li>

                <li>
                  <a href="./services2.html">Services 2</a>
                </li>
              </ul><!-- End .menu -->
```

After the change without vertical spacing

```HTML
            <ul class="menu">
                <li>
                  <a href="./services1.html">Services 1</a>
                </li>
                <li>
                  <a href="./services2.html">Services 2</a>
                </li>
              </ul><!-- End .menu -->
```

**Comment by geoffmcl** [comment]
@Zackio, might be a 'bug' or a 'preference' ;=))

It seemed 'classic' Tidy added LOTS of vertical space, and hope I have left that mostly untouched if you add `--vertical-space yes` to the config, although I too do not particularly 'like' the double blank line you show...

Unless someone beats me to it, and submits a PR I will take another look when I get a chance, but as mentioned elsewhere I am putting 'Pretty Print' output issues on the backburner for now...

So am marking this issue accordingly... As always, thanks for testing and reporting...

**Comment by Zackio** [comment]
I'm just going to stick to the older version as that's doing what I need. I'm on a mac BTW, I think I read something about someone testing on a mac.

**Comment by geoffmcl** [comment]
@Zackio as you may have noted, this `vertical-space` option is being dealt with and discussed in #228. Maybe you have some preferences here... and that includes where the so called `classic` mode should be employed...

If you get the chance to pull the latest `master` 5.1.x, and redo the test... 

Is this still a problem? If yes, maybe we should bump this to `bug` status...

Now that release 5.0.0RC1 is rolling, it is certainly the time to re-visit, and if necessary `fix` this...

Do you have any problem compiling from source? 

We are presently missing a MAC binary from - http://www.htacg.org/binaries/ - 

Can you help with that? That is generate a Disk Image file, and put is somewhere I can get it? That would be very helpful... thanks...

**Comment by geoffmcl** [comment]
@Zackio as you may have read else where have fully updated the `master` branch, and it contains **lots** of `newlines` features, fixes, changes... version 5.1.8 (2015.09.04).

I hope you get a chance to pull it, and check it out ;=)) And make sure you try the **new feature** `--vertical-space auto` option... or download a binary from http://www.htacg.org/binaries/ ... but still in need of a mac binary...

Since this release addresses and changes some of the above `spacing` issues, will close this for now, but feel free to re-open, or post a new issue.

**Comment by geoffmcl** [comment]
@Zackio as you may have noticed @balthisar has added some later MAC [binaries](http://www.htacg.org/binaries/) up to version 5.1.14, but if you can build from source then the `master` branch is 5.1.17 with more improvements...

Hope you get a chance to try the latest...

**Comment by balthisar** [comment]
Actually that should be http://binaries.html-tidy.org/ now.
