### ISSUE TITLE
HTML_TIDY environment variable not working

### ISSUE THREAD

**Issue by Pajamaman** [htacg/tidy-html5#191]
I'm afraid I may be missing something really obvious, because it seems like this should be so simple.

    $ echo $HTML_TIDY
    /home/rmorton/.tidyconfig

    $ cat $HTML_TIDY
    doctype: omit
    indent: auto
    indent-spaces: 4
    wrap: 0

    $ ls -l $HTML_TIDY
    -rw-rw-r-- 1 rmorton rmorton 94 Apr  7 22:11 /home/rmorton/.tidyconfig

To summarize, the environment variable is set correctly. The file is readable and, as far as I can tell, formatted correctly. The file I'm trying to tidy looks like this:

    <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="31"><B>Currently we have these articles available:</B>

                <blockquote>
                	<p><a href="foo.html">The History of Foo</a><br>
                	  An informative piece of information.</p>
                  <p><a href="bar.html">A Horse Walked Into a Bar</a><br>
                    The bartender said "Why the long face?"</p>
                </blockquote>
                </td>
                           </tr>
        </table>

The program doesn't seem to be reading the config file at all:

    $ tidy5 ~/Desktop/articles.html | cat
    line 1 column 1 - Warning: missing <!DOCTYPE> declaration
    line 1 column 1 - Warning: inserting implicit <body>
    line 1 column 1 - Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    3 warnings, 0 errors were found!

    About HTML Tidy: https://git<!DOCTYPE html>
    <html>
    <head>
    <meta name="generator" content=
    "HTML Tidy for HTML5 for Linux version 4.9.23">
    <title></title>
    </head>
    <body>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
    <td height="31"><b>Currently we have these articles available:</b>
    <blockquote>
    <p><a href="foo.html">The History of Foo</a><br>
    An informative piece of information.</p>
    <p><a href="bar.html">A Horse Walked Into a Bar</a><br>
    The bartender said "Why the long face?"</p>
    </blockquote>
    </td>
    </tr>
    </table>
    </body>
    </html>
    hub.com/htacg/tidy-html5/tree/develop-500
    Bug reports and comments: https://github.com/htacg/tidy-html5/issues
    Or send questions and comments to: https://lists.w3.org/Archives/Public/public-htacg/
    Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
    Validate your HTML documents: http://validator.w3.org/nu/
    Lobby your company to join the W3C: http://www.w3.org/Consortium

What am I missing?

**Comment by geoffmcl** [comment]
@Pajamaman, not sure what you are missing ;=((

I have checked the code on reading the config using HTML_TIDY, and line 987 of tidy.c looks fine -

````
    if ( (cfgfil = getenv("HTML_TIDY")) != NULL )
    {
        status = tidyLoadConfig( tdoc, cfgfil );
        if ( status != 0 )
            fprintf(errout, "Loading config file \"%s\" failed, err = %d\n", cfgfil, status);
    }
````

So I just put your config into a file cfg_191.txt, and 
your html into in_191.html, and did and got -

````
~/projects/html_tidy/tidy-html5/test/input5$ export HTML_TIDY=cfg_191.txt
~/projects/html_tidy/tidy-html5/test/input5$ tidy5 in_191.html
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
line 1 column 1 - Warning: inserting implicit <body>
line 1 column 1 - Warning: inserting missing 'title' element
Info: Document content looks like HTML5
3 warnings, 0 errors were found!

<html>
<head>
    <meta name="generator" content="HTML Tidy for HTML5 for Linux version 4.9.23">
    <title></title>
</head>
<body>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td height="31">
                <b>Currently we have these articles available:</b>
                <blockquote>
                    <p><a href="foo.html">The History of Foo</a><br>
                    An informative piece of information.</p>
                    <p><a href="bar.html">A Horse Walked Into a Bar</a><br>
                    The bartender said "Why the long face?"</p>
                </blockquote>
            </td>
        </tr>
    </table>
</body>
</html>

About HTML Tidy: https://github.com/htacg/tidy-html5/tree/develop-500
Bug reports and comments: https://github.com/htacg/tidy-html5/issues
Or send questions and comments to: https://lists.w3.org/Archives/Public/public-htacg/
Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
Validate your HTML documents: http://validator.w3.org/nu/
Lobby your company to join the W3C: http://www.w3.org/Consortium
~/projects/html_tidy/tidy-html5/test/input5$ 
````
And the same from `$ tidy5 in_191.html | cat`...

So obviously the config was read from the HTML_TIDY export, and the results are 
indeed indented... so can not see a problem...

Some small things would be that since the config is `--doctype omit`, then maybe tidy should 
not give the DOCTYPE warning... and the fact that this source is also now in the `master' branch,
but they do not seem to be your main problem...

Can you try `$ tidy5 -config /home/nmorton/.tidyconfig ~/Desktop/articles.html`, and see what you get...

Don't know what else to suggest since I can not replicate the problem! Not in linux, nor Windows..

**Comment by geoffmcl** [comment]
@Pajamaman, as you may have noticed I have 'fixed' the other two niggles, and bumped the version to 4.9.24

And as indicated you should now switch back to the default 'master' branch, but at least for now am also keeping the develop-500 branch up-to-date, but will eventually drop this branch...

**Comment by Pajamaman** [comment]
Cool, thanks for looking into this. I will try using the config argument via the command line when I get a chance.

(btw I'm on Ubuntu 14.04)

**Comment by Pajamaman** [comment]
Oops, didn't mean to close.

**Comment by Pajamaman** [comment]
Okay, using the config argument works but the environment variable still doesn't. Do I need to enable environment variable config when I make tidy or something?

**Comment by geoffmcl** [comment]
@Pajamaman, no, checking for HTML_TIDY is compiled there by default... no additional config required...

I just did some experiments setting a 'bad' config file name, or bad content, and I can see warnings, like ...

````
~$ tidy5 --version
HTML Tidy for Linux version 4.9.24

# point to a non-existing file
~$ export HTML_TIDY=rubbish.txt
~$ tidy5 --version
Config: Can't open "rubbish.txt"

Loading config file "rubbish.txt" failed, err = -1
HTML Tidy for Linux version 4.9.24

# create an empty config
~$ touch temp1.txt
~$ export HTML_TIDY=temp1.txt
~$ tidy5 --version
HTML Tidy for Linux version 4.9.24

# add a bad parameter
~$ echo bad-conf: rubbish >>temp1.txt
~$ tidy5 --version
Config: unknown option: bad-conf
Loading config file "temp1.txt" failed, err = -1
HTML Tidy for Linux version 4.9.24
````

So this all works for me. Can you try that, and advise?

**Comment by Pajamaman** [comment]
ehhhhh I figured it out but it's really embarassing. I forgot to put `export` in front of `HTML_TIDY=~/.tidyconfig` in my .bashrc.
