### ISSUE TITLE
Tidy does not allow block elements in <caption>

### ISSUE THREAD

**Issue by willydee** [htacg/tidy-html5#196]
According to http://dev.w3.org/html5/spec-author-view/the-caption-element.html#the-caption-element arbitrary flow content is allowed within `CAPTION` elements, and the following code passes the validation without warnings. 
```html
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<table>
  <caption>
    <nav><button>Test</button></nav>
  </caption>
  <tbody>
    <tr><td>Lorem ipsum</td></tr>
  </tbody>
</table>
</body>
</html>
```
Tidy output:
```
line 8 column 3 - Warning: missing </caption> before <nav>
line 9 column 5 - Warning: <nav> isn't allowed in <table> elements
line 7 column 1 - Info: <table> previously mentioned
line 10 column 3 - Warning: discarding unexpected </caption>
line 8 column 3 - Warning: trimming empty <caption>
Info: Document content looks like HTML5
4 warnings, 0 errors were found!
```

**Comment by willydee** [comment]
Probably related to https://github.com/htacg/tidy-html5/issues/169

**Comment by geoffmcl** [comment]
@willydee, thanks for the pull request #197. Your patch certainly does the job ;=))

The only thing I noted is maybe we should 'expand' the comment in `lexer.c(2750):` to include this issue when calling `AdjustTags`... but quite minor...

And yes, we can expect more dynamic table adjustments as we move forward supporting html5++ while still maintaining full html4-- support.

Out of time to finalise and test a little more today, but will get to this soonest... Thanks again...

**Comment by geoffmcl** [comment]
@willydee, Thanks for this PR... merged and closed, bumped version, and added comments in lexer.c

Now tidy5 passes this, like the validator, without problems...

And constructed a backwards compatible test -
````
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv=Content-Type content="text/html; charset=utf-8">
  <title>Tidy does not allow block elements in caption #196</title>
</head>
<body>
<table>
  <caption>
    <nav><button>Test</button></nav>
  </caption>
  <tbody>
    <tr><td>Lorem ipsum</td></tr>
  </tbody>
</table>
</body>
</html>
````

and as expected the 'warnings' return, just like in the validator -
````
line 10 column 3 - Warning: missing </caption> before <nav>
line 11 column 5 - Warning: <nav> isn't allowed in <table> elements
line 9 column 1 - Info: <table> previously mentioned
line 12 column 3 - Warning: discarding unexpected </caption>
line 10 column 3 - Warning: trimming empty <caption>
4 warnings, 0 errors were found!
````

Please re-test when you get a chance, and close this... Thanks again...

**Comment by willydee** [comment]
@geoffmcl, thanks for integrating my patch. Works like a charm.

Best regards, willydee
