### ISSUE TITLE
No unix script for html5 testsuite

### ISSUE THREAD

**Issue by lacombar** [htacg/tidy-html5#198]
n/a

**Comment by geoffmcl** [comment]
@lacombar had a quick look at this script and it looks fine...

I could just copy it over, but that loses your name on the commit, and it becomes my commit...

Can you create a Pull Request?

Similarly for Issue #199...

Or is there a way to merge from your clone? Have not tried this often... can handle PRs...

**Comment by geoffmcl** [comment]
@lacombar pull request now merged...

When you get a chance please recheck and close if fixed...

Thanks...

**Comment by geoffmcl** [comment]
@lacombar no further comments in the last 3 weeks so assume fixed.

Accordingly am closing this now, but feel free to re-open, or open other issues... thanks...
