### ISSUE TITLE
HTML5 <template> tag not supported

### ISSUE THREAD

**Issue by lacombar** [htacg/tidy-html5#199]
```
line 11 column 1 - Error: <template> is not recognized!
line 11 column 1 - Warning: discarding unexpected <template>
line 14 column 1 - Warning: discarding unexpected </template>
2 warnings, 1 error were found!
```

**Comment by geoffmcl** [comment]
@lacombar like #198, can you create a PR to keep your name on the commit?

**Comment by geoffmcl** [comment]
@lacombar I just experimented in a fresh tidy-html5 clone and clone of your aerilon repo into tidy-aerilon folder...

I can get all these changes into master by doing -

 1. cd tidy-html5
 2. git remote add aerilon ../tidy-aerilon
 3. git pull aerilon master
 4. git remote remove aerilon

But as suspected this does fetch and merge your #198 and #199 changes in one new commit authored by ME. Using a PR should keep you as the 'Author'

**Comment by geoffmcl** [comment]
@lacombar pull request now merged...

When you get a chance please recheck and close if fixed...

Thanks...

**Comment by geoffmcl** [comment]
@lacombar no further comments in over 3 weeks so assume fixed, and closing this issue...

Feel free to re-open, or open a new issue... thanks...
