### ISSUE TITLE
Broken links on website

### ISSUE THREAD

**Issue by dregad** [htacg/tidy-html5#203]
Hi guys,

Just to let you know that I hit a few broken links on http://www.htacg.org/, I suppose it's a side effect of moving to the new domain. Same problem also exists at http://www.html-tidy.org/

For example, in the FAQ at http://www.htacg.org/tidy-html5/#freq, both links lead to 404 errors.

**Comment by geoffmcl** [comment]
@dregad will certainly look into how to fix these... thanks for reporting...

**Comment by geoffmcl** [comment]
@dregad hmmm, just tried all the links I could find, and found nothing broken... has this been fixed?

Else please give the specific broken link(s)... thanks,,,

**Comment by dregad** [comment]
Hi Geoff,

> just tried all the links I could find, and found nothing broken

I don't know what links you tried, but for sure the problem persists... As per my original report

> For example, in the FAQ at http://www.htacg.org/tidy-html5/#freq, both links lead to 404 errors.

If you follow that URL, you'll see 2 links in the section, both are broken...

* "issues tracker" http://www.htacg.org/tidy-html5/3
* "in our github repo" http://www.htacg.org/tidy-html5/4

**Comment by geoffmcl** [comment]
@dregad sorry missed those two - now fixed I hope...

Advise if you find others, and thanks for reporting...

**Comment by dregad** [comment]
It works now. Cheers !
