### ISSUE TITLE
Line breaks after equal symbol in attributes

### ISSUE THREAD

**Issue by Pajamaman** [htacg/tidy-html5#205]
HTML:

```
Gluten-free Bushwick selvage, plaid asymmetrical banh mi tofu 3 wolf moon slow-carb meditation <a href="#mumblecore">mumblecore</a> next level Tumblr. Tote bag disrupt occupy, actually chia biodiesel quinoa before they sold out lumbersexual listicle seitan vinyl. YOLO cornhole organic hashtag bitters Marfa.
```

Config:

```
show-body-only: true
show-errors: 0
show-info: false
show-warnings: false
wrap: 120
quiet: true
```

Output:

```
Gluten-free Bushwick selvage, plaid asymmetrical banh mi tofu 3 wolf moon slow-carb meditation <a href=
"#mumblecore">mumblecore</a> next level Tumblr. Tote bag disrupt occupy, actually chia biodiesel quinoa before they
sold out lumbersexual listicle seitan vinyl. YOLO cornhole organic hashtag bitters Marfa.
```

Why does it break after the equal symbol in `<a href="#mumblecore">`? Is there an option to make it not do that?

**Comment by geoffmcl** [comment]
@Pajamaman, well as far as I can tell tidy has **always** done that. Even back to tidy in 2000, the Dave Raggett's Original, the earliest copy I could find... 

It just depends on choosing a specific wrap value... Change the wrap value for that snippet and it will not happen...

So if this is about adding an `option` to avoid this, I do not think there is one already, but with so many otions... Maybe someone can help here...

But if there is presently none then it will certainly be considered if you present a patch or PR...

**Comment by geoffmcl** [comment]
@Pajamaman no further comment for over 3 weeks so am closing this for now...

Feel free to re-open, or add a PR adding a new feature to avoid this if necessary... thanks...
