### ISSUE TITLE
Wrapping block elements in <a>

### ISSUE THREAD

**Issue by michaeljwilliams** [htacg/tidy-html5#211]
Tidy does not like it when I wrap block-level elements in anchor tags:
```
<a>
  <div>
    <p>Tidy says "inserting implicit <a>"</p>
  </div>
</a>
```
tidy -v: HTML Tidy for Mac OS X version 4.9.15

Anchor wrapping is new in HTML5, see http://html5doctor.com/block-level-links-in-html-5/

**Comment by geoffmcl** [comment]
@michaeljwilliams, can not replicate the problems in the current tidy version 4.9.26!

I get `No warnings or error were found` when tidying (input5/in_211.html) -

```
<!DOCTYPE html>
<head>
<meta charset="utf-8">
<title>Issue #211</title>
</head>
<body>
<a>
  <div>
    <p>Tidy says "inserting implicit &lt;a&gt;"</p>
  </div>
</a>
</body>
</html>
```

Can you update and test again... thanks...

**Comment by michaeljwilliams** [comment]
Updating was a pain last time. I'll take your word for it and wait for the 5.0 binaries.

**Comment by geoffmcl** [comment]
@michaeljwilliams sorry to hear updating is a **pain** ;=((

But what is the problem? Maybe I can help... I note you are in a MAC OS X, so it should be as easy as open a terminal window, git clone the repo, then cmake, and build...

The actual steps would be -

 1. Open Terminal Windows
 2. Navigate to where you want to clone tidy
 3. $ git clone git@github.com:htacg/tidy-html5.git # should create a tidy-html5 folder
 4. $ cd tidy-html5/build/cmake # get into the build folder
 5. $ cmake ../.. # generate the unix Makefile
 6. $ make # compile and link
 7. $ make install # install tidy5, but not sure where this goes in OS X
 
If you have not setup github.com ssh access, then maybe in step 3 you would need to use the READ ONLY repo - `https://github.com/htacg/tidy-html5.git`
 
And even without the install step 7, in tidy-html5/build/cmake you should then have an up-to-date binary, called `tidy5`... can be run with `./tidy5 -v`...

And if you have already done the step 3 somewhere else, then navigate into that directory, and change step 3 to just `$ git pull`, and this will update the source to the latest... then onwards step 4, 5, 6, ...

I know others have built tidy5 in OS X, and maybe they could also help with any problems... it should be **easy** ;=)) we need more 'testers' before 5.0 is released...

**Comment by michaeljwilliams** [comment]
The trouble I had was with cmake. It doesn't want to install.

**Comment by geoffmcl** [comment]
@michaeljwilliams , I see from a previous post, #164, you are on on Mavericks (10.9.5), and reported cmake install problems back then... 

And to confirm, the stable branch is now `master`...  and yes building tidy from source absolutely requires cmake! It is a cross platform `generator` that can build a Makefile, and other native build systems. And is now the base build system in **MANY** projects...

I will get around to deleting the develop-500 branch which is now no longer up-to-date!!! 

And then again in #166, where it seems you reported being able to build and install cmake from source using `sh boostrap`. What happened to that installation?

I personally always use the CLI interface, and have little experience with the GUI, which in some platforms is a separate install, after a successful CLI install.

On stackoverflow I can read others also had problems installing cmake using the dmg files - See : http://stackoverflow.com/questions/18857408/cannot-install-cmake-for-mac-os-x-10-8 - 

There the offered solution was -

```
You can install cmake via (Homebrew)(http://brew.sh/)

Install Homebrew

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Install cmake via Homebrew

brew install cmake
```

**But take care if you then also try to build and install tidy using homebrew!**

Unless they have fixed the script this can lead to problems - see #30 - read my post at/near the bottom where I found the `tidy` script seemed to not be doing the right thing! And offered the simple steps in a terminal window... which you have seen before...

I can see from your multiple posts this has been a trying experience for you, but I hope you will find the time to continue to **share** your experiences here so other OS X owners can benefit... and sorry cmake is causing such **pain** ;=()

And hope other OS X users who have successfully installed cmake can also share... Also please add your OS X version, as it seems this can change things... thanks...

**Comment by michaeljwilliams** [comment]
Thanks for your help, but to be honest I just don't want to deal with this right now. I have finals coming up...
