### ISSUE TITLE
online configuration documentation lost?

### ISSUE THREAD

**Issue by rickdog** [htacg/tidy-html5#213]
The options link at http://www.htacg.org/tidy-html5/documentation/ is a 404.  (http://www.htacg.org/quickref.html)

plz update to http://www.htacg.org/tidy-html5/quickref.html

**Comment by geoffmcl** [comment]
@rickdog yes it is appears wrong... will fix it soonest... thanks for reporting...

**Comment by geoffmcl** [comment]
@rickdog that link should be fixed now... advise if you find any others... thanks...

**Comment by geoffmcl** [comment]
After a few more tries, SEEM to have now got this right ;=()

Required checking out the gh-pages of the tidy-html5 repo, and modifying documentation/_posts/2000-01-01-part_intro.md...

But still do not quite understand why a url reference `[2]: /tidy-html5/tidylib_api/` works by resolving to http://www.htacg.org/tidy-html5/tidylib_api/ which gets there, but the actual documentation is in repo root/tidylib_api???

The mysteries of yaml ;=))

And also manage to add some garbage to the page, which will also try to fix...
