### ISSUE TITLE
Binaries Links ran into 404

### ISSUE THREAD

**Issue by RalfRoemling** [htacg/tidy-html5#214]
Hi Overthere,
thx for your great work on tidy5. I tried downloading from http://www.htacg.org/binaries/ but the links seem to be broken, I only get 404s. Can you reproduce this?

Regards,
Ralf

---

Ralf Roemling 
Websites | Mailings | Search Engine Optimization | www.roemling.org

**Comment by geoffmcl** [comment]
@RalfRoemling yes, we are aware of that and it should be fixed shortly... thanks for reporting...

It is for that reason that we have not yet added any later versions...

And it is one of the last few remaining things before setting up the first 5.0.0RC1 for testing.. We want to make sure the release candidate is available for the widest testing possible, not only for those who can compile from source...

Soon I hope ;=))

**Comment by RalfRoemling** [comment]
Hi Geoff, thx for the update and I’m looking forward to RC1. Have a great time! Ralf :-)

**Comment by geoffmcl** [comment]
@RalfRoemling if you have `wget` or similar http fetch tools, or even in a browser, you can use -

wget http://www.htacg.org/binaries/binaries/tidy-4.9.26/tidy5-4.9.26-win64.zip

Note the double `binaries/binaries` folder...

**Comment by RalfRoemling** [comment]
Worx :-)

  Tags: html-tidy

**Comment by geoffmcl** [comment]
@RalfRoemling and now clicking on the links should start the downloads... maybe refresh the page...

In the coming days might put up one more version, just to make sure it all works... and develop a process to make it simple...

Hopefully later in the week should be ready for the first **5.0.0RC1**... this will be called just `tidy`... not before time ;=))
