### ISSUE TITLE
Not all options are applied and unexpected output generated

### ISSUE THREAD

**Issue by vladimir-kovalenko** [htacg/tidy-html5#219]
tidy-mark, doctype are not applied

My configuration file is as follows:

show-warnings: no
show-errors: 0
quiet: yes
output-xhtml: yes
output-xml: yes
word-2000: yes
doctype: omit
drop-proprietary-attributes: no
show-body-only: yes
indent-spaces: 0
indent: no
indent-attributes: no
wrap-asp: no
wrap-jste: false
wrap-php: no
wrap-sections: no
wrap-script-literals: no
lower-literals: yes
numeric-entities: yes
vertical-space: no
wrap: 0
quote-marks: yes
char-encoding: utf8
input-encoding: utf8
output-encoding: utf8
tidy-mark: no
show-body-only: 1

And the input is as follows:

<div><nav>
  <a href="/html/">HTML</a> |
 <a href="/css/">CSS</a> |
  <a href="/js/">JavaScript</a> |
  <a href="/jquery/">jQuery</a>
</nav>
</div>

  <a href="/html/">HTML</a> |
  <a href="/css/">CSS</a> |
  <a href="/js/">JavaScript</a> |
  <a href="/jquery/">jQuery</a>
</body>

I get the following output:

C:\Users\vlk\Desktop\Tidy\tidy5\bin>tidy5.exe source.html -config config.txt -o result.html
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
line 1 column 1 - Warning: inserting implicit <body>
line 1 column 1 - Warning: inserting missing 'title' element
Info: Document content looks like HTML5
3 warnings, 0 errors were found!

<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Windows version 4.9.32">
<title></title>
</head>
<body>
<div>
<nav><a href="/html/">HTML</a> | <a href="/css/">CSS</a> | <a href=
"/js/">JavaScript</a> | <a href="/jquery/">jQuery</a></nav>
</div>
<a href="/html/">HTML</a> | <a href="/css/">CSS</a> | <a href=
"/js/">JavaScript</a> | <a href="/jquery/">jQuery</a>
</body>
</html>

Problems:

1. Despite doctype: omit, there is a doctype generated and there is a warning about it.
2. Despite tidy-mark: no, there is tidy mark generated.
3. <html />, <body /> and <title /> elements are generated, despite it is a part of the document and in the previous version there was no such behavior.
4. Despite show-warnings: no, there are warnings shown.

**Comment by vladimir-kovalenko** [comment]
I have found the problem. I have specified command line incorrectly. Input file must follow all options. And it looks like the following:

C:\Users\vlk\Desktop\Tidy\tidy5\bin>tidy5.exe -config config.txt source.html

**Comment by geoffmcl** [comment]
@vladimir-kovalenko yes the input file must follow all options... then you can have more options and another input file, and so on...

Closing this as 'fixed', but thanks for reporting...
