### ISSUE TITLE
.NET and PInvoke

### ISSUE THREAD

**Issue by vladimir-kovalenko** [htacg/tidy-html5#220]
Hi,

I am trying to use .NET wrapper from https://github.com/markbeaton/TidyManaged. It runs, but I get output, which I do not expect and differs from what I get when I do the same from command line. As an example, doctype: omit and tidy-mark: no are not applied and I always get doctype and tidy mark in output.

I have reviewed all the code for both tidy and wrapper and I do not find where the problem may be.

Has anyone ever tried to do something similar?

**Comment by vladimir-kovalenko** [comment]
I figured it out. Below is information for someone who will have the same problem. 

Tidy HTML5 implementation added more items to certain enums. Specifically to TidyDoctypeModes and TidyOptionId. This made all enum values shifted and as a result setting one property resulted in setting property that follows the one in question. After syncing the specified enums, it all seems to work fine.

I am not sure if I will be able to make a patch to TidyManaged repository, but I will try.

**Comment by geoffmcl** [comment]
@vladimir-kovalenko yes, as you figured out each time Tidy5 changes an enumeration, or list of options `TidyManaged` has to be changed appropriately to match **exactly** ;=().

It would be good if you forked `TidyManaged` into your own github user space, cloned and worked on your fork to get it to match the current tidy5. Then when you 'fix' your fork, and pushed, you could present a pull request to @markbeaton to update there as well...

Good luck...

Meantime closing this as not being a tidy5 problem... but thanks for reporting and sharing...

**Comment by markbeaton** [comment]
Hi all - I'm the author of the TidyManaged code - unfortunately I don't have the time (or a Windows machine) to maintain (or update for tidy5) the TinyManaged project any more - @vladimir-kovalenko, would you be interested in taking it over?

**Comment by vladimir-kovalenko** [comment]
Hi Mark,

I am afraid I will not have time to duly maintain it either. I am new to GitHub. So if it is possible to make me a contributor or co-owner of the project so that you still be the owner of the project, I will try to make necessary updates from time to time.

As of now I made minimum needed changes to make it compatible with tidy5 and pushed.
