### ISSUE TITLE
Option to skip all unknown tags

### ISSUE THREAD

**Issue by qualiware-global** [htacg/tidy-html5#225]
There is a number of new-*-tags options. But it is not possible to set to skip all unknown tags. In my case there is no way to predict what user will enter (more likely copy-paste). This results in that parsing may end up with errors and there will be no output from tidy. With this regard there are two questions:

1. There is a chance that there is such an option and I just did not find it. Is there one?
2. If there is no such an option, do you think it makes sense to have one?

**Comment by geoffmcl** [comment]
@qualiware-global I know of no option to skip all unknown tag...

And not sure of the use case for such an option... maybe if you explained more...

If it is a problem of no output from tidy on an error then you can use the `--force-output yes` to ensure there is output...

**Comment by geoffmcl** [comment]
@qualiware-global see some more discussion on this in issue #119, where `custom` elements has been used instead of `unknown` tags...

Am closing this for now since there have been no further comments for over a month, but feel free to re-open or post a new issue...
