### ISSUE TITLE
Newlines insert in script elements; vertical-space option ignored

### ISSUE THREAD

**Issue by nokome** [htacg/tidy-html5#227]
tidy 5.0.0RC1 seems to always insert a newline at the start and end of script (and pre) elements. From a code aesthetics  point of view, this is undesirable for situations where the script is an inline element (in my case a MathJax element). Potentially related is the fact that the `vertical-space` option seems to have no effect. I am compiling against tidylib but the below illustrates the issue.

```sh
tidy --vertical-space no --indent no --wrap 0 --tidy-mark no html-test-doc.html
```

Input:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p>
      Some old equation <script type="math/asciimath">E=mc^2</script>.
    </p>
  </body>
</html>
```

Expected output:
```html
<!DOCTYPE html><html><head><meta charset="utf-8"><title></title></head><body><p>Some old equation <script type="math/asciimath">E=mc^2</script>.</p></body></html>
```

Actual output:
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title></title>
</head>
<body>
<p>Some old equation 
<script type="math/asciimath">
E=mc^2
</script>.</p>
</body>
</html>
```

**Comment by nokome** [comment]
So, I did some more trawling around through the issues and see that this is probably a duplicate of both #158 and #163. Sorry for adding more clamour.

**Comment by geoffmcl** [comment]
@nokome thank you for testing 5.0.0RC1... that is important...

yes, newlines inserted in `<pre>` tags #158 (feature and pretty print) is an old, **OLD** problem, still to be resolved... thankfully it is **NOT** a problem in some browsers, but others do make a new line in the display which should not be there! A big `horror` of `tidy`...

And Add option to prevent outputting unnecessary vertical whitespace #163 (feature and pretty print) is a clear request that `--vertical-space f` mean almost **NO** vertical space ;=)) Sort of like a compact html stream - just one line - maybe an interesting feature addition someone could be interested in coding...

Both `requests` are marked `indefinite future`, which means we are still looking for the C coder to take interest, give their time, and work on these two great **features**...

Are you the one? ;=))

Anyway, again, tar muchly for testing 5.0.0RC1... and reporting...

**Comment by nokome** [comment]
@geoffmcl I'll try to have another look at the code to see if I've got any chances of doing something constructive. If not, I would consider offering a bounty for one or both of these issues on Bountysource - would that be acceptable to HTACG?

**Comment by geoffmcl** [comment]
@nokome had a look at Bountysource - looks quite interesting... a good way to motivate a programmer ;=))

From my quick reading around their site I can not see any problem with accepting such code if it is released under the same, or a compatible license, as Tidy, as written in the header tidy.h...

But I am no expert in these matters...

**Comment by geoffmcl** [comment]
@nokome as covered in #228, #231, and others, think we can close this now...
