### ISSUE TITLE
User leading newline text content of pre is eaten!

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#230]
Some of this converstaion was openned in #228 by @nokome... and note this is not related to #158...
 
When I open a `<pre>` tag I too can often start with a newline, like @nokome, and I expect that in the output..

While parsing the `<pre>` content **is** done using `void TY_(ParsePre)( TidyDocImpl* doc, Node *pre, GetTokenMode ARG_UNUSED(mode) )` where the passed in mode is ignored, and in getting the next text token, it uses `Preformatted` in `while ((node = TY_(GetToken)(doc, Preformatted)) != NULL)` that is **TOO LATE**!

The newline character was already eaten back in the `lexer.c(2599), in case LEX_STARTTAG:`

Tidy has done `ParseTagName( doc )`, returning the `>` of `<pre>`. 

A comment there makes the intentions very clear -

```
    /* swallow newline following start tag */
    /* special check needed for CRLF sequence */
    /* this doesn't apply to empty elements */
    /* nor to preformatted content that needs escaping */
``` 

And then proceeds to `eat` the next newline with -
```
    if ((mode != Preformatted && ExpectsContent(lexer->token))
        || nodeIsBR(lexer->token) || nodeIsHR(lexer->token))
    {
        c = TY_(ReadChar)(doc->docIn);
        if (c != '\n' && c != '\f')
            TY_(UngetChar)(c, doc->docIn);
        lexer->waswhite = yes;  /* to swallow leading whitespace */
    }
    else
        lexer->waswhite = no;
```

Now the passed in `mode` could in some circumstance actually already be `Preformatted`, but certainly not if we are parsing `<body>`, or indeed **MANY** other elements...

The selected solution is, just above the above `if`, to check what this `node` is, and if `<pre>` case, and maybe some others, do **NOT** eat the leading newline, with a patch something like -

```
    /*\
     * Issue #230: Need to KEEP this user newline character in certain 
     * circumstances, certainly for a <pre> startag...
     * Maybe this needs to be extended to other 'text' content nodes,
     * like style, script, ... if desired, required...
    \*/
    if ( nodeIsPRE(lexer->token) )
    {
        mode = Preformatted;
    }
```

Still to do some more testing, but so far this is looking good...

Sample HTML -

```
<!DOCTYPE html>
<html>
<head>
<title>newline inserted lost in pre tag</title>
</head>
<body>
<p>before</p>
<pre>
User newline here.
    Some indented content with newline.
Again user newline
</pre>
<p>after</p>
</body>
</html>
```

Maybe others could cut the above patch into their lexer.c, and test on their favorite html ;=))

Open for comment...

**Comment by nokome** [comment]
Great to see this addressed. I for one would like to see it extended to `<style>` and `<script>`.

**Comment by geoffmcl** [comment]
@nokome you may be **right**... but I need the code proof that these need such a `saver` ;=))

Maybe they too lose any leading newline ;=((

It is after all a simple extension of this patch... but I have not yet had time to fully followed the path for `<style>` or `<script>` content gathering...

Maybe some simple html5 examples would suffice... showing now, output, and expected...

**Comment by nokome** [comment]
My test file `test-newline-eaten.html`:

```html
<!DOCTYPE html>
<html>
	<head>
		<title></title>
	</head>
	<body>
		<pre>
Starts with newline</pre>
		<style>
Starts with newline</style>
		<script>
Starts with newline</script>
	</body>
</html>
```

What I get with my "no vertical space" fork rebased to upstream 33494a4aea444df56857513e17ee34fe92f678b9 (so including PR #229):

```sh
tidy --vertical-space no --wrap 0 test/test-newline-eaten.html
```
```
<!DOCTYPE html><html><head><meta name="generator" content="HTML Tidy for HTML5 for Linux version 5.1.2"><title></title></head><body><pre>Starts with newline</pre><style>Starts with newline</style><script>Starts with newline</script></body></html>
```

When I add @geoffmcl's patch and extend it to `<style>` and `<script>` (stencila/tidy-html5@a69ddfeec92cd4df27c161e0163629fd228cfbbe)

```sh
tidy --vertical-space no --wrap 0 test/test-newline-eaten.html
```
```html
<!DOCTYPE html><html><head><meta name="generator" content="HTML Tidy for HTML5 for Linux version 5.1.2"><title></title></head><body><pre>
Starts with newline</pre><style>
Starts with newline</style><script>
Starts with newline</script></body></html>
```
The latter is the expected output. :tada: 

Unfortunately, with vertical spacing on, you still get the extra newline in the  `<style>` and `<script>` elements.

```sh
tidy test/test-newline-eaten.html
```
```html
<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Linux version 5.1.2">
<title>
</title>
</head>
<body>
<pre>
Starts with newline</pre>
<style>

Starts with newline
</style>
<script>

Starts with newline
</script>
</body>
</html>
```

That is because PR #229 only addressed `<pre>` element. So, stencila/tidy-html5@0bf0d85 does the analagous fix for script and style and then you get the expected,

```sh
tidy test/test-newline-eaten.html
```
```html
<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Linux version 5.1.2">
<title>
</title>
</head>
<body>
<pre>
Starts with newline</pre>
<style>
Starts with newline</style>
<script>
Starts with newline</script>
</body>
</html>
```

Note that there is code in `void PPrintScriptStyle( TidyDocImpl* doc, uint mode, uint indent, Node *node )` that provides for indenting. With indenting on style and script get indenting but pre doesn't. Not sure if that inconsistency matters. I personally would prefer style and script to be treated just like pre, but others may prefer them pretty printed.

**Comment by geoffmcl** [comment]
With the 5.1.8 release with lots of `newline` changes, fixes and the `--vertical-space auto` option closing this...
