### ISSUE TITLE
Creeping newline in script data...

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#238]
Sample:
```
<script>
var v = 0;
</script>
```

Output:
```
<script>

var v = 0;
</script>
```

At present Tidy v5.1.5.D231, that is the `issue-228` branch, unconditionally starts the script block with a newline. That is it flushes the tag (and attributes, if any), and adds a newline...

I guess in the past that was no problem since any leading newlines in the script data were eaten during the data collection, so was always just one at the beginning of the output...

Now Tidy! fully preserves any `user` newline at the beginning of a script tag, thus this newline in the output will also be preserved, and we now have two(2) newlines...

And if that out file is tidied, we would have three, and so on... that is a creaping newline in script data after each time tidy is run... a BUG ;=))

And on examining the lexer, there is a newline `('\n')` in the lexer, so this problem starts back up when the `<script ...>` tag is flushed to output... and a newline added...

Still chasing it down... note, it seems this **only** applies to the `issue-228` branch...

**Comment by geoffmcl** [comment]
Found a fix, but not entirely happy with it... it works but...

```
diff --git a/src/pprint.c b/src/pprint.c
index 4b4593d..e8f4523 100644
--- a/src/pprint.c
+++ b/src/pprint.c
@@ -1939,7 +1939,22 @@ void PPrintScriptStyle( TidyDocImpl* doc, uint mode, uint indent, Node *node )
 
     PPrintTag( doc, mode, indent, node );
 
-    TY_(PFlushLineSmart)(doc, indent);
+    if ( !xhtmlOut && ( node->content != NULL ) && (node->content->type == TextNode) && doc->lexer && doc->lexer->lexbuf )
+    {
+        /*\ 
+         * Issue #238 - First cut, but seems too 'messy' - need elegence!
+         * avoid adding a newline if the script text data begins with a newline 
+        \*/
+        uint start = node->content->start;
+        if (doc->lexer->lexbuf[start] != '\n')
+        {
+            TY_(PFlushLineSmart)(doc, indent);
+        }
+    }
+    else 
+    {
+        TY_(PFlushLineSmart)(doc, indent);
+    }
 
     if ( xhtmlOut && node->content != NULL )
     {
```

Anyway, the idea here is simple -

  - we are in a service PPrintScriptStyle(...), so
  - if the first text node text starts with a newline
  
avoid the PFlushLineSmart, which will 'add' another newline, unless `--vertical-space auto` - the macro `if (TidyAddVS)` tests this...

And to make sure we all agree on the `exact` meanings, we have -

 - `--vertical-space no` is the default, and means normal vertical space.
 - `--vertical-space yes` means classic - ie adds more vertical space - and 
 - `--vertical-space auto` means almost **NO** vertical space in output...

But here it seems we **MUST NOT** add another newline, else we get the creeping newline syndrome ;=))

Still looking deeper, like why this newline is in the lexer. Suspect it was not there previously... 

Normally leading spaces are either not collected, or trimmed off later... But there have been some changes in this code path... have the feeling less are trimmed... ???

**Comment by geoffmcl** [comment]
On exploring **why** this newline is in the lexer, as suspected, a previous fix for Issue #230 has **removed** the eating of a newline after a start tag, with the code fix :-

```
    /*\
     * Issue #230: Need to KEEP this user newline character in certain 
     * circumstances, certainly for <pre>, <script>, <style>...
     * Any others?
    \*/
    if ( nodeIsPRE(lexer->token) || nodeIsSCRIPT(lexer->token) || nodeIsSTYLE(lexer->token))
    {
        mode = Preformatted;
    }
```

We can see `pre`, `script`, and `style` are **excepted** from this process, which leaves the newline in the file data to be collected with the following `text`, thus gets into the lexer buffer... thus we get two on output... urgo the creeping newline...

Well except for the `<pre>` which now deliberately avoids adding an uncondtional newline after the tag output... see @bobbens @camoy Fix #158 which has no `PFlushLineSmart` after the PPrintTag( pre or textarea )...

We certainly want that for the `<pre>` so we can respect and keep any user newline in the text data, or not, as the case may be... but maybe that is not so true for `<script>`, or `<style>`???

And in that #230 discussion, initially only excepted `<pre>`, but was persuaded to add the other two for the `test-newline-eaten.html` test sample given...

Sooo, reverting my pprint.c (too messy!) patch, and returning to just excepting the `<pre>` tag with the simple fix...

```
diff --git a/src/lexer.c b/src/lexer.c
index 07b5274..5d5d0fa 100644
--- a/src/lexer.c
+++ b/src/lexer.c
@@ -2628,8 +2628,9 @@ static Node* GetTokenFromStream( TidyDocImpl* doc, GetTokenMode mode )
                  * Issue #230: Need to KEEP this user newline character in certain 
                  * circumstances, certainly for <pre>, <script>, <style>...
                  * Any others?
+                 * Issue #238: maybe **ONLY** for <pre>
                 \*/
-                if ( nodeIsPRE(lexer->token) || nodeIsSCRIPT(lexer->token) || nodeIsSTYLE(lexer->token))
+                if ( nodeIsPRE(lexer->token) )
                 {
                     mode = Preformatted;
                 }
```

Also seems to **fix** the problem ;=))

I certainly prefer this patch than the messy one in `pprint.c`... That is it seems best avoid creating the problem in the first place that would need a bigger fix later in the pprint output...

And running the new exe on the #230 `test-newline-eaten.html`, I seem to get as I expect, desire...

Ouput: with `--vertical-space no|yes`

```
<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Windows version 5.1.6.D231">
<title></title>
</head>
<body>
<pre>
Starts with newline</pre>
<style>
Starts with newline
</style>
<script>
Starts with newline
</script>
</body>
</html>
```

Note the default `no`, and a `yes` are the same! That is there are no additional newlines for `classic` mode in this sample...

Output: `--vertical-space auto' **the new feature**

```
<!DOCTYPE html><html><head><meta name="generator" content=
"HTML Tidy for HTML5 for Windows version 5.1.6.D231"><title></title></head><body><pre>
Starts with newline</pre><style>Starts with newline</style><script>Starts with newline</script></body></html>
```

Note the **only** newline for `auto` is the one the user put in the `<pre>`... well except the attribute wrap which I could turn off... or by adding `--wrap 0`...

Will reflect on this a little, and appreciate any comments and testing, but this looks like **the way forward** for this `issue-228` branch ;=))

**Comment by skynet** [comment]
:+1

**Comment by geoffmcl** [comment]
Have now pushed this fix to the `issue-228` branch, and bumped the version...

**Comment by geoffmcl** [comment]
Further testing with version 5.1.7.D231 indicates this is solved... so am closing this...

Again time to consider merging this `issue-238` branch back into `master` as mentioned in #231
