### ISSUE TITLE
Tidy doesn't work as expected when called from a Ruby script

### ISSUE THREAD

**Issue by mbmasuda** [htacg/tidy-html5#241]
I have a folder of Markdown documents that I translated to HTML using Pandoc 1.14.0.4.  The command used to translate from Markdown to HTML is:

    pandoc -t html5 -s --no-highlight --no-wrap MY_MARKDOWN.md -o MY_HTML.html

The `<head>` section from one such HTML file is as follows:

    <head>
      <meta charset="utf-8">
      <meta name="generator" content="pandoc">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
      <title></title>
      <style type="text/css">code{white-space: pre;}</style>
      
    </head>

Notice the presence of the empty `<title>` element.

I wrote a small Ruby script to process the HTML files so that I could paste them into my content management system.  The last line of my Ruby script is:

    %x(tidy -m -i -w 0 -utf8 #{File.join(dir, "*.html")})

This runs Tidy on all of the HTML files in the directory `dir`.  When I run this script on a folder of HTML files, the output from Tidy is:

    line 1 column 1 - Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    Info: Document content looks like HTML5
    No warnings or errors were found.

    line 1 column 1 - Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    line 1 column 1 - Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    line 1 column 1 - Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    line 1 column 1 - Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    line 1 column 1 - Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    line 1 column 1 - Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    line 1 column 1 - Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    Info: Document content looks like HTML5
    No warnings or errors were found.

    line 1 column 1 - Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    line 1 column 1 - Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    About HTML Tidy: https://github.com/htacg/tidy-html5
    Bug reports and comments: https://github.com/htacg/tidy-html5/issues
    Or send questions and comments to: https://lists.w3.org/Archives/Public/public-htacg/
    Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
    Validate your HTML documents: http://validator.w3.org/nu/
    Lobby your company to join the W3C: http://www.w3.org/Consortium

Note the warnings about missing "title" elements, even though they all have "title" elements present (albeit blank).

On the files with the warning about the missing "title" element, Tidy does not actually process the file.  I can tell because the indentation is not changed, and the following `<meta>` tag does not get added:

    <meta name="generator" content="HTML Tidy for HTML5 for Mac OS X version 5.1.2">

However, when I make a new folder with Pandoc-generated HTML files and re-run the Ruby script except commenting out the `%x(tidy -m -i -w 0 -utf8 #{File.join(dir, "*.html")})` portion, and then in the shell running

    $ cd /path/to/my/Pandoc-generated/HTML/files/on/which/I/ran/my/Ruby/script
    $ tidy -m -i -w 0 -utf8 *.html

I get the expected output of no warnings or errors on any of the files:

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    About HTML Tidy: https://github.com/htacg/tidy-html5
    Bug reports and comments: https://github.com/htacg/tidy-html5/issues
    Or send questions and comments to: https://lists.w3.org/Archives/Public/public-htacg/
    Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
    Validate your HTML documents: http://validator.w3.org/nu/
    Lobby your company to join the W3C: http://www.w3.org/Consortium

and Tidy has run on all of the files, which I can verify by looking at the indentation and seeing the addition of the Tidy `<meta>` tag.

As far as I can tell, the same files always fail to be processed by Tidy when run from the Ruby script.  I checked, and all of the `<head>` sections have empty `<title>` elements in them before running the Ruby script.  I don't know what the difference is between running Tidy from my Ruby script and running it directly in the shell so I am stuck.

**Comment by geoffmcl** [comment]
@mbmasuda I think the answer lies in your last comment...

> I don't know what the difference is between running Tidy from my Ruby script and running it directly in the shell so I am stuck.

Well one would expect `no` difference! Maybe they find different versions of tidy? Ruby may install its own? Need to check what the script output of `%x(tidy -v)` is, versus `$ tidy -v`. But even different versions does not seem to be the answer...

Are we talking about the exact **same** file set? 

That is, is the script `#{File.join(dir, "*.html")}` producing the **same** set of files as `$ ls *.html`? Obviously using the same runtime directory???

Hmmm, there is a little `trick` to **show** the file name in case of `warnings` or `errors` and that is add the option `--gnu-emacs yes` to the command...

This will cause `warnings` like you show -
```
    line 1 column 1 - Warning: inserting missing 'title' element
```
to be ouput as -
```
<file>.html:1:1: Warning: inserting missing 'title' element
```
so you can see the file names... then you can run tidy from the shell on that **same** file... 

Unfortunately there is no way to get tidy to output the file name if there are no `warnings` or `errors`... Maybe someone could `add` this feature to tidy ;=))

Needles to say, tidy version 5.1.2 does **NOT** issue a `warning` for a `blank` title element. And will in fact insert such a `blank` title element if none is found...

In the cases where this warning is issued you need to check and **see** that the file must not have a title element... This would be a **bug** if you could show me **one** instance where this is not true.

So on Rudy, just do not know, but hope there are some ideas, clues in the above...

**Comment by mbmasuda** [comment]
Hello @geoffmcl, thank you for the suggestions of things to check.  Since this problem is happening on my work computer, I will get back to you next week with the results of some tests.

**Comment by mbmasuda** [comment]
Hi @geoffmcl, I have done some tests and have the results.

I have confirmed that 

    $ which tidy

and

    $ tidy -v

at the shell return the same values as 

    %x(which tidy)

and

    %x(tidy -v)

in my Ruby script.

I also printed out the value of #{File.join(dir, "*.html")} in my Ruby script.

I created a new Markdown test file with this content:

    # Pandoc-Generated HTML from Markdown Source

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eros risus, suscipit eu finibus quis, posuere et tellus. Sed sed risus sit amet quam scelerisque condimentum. Nam iaculis urna ut tellus gravida lacinia. Fusce id tincidunt elit, vitae dapibus metus. Mauris in nisi eget lectus rhoncus feugiat. Donec consequat sapien quis condimentum eleifend. Phasellus sodales purus fermentum tellus egestas, non auctor magna condimentum. Pellentesque vehicula imperdiet dui vel sollicitudin. 

    Nullam vel urna sed tellus vulputate luctus ac et ante. Sed et ipsum felis. Nunc semper lorem non turpis mollis volutpat. Vivamus elementum felis at mauris tempus, id pellentesque elit commodo. Fusce iaculis quam dui. Ut sit amet varius velit. Quisque hendrerit eros a suscipit pulvinar. Ut nec est id leo consectetur euismod. Sed eget porttitor arcu. Nunc vel pretium sapien.

    Fusce ut mauris vel ex viverra vehicula. Sed tincidunt elit ut lacus maximus accumsan. Quisque molestie pretium massa, sed sollicitudin eros cursus vitae. Integer imperdiet eros nec aliquam facilisis. Vestibulum elementum velit quis neque laoreet egestas. Cras sodales mattis scelerisque. Nullam ante nulla, cursus at congue vel, condimentum nec dui. Aenean porta id neque quis iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus lacinia sit amet urna eu gravida. Proin maximus sodales erat, non pretium dui molestie vel. Donec quis congue lorem. Ut tempus libero metus. Pellentesque gravida massa quis urna blandit, nec facilisis magna malesuada.

    Aliquam pretium, nisl pellentesque interdum malesuada, nibh urna sagittis nisi, sed rhoncus orci odio quis odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut dignissim elit volutpat massa ultrices eleifend. In nec quam et nibh scelerisque facilisis. Duis congue orci eget aliquam tincidunt. Nam laoreet sagittis dui quis ultricies. Duis et lacus aliquet, elementum justo sit amet, maximus eros. Vestibulum tincidunt lacinia magna ac consequat. Maecenas convallis, augue pharetra tempus condimentum, orci libero feugiat lorem, eu laoreet enim erat ut eros. Duis egestas, mauris in sodales faucibus, tellus lectus elementum nulla, nec ullamcorper felis nisi a neque.

    In vulputate ipsum sit amet odio iaculis condimentum. Donec lacinia sapien ut dolor eleifend scelerisque. Nam egestas aliquam arcu a ullamcorper. Aenean eget diam eu leo tristique tempus. Pellentesque bibendum odio ipsum. Morbi vitae diam ligula. Integer finibus ultricies pharetra. Donec aliquet, tellus ut ornare pharetra, turpis ante consequat velit, sed dapibus justo augue vel est. Nunc mollis semper erat vitae dictum. Nunc volutpat, ligula nec mollis tristique, nulla tellus sollicitudin diam, ut congue nibh dolor ut erat. Suspendisse feugiat, orci sit amet convallis posuere, ipsum lacus ullamcorper tortor, et faucibus nisl mi ac metus. Vivamus rutrum orci eget eros sollicitudin, a aliquet ipsum lobortis. Integer placerat augue eu nibh euismod auctor. 

and I copied it three times into `1.md`, `2.md`, and `3.md` just to see if I would get different results.

Next, I used a Ruby script to run Pandoc on the Markdown files to translate them to HTML.  The purpose of using the Ruby script is so that it will convert a whole folder of Markdown instead of me having to run Pandoc on each file separately.  Anyways, the result is that there is a folder of HTML files.

Then I ran the other Ruby script that includes the call to Tidy.  The result was that I got the warning about a missing "title" element but nothing happened to the file despite there already being a "title" element in the Pandoc-generated HTML.

Next, I ran Tidy directly from the shell on my HTML files and it correctly reported no warnings.

Then I re-ran my Ruby script that includes the call to Tidy and still got the warning about missing "title"s.  A transcript of the interaction is below:

    [utilities Mon Aug 24 10:53:41]$ which tidy
    /usr/local/bin/tidy
    [utilities Mon Aug 24 11:18:11]$ tidy -v
    HTML Tidy for Mac OS X version 5.1.2
    [utilities Mon Aug 24 11:18:14]$ ruby pandoc.rb ~/Desktop/tidy-example/ html
    [utilities Mon Aug 24 11:18:29]$ ruby pandoc-to-hippo.rb ~/Desktop/tidy-example/20150824T111829-0700-html/
    /usr/local/bin/tidy
    HTML Tidy for Mac OS X version 5.1.2
    /Users/masudamm/Desktop/tidy-example/20150824T111829-0700-html/*.html
    /Users/masudamm/Desktop/tidy-example/20150824T111829-0700-html/1.html:1:1: Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    /Users/masudamm/Desktop/tidy-example/20150824T111829-0700-html/2.html:1:1: Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    /Users/masudamm/Desktop/tidy-example/20150824T111829-0700-html/3.html:1:1: Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!


    About HTML Tidy: https://github.com/htacg/tidy-html5
    Bug reports and comments: https://github.com/htacg/tidy-html5/issues
    Or send questions and comments to: https://lists.w3.org/Archives/Public/public-htacg/
    Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
    Validate your HTML documents: http://validator.w3.org/nu/
    Lobby your company to join the W3C: http://www.w3.org/Consortium
    [utilities Mon Aug 24 11:18:51]$ 
    [utilities Mon Aug 24 11:19:05]$ 
    [utilities Mon Aug 24 11:19:05]$ 
    [utilities Mon Aug 24 11:19:05]$ tidy -m -i -w 0 -utf8 /Users/masudamm/Desktop/tidy-example/20150824T111829-0700-html/*.html
    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.

    Info: Document content looks like HTML5
    No warnings or errors were found.


    About HTML Tidy: https://github.com/htacg/tidy-html5
    Bug reports and comments: https://github.com/htacg/tidy-html5/issues
    Or send questions and comments to: https://lists.w3.org/Archives/Public/public-htacg/
    Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
    Validate your HTML documents: http://validator.w3.org/nu/
    Lobby your company to join the W3C: http://www.w3.org/Consortium
    [utilities Mon Aug 24 11:19:42]$ 
    [utilities Mon Aug 24 11:19:56]$ 
    [utilities Mon Aug 24 11:19:57]$ ruby pandoc-to-hippo.rb ~/Desktop/tidy-example/20150824T111829-0700-html/
    /usr/local/bin/tidy
    HTML Tidy for Mac OS X version 5.1.2
    /Users/masudamm/Desktop/tidy-example/20150824T111829-0700-html/*.html
    /Users/masudamm/Desktop/tidy-example/20150824T111829-0700-html/1.html:1:1: Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    /Users/masudamm/Desktop/tidy-example/20150824T111829-0700-html/2.html:1:1: Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

    /Users/masudamm/Desktop/tidy-example/20150824T111829-0700-html/3.html:1:1: Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!


    About HTML Tidy: https://github.com/htacg/tidy-html5
    Bug reports and comments: https://github.com/htacg/tidy-html5/issues
    Or send questions and comments to: https://lists.w3.org/Archives/Public/public-htacg/
    Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
    Validate your HTML documents: http://validator.w3.org/nu/
    Lobby your company to join the W3C: http://www.w3.org/Consortium
    [utilities Mon Aug 24 11:19:59]$ 


This is the content of the Ruby script `pandoc-to-hippo.rb`:

    if ARGV.length != 1
      puts "This command takes one argument:"
      puts "1. Path to a folder containing Pandoc-converted HTML documents"
      puts "example: ruby pandoc-to-hippo.rb ~/Desktop/input"
      exit
    end

    path = ARGV[0]

    dir = Dir.new(path)

    dir.each do |filename|
      if File.extname(filename) == ".html"
        string = File.open(File.join(dir, filename)).read
        pandoc_to_hippo = {"actionscript" => "as3",
                           "cs" => "c#",
                           "html" => "xml",
                           "xml" => "xml",
                           "javascript" => "js",
                           "json" => "js",
                           "java" => "java"}
        string.gsub!('</code></pre>', '</pre>')
        string.gsub!('<pre><code>', '<pre class="brush:plain;">')
        string.gsub!(/<pre class="(.*?)"><code>/) do |match|
          value = pandoc_to_hippo.fetch($1, false)
          if value
            "<pre class=\"brush:#{value};\">"
          else
            '<pre class="brush:plain;">'
          end
        end
        string.gsub!(/<colgroup>.*?<\/colgroup>/,'')
        string.gsub!('<table>','<table class="auto-width">')
        File.open(File.join(dir, filename), "w").write(string)
      end
    end

    puts %x(which tidy)
    puts %x(tidy -v)
    puts File.join(dir, "*.html")
    %x(tidy -m -i -w 0 -utf8 --gnu-emacs yes #{File.join(dir, "*.html")})

**Comment by geoffmcl** [comment]
@mbmasuda you are certainly having some **ruby-pandoc-tidy** fun ;=))

Ok, you seem to have proved there is no difference between runnig Tidy! from the shell, or from within a ruby script... as expected... and you say you have checked it is the same file set... soooo...

First I do **NOT** know `pandoc` very well... I just installed it in my Ubuntu 14-04 system for a trial...

I created a simple 1.md -
```
# heading

para 1
```

And ran `$ pandoc -f markdown -t html5 -o 1.html 1.md`, and the default html I get **has no title**! It is just 2 lines -

```
<h1 id="heading">heading</h1>
<p>para 1</p>
```

Sooo, then when I run `$ tidy -m -i -w 0 -utf8 --gnu-emacs yes 1.html`, I get what I expect. 3 warnings about no doctype, no body, **and** a warning about no heading...

But, **take care here**, thanks to the `-m` option, now 1.html is converted to -

```
<!DOCTYPE html>
<html>
<head>
  <meta name="generator" content="HTML Tidy for HTML5 for Linux version 5.1.6.D231">
  <title></title>
</head>
<body>
  <h1 id="heading">heading</h1>
  <p>para 1</p>
</body>
</html>
```

Note a `blank` title element has been added by Tidy. And of course if I run Tidy! again I will now **not** get any warnings... simple before and after...

Now I note there is a `pandoc` option `-T title`, and maybe other options, and when I add this I do get `full` html, with all sorts of **strange** things added! But the important change is it does now have a **title** ;=))!

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <title>title - </title>
  <style type="text/css">code{white-space: pre;}</style>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<h1 id="heading">heading</h1>
<p>para 1</p>
</body>
</html>
```

And running `tidy` on this source has no warnings or errors, as expected...

So it seems all is fine with Tidy! ;=)) 

One should be quite **careful** when using the `-m` (modify the original input files) option. Naturally you can expect a difference between when Tidy! is first run on the source, and then further runs on the now `tidied`, changed source...

You will note here I am using the very latest Tidy!, version 5.1.6.D231, from the `issue-228` branch, but in this sample should be the same for the version 5.1.2 you show from the `master` branch...

And you should carefully check your `pandoc` options used... it seems the -H and -B also allow you to `include` other files in the html header... etc, etc, ...

After you run `$ ruby pandoc.rb ~/path html`, you should **physically** check the contents of **more than one** `~/path/number/???.html` file does contain a title element **BEFORE** you run Tidy!

Tidy is clearly telling you it does not! But it will be there **after** you run Tidy! with the `-m` option...

In your very first head example, you **do** show a blank `<title></title>`, which first is quite different to what I got, namely `<title>title - </title>`, but maybe your `pandoc` options used allows it to omit the title element in certain specific source md situations... Seems the only answer...

You showed options of `pandoc -t html5 -s --no-highlight --no-wrap MY_MARKDOWN.md -o MY_HTML.html` and using that I do get a `blank` title, I think due to the `-s`, but as suggested above, maybe the md source content influences whether this is added or not???

A question for the pandoc list/forum/...

I am sure when tidy reports missing 'title', there is **none** in that source file. You have to work out exactly what caused this to happen... as stated this seems to be the **only** explanation at this time...

I hope this helps clear things up for you...

**Comment by mbmasuda** [comment]
Hi @geoffmcl, thanks for taking the time to investigate.  The `-s` option in the Pandoc call makes the file standalone, and is what causes the empty `<title>` element to get added.  In the below transcript, I have a single Markdown document that I translate to HTML, then call my `pandoc-to-hippo.rb` script on.  I show the content of the HTML file before I run the script and it has a `<title>` in it.  Then I run the script and Tidy says there is a missing `<title>` but does not appear to actually do anything since I show the content of the HTML file again and it is exactly the same.  Next, I run Tidy from the shell and it reports no warnings and the Tidy `<meta>` tag gets added to the HTML.  Finally, I run `pandoc-to-hippo.rb` again and still get missing `<title>` warnings, even though Tidy just ran successfully from the shell.

    [utilities Tue Aug 25 10:06:32]$ ls ~/Desktop/tidy-example/
    tidy-example.md
    [utilities Tue Aug 25 10:14:42]$ cat ~/Desktop/tidy-example/tidy-example.md 
    # Tidy example

    Lorem ipsum dolor sit amet, consectetur adipiscing elit.[utilities Tue Aug 25 10:14:53]$ 
    [utilities Tue Aug 25 10:14:55]$ 
    [utilities Tue Aug 25 10:14:56]$ ruby pandoc.rb ~/Desktop/tidy-example/ html
    [utilities Tue Aug 25 10:15:18]$ ls ~/Desktop/tidy-example/
    20150825T101517-0700-html	tidy-example.md
    [utilities Tue Aug 25 10:15:22]$ ls ~/Desktop/tidy-example/20150825T101517-0700-html/
    tidy-example.html
    [utilities Tue Aug 25 10:15:30]$ cat ~/Desktop/tidy-example/20150825T101517-0700-html/tidy-example.html 
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="generator" content="pandoc">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
      <title></title>
      <style type="text/css">code{white-space: pre;}</style>
      
    </head>
    <body>
    <h1 id="tidy-example">Tidy example</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </body>
    </html>
    [utilities Tue Aug 25 10:15:45]$ ruby pandoc-to-hippo.rb ~/Desktop/tidy-example/20150825T101517-0700-html/
    /usr/local/bin/tidy
    HTML Tidy for Mac OS X version 5.1.2
    /Users/masudamm/Desktop/tidy-example/20150825T101517-0700-html/*.html
    /Users/masudamm/Desktop/tidy-example/20150825T101517-0700-html/tidy-example.html:1:1: Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!


    About HTML Tidy: https://github.com/htacg/tidy-html5
    Bug reports and comments: https://github.com/htacg/tidy-html5/issues
    Or send questions and comments to: https://lists.w3.org/Archives/Public/public-htacg/
    Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
    Validate your HTML documents: http://validator.w3.org/nu/
    Lobby your company to join the W3C: http://www.w3.org/Consortium
    [utilities Tue Aug 25 10:16:09]$ 
    [utilities Tue Aug 25 10:16:14]$ cat ~/Desktop/tidy-example/20150825T101517-0700-html/tidy-example.html 
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="generator" content="pandoc">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
      <title></title>
      <style type="text/css">code{white-space: pre;}</style>
      
    </head>
    <body>
    <h1 id="tidy-example">Tidy example</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </body>
    </html>
    [utilities Tue Aug 25 10:16:19]$ 
    [utilities Tue Aug 25 10:16:25]$ tidy -m -i -w 0 -utf8 ~/Desktop/tidy-example/20150825T101517-0700-html/tidy-example.html 
    Info: Document content looks like HTML5
    No warnings or errors were found.


    About HTML Tidy: https://github.com/htacg/tidy-html5
    Bug reports and comments: https://github.com/htacg/tidy-html5/issues
    Or send questions and comments to: https://lists.w3.org/Archives/Public/public-htacg/
    Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
    Validate your HTML documents: http://validator.w3.org/nu/
    Lobby your company to join the W3C: http://www.w3.org/Consortium
    [utilities Tue Aug 25 10:16:57]$ 
    [utilities Tue Aug 25 10:17:00]$ cat ~/Desktop/tidy-example/20150825T101517-0700-html/tidy-example.html 
    <!DOCTYPE html>
    <html>
    <head>
      <meta name="generator" content="HTML Tidy for HTML5 for Mac OS X version 5.1.2">
      <meta charset="utf-8">
      <meta name="generator" content="pandoc">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
      <title></title>
      <style type="text/css">
      code{white-space: pre;}
      </style>
    </head>
    <body>
      <h1 id="tidy-example">Tidy example</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </body>
    </html>
    [utilities Tue Aug 25 10:17:03]$ 
    [utilities Tue Aug 25 10:17:12]$ ruby pandoc-to-hippo.rb ~/Desktop/tidy-example/20150825T101517-0700-html/
    /usr/local/bin/tidy
    HTML Tidy for Mac OS X version 5.1.2
    /Users/masudamm/Desktop/tidy-example/20150825T101517-0700-html/*.html
    /Users/masudamm/Desktop/tidy-example/20150825T101517-0700-html/tidy-example.html:1:1: Warning: inserting missing 'title' element
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!


    About HTML Tidy: https://github.com/htacg/tidy-html5
    Bug reports and comments: https://github.com/htacg/tidy-html5/issues
    Or send questions and comments to: https://lists.w3.org/Archives/Public/public-htacg/
    Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
    Validate your HTML documents: http://validator.w3.org/nu/
    Lobby your company to join the W3C: http://www.w3.org/Consortium
    [utilities Tue Aug 25 10:17:17]$ 
    [utilities Tue Aug 25 10:17:20]$

**Comment by geoffmcl** [comment]
@mbmasuda one little thing... you can reduce the output by adding the options `--show-info no`... just reduces the clutter of repeated information...

#### But we are still in the same place ;=((

How can `$ ruby pandoc-to-hippo.rb ...` produce a different output from tidy than running `$ tidy -m -i -w 0 -utf8 ~/.../tidy-example.html`?

Maybe offer a virtual prize to someone that spots the problem, the difference ;=))

Other than that??? Keep at it! There must be a difference we are not yet seeing...

Again, I would state tidy will **not** issue a warning if it finds a title element in the document...

**Comment by geoffmcl** [comment]
@mbmasuda have you solved this yet?

But since there does not seem to be a problem with the actual Tidy code, am closing this, but feel free to re-open or open another issue...
