### ISSUE TITLE
website: "configuration quick reference here" is 404

### ISSUE THREAD

**Issue by BMOv2600** [htacg/tidy-html5#246]
[Tidy Documentation](http://google.com) links to this url

>[http://www.html-tidy.org/tidy-html5/quickref.html](http://www.html-tidy.org/tidy-html5/quickref.html)

Which is giving me a 404.

Chrome Version 44.0.2403.157
Yosemite 10.10.4

**Comment by geoffmcl** [comment]
@BMOv2600 thank you for reporting...

I **thought** I had fixed this! 

See issue #213... but as you can see I do not exactly understand `yaml` **voodoo** ;=))

That is the link given on the http://www.htacg.org/tidy-html5/documentation/ page... That seem to be still working...

Or have you found **another** that need fixing?

The `Tidy Documentation` link you gave only seems to point to http://google.com???

The `correct` link for the quick ref is http://www.htacg.org/tidy-html5/quickref.html

Maybe you could checkout the gh-pages branch -
```
$ cd tidy-html5
$ git checkout gh-pages
```

and find the link in the `documentation/_posts/*.md` docs that needs to be fixed...

**Comment by BMOv2600** [comment]
Yeah, sorry about that link.  "Tidy Documentation" in my OP should have been http://www.htacg.org/tidy-html5/documentation/. Clipboard malfunction, I guess.

Anyway, http://www.html-tidy.org/tidy-html5/quickref.html works for me now.

And I think I missed #213 because I didn't see it in my search for "404," or maybe I missed it because it was marked closed. 

I think you can consider the issue resolved now though.

Thanks.

**Comment by geoffmcl** [comment]
@BMOv2600 thanks for checking and confirming the link now correct...

Will close this, but feel free to re-open, or post other issues...
