### ISSUE TITLE
Dockerfile for tidy-html5

### ISSUE THREAD

**Issue by vielmetti** [htacg/tidy-html5#251]
`tidy-html5` has a number of build dependencies that are incompletely specified in the README. It would be super helpful if the project had a `Dockerfile` that specifically enumerated and installed all of those dependencies, so that `tidy` is easy to incorporate into a Dockerized workflow, and especially to assist in testing ports.

**Comment by geoffmcl** [comment]
@vielmetti I personally am basically a `Windows` person and only keep a dual boot linux distro for quick building and testing...

This was the first I had heard of `Dockerfile`, so can only leave it to others to deal with this... And although I work with a **considerable** number of FOSS projects, none so far have such a `beast` ;=))

But really tidy only has a few simple build dependencies as enumerated **clearly** in the README.md.

I suppose that would be -

 - $ [sudo] apt-get install git
 - $ [sudo] apt-get install cmake
 - And what ever installs gcc, libc headers, ie the normal build tools in linux
 
What else do you think is needed? 

To me Tidy! is **very** light weight compared to some project ;=))

**Comment by vielmetti** [comment]
Making progress - the only unexpected dependency was `xsltproc` to build the man pages - and some questions of how the releases are tagged so that I can pick up the desired one. When I get something workable I'll send in a PR.

**Comment by geoffmcl** [comment]
@vielmetti oops forgot that... Yes, in unix/linux there is an extra build dependency of `xsltproc`... for the man page...

And if you want to build the docs - `$ [sudo] make documentation` - also needs `doxygen`...

And there may be some other things if you want to generate release binaries - `$ [sudo] make package` - but not sure of that list...

But there is no real user use in building the `api documentations`, or the `release binaries`, so maybe these additions are special for `maintainers` that want to update the API documents and/or the binary distribution page...

A PR is always welcome ;=))

**Comment by vielmetti** [comment]
Yup! https://github.com/htacg/tidy-html5/pull/255 is a pull request. I had to pull in the `rpm` package because the build depends also on `rpmbuild`. Other than that, this does everything...tested on amd64...next to test is on ARM (Raspberry Pi and Pi 2, which will need a slightly different base image).

**Comment by vielmetti** [comment]
I closed the pull request because it was rejected. I'll look at putting together a new one if it makes sense.

I see getting a Dockerfile into the distribution as part of the sign of project maturity that will help Debian, Ubuntu, etc. decide to pick up the project as "official", since it greatly eases the automated build-test cycle. (Similarly, automating builds with Travis seems to be equally important, to make sure that as many automated tests run as possible on every single code change.)

That said, this particular first pass was proper to reject because it had some flaws that were evident. I will maintain it on my project fork and come back to it when the time is right.

**Comment by vielmetti** [comment]
I'll note an additional versioning dependency:

`doxygen` wants to be a recent version, e.g. version `1.8.9.1`. If it's an earlier release, e.g. the `Doxygen version 1.7.6.1` that Travis CI provides, then it will generate a whole raft of errors. 

On my Raspberry Pi 2, `doxygen` is running at `Doxygen version 1.8.1.2`. I don't know yet if that will work, have to check my build logs, and I don't know yet if there's a more recent build available.

**Comment by vielmetti** [comment]
PR was rejected, so closing. Someone else who comes along can ask to bring it back up to life.
