### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by vielmetti** [htacg/tidy-html5#252]
When I do an `apt-get install tidy` on my Raspberry Pi running Raspbian (Debian), I get this version

```
Setting up tidy (20091223cvs-1.2+deb7u1) ...
```

The documentation should include whatever incantations are necessary to pick up the current released version of `tidy` through a Debian install from some repo.

**Comment by geoffmcl** [comment]
@vielmetti, yes it is very **sad** `apt-get install tidy` only seems to gets you a 2009 cvs version of Tidy! This is VERY OLD! 5 plus years...

But we, the HTACG Tidy community, can only urge package managers to pick up and offer later releases in their distribution... 

We have tagged some dozen `Releases` - https://github.com/htacg/tidy-html5/releases

We maintain our own binary distribution page - http://www.htacg.org/binaries/ - a page shown in the README.md

You should send a strong note to `Raspberry Pi` urging, asking, demanding, pleading, ... that they **update** their tidy package distribution to a later version...

And help us understand what **more** we, as HTACG, need to do to get the **latest** tidy into distribution...

Will leave this open in case others want to comment, but at this point I know of nothing else for Tidy! to do ;=((

Quite a number of issues have touched this package manager topic - #99, #120, #159, #174, #194, #223, #224, #231, and maybe others... just searching `package` and `manager`...

**Comment by vielmetti** [comment]
Noted in this bug on Ubuntu for tidy:

https://bugs.launchpad.net/ubuntu/+source/tidy/+bug/1029209?comments=all

**Comment by vielmetti** [comment]
And also noted in the `tidy-html5` page for Debian, which is I think where we need to go next:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=770129

**Comment by vielmetti** [comment]
Issue has been raised with the Debian community, and it's not a bug in tidy, so this can close.
