### ISSUE TITLE
Homebrew packaging for tidy-html5

### ISSUE THREAD

**Issue by vielmetti** [htacg/tidy-html5#253]
The current version of tidy-html5 available via homebrew is 4.9.35; it would be good to get the 5.0.0 release into that package system.

**Comment by geoffmcl** [comment]
@vielmetti it would be even **better** to get the latest **5.1.9** into homebrew ;=))

Release 5.0.0 is already several months old, **and** 

Release **5.1.9** has several **new** features, a few bug fixes, and is `stable`... already been tested lots... passes all 227 backward compatibility tests with no problems, all the accessibility tests... etc...

But hey, any and all distribution updates are great ;=))

**Comment by vielmetti** [comment]
5.0.0 is installed in Homebrew (and it already had been; a `brew update` pulled it in). Closing.
