### ISSUE TITLE
test script links to wrong binary ("tidy" vs "tidy5")

### ISSUE THREAD

**Issue by vielmetti** [htacg/tidy-html5#254]
If I do a build of the system with all default set and then try to run tests, the default tests do not find the `tidy` binary in the correct place.

```
testone.sh: Can NOT locate binary '../build/cmake/tidy5'!
testone.sh: Fix me with the correct location of the binary to run.
```

however the build with all defaults set creates `../build/cmake/tidy` , not `../build/cmake/tidy5` . 

Further there is no way to run that `testone.sh` script and override the location of the binary without editing the script.

**Comment by geoffmcl** [comment]
@vielmetti well `$ ./testall.sh` runs fine in my linux system...

See https://github.com/htacg/tidy-html5/commit/88a656f0293b3a1a457ef2a777117f2da6c66ff3

What version do you have?

**Comment by vielmetti** [comment]
ah, my fault, I was running 5.0.0. Updated my build...closing.
