### ISSUE TITLE
Release 5.0.0 to MacPorts

### ISSUE THREAD

**Issue by vielmetti** [htacg/tidy-html5#257]
Homebrew has 5.0.0, but MacPorts is a rev back at 4.9.36.

https://trac.macports.org/ticket/48838 is a ticket I just opened up.

Noting a previous issue https://github.com/htacg/tidy-html5/issues/120 where a lot of this was discussed. As I understand it, when MacPorts is watching a repository, it "automatically" gets notified of new releases if the new releases are (somehow) properly tagged.

**Comment by geoffmcl** [comment]
@vielmetti and read #224 for **lots** more on tagging...

I certainly hope tidy is now `(somehow) properly tagged`... ;=))

And is it just me, but again while this is an `interesting`, important comment, piece of information which is good to know by those of us very interested in tidy, but should the `issues` system be used for this? 

Why not a tidy list? Do we need other places opened for comments?

Here in `issues` we are faced with what `label` to apply to it, what `milestone` to add... what to do about it...

And then how, when is it closed? By whom?

As basically a `comment` on something you have done, completed, it is sort of self closing!

Or are you suggesting we should leave it open just so new comers can read it without clicking the [ closed ] filer.

If so, for how long?

A little confused...

**Comment by vielmetti** [comment]
This issue is closed when Macports releases 5.0.0 (or later). It hasn't done that yet, cf:

```
Edwards-MacBook-Air:~ emv$ /opt/local/bin/tidy -v
HTML Tidy for Mac OS X version 4.9.36
```

And it should stay open with the "Build/Install/Distribute" label until that task is complete, or until Macports closes their ticket one way or another.

**Comment by vielmetti** [comment]
The response from MacPorts, picked up by @ryandesign

```
#48838: tidy: update to 5.0.0
---------------------------------+--------------------------
  Reporter:  edward.vielmetti@…  |      Owner:  ryandesign@…
      Type:  update              |     Status:  assigned
  Priority:  Normal              |  Milestone:
 Component:  ports               |    Version:
Resolution:                      |   Keywords:
      Port:  tidy                |
---------------------------------+--------------------------
Changes (by ryandesign@…):

 * keywords:  tidy =>
 * owner:  macports-tickets@… => ryandesign@…
 * version:  2.3.3 =>
 * status:  new => assigned


Comment:

 Yes, I will do this. Because the library version changes, I will need to
 also identify all ports linking with libtidy and cause them to rebuild.
```

**Comment by ryandesign** [comment]
There's no reason to open a ticket in tidy's issue tracker if you want a port in MacPorts updated. Instead, you file a ticket in the MacPorts issue tracker.

**Comment by vielmetti** [comment]
Closing now, thanks @ryandesign - let us know if any of the ports linking with libtidy run into issues.
