### ISSUE TITLE
"Chocolatey" packaging for Windows distribution

### ISSUE THREAD

**Issue by vielmetti** [htacg/tidy-html5#259]
Chocolately is a package manager for Windows, which you can see here:

https://chocolatey.org/

> Chocolatey NuGet is a Machine Package Manager, somewhat like apt-get, but built with Windows in mind.

It would be very suitable to have the current builds of `tidy-html5` available through this package manager. At this point I am not sure the exact path to make this happen.

Discussion on Gitter at https://gitter.im/chocolatey/choco?at=55f5d0fe6cdc8ce37109e828 suggests "should be easy", and this helps issue #222 by making `tidy-html5` available through one more package manager.

**Comment by vielmetti** [comment]
I pointed the Chocolatey people at

http://www.htacg.org/binaries/

and they noted that this is marked "experimental"

> Note! This is an experimentatl binaries release! This is a WIP.

**Comment by geoffmcl** [comment]
@vielmetti agreed, the word 'experimental' has long outlasted its usefulness, if there was one...

Try again! 

Maybe need to push refresh to refresh your cache...

Thanks...

**Comment by geoffmcl** [comment]
@vielmetti have replied to https://lists.w3.org/Archives/Public/html-tidy/2015JulSep/0019.html

**Comment by vielmetti** [comment]
Rather than close this issue, it would make sense (if this doesn't belong in the main repo) to build another repo to host these files, e.g. the way https://github.com/atom/chocolatey or https://github.com/chevdor/ethereum-chocolatey .

It is, however, necessary to keep these files under revision control, so that if there are changes that they can be tracked.

**Comment by geoffmcl** [comment]
@vielmetti see reply on the appropriate forum...
