### ISSUE TITLE
offer a filter to HTML5-polyglot

### ISSUE THREAD

**Issue by ppKrauss** [htacg/tidy-html5#265]
The standard http://www.w3.org/TR/html-polyglot/
as commented here http://stackoverflow.com/q/28520661

**Comment by geoffmcl** [comment]
@ppKrauss thanks for the post... my first introduction to `polyglot markup` ;=))

In reading the W3C doc, the best definition I saw was -

"A document that uses `polyglot markup` ... parses into identical document trees (with some exceptions, as noted in the Introduction) when processed either as HTML or when processed as XML..."

Interesting idea... sort of subset of HTML5 that can be represented in XML... or something like that...

From stackoverflow -

> a tool that transforms (or filters losing spurious information) "any HTML5" into Polyglot XHTML5?

No, I do not know of such a 'tool'!

But the libTidy API could be used quite easily to **create** such a tool... as one of the posts mentions...

It could read the input into tidy's internal representation of the DOM tree, through the library API, filter, or adjust that tree, again through the lib API, deleting `spurious` information, then finally, again use the lib API, write an output...

So again, I do not know of such a tool, but one could be written using the libTidy API... 

Any takers? I would assist where I can...

**Comment by geoffmcl** [comment]
No further comments for over a month, so closing this for now...

Please feel free to re-open, or open another issue... thanks...

**Comment by ppKrauss** [comment]
Sorry, I lost the link here... 

* "libTidy API could be used quite easily to create such a tool": yes, I think also. Well, I think libTidy can be "the tool" also, not only "used to". Perhaps some parts of the [TR/html-polyglot](http://www.w3.org/TR/html-polyglot/) can be translated directly into XSLT (I can help to create at Github such generic-use XSLT), but others will be easy to implement here with a libTidy.

* the main use is to represent "only content" (no JS or CSS interface-oriented) for scientific articles, books, technical norms, etc.  in a neutral and interchangeable way.
 
... If you show how to start the task, I can help... I know XHTML, some C, DOM, XSLT, ... And undertand how to "translate" the W3C TR into algorithms,  but I am not a good C programmer.

**Comment by geoffmcl** [comment]
@ppKrauss oops, my offer to `assist where I can` does not mean I want to write such a **filter**! Just no interest...

To be able to create such a tool, and use the libtidy API, you have to be able to write C/C++ code. It can parse HTML/XHTML, and build a tree of nodes, that could be **filtered**, or **converted** to give a  `html-polyglot` output... If that the `tool` you are looking for!

We provide a simple [Hello World](http://api.html-tidy.org/tidy/tidylib_api_5.0.0/tidylib.html#example_hello) skeleton showing basic API services...

The source of the tidy [console app](https://github.com/htacg/tidy-html5/blob/master/console/tidy.c) is itself an example of a html file input, and then an output in various forms...

I have more examples in my [tidy-test](https://github.com/geoffmcl/tidy-test) repo, some of which, for example fetch a url page, using libcurl, and output just the text (url2txt). This show how to enumerate the tidy nodes set up from parsing the html document, and just show some of them, in this case the text nodes, but that is the same idea of a `filter`...

These all **show how to start the task**, but that certainly requires being able to read and write C/C++.

To repeat. Any takers? I would assist where I can...
