### ISSUE TITLE
AARGGGGHHHHHHH = Docs

### ISSUE THREAD

**Issue by pedromorgan** [htacg/tidy-html5#270]
Am so confused..

I am trying to help with the docs and to get to this again
http://tidy5docs-htacg.rhcloud.com/
Which was not popular and no feedback..

So guys

there
https://github.com/htacg/tidy-html5/tree/master/documentation
and
https://github.com/htacg/tidy-html5/tree/master/build/documentation

So when u decide which is the real one and the other is exised then please let me know ..
Am not a fan of co joined twins.. whilst coding...probably.. maybe ...

**Comment by pedromorgan** [comment]
So @geoffmcl  I think u realise like I just done that its a cmake build.. (doh! brain cells)...

And can see it here ;-))))))))))))
http://www.htacg.org/tidy-html5/tidylib_api/

I want that site to be here..
http://www.html-tidy.org/

And to roll the copy and "fluff" into an into to docs..

At the moment.. its really f*(&^%& confusing what is what..

I suggest end target for docs and Api docs and "@new features" and "@dereciated"
is autogen from doxygen and end up here
http://www.html-tidy.org/
So the others will need to redirect.. ..

This way its all in the "tidy-html5" repos with minimal overhead.. and bound together using doxygens features such as TODO, etc etc etc 

imho and highly recommended for u young c hackers...
Trust me I deal with php and java coders, but doxygen is it.. and even @geoffmcl  can change a home page..

**Comment by pedromorgan** [comment]
Infact @geoffmcl 
We can include the "CODESTLYE" and other files on the site here.. 
http://www.html-tidy.org/

**Comment by geoffmcl** [comment]
Hi @pedromorgan, thanks for looking into this...

Yes, I/We tried to **move** the `documentation` source from `build/documentation` to just the `documentation` sub-directory... Anything remaining in `build/documentation` is intended to be **deleted**.

And yes, the building of the doxygen API docs is just a cmake process... 

To generate the API documentation you need to do the standard tidy build first, no need to install, and then add an important cmake option -DBUILD_DOCUMENTATION:BOOL=YES to add a documentaion target... as follows...

```
$ cd tidy-html5
$ git checkout master
$ git pull
$ cd build/cmake
$ ./build-me.sh # simple build, and then, and if all ok...
# gen docs target...
$ ./build-me.sh -DBUILD_DOCUMENTATION:BOOL=YES
$ [sudo] make documentation
```

And in looking at the CMakeLists.txt that sets up this target I note an **error** on [line 216](https://github.com/htacg/tidy-html5/blob/master/CMakeLists.txt#L216).

This line uses the `tidy1.xsl` from `build/documentation` which is **wrong**! Now the only difference between the two `tidy1.xsl`, is a relative PATH to tidy-config.xml -

```
27c27
< <xsl:variable name="CONFIG" select="document('../cmake/tidy-config.xml')"/>
---
> <xsl:variable name="CONFIG" select="document('tidy-config.xml')"/>
```

Tell me the PATH change for `documentation/tidy1.xsl`, if any, and I will effect the **fix** for CMakeLists.txt... that should make the `build/documentation' folder completley redundant, and can be **deleted**!

Also just to be very clear, there are sort of **two** tidy sites for these doxygen generated API docs - 

 1. http://www.htacg.org/tidy-html5/tidylib_api/, **and**
 2. http://www.html-tidy.org/tidylib_api/
 
Maybe this is the reason why I can not get the links correct! See #268, #214, #203, and maybe others... It seems when adjusted for one, the other becomes a **broken link**... or something???

I suppose we could questions - do we need to keep **both** URI? - I would certainly **prefer** to keep then **both** if the generated links can be got right! And they are both just DNS records with the actual docs in the repo...

And I even like, would keep things like - http://tidy5docs-htacg.rhcloud.com/. and/or say tidy.freeflightsim.org... and/or https://travis-ci.org/vielmetti/tidy-html5/jobs/80416894 if  @vielmetti chooses to expose the docs he built... and others...

Is it not better to have **more** sites, rather that put all the eggs in one basket, and redirect all others to it?

And while all links to within the `tidylib_api` folder can and should be relative if possible, there are some few sort of **external** links to outside the API docs themselves. Maybe these need to be **absolute**... or something...

And please do not **mix** or **confuse** -

 - these doxygen generated API docs, which is in the `master` branch, and 
 - the home-site pages, which are in the `gh-pages` branch... 
 
I like that these two things separated, and certainly do **not** want, nor would accept doxygen use on the home site pages - http://www.html-tidy.org - those `gh-pages` pages will should remain under manual adjustment at least for now...

And to **repeat** strongly and clearly, while I am not adverse to having some 3rd party API doc sites that just show the latest single form API docs, and thus we need to sprinkle some "@new features" and "@dereciated" fluff here and there for this...

But for tidy owned site(s), to be in sub folders... each containing the one time only built docs, version separated like -

 - tidylib_api/5.1.11
 - tidylib_api/5.0.0
 - tidylib_api/4.9.20
 - ... etc ...
 
As indicated in #248. Maybe we can have **two** doxygen configs - one the generate just one `tidylib_api`, and the other to use the lib tidy version information to generate in `tidylib_api/5.1.11`... this latter should be the default gen...

And if this is too messy, then **only** generate the version `tidylib_api/5.1.11` for the tidy owned sites... 

And we need to design a `tidylib_api/index.html` page that lists the available versions. I would like to add some notes about each version...

Hope we can get these doxygen API docs worked out, agreed... 

And once this is working, I would like to work with you to maybe add some more special pages, like we did for fgms... to try to add some `useful-to-programmers` pages, in addition to the copious listing stuff doxygen builds...

Maybe some HOWTO things like `create a new feature`, `enable debug options`, etc, etc... but that's for later...

Right now there is a need to get the API docs up there, published ;=)) HELP NEEDED!

**Comment by balthisar** [comment]
I've fixed all the links.

Please note that I created a new repo for documentation. This serves as a point for both the developers as well as the tidy-html-org website.

My suggestion is to remove _everything_ having to do with documentation (except the files needed to build it) from future releases (I'll eventually look into this myself if no one else does). currently there are redundant scripts that aren't needed with cmake, too.

Also note that rather than a subdirectory as indicated, these are now on the api.html-tidy.org subdomain. This made it easy to segregate, and will keep the main repo from exploding in size every time we add a new version.

I'll leave the open for now so that everyone can comment about current design. Specifically @geoffmcl wanted to see some notes or whatnot that are _not_ included with the current release. This should be simple to add.

**Comment by geoffmcl** [comment]
@balthisar thanks for the repo addition... looks good... 

And I too hope we can delete the `build/documentation` folder, in favor of just using only the `documentation` folder, thus removing some duplicated, and perhaps confusing, stuff...

Concerning the additional pages, I do not have any complete at the moment... I have some notes, but are not yet formed into complete pages, ideas...

So from my perspective this can be closed...

**Comment by balthisar** [comment]
> So from my perspective this can be closed...

Okay, then!
