### ISSUE TITLE
docs: update Mac install instructions to reflect tidy @5.0.0 release on MacPorts

### ISSUE THREAD

**Issue by vielmetti** [htacg/tidy-html5#271]
http://www.html-tidy.org/ at "Get Tidy" should reflect the availability of tidy-html5 v5.0.0 (as "tidy") through the Macports package manager.

```
#48838: tidy: update to 5.0.0
---------------------------------+--------------------------
  Reporter:  edward.vielmetti@…  |      Owner:  ryandesign@…
      Type:  update              |     Status:  closed
  Priority:  Normal              |  Milestone:
 Component:  ports               |    Version:
Resolution:  fixed               |   Keywords:
      Port:  tidy                |
---------------------------------+--------------------------
Changes (by ryandesign@…):

 * status:  assigned => closed
 * resolution:   => fixed


Comment:

 r140482 should fix it, except for zorba, which has other problems.
```

**Comment by geoffmcl** [comment]
@vielmetti thanks for the good idea ;=))

Maybe you or @ryandesign could assist by drafting some text for the [get_tidy](
https://github.com/htacg/tidy-html5/blob/gh-pages/index/_posts/1970-06-01-get_tidy.md) page, if you get the time...

In general we **welcome** updates, ideas for the site pages. These can be by -

 - making the suggestion, like this...
 - add some draft text changes, either as plain text, or in md
 - adding a PR, but would prefer some discussion on that before...

I will certainly keep Macports in mind, and try to think of some wording, paragraphs, outline... thanks again...

**Comment by ryandesign** [comment]
If you like, you could give short installation instructions using each package manager, perhaps grouped by OS. For example, you might start with this:

> ## OS X
> 
> * [MacPorts](https://www.macports.org/): `sudo port install tidy`
> * [Homebrew](http://brew.sh/): `brew install tidy-html5`

I'm omitting [Fink](http://finkproject.org/) because I couldn't find a modern version of tidy there yet.

**Comment by geoffmcl** [comment]
@vielmetti, thanks for the `you might start with this` suggestion. It looks good... a very positive start...

But, oops, I have a personal reversed on site updates... sorry, but that can happen ;=((

In general site updates are a **good** thing, but I have a rave about that... skip to `done rave` to skip this ;=))

At present the tidy site pages are in the `gh-pages` branch of the tidy-html5 repo... no problem with that... each time a push is done the site pages are updated... all great... simple... easy...

But how are the pages updated? Changed? 

At present the site pages are represented as markdown documents, processed by yaml, to produce html... no problem with that... it works fine... it looks good... good css... all perfect... So a change means modifying the MD, and push...

But this is **HTML Tidy** we are talking about! 

Why on earth would grandfather `tidy` have baby `yaml` produce html for it from md?

Tidy is the **king** of all HTML!

To me, `HTML Tidy` site pages should -
 
 1. be written in html5++
 2. be tidied, cleaned, indented, pprint-ed, by `tidy`
 3. bear the `HTML Tidy`, logo, and
 4. when tested with the W3C validator, bear the HTML5++ logo.

Maybe this can all be done using `markdown`. But that is not the point! 

This is **HTML Tidy**, and it seems to me it's pages should be in the repo as HTML, not MD!

I would seek some help to convert the current `markdown + yaml` to just `yaml`, publishing tidy cleaned html5 pages, each proudly showing the Tidy+W3C icons...

done rave!

So my personal reversal on site updates is that unfortunatley I do not have the time to look at `suggestions`, or suggested `text`... Maybe others can help with that...

I would look at a PR, where I can quickly review the simple change, and merge, **or** ask questions, why this, that...

So who out there can help with these site update issues? Like this, and others...

**Comment by balthisar** [comment]
http://www.html-tidy.org/#get_tidy

MacPorts instruction added.
