### ISSUE TITLE
ports: Fink package manager for Mac does not have tidy-html5

### ISSUE THREAD

**Issue by vielmetti** [htacg/tidy-html5#272]
`fink` is a Macintosh package manager.

http://pdb.finkproject.org/pdb/browse.php?summary=tidy

shows their current `tidy` support, which doesn't include tidy-html5. as mentioned in #271.

In reading through the `fink` documents I couldn't figure out how on earth someone would submit a port or package suggestion to them, so this issue can be closed when fink is aware that tidy-html5 exists and someone decides to do (or not do) a port.

**Comment by geoffmcl** [comment]
@vielmetti, well their help page says "You can provide feedback through the mailing lists, through the various trackers at SourceForge (see the home page for direct links), or directly to package maintainers.", but took some time finding addresses for the latter...

See https://sourceforge.net/projects/fink/ shows `Brought to you by: alexkhansen, danielj7, dmacks, dmrrsn, and 5 others` so you could write to them...

Certainly the http://pdb.finkproject.org/pdb/package.php/tidy package has a 2009 date (090425), and of course only points to the SF source... they are sadly in need of an update...

Maybe if you joined say the beginner or user lists, you could add a post there... and/or this tracker - https://sourceforge.net/p/fink/package-submissions/ - seems to specifically ask for package updates... or...

**Comment by vielmetti** [comment]
Ticket opened at https://sourceforge.net/p/fink/package-requests/1044/ , so I think this issue can close.

**Comment by vielmetti** [comment]
I'll open a new ticket (as a documentation issue) when this package shows up in Fink.

**Comment by vielmetti** [comment]
tidy-html5 is now available via Fink.
