### ISSUE TITLE
clean option bug

### ISSUE THREAD

**Issue by chg365** [htacg/tidy-html5#287]
![test html](https://cloud.githubusercontent.com/assets/13881994/10508887/58073802-735c-11e5-8819-b41f87ec4325.png)
![out](https://cloud.githubusercontent.com/assets/13881994/10508914/7a525f40-735c-11e5-8ccf-8a8afdf717ff.png)

**Comment by balthisar** [comment]
@chg365, can you post the text here? I can't type Hanzi for troubleshooting.

Also which version of Tidy is this?

**Comment by geoffmcl** [comment]
@chg365 am closing this as a **repeat** of issue #286... 

Thanks for the images, but now understand the utf-8 is badly mangled when being transferred from the span to the generated css... These images should have been only added to #286,,,

Please monitor #286 and only add any comments to there... thanks...
