### ISSUE TITLE
Add drop-tags with comma delimited list configuration option

### ISSUE THREAD

**Issue by logistiker** [htacg/tidy-html5#291]
Sometimes you just want to drop a tag or several tags (like `<script>` or `<style>`) for filtering purposes.  It would be nice if html tidy could do this with a specified list of tags through a "drop-tags" configuration option.  Then I wouldn't have to parse the document again after repairing it with tidy to remove certain tags.

**Comment by geoffmcl** [comment]
@logistiker this is related to feature request #226, to build a **HTML Cleaner**... 

As you can see, @flok99 added node and attribute deletions to the libtidy API...

So in your personalised version of `tidy.c` you could add a `deleteStyle(tdoc)`, a `deleteScript(tdoc)`, etc, just before the `status = tidySaveFile( tdoc, htmlfil );`, and it would be done... you would not 
have to parse the result again...

So this is easily achieved outside the tidy library. See [test226.cxx](https://github.com/geoffmcl/tidy-test/blob/master/src/test226.cxx) as an example, showing the tidy node tree before and after deletions...

Now, as to whether we take this one step further and add a configuration option like say `--drop-tags any;tag;list` into the tidy library... hmmm, that does feel like destruction of the document... Should libtidy offer such a killer option?

I do not think I personally would be interested in coding such an option, but maybe there are other use cases out there where this would be beneficial? Certainly if a PR was presented, with a sound use case, it would be considered, but no guarantee of inclusion...

That I will leave open for comment.

**Comment by logistiker** [comment]
The idea was to not have to parse the document again after tidy parsed the document in order to remove tags.  I figured that since tidy already has the ability to remove certain tags, it should be trivial to allow it to remove any tag.  I'm also parsing with tidy within php so I wouldn't want to affect the default behavior of tidy by changing tidy.c because the filtering of those tags may not always be desired (hence the configuration option).

**Comment by geoffmcl** [comment]
@logistiker it is trivial to remove any tag... that is agreed ;=))

But I guess we have a difference on `parse the document`. Even with such an option, this could not be done during what I will call `document parsing` phase - reading the file byte by byte and adding the contents to a (DOM like) node tree.

You could not get into deleting a tag until **all** of the tag say `<style...> 1000+ lines </style>` was in the tree... such a removal would have to be done `post document parsing`, where already many filter, many options begin to maniuplate, test, change the tree of nodes, ready for the final phase, output... 

Like an option `--show-body-only yes` does not mean we can avoid parsing the doctype and head, even though we know these will never be output...

So there is no double `parse the document` as you suggest. And such deletions can be just as efficiently handled in `tidy.c` as within the library...

Now, using tidy within say php is a use case for this being a library option... `tidy.c` is not involved... 

But why do you want such a `stripped` document? Now useless for human viewing, what html is about... I know lots of pages that are 100% script, and if you stripped the script tag you have nothing... just curious...

**Comment by logistiker** [comment]
In my case, I'm trying to adhere to requirements for an xml feed that cannot contain script or style tags so I have to strip them out even if it means the document doesn't render the same anymore.  I guess the end that's digesting it doesn't care if that's the case.  I can also imagine cases where you'd want to accept html in a form field but disallow script tags in them so malicious script cannot be posted.  

Anyway, in my xml feed case, I'm using tidy to clean up the html and then DOMDocument (via libxml2) to parse the html and create a dom tree for the simple purpose of stripping tags like script and style .  I tried using DOMDocument alone to parse the tree (it trips up a lot more with `<script>`)but it didn't fair as well as parsing with tidy, fixing the tree and then parsing again with DOMDocument to remove nodes.

**Comment by balthisar** [comment]
I can almost see a use case for this, but it wouldn't be very high on the radar. Stripping &lt;script.> and &lt;style/> tags when used with `show-body-only` has a potential case in document migration, for example. 

If you manage to post a PR I'd be happy to consider it.

**Comment by geoffmcl** [comment]
Agreed, `almost` a use case ;=))

Certainly a PR would be considered...

**Comment by geoffmcl** [comment]
As no further comment or action since Nov, closing this for now...

Please feel free to reopen, or raise another issue... thanks...
