### ISSUE TITLE
Don't mangle non-ASCII output filenames

### ISSUE THREAD

**Issue by praiskup** [htacg/tidy-html5#294]
See that tidyp has this fixed:
https://github.com/pghmcfc/tidyp/commit/eb122ce8af8f84d08f431

My older report:
http://article.gmane.org/gmane.comp.web.html-tidy.tracker/3019

**Comment by geoffmcl** [comment]
@praiskup sorry for the brief delay on this...

See @mcepl PR #298 which should fix this...

**Comment by geoffmcl** [comment]
@praiskup @mcepl PR #298 merged, and version bumped - thanks for this fix.
