### ISSUE TITLE
How to prevent trimming empty tags

### ISSUE THREAD

**Issue by Beep6581** [htacg/tidy-html5#299]
First I wanted to thank you very much for the continued work on this program!

I cleaned up a HTML5 page written by someone else which I'm tasked with updating, and they used some framework which uses empty `<i>` and `<li>` tags for inserting icons and other CSS things. Example:
`<i class="fa fa-envelope fa-3x"></i>`
What can I do to prevent tidy-html5 from stripping those away?

**Comment by geoffmcl** [comment]
@Beep6581 I guess the option you are looking for is `--drop-empty-elements no`! It defaults to `yes`. See [quickref](http://api.html-tidy.org/tidy/quickref_5.0.0.html#drop-empty-elements)

You may also want `--drop-empty-paras no` to keep those also... The other two `drop` options default to `no`...

HTH.

**Comment by Beep6581** [comment]
Thank you.
I'm using the latest git version but `--drop-empty-elements` does not appear in -help, I think it should be added there.
Speaking of which, it would also be good if "--help" worked, with the two dashes, as that is more common than the single-dash version, at least in Linux.

**Comment by geoffmcl** [comment]
@Beep6581 agreed the -h or -? help options only show a relatively small number to the available options - sort of like a brief help - but at the bottom, under `Miscellanious`, there are `-help-config`, and `-show-config`, which output the some 95 config options...

There are also some xml outputs, like `-xml-config`... this is used, with `xsltproc` to produce the `$ man tidy` page, which has both. It commences with the brief help, and then lists all config options... 

So if you are building from git source, and have `xsltproc` installed, and finished with `[sudo] make install`, then you have a `$ man tidy` with the latest, while some of our online help pages may not be...

It is agreed perhaps we should allow the most common unix `--help`, but should it just give the brief help, or the config help, or both? I am certainly not totally happy that at present all you see is `Config: unknown option: help`, and you are in stdin reading mode, needing like Ctrl+c to exit... will try to find time to look at this... unless someone beats me to it and offers a PR...

Meantime, I hope the `drop-empty-elements` works for you... and we can close this...

**Comment by Beep6581** [comment]
It didn't cross my mind that "config options" are what I want. My thinking went like this: if -help shows me the options I can use with tidy (I assumed those were all the options, because "Options for HTML Tidy for Linux" implies the list is complete), then "config options" must be some other things which are irrelevant to me, so I didn't even look. If you intend to keep -help brief, then it would be good to make it very clear that these are the "most popular options" or whatever the reason is you chose to show those particular ones, and that the user can "Refer to http://www.html-tidy.org/documentation/ for a *complete* list of options".

As for the question of whether -(-)help should be brief or complete, I think it would be easier for you to format text elsewhere instead of in the stdout --help response, and then just have -(-)help point the user to it, making it clear that the things they see in -(-)help are just a small subset.

tidy-html5 worked great for me, thank you for keeping it alive :)

**Comment by geoffmcl** [comment]
@Beep6581 well it is hard to know what to emphasise, what is brief help, what is full help, etc, and we may all differ in that decision anyway, but the words there near the bottom of the -? help seem clear that there is **more** to see ;=))

```
Use --optionX valueX for any configuration option "optionX" with argument
"valueX". For a list of the configuration options, use "-help-config" or refer
to the man page.
```

But as mentioned will try initially to include `--help` to be the same as `-help`, `-h`, `-?` as a  double `-` option exception that has a long tradition, at least in unix... And it seems we already except `--version` being the same as `-v`

And I personally do not know the exact reason that set were chosen for the brief help, but I do not think `popularity` was one of them ;=))

But using any new tool, utility, ... I generally do `--help` and `--version` and am disappointed, even annoyed, if I do not get a suitable response...

**Comment by geoffmcl** [comment]
@Beep6581 have pushed a small patch to version 5.1.21... turned out to be very easy, and we already do it for a number of options... thanks for this urging...

If you have any specific suggestions for improving the `--help` output would certainly listen...

Anyway, given that you have now found the full list of configeration options I guess we can close this...

Feel free to re-open, or add a new isssue - thanks.

**Comment by Beep6581** [comment]
Thank you Geoff :) Yes I will report if I find anything.
Kind regards.

**Comment by Kristinita** [comment]
**Type: Hack solution** :star:

### 1. Solution

[**Invisible space character `&#8203;`**](https://stackoverflow.com/a/37594612/5951529) inside the empty tag. Tidy don’t remove it, and it shouldn’t cause additional problems.

But it looks like a hack solution. I don’t think, that empty tags are the good practice of framework creators.

### 2. Example

The element of the Bulma framework [**required the markup with empty tags**](https://bulma.io/documentation/components/navbar/#navbar-burger):

```html
<span aria-hidden="true"></span>
<span aria-hidden="true"></span>
<span aria-hidden="true"></span>
<span aria-hidden="true"></span>

```

I replaced it to:

```html
<span aria-hidden="true">&#8203;</span>
<span aria-hidden="true">&#8203;</span>
<span aria-hidden="true">&#8203;</span>
<span aria-hidden="true">&#8203;</span>

```

I don’t get problems due to these changes.

Thanks.
