### ISSUE TITLE
The example code is wrong

### ISSUE THREAD

**Issue by benkasminbullock** [htacg/tidy-html5#301]
The example code found here:

    http://www.html-tidy.org/developer/

does not compile. First of all the #include directives are followed by semicolons:

    #include <tidy.h>;

This is very clearly an error.

I would suggest using a machine-readable file here which has been tested for compilability.

**Comment by geoffmcl** [comment]
@benkasminbullock thanks for the report... yes that sample code also had another error, namely that the include file `buffio.h` is now `tidybuffio.h`...

Refresh the page and it should be fixed... thanks...

**Comment by benkasminbullock** [comment]
@geoffmcl Do you want me to close this myself? Assuming so.

**Comment by geoffmcl** [comment]
@benkasminbullock, yes, feels nicer if the opener does the closing... thanks...

**Comment by balthisar** [comment]
Thanks for the fixes. I'm not sure how that got corrupted in the first place. It was a copy and paste job from the old site at http://tidy.sourceforge.net/libintro.html.
