### ISSUE TITLE
gnukfreebsd compilation

### ISSUE THREAD

**Issue by benkasminbullock** [htacg/tidy-html5#302]
Currently the default compilation fails on gnukfreebsd.

See this:

http://www.cpantesters.org/cpan/report/6e229334-8b8f-11e5-afef-e7dd1d056eec

and this:

http://www.cpantesters.org/cpan/report/77888ed8-8b85-11e5-afef-e7dd1d056eec

There doesn't seem to be a gnukfreebsd handler in the options in tidyplatform.h.

**Comment by geoffmcl** [comment]
@benkasminbullock ok, it looks like it is trying to include `<sys/utime.h>` because `HAS_FUTIME` is defined as 1.

```
tidy-html5.h:446:23: fatal error: sys/utime.h: No such file or directory`
```

It seems tidy-html5.h header is generated by make-c-file.pl, but looks like a simple combining of the tidy headers tidyplatform.h, tidyenum.h, tidy.h, and tidybuffio.h...

Does the gnukfreebsd platform have `<utime.h>` instead?

If yes, then we need a way to `detect` the OS... 

In tidyplatform.h we already have several BSD_BASED_OS, namely `__FreeBSD__`, `__NetBSD__`, `__OpenBSD__`, `__DragonFly__`, `__MINT__`, `__bsdi__`.

What would be the equivalent in gnukfreebsd? And `HAS_FUTIME` could be set to 0.

I further assume `PRESERVE_FILE_TIMES` is set to 1 in this platform. Is it? 

If this option is off then maybe we do not need the utime() functions, or perhaps there is an aternative that can set the file time appropriately...

Of course I need big **HELP** to fix this since I do not have access to a gnukfreebsd box to test...

**Comment by geoffmcl** [comment]
@benkasminbullock I have now looked at the `make-c-file.pl` found at [HTML-Valid-0.00_01](http://search.cpan.org/~bkb/HTML-Valid-0.00_01/MANIFEST), and you seem to have understood this, and there is a `sub print_h_defines ($out);` which does set -

```
#define PRESERVE_FILE_TIMES 0
#define HAS_FUTIME 0
```

This is set at the top, and maybe `tidybuffio.h` just needs to be adjusted to watch if these have already been so defined, and not reset their value... and does not need to include either `<sys/utime.h>` nor `<utime.h>` at all...

Should be a simple fix...

**Comment by benkasminbullock** [comment]
@geoffmcl Just to be clear I don't have gnuk/freebsd either, I got these reports from CPAN testers. I am just passing along the information. I don't want to use the file operations from tidy-html5 so I have switched that off, as you correctly noticed. The tests above are for this version of the source code:

https://metacpan.org/source/BKB/HTML-Valid-0.00_01

The results look like this:

http://matrix.cpantesters.org/?dist=HTML-Valid+0.00_01

The currently testing source code is as follows:

https://metacpan.org/source/BKB/HTML-Valid-0.00_02

I don't have gnukfreebsd results yet:

http://matrix.cpantesters.org/?dist=HTML-Valid+0.00_02

As it says in the comments of make-c-file.pl, I don't expect to use any of the file operations in tidy-html5, but only use it to operate on in-memory buffers, so for my own purposes I am just switching PRESERVE_FILE_TIMES off wholesale. However I reported this in case the tidy-html5 project wanted to support the gnukfreebsd platform for the standalone program or for other languages or projects.

I'll continue to report issues as I find them. I hope it helps.

**Comment by geoffmcl** [comment]
@benkasminbullock ok, you do not have a gnuk/freebsd, nor I presume a Darwin box for #305. And to me these small build problems can only be addressed by a person with that OS, and who is willing to conduct tests, and help in a fix...

There seems no way I could **guess** what needs to be done from these simple error reports, without the ability to test and confirm... We do want to support just about **every** platform, including `gnukfreebsd` and `darwin`, but I can only test in the platforms I have.

So this HTML Tidy `issues` does **not** seem like the right place for these reports. 

 1. First there could be **many**, and would increase if such [CPAN Testers](http://matrix.cpantesters.org/?dist=HTML-Valid+0.00_01) and/or [meta::cpan](https://metacpan.org/source/BKB/HTML-Valid-0.00_02) extend to say [HTML-Tidy-1.56](https://metacpan.org/pod/HTML::Tidy), and any others using HTML Tidy library.
 2. Could be open for a **long** time, until the above mentioned developer with that particular setup comes forward, thus pollutes the list.
 3. Some of the results seem inconsistent. `HTML-Valid+0.00_01` reports `darwin` as green, `gnukfreedsb` orange, and `HTML-Valid 0.00_02` the reverse, albeit different versions?
 
So I have moved these to one of our public list, say https://lists.w3.org/Archives/Public/html-tidy/ under the topic like `CPAN Tester Error Reports` - see https://lists.w3.org/Archives/Public/html-tidy/2015OctDec/0007.html

Accordingly, will close this and #305... as stated thanks for reporting...
