### ISSUE TITLE
Duplicate TidyAttr_ARIA_ORIENTATION in W3CAttrsFor_B

### ISSUE THREAD

**Issue by benkasminbullock** [htacg/tidy-html5#304]
There is a duplicate in the following:

const AttrVersion TY_(W3CAttrsFor_B)[] =  

 { TidyAttr_ARIA_MULTISELECTABLE,  xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },
  { TidyAttr_ARIA_ORIENTATION,      xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },
  { TidyAttr_ARIA_ORIENTATION,      xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },
  { TidyAttr_ARIA_OWNS,             xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },

Unfortunately due to the file size I cannot link directly but I have confirmed this with the latest version on the master branch, here:

https://raw.githubusercontent.com/htacg/tidy-html5/15563fff511eaf7aea848b7641aef2a6da7db008/src/attrdict.c

Using the following script:

    #!/home/ben/software/install/bin/perl
    use warnings;
    use strict;
    use utf8;
    use FindBin '$Bin';
    open my $in, "<", 'attrdict.c' or die $!;
    my $prev = 'nevermatch';
    while (<$in>) {
        if (! /^\s*$/) {
            if ($_ eq $prev) {
                print "$.: duplicate $_\n";
            }
        }
        $prev = $_;
    }
    
I also found the following duplicate lines, all containing ARIA_ORIENTATION:

635: duplicate   { TidyAttr_ARIA_ORIENTATION,      xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },

746: duplicate   { TidyAttr_ARIA_ORIENTATION,      xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },

857: duplicate   { TidyAttr_ARIA_ORIENTATION,      xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },

974: duplicate   { TidyAttr_ARIA_ORIENTATION,      xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },

1087: duplicate   { TidyAttr_ARIA_ORIENTATION,      xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },

1208: duplicate   { TidyAttr_ARIA_ORIENTATION,      xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },

1318: duplicate   { TidyAttr_ARIA_ORIENTATION,      xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },

1429: duplicate   { TidyAttr_ARIA_ORIENTATION,      xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },

1489: duplicate   { TidyAttr_ARIA_ORIENTATION,      xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },

1609: duplicate   { TidyAttr_ARIA_ORIENTATION,      xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50 },

This is from the distribution file attrdict.c of the 5.0.0 distribution.

I hope this helps.

**Comment by geoffmcl** [comment]
@benkasminbullock it certainly does... have pushed a fix to `master`...

Since it is not really a bug, will not bother to cherry pick the commit back into the 5.0.0 release... but it will be there for the future...

Thanks for catching this...
