### ISSUE TITLE
Darwin compilation

### ISSUE THREAD

**Issue by benkasminbullock** [htacg/tidy-html5#305]
As you can see here:

http://matrix.cpantesters.org/?dist=HTML-Valid%200.00_02

there have been some problems with compiling on Darwin. It seems that "uint" does not get defined on this platform.

**Comment by geoffmcl** [comment]
@benkasminbullock like #302, see https://lists.w3.org/Archives/Public/html-tidy/2015OctDec/0007.html

If you find more, please add them to the above list... thanks for reporting...

**Comment by benkasminbullock** [comment]
Possibly it might make things easier to use the C99 feature

    #include <stdint.h>

and replace all the `uint`s with `uint32_t`? It's implicitly assumed that uint is at least 32 bits in the code. This should be recognized by most compilers except the Microsoft Windows one which is not updated to C99, so for Microsoft Windows the uint32_t would need to be a macro or something. Just a suggestion.
