### ISSUE TITLE
Option "doctype-mode" is undocumented

### ISSUE THREAD

**Issue by benkasminbullock** [htacg/tidy-html5#312]
At the moment there is no documentation for "doctype-mode" in localize.c (it's missing an entry for `TidyDoctypeMode`). I found this error in 5.0.0, but I have confirmed this against 496c81c48d540f7f9ddf485cceef9443c8c7ad08.

**Comment by geoffmcl** [comment]
@benkasminbullock this is how it should be!

The TidyDoctypeMode is **ONLY** for internal library use. That is "doctype-mode" is **NOT** a user option, so no user documentation.

The first clue to that is in the public `tidyenum.h` - it says `/**< See doctype property */`, with no other explanation. Sort of like saying to a user, forget it, look somewhere else...

The next clue to a library developer is that there is no `parser` for the option. It is a NULL. Every other option has a `parser`, well except also the first `TidyUnknownOption`, and the last `N_TIDY_OPTIONS`...

While it is appreciated you **combing** through the source for `errors`, I hope you are beginning to learn that without digging deeper, like where is it used? how is it described, or not described? are all clues as to its nature, and a simple overview can lead to false positives.

So closing this as a non-issue... but feel free to re-open, or post a new issue.

**Comment by benkasminbullock** [comment]
> While it is appreciated you combing through the source for errors, I hope you are beginning to learn that without digging deeper, like where is it used? how is it described, or not described? are all clues as to its nature, and a simple overview can lead to false positives.

What? I'm not combing through the source for errors. I'm generating the documentation of the options from the source code automatically and noticed that this was undocumented.

https://github.com/benkasminbullock/html-valid/blob/eb6f0f47fb9c27468f07a657069ec91b56c427aa/tools/get-option-doc.c

**Comment by geoffmcl** [comment]
@benkasminbullock oops, did not mean to imply anything bad ;=() sorry...

Maybe change the line 79 to `printf ("doc: undocumented. May be an internal option.\n");`

And now we are **both** aware of what this is, you could skip it, or something...

**Comment by benkasminbullock** [comment]
Since this "option" causes a segmentation fault, the safe thing to do is not to document it at all, and actively prevent anyone from setting the option.

**Comment by balthisar** [comment]
@benkasminbullock, FYI tidy can generate similar output directly: `tidy -xml-config`. It successfully doesn't include `doctype-mode`. Granted you get XML output, but a simple XSL transformation with `xsltproc` can format it any way you want. Check out the `/documentation` in the source for examples (it's how we generate our documentation).
