### ISSUE TITLE
parseStatus is an unused field within TidyDocImpl

### ISSUE THREAD

**Issue by benkasminbullock** [htacg/tidy-html5#313]
The following field:

    tidy-int.h:70:    int                 parseStatus;

is not used anywhere else within the library, and is purely an internal variable (part of TidyDocImpl, non-user visible type).

**Comment by geoffmcl** [comment]
@benkasminbullock yes, it appears it is `unused` at this time... do not have time right now to go back in history to find where and when it was used, if ever...

But will leave it there as a sort of `spare` int variable in the main (opaque to users) structure. There have been times in development that I have wanted another `flag` in the internal doc, and will try to remember this next time that comes up... thanks...

That is I do not think this 4-byte allocation save is important at this time, so closing this, but thanks for pointing it out.

**Comment by benkasminbullock** [comment]
The reason to delete this is to make the source code easier for other people to read, not to save four bytes.
