### ISSUE TITLE
indent-with-tabs uses too many tabs for indent attributes

### ISSUE THREAD

**Issue by AnWeber** [htacg/tidy-html5#335]
tidy (v.5.1.25) uses too many tabs to indent attributes in new line
- config.txt

```
wrap-attributes: yes
indent-with-tabs: yes
indent-attributes: yes
```
- html.txt

```
<div id="test" class="test"></div>
```
- command line

```
tidy -config config.txt -o out.html html.txt
```
- out.html

```
<!DOCTYPE html>
<html>
<head>
<meta name="generator"
                        content="HTML Tidy for HTML5 for Windows version 5.1.25">
<title></title>
</head>
<body>
<div id="test"
                    class="test"></div>
</body>
</html>
```

Instead of 6 tabs 1 tab is expected. Using this file with indent-with-tabs disabled the formatting is valid.

[config.txt](https://github.com/htacg/tidy-html5/files/60168/config.txt)
[html.txt](https://github.com/htacg/tidy-html5/files/60169/html.txt)

**Comment by geoffmcl** [comment]
@AnWeber thanks for the report, sample, version, etc... yes, 6 tabs seems a tad too many ;=))

This is still present in the latest 5.1.32Exp version... `issue-329` branch...

Will look at this soonest. If you find a solution in the code, say in your fork, then patches, PRs very welcome... thanks...

**Comment by geoffmcl** [comment]
@AnWeber hmmm, without the [indent-with-tabs](http://api.html-tidy.org/tidy/quickref_5.1.25.html#indent-with-tabs) the indent for the `content="HTML..."` is 6 spaces... those spaces are converted to tabs... in pprint.c... [Line 685](https://github.com/htacg/tidy-html5/blob/master/src/pprint.c#L685)...

We need to do something else if `indent_char` is a tab, other than output 6 tabs! That is `if (indent_char == '\t')`, or the option `if (cfgBool(doc, TidyPPrintTabs))` is true... but what to do?

We could go back to where that was set, but there is some pretty hairy code there, and anyway that would really mess with the space indenting, outputting, so I think that `GetSpaces(pprint)` number stays...

But then it is the question of how many spaces does that user want the tab to represent, like 2, 4, 8, ...?

So then the tab count output could be `int cnt = spaces / user_tab_spaces; if ((cnt == 0) && spaces) cnt++;`. Now we know how many tabs to output... I do not think the answer should/will always be 1!

We could double up and use [tab-size](http://api.html-tidy.org/tidy/quickref_5.1.25.html#tab-size), but that is for input, not output. 

We could use [indent-spaces](http://api.html-tidy.org/tidy/quickref_5.1.25.html#indent-spaces) but I susupect that is already used in a different way... Note it is set to 1 in [config.c:1238](https://github.com/htacg/tidy-html5/blob/master/src/config.c#L1238) when the use tabs option is on...

So do we need another option, say `tab-stops` or something? Say TidyTabStops, "Representing the number of columns per tab when replacing indent space with tabs. See also indent-with-tabs, indent-spaces, indent-attributes, and indent"

Or can we default to something used in all cases, or fix this some other way... 

Comments, ideas, patches, PR, very welcome...

**Comment by AnWeber** [comment]
@geoffmcl my prefered solution is using 1 tab = indent-spaces

following use cases are possible

* always 1 tab
```
<div>
	<div aaa="foo1"
		bbb="bar"></div>

	<longtagname aaa="foo2"
		bbb="bar"></longtagname>

	<div aaa="foo3"
		bbb="bar">
		<longtagname aaa="foo4"
			bbb="bar">
			<div aaa="foo5"
				bbb="bar">
		</longtagname>
	</div>
</div>
```
the indention of attributes of foo3 and tag foo4 are the same. not nice, but acceptable.

* dynamic tab by using getSpaces() / magicvalue (in example 2).
```
<div>
	<div aaa="foo1"
				bbb="bar"></div>

	<longtagname aaa="foo2"
								bbb="bar"></longtagname>

	<div aaa="foo3"
				bbb="bar">
		<longtagname aaa="foo4"
									bbb="bar">
			<div aaa="foo5"
				bbb="bar">
		</longtagname>
	</div>
</div>
```
on long tag names getSpaces() results with more spaces. the attributes of foo1 and foo2 will get other indention position. not nice.
the attribute of foo4 gets a more indented than the next tag foo5. the indent of foo5 could be corrected to use the same count like attributes of foo4, but a complete document will look really choppy.

in my opinion the cleanest solution is using only 1 tab.

**Comment by geoffmcl** [comment]
@AnWeber I have no particular problem with the stop-gap method of always just using 1 tab, but nobody has stepped forward to make this change, so am moving the milestone to 5.3.

We are considering a release 5.2 shortly, and it is unlikely to be addressed and tested before then...

**Comment by AnWeber** [comment]
Thanks for the information. It is fine for me. I switched from using tabs
to spaces. So this feature has no top priority from my side.

Geoff McLane <notifications@github.com> schrieb am Do., 24. März 2016 19:26:

**Comment by geoffmcl** [comment]
While this remains a problem, but no work has been done on it, and we are about to release a 5.4, am moving it to `next` 5.5... thanks...

**Comment by geoffmcl** [comment]
@AnWeber reviewing this again, have decided to at least use `tab-size`, to reduce the **tabs** output, in most cases to 1...

Have moved this writing of the `indent_char` to output to a single `WriteIndentChar(doc)` service, where there is more control...

While it is not exactly related, have pushed this fix to the `issue-333` branch for testing... thanks...

**Comment by geoffmcl** [comment]
That `WriteIndentChar(doc)` may be helpful in issue #508 where we want to add one additional indent when lines are wrapped by Tidy..

**Comment by balthisar** [comment]
Because `issue-333` was merged, and upon testing, I will close this.
