### ISSUE TITLE
Ubuntu install error with DEB package

### ISSUE THREAD

**Issue by CuthbertJungle** [htacg/tidy-html5#344]
http://binaries.html-tidy.org/binaries/tidy-5.1.25/tidy-5.1.25-64bit.deb

Error message:
The package is of bad quality.

The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

Lintian check results for /home/david/Downloads/tidy-5.1.25-64bit.deb:
E: tidy: control-file-has-bad-permissions md5sums 0664 != 0644
E: tidy: maintainer-name-missing maintainer@htacg.org
Use of uninitialized value $name in pattern match (m//) at /usr/share/perl5/Lintian/Check.pm line 203.

**Comment by geoffmcl** [comment]
@CuthbertJungle ok, wow... I generated that in my Ubuntu 14.04 LTS, using CMake/CPack version 2.8.12.2...

Maybe need adjustments in [CMakeLists.txt](https://github.com/htacg/tidy-html5/blob/master/CMakeLists.txt#L346)? There are LOTS of CPack variables and maybe I missed some... suggestions... fixes... patches...

As basically a Windows person I really needs help in linux...

**Comment by sataris** [comment]
@geoffmcl  I believe the md5sum error is fixed from CMake 3.3+

**Comment by geoffmcl** [comment]
@sataris thanks for the information about CMake 3.3+

The actual package building has been moved out of this main source repo, to its own [binaries](https://github.com/htacg/html-tidy.org.binaries) repo, so we have a chance to use other packaging methods, other than cmake.

In any case we have concluded the CMake/CPack packaging is **too rudimentary** for both Windows and MAC OS X, and are already planning alternative `packaging` for those systems...

@CuthbertJungle we are considering a new release 5.2 shortly, and will try to certainly take care that any package we generate for unix passes the lintian tests... and have moved this to [Issue 1](https://github.com/htacg/html-tidy.org.binaries/issues/1) in the `binaries` repo...

Please continue any comments on this to there...

Meantime closing this here...
