### ISSUE TITLE
Ability to keep attribute name="value" together on a line, and newline before attribute names

### ISSUE THREAD

**Issue by mstanleyjones** [htacg/tidy-html5#367]
We would like to find the magic set of configuration options to ensure that an attribute's name and value are never broken by a newline if possible. For instance, we currently get output like this:

````
<p class="p">A scalable, distributed, column-oriented data store. Apache HBase provides real-time read/write random access to very large datasets hosted on <a class="xref" href=
"glossaries.html#glossary__glos_hdfs">HDFS</a>.</p>
````

We would prefer the output to be something like this:

````
<p class="p">A scalable, distributed, column-oriented data store. Apache HBase provides real-time read/write random access to very large datasets hosted on <a
 class="xref"
 href="glossaries.html#glossary__glos_hdfs"
>HDFS</a>.</p>
````

We're not too picky but we would like some way to ensure that the href= is on the same line as the "glossaries.html#glossary__glos_hdfs". Is this possible? If it's not possible right now, can you point me to the area of the code that I might be able to modify to make it so?

**Comment by mstanleyjones** [comment]
By the way, we can work around this with a scary but effective sed command, right after running the tidy. The following sed looks for lines that end with `=` and join them to the following line:

````
sed -i ':a;/=$/{N;s/\n//;ba}'
````

**Comment by geoffmcl** [comment]
@mstanleyjones there is presently no direct option to modify this... so this would be a new feature... 

You can set [wrap](http://api.html-tidy.org/tidy/quickref_5.1.25.html#wrap) to zero, `-w 0`, but then the whole paragraph `<p class="p">` through to `</p>` would be all one line, which you may also not want...

As to where it happens in the code, of course it is all in pprint.c. The 'printing' is a two layer approach. The node tree output it first stored in the `pprint->linebuf`, as an array of correctly encloded `uints`, and this array is flushed at various points to the actual output... this two level approach makes following exactly what happens a little difficult some times...

In this case the whole single string `large ... on <a class="xref" href="glossaries.html#glossary__glos_hdfs">` has been stored without a line break, during this first level placement, and at various points, a variable `pprint->wraphere` gets set...

In the output phase the first flush is just up to this `pprint->wraphere` point - see current `master` 5.1.36, line [610](https://github.com/htacg/tidy-html5/blob/master/src/pprint.c#L610) in the `WrapLine()` sevice. The line is output up to `href=`, a newline inserted, and the remaining text moved up in the head of the `pprint->linebuf` buffer by  `ResetLineAfterWrap()`... and the `PPrintTree()` continues...

So to change this behaviour you would have to change the setting of the `pprint->wraphere` point. This is set in `SetWrap()`, in `PPrintChar()` and `ResetLineAfterWrap()` if the char is a space, and in other places, usually to the current length of the line buffer, as each html element, or attribute component is added, so it is not easy to control... and is reset in `ResetLine`...

With such a new option, you could put all setting of `pprint->wraphere` into a single pprint function, and if the option is on, review what is in the buffer and set an appropriate value, but as suggested not so easy... 

And I am not sure of the use case for such an option. The memory is little dim, but I think others have desired something like this... maybe they could comment again...

HTH.

**Comment by mstanleyjones** [comment]
Thanks so much for the explanation, @geoffmcl. Since I found a workaround and obviously my request is not common, I'm not going to do this. It did strike me that the least invasive solution might be to just disallow `=` from being a wrappable character. But I understand that spacing in that context is not significant in XML so it's probably out of the scope of HTML Tidy to address it.

Regardless, I think your explanation will be a great resource when some hapless person in the future searches for something like this. Thanks again for taking the time.

**Comment by geoffmcl** [comment]
@mstanleyjones thanks for the reply... and close...

Actually it is not that the `=` is a wrappable character, but rather the `"` on the attribute value...

**Comment by jcubic** [comment]
I also have this problem but in my case I had whitespace after newline (the quote was indented) so I've added `-e ':a;/=$/{N;s/\n\s*//;ba}'` instead to my sed command.
