### ISSUE TITLE
Don't flag whitespace/newlines in data URIs

### ISSUE THREAD

**Issue by Warbo** [htacg/tidy-html5#371]
`tidy` seems to warn about URIs which contain newlines:

```
$ tidy -v
HTML Tidy for Linux/x86 version 5.1.36
$ echo -e '<!DOCTYPE html>\n<html><head><title /><body><img alt="test" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAHCAQAAACSTrSSAAAALklEQVQI12P4zwWCDFCSAUpC\nITZBmAYGbIIwDQzYBP8jjMVuH1gMl31wSVxGAwA9sy2r1NR+QwAAAABJRU5ErkJggg==" /></body></html>' | tidy -e

line 2 column 28 - Warning: <img> discarding newline in URI reference
Info: Document content looks like HTML5
Tidy found 1 warning and 0 errors!


About HTML Tidy: https://github.com/htacg/tidy-html5
Bug reports and comments: https://github.com/htacg/tidy-html5/issues
Official mailing list: https://lists.w3.org/Archives/Public/public-htacg/
Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
Validate your HTML documents: http://validator.w3.org/nu/
Lobby your company to join the W3C: http://www.w3.org/Consortium

Would you like to see Tidy in proper, British English? Please consider 
helping us to localise HTML Tidy. For details please see 
https://github.com/htacg/tidy-html5/blob/master/README/LOCALIZE.md
```

However, for data URIs it can be very useful to break up huge lines into more manageable pieces (e.g. editors like Emacs don't handle long lines particularly well).

Breaking up data URIs is specifically mentioned on their [MDN page](https://developer.mozilla.org/en-US/docs/Web/HTTP/data_URIs#Common_problems).

**Comment by geoffmcl** [comment]
@Warbo thanks for the comment...

While mozilla developers may think this is a `good thing`?, it seems the W3C validator also issues an error on your sample -

```
Error: Bad value 
... for attribute src on element img: Illegal character in scheme data: line break is not allowed.
... Characters should be represented in NFC and spaces should be escaped as %20.
```

The links given are [img](http://w3c.github.io/html/single-page.html#the-img-element) and [NFC](http://www.macchiato.com/unicode/nfc-faq)

Tidy is thus following this... 

Even [wikipedia/Data_URI_scheme](https://en.wikipedia.org/wiki/Data_URI_scheme) states "Permitted characters within a data URI are the ASCII characters for the lowercase and uppercase letters of the modern English alphabet, and the Arabic numerals. Octets represented by any other character must be percent-encoded, as in `%26` for an ampersand `&`.", but then strangely gives a red dot example broken into lines, which Tidy will warn about, and remove...

Now maybe you, and others, think there is a use case that this should be optional, but I will let you, them comment on that... 

For the moment Tidy correctly warns, and removes, such `invalid` characters...
