### ISSUE TITLE
significant whitespace added inside <textarea> and <pre>

### ISSUE THREAD

**Issue by JasonWoof** [htacg/tidy-html5#374]
originally reported here 9.5 years ago: https://sourceforge.net/p/tidy/bugs/787/

tidy adds whitespace inside textarea and pre tags. This changes the meaning of the document.
If I run tidy on the following:

```
<textarea>foo</textarea>
```
tidy turns this into:
```
<textarea>
foo
</textarea>
```
See the above link for more details and discussion.

The HTML5 spec says to ignore the first character in a textarea if it is a newline, but I don't think it says to ignore a newline at the end.

**Comment by geoffmcl** [comment]
@JasonWoof thanks for the quick reaction, nearly 10 years later, if you are the same Jason that filed that initial SF bug...

But I guess my post on closing that out-of-date SF bug should have said - "... **maybe** current tidy still exhibits this/these problems. **If it does** please file an issue..."

With the above input I get an output of **exactly** `<textarea>foo</textarea>` using tidy 5.1.36, the current `master` version... and I get the **same** with `<pre>foo</pre>`!

I have not yet closed [sf790](https://sourceforge.net/p/tidy/bugs/790/), a `pre` example, but when I do will make sure I add the **maybe** and the **iff** ;=))

If you get the chance to build the current tidy, maybe you can do some more testing, and close this issue if solved...

But thanks for caring about tidy and taking the time...

**Comment by JasonWoof** [comment]
Ahh, I didn't build the latest and test because you said "it seems current tidy still exhibits this/these problems". Glad to hear that was a typo :)

I am the original reporter :)

So glad to hear that tidy is being maintained! I thought it was abandoned long ago. Maybe I'll nudge debian to include something newer than 2009

**Comment by geoffmcl** [comment]
@JasonWoof yes, I will try to watch my wording ;=))

> Maybe I'll nudge debian to include something newer than 2009

That would be **FABULOUS** ;=))

Have a look at Issue #354 - seems the maintainer is [MIA](https://lists.debian.org/debian-devel/2011/06/msg00000.html), for many years, also called Jason! 

@Daniel has offered to pick up this tidy orphan but little or nothing visible is happening...

Anything you can do to help would be **MOST** appreciated, and as stated, in various places, just shout if there is anything I can do to help as a Tidy maintainer...

**Tidy is ALIVE and WELL!**

**Comment by JasonWoof** [comment]
Oh, I don't see what I could add to that thread, glad to see it's
in progress.

Sorry about losing your debian maintainer. That's rough. A game I
co-authored was in debian for a while until the maintainer
disappeared for a few years.

-- 
Jason
