### ISSUE TITLE
Localization in French - language_fr.po - POEdit

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#385]
Since January I have slowly progressed with my translations to French, using POEdit, although I hope **no** native French ever reads it ;=)) It really sucks!!!

But I have reached about 40%, and wanted to see how it looked. I have done **all** the error and warning messages. Have **not** done the access test messages, and only some of the big xml output descriptions. These are really hard! But felt I had enough to run some tests...

The first problems is that I started with a `Tidy.pot` dated 2016-01-23, but now note the current `master` contains one dated 2016-02-17.

Now there are no positional parameters. Ok, dealt easily with that - globally replace every `%1$` with `%`. Likewise for 2, 3 and 4. No problem... done... fixed in my `language_fr.po`, and POEdit had no probs...

Note all the `#, c-format` have been removed. Ok, again a quick global replace.

This got me down to a reasonable readable diff ;=)) 

Now I see many comment lines have been expanded from about 3 lines to 8 lines, and some even more. But I guess, since these are comment lines, I can forget these?

And as an aside, is it really necessary to repeat this 8 (or more) line comment block on just about every option? I would think that such an **`#. Important notes for translators:`** need only be shown once. And in fact should maybe **only** be in the [README.md](https://github.com/htacg/tidy-html5/blob/master/localize/README.md). But I am new to this, and I digress...

The main problem is in the changed `msgid` strings. Here I am not yet talking about **new** or **changed** `msgids`, but what looks like an error change, like an early one, `STRING_DOCTYPE_GIVEN`, but occurs on several others, from my diff -

```
@@ -37,7 +37,7 @@
 msgstr ""

 msgctxt "STRING_DOCTYPE_GIVEN"
-msgid "Doctype given is \"%s\""
+msgid "Doctype given is \"%s\
 msgstr ""

 #. The strings "Tidy" and "HTML Tidy" are the program name and must not be translated.
```

It looks like it is now missing the trailing `""` pair, which I assume important? But ok, maybe just a small `pot` problem to be fixed.

Then there are really `changed` strings, and `new` strings. **How to deal with these?**

Yes, when the `tidy.pot` is fixed, I can generate a **new** language_fr.po, and start again. And maybe my POEditor can help me recover, or merge the 40% I have already done, I suppose provided the `msgid` can be matched. Still to explore that. Or otherwise I could write say a perl script to handle the merge... not too hard... but I do not want to have to redo that 40%!

Anyway, seek advice, comments on how to proceed to use the `changed` tidy.pot. Maybe I missed something in the documentation. All help appreciated... and it seems it might help others with later `changes`, which will occur now and then...

**Comment by geoffmcl** [comment]
It seems this `tidy.pot` error of some missing trailing `""` on several strings comes from an error in `poconvert.rb`, because the strings seem ok in `language_en.h`.

````
    { STRING_DOCTYPE_GIVEN,  0,   "Doctype given is \"%s\""   },
````

I just ran `poconvert.rb` in windows, could not get it to run in linux, and the new file it created seems to have the same problems... But maybe I do not understand the process properly...

I can see in that Ruby script -

````
        # Eliminate C double-double-quotes.
        tmp = tmp.join.gsub(/""/) { |g| }
````

but maybe has nothing to do with this...

Some Ruby help needed, I think...

**Comment by balthisar** [comment]
Can you push the French script so I can take a look at it? Or email it to me.

The Ruby script _should_ be stable now, so if the POT you're using is from the stable version, then there should be no issues with quotes and comments and so on. When strings and such are added, this work magically, too.

Say that you're working with a POT, but master English changes in the meantime. If you generate a header with the tool, it will be based completely on the English header file using the French from the POT; the French header will be "clean." If you want your French POT to be clean, too, then reverse the process: make a "clean" header, then use the tool to generate a new POT. It will be based on the English, but carry the French translation.

The comments are VERY verbose, and very repetitive! This is a consequence of the PO/POT format, which wants a comment for every translated string. That is, translators can pick any arbitrary string to translate and have the special instructions there.

What I might do is keep this in the English header only, i.e., any time we generate a header file from a POT, I'll just leave off the comments. As noted above, when a header is converted to a POT, all of the comments come from the English header anyway.

No ETA I'm afraid; I'll try to review it this week.

**Comment by geoffmcl** [comment]
@balthisar as stated my `language_fr.po` is a WIP - only 40% done - so I do not want to push it, and then have to push each update I make there after, but will send it direct. I am trying to get into a habit of doing a few more each day, and do not want to get into perpetual 'pushing' ;=))

As stated, the Ruby script fails to run in my linux, so can not call that **stable** ;=))

````
~/projects/html_tidy/tidy-html5/localize$ ./poconvert.rb msginit ../src/language_en.h
./poconvert.rb:389:in `block (3 levels) in parse_header': undefined method `[]' for #<Enumerator:0x00000001f581a0> (NoMethodError)
	from ./poconvert.rb:388:in `each_value'
	from ./poconvert.rb:388:in `block (2 levels) in parse_header'
	from ./poconvert.rb:387:in `scan'
	from ./poconvert.rb:387:in `block in parse_header'
	from ./poconvert.rb:386:in `scan'
	from ./poconvert.rb:386:in `parse_header'
	from ./poconvert.rb:316:in `source_file='
	from ./poconvert.rb:290:in `initialize'
	from ./poconvert.rb:589:in `new'
	from ./poconvert.rb:589:in `convert_to_po'
	from ./poconvert.rb:1016:in `msginit'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from ./poconvert.rb:1140:in `<main>'
~/projects/html_tidy/tidy-html5/localize$ 
````

To my surprise it did run in windows, sans error -

````
F:\Projects\tidy-html5\localize>ruby poconvert.rb msginit ..\src\language_en.h
Wrote a new file to F:/Projects/tidy-html5/localize/language_en.po
msginit exited without errors.
````

Is that not the correct usage? Is not `language_en.h` the base for everything thereafter?

The output almost exactly matched the tidy.pot, one msg change and one new one, but **still** with the missing trailing `""` errors mentioned. That seems a **bug** in my book.

I am begining to understand the PO/POT format, but how many times does a tranlator want to read the same long comment, saying the same thing, especially about trying to stick to a 78 width per line, what to not translate, and what html to put around what content type. To me these are sort of **pre-instructions**. Once read once should be remembered, and applied throughout!

I could understand adding some individual message instructions, like adding where this is used, providing context to the string, that may help in the translation, understanding the meaning better, but not a continual nag about 78, no change to say 'HTML Tidy', and how to add html format to various components within the string. This is just repetative and thus un-helpful. As stated I think such common instructions should **only** be in the README before you start a translation. I would delete them **all** from the `language_en.h` header.

But I am not a `professional` translator. My first time using POEdit. Maybe they do expect such repetition! So they could start with any random message. Let's hear from others on that...

To overcome the present short comings of `poconvert.rb` I have written a `poconvert.pl`, not hard, to at first do the header to po conversion, and what I did was only ever add each comment once, and added a README output to collect them together as **common** pre-instructions, that apply to **all** strings... Maybe they could be in a README.en.md, and then we could add a README.fr.md, etc...

And I will be extending this to not only start with the `language_en.h` base, but also load my current `language_fr.po`, and thus fill in `msgstr` that have been done... that is a merge function... even warning that the `msgid` has changed, thus should re-check the translation... also a fun WIP...

So no problem on the ETA... I now have a way forward ;=))

**Comment by geoffmcl** [comment]
It's is amazing what you discover by taking the effort of a perl decoding the `language_en.h` file, and outputting a `language_en.po` file. You learn a **lot**!

And then loading my `language_fr.po` and **merging** that into the output, and also comparing the respective `msgid` text, for a given `msgctxt`, you learn even **more** ;=))

From my `msgid` diff I can see you made quite a number of **good** `msgid` changes between version 2016-01-23 and 2016-02-17. Thanks... Some minimal, but important additions of the ending `;` char on some entities, for instance, but many others, what all seem like, **changes-for-the-better**...

It took a bit to get the output all accepted by POEdit, firstly correctly dealing with the plurals, but mainly due to perl does **not** input/output utf-8 by default, but that can be fixed/forced. But there still seem some encoding problems in the results, as indicated in the POEdit display!

One particular one is the replacement of double inverted commas in English by the French guillemet characters `« »`... probably `U+00AB` and `U+00BB`, `&laquo;` and `&raquo;`... these still shows up wrong in the perl output in POEdit??? And a few others, to be explored...

Still to publicly publish my `poconvert.pl`... it is still a WIP...

But as I say... lots of fun moving forward...

**Comment by balthisar** [comment]
Hi Geoff,

What Linux are you using?

With a quick test in Ubuntu 14.04:

> jderry@UbuntuBox:~/Development/tidy-html5/localize$ ./poconvert.rb
msginit ../src/language_en.h
> Wrote a new file to
/home/jderry/Development/tidy-html5/localize/language_en.po
> msginit exited without errors.

Would you zip and send me the language_en.h file you're using? I doubt
they're different, but _something_ is different!

Also in Ubuntu using your POT:

> jderry@UbuntuBox:~/Development/tidy-html5/localize$ ./poconvert.rb msgfmt
translations/language_fr.po
> Wrote a new header file to
/home/jderry/Development/tidy-html5/localize/language_fr.h
> msgfmt exited without errors.

There error you're getting in the first one looks like some value is NULL,
but I can't track down the issue if I can't replicate it on my system! I'm
using the current, fresh-pulled-just-now master branch.

And just to test turning the H back into a PO:
> jderry@UbuntuBox:~/Development/tidy-html5/localize$ ./poconvert.rb
msgunfmt language_fr.h
> Wrote a new file to
/home/jderry/Development/tidy-html5/localize/language_fr.po
> msgunfmt exited without errors.


And now looking at the diffs, I see the issue with the quotes. I'll have to
track down if this is an H->PO issue, or if the PO->H didn't work.

Hmm... is this a locale thing? Let me try:
> jderry@UbuntuBox:~/Development/tidy-html5/localize$ export
LANGUAGE=fr_FR.utf8
> jderry@UbuntuBox:~/Development/tidy-html5/localize$ ./poconvert.rb
msginit ../src/language_en.h
> Wrote a new file to
/home/jderry/Development/tidy-html5/localize/language_en.po
> msginit exited without errors.

Well, that's an error; it should have generated a French PO instead of an
English one, but that's because "known locales" is lifted directly from
GNU, and it only recognizes two digit codes. I can use the l parameter to
force French, though:
> jderry@UbuntuBox:~/Development/tidy-html5/localize$ ./poconvert.rb
msginit ../src/language_en.h -l fr
> Wrote a new file to
/home/jderry/Development/tidy-html5/localize/language_fr.po
> msginit exited without errors.


My next steps:
- I'll see what's going in with the quotes.
- I'll eliminate the comments in non-English Headers.
- I'll try to figure out what the NULL failure is if you give me the header
causing it, and/or tell me which Linux you're using. If it's on the Pi,
though, I don't think I can virtualize that!

Hmmm... another thought, what's your Ruby version? Looks like I have
2.2.1p85 on my Ubuntu.


Overall working on the localization has been a fun learning experience for
me, too. I had no idea this big, formal ecosystem existed out there, but as
I look around it's _not_ just a GNU or Unix thing. I see PO's used in
servers, PHP, Ruby, professional translation services, and more. I hope by
somewhat supporting this, someone will come along and offer a translation
for us! I'll keep working on the Spanish as I have time, but it's probably
about the same quality as your French!





On Tue, Mar 22, 2016 at 8:40 AM, Geoff McLane <notifications@github.com>
wrote:

> It's is amazing what you discover by taking the effort of a perl decoding
> the language_en.h file, and outputting a language_en.po file. You learn a
> *lot*!
>
> And then loading my language_fr.po and *merging* that into the output,
> and also comparing the respective msgid text, for a given msgctxt, you
> learn even *more* ;=))
>
> From my msgid diff I can see you made quite a number of *good* msgid
> changes between version 2016-01-23 and 2016-02-17. Thanks... Some minimal,
> but important additions of the ending ; char on some entities, for
> instance, but many others, what all seem like, *changes-for-the-better*...
>
> It took a bit to get the output all accepted by POEdit, firstly correctly
> dealing with the plurals, but mainly due to perl does *not* input/output
> utf-8 by default, but that can be fixed/forced. But there still seem some
> encoding problems in the results, as indicated in the POEdit display!
>
> One particular one is the replacement of double inverted commas in English
> by the French guillemet characters « »... probably U+00AB and U+00BB,
> &laquo; and &raquo;... these still shows up wrong in the perl output in
> POEdit??? And a few others, to be explored...
>
> Still to publicly publish my poconvert.pl... it is still a WIP...
>
> But as I say... lots of fun moving forward...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/htacg/tidy-html5/issues/385#issuecomment-199562790>
>



-- 
---
Jim Derry
Clinton Township, MI, USA
Nanjing, Jiangsu, China PRC

**Comment by balthisar** [comment]
Have a look at branch `localize_tuneup` which should address the quotes issue (which was definitely a **bug**!), and generates headers without the POT comments (unless you add switch `--force-comments`).

I'm still running successfully on Mac OS X, Ubuntu 14.04, and Windows 7, though, with no strange errors.

**Comment by balthisar** [comment]
By the way your French text for `TEXT_HTML_T_ALGORITHM` has really strange wrapping in your PO file. I wonder if this is from your PO editor?

And for the record, unlike "real" PO workflow, our `msgid` is a throwaway; it's safe to ignore changes in DIFF. If your PO it out of date, a round trip conversion to H and back to PO will update all of the `msgid` strings, which are simply reference for the translators. As in Tidy, the _real_ key is the `msgctxt` field.

**Comment by geoffmcl** [comment]
@balthisar this will be brief - visitors, lunch, shopping, french - so a very short computer day!

#### Linux running poconvert.rb

First I do not think it can be the `language_en.h` file I used. That is the file in the repo, so should be exactly the **same** as you!

Now tried in RPI Raspbian, and it fails there too -

````
pi@raspberrypi ~/Projects/tidy-html5/localize $ ./poconvert.rb msginit ../src/language_en.h
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./poconvert.rb:8:in `<main>'
pi@raspberrypi ~/Projects/tidy-html5/localize $ ruby -v
ruby 2.1.5p273 (2014-11-13) [arm-linux-gnueabihf]
````

And my Ubuntu is 14.04.4 LTS, but the Ruby is `ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]`. Synaptic shows this as the 'default version', but also shows some installed ruby2.0 pieces, some installed??? And I can see there are many components of **both** not installed... maybe I am missing one, some of them????

Ah, ha, I can now see there is a ruby-full 1:1.9.3.4 **unchecked**. I will get around to trying this later, in Ubuntu. Maybe that will fix that there...

But I have a big problem in RPI in that my /dev/root is nearly full, and have started to read-up, and try to understand how to extend this partition, but it looks `complicated`, and **dangerous**... it now has a 1 TB USB Samsung drive attached so has ooddles of space...

#### Fixed bug

Glad you found the **bug**, and I am surprised it was the line I pointed out. Maybe I know more ruby than I thought ;=))

#### Changed msgid

I think I do understand the role of this, and `msgctxt`, and yes minor changes can be ignored, but **not** if the change results in a completely `different` meaning, thus the `translation` **has** to also be corrected. So washing this via a round trip conversion still means you must take notice of the change sometimes!

That is why in my `poconvert.pl`, in my merge function, taking the latest and greatest `language_en.h`, joining in my old `language_fr.po`, I can also alert myself to those `msgid` updates, changes, compared to the string I used for the translation, to see what translations I should re-visit with the aim of correcting them also. Does that make sense?

And that `problem`, if we can call it that, would be the same for **every** translation. Many changes in the base `language_en.h` have to alert the translator to re-look at certain translations. But this would be true for **any** tool-chain used. How is this handled in an all PO/POT tool-chain? How are base project.POT changes communicated to translated PO generators?

And, yes, I too have noted some quite messed up re-lining of some big messages. I am not sure if this was me doing something wrong, or POEdit doing the change... and have again started to think about using my `poconvert.pl` to carefully do the relining to max. 78... should not be too hard...

But as stated, off do other things today...

**Comment by balthisar** [comment]
I'll see if I can replicate the problem with older Ruby and make a fix.

The way that changes are made in the "real" GNU gettext system is the original, English string serves as the master key. If you make a change to the English string, it gets flagged as a new string in the PO/POT. There are modifiers for "fuzzy" strings that may or may not be the same. The gettext utilities will try to match existing translations to the new English string based on how closely the old and new strings match, and assign fuzzy automatically.

Is there a chance that we will completely change the meaning of a string? We might update wording, etc., but we'll never change something's fundamental meeting, I would think.

In any case, I'll consider a strategy for adopting "fuzzy"; I suppose we could embed extra metadata in the comments or something. I don't want to get TOO crazy with this, but when we modify the `language_en.h` file, one of us should regenerate all of the language-specific POT's. We should already be doing this today.

For the "we should already be doing this today" thing I could write a quick shell script or add a new command to the Ruby application to perform this updating automatically.

Then a new step would be to DIFF the new `language_en.h` with the previous one, and mark all of updated strings as "fuzzy" in the updated-POTs.

They'll then _stay_ fuzzy until a translator clears them.

For the purposes of diffing I would use git's diff, and take an sha as a parameter. So we would compare the current file system `language_en.h` with a version from a specific commit.

**Comment by balthisar** [comment]
In `localize_tuneup` branch, `poconvert.rb` should work on Ruby 1.9.3 now, tested in Ubuntu. I'm having difficulty installing.

On the Pi, did you `gem install bundler`? And then `gem install` from within the `localize/` directory? As the tool isn't using any strange gems that might end up in off-the-wall locations, it's _probably_ safe to delete line 8 from `poconvert.rb`; if installing the dependencies doesn't fix it, try deleting this line; if it works, feel free to push it (I don't want to push it untested, as I have no Pi!).

**Comment by geoffmcl** [comment]
@balthisar pulled the latest `localize_tuneup` branch, and can confirm `poconvert.rb` now works fine in Ubuntu, with Ruby 1.9.3... thanks...

On RPI, I think you meant `$ sudo gem install bundler`, and then in the `localize/` directory `$ bundle install`. And yes, after these 2 steps, `poconvert.rb` runs fine in RPI, at least for the `msginit` action... again thanks...

As far as I am concerned this `localize_tuneup` branch could be merged to `master`...

Concerning the **fuzzy** `msgid` changes, while I agree it would be perhaps rare we completely change the meaning of a `msgid`, but it could happen. And there is the simple case of say changing the `default` for example, has to also then be changed in **all** the translations. 

And then there are **new** strings, where it would also be nice if these were flagged. As you point out, since this all starts with the base `language_en.h`, then there is a git diff using a previous sha, assuming the person doing the translation for tidy is also git savvy... 

In my WIP `language_fr.po` case that turned out to be `$ git diff 9ae15f45a7e14 src\language_en.h`. This got me a reasonable diff to look at. Of course it is a little **muddied** by the previous 3 lines of comment to the new 8 lines beginning `Important notes for translators:...`, but ok can read past these...

Then there are still lots difference that **do** effect my current translation, like the simple cases of `<code>omit</code>` is now `<var>omit</var>`, etc... which do not actually effect the translation per se, but must still be adjusted in the french string.

But ok, I understand this is the **tough** work of the translator, and must be done... and we can only help where we can...

I am afraid I did not exactly understand `should regenerate all of the language-specific POT's`! Surely, at this stage we only have `tidy.pot`, the english base file, generated from extracting text from our code base of `language_en.h`. And then from that `tidy.pot` base we could have many language PO files... including one exactly equivalent, `language_en.po`...

Yes, when I say **finish** my `language_fr.po`, I suppose we could also generate a `tidy_fr.pot` for people who would prefer to translate from french to their native language, but we are certainly not there yet... But again maybe I am missing something else here...

As far as this issue is concerned, I now have a working `poconvert.rb` in **all** my systesm, and can quietly move forward completing the translation, as bad as it may be ;=))

**Comment by geoffmcl** [comment]
Wow, I just did a `msgfmt` on my most recent `language_fr.po`... copied the source language_fr.h to `src/`... a few fixes in `language.h`, compiled and ran like `$ echo abc | release\tidy -lang fr_fr` and it worked ;=))

Of course, the windows console output does not correctly support utf-8, so I saw some messy characters ;=/ But so nice to see warnings like -

```
Ligne: 2 Col: 1 - Attention:manquante <!DOCTYPE> d+¬claration
```

This is working fine... now to (slowly) work on the other 60% ;=))

**Comment by geoffmcl** [comment]
Oops, spoke too soon... still some very **bad** things... sent the output to a file, `-o temp1.txt`, and used a utf-8 aware editor to read it...

While the `Ligne: 2 Col: 1` and `Info:` msgs are valid UTF-8, and I see `french`, the other message file outputs contain the previous error hex `ef bf bf ef bf bf` ;=((

Obviously more fixes needed in #383... all message file output has to be **`unconverted`** - it is already valid utf-8... 

Some work to do... which is why I needed to get to this point to expose the problem...

**Comment by balthisar** [comment]
> I am afraid I did not exactly understand "should regenerate all of the language-specific POT's"! Surely, at this stage we only have tidy.pot, the english base file, generated from extracting text from our code base of language_en.h. And then from that tidy.pot base we could have many language PO files... including one exactly equivalent, language_en.po

My bad typo. I meant the PO's. If we change language_en.h, then we should make the new POT, and also update the existing PO's. This is fairly easy; I just did it `./poconvert.rb xgettext` which uses the English file by default, and `./poconvert.rb msgunfmt file1 file2...` (I regen'd these to add translator documentation to your new option).

What I'll do, though, is add a new command to poconvert (something like newbase) to do all of this automatically, but more importantly to FLAG the fuzzy stuff. Then anything that's changed in language_en will be marked as fuzzy in all of the PO's.

New strings will simply be blank in the PO's. POEdit and the PO online editors I've looked at will highlight these cases. And of course Tidy will fall back to English for these missing strings.

* * *

Ah, yes, on the RPI you need admin for Ruby gem stuff. I'll recommend you install RVM; it can manage multiple Ruby versions and multiple sets of Gems all in a user account. It made it _really_ easy to figure out what was wrong in 1.9.3, for example, without causing a world of hurt from dependency conflicts!

* * *

> Of course, the windows console output does not correctly support utf-8

Any particular characters causing you grief? I've been testing with Spanish which shares _some_ of the accented Characters with French, and they've been rendering properly. Of course there's the nuclear option of setting your system's locale to French; we know from getting Chinese working that even Chinese works in the Windows console with that option!

**Comment by geoffmcl** [comment]
@balthisar ok, that would be great to automate the update of the various language_XX.po files... and still to explore what this `fuzzy` means/does...

Yes, from reading only, installing RVM seems to allow multiple ruby versions... but I sort of hope I will never need that ;=)) I am not likely to get into ruby script debugging and fixing any time soon...

In the windows console, all multi-byte utf-8 characters are presently displayed only as sequences of extended ASCII characters, and I can not seem to find anything I can do to temporarily change that! Yes, as mentioned, there are deeper registry changes that can be made, through the control panel, then reboot... I am sure this would work...

In Control Panel -> Region and Languages - Administrative tab, it shows the current language as `English (United States)`, but there is a `Change System Locale...` button, which opens a dialog with a dropdown where I can select up to about 100 languages. I am sure selecting say `French (France)`, or `Chinese (Simplified, PRC)`, etc, and re-boot, I would then be able to 'see' the French say... But I am **not** willing to do this!

It is not a problem. As stated it all works well in the Ubuntu linux terminal, even when the locale is set to en_US. Running `$ locale` it shows  `LANGUAGE=en_US`, `LANG=en_US.UTF-8`, while most of the `LC_XXXX` show `en_GB.UTF-8`. But it **still** correctly displays the multi-bytes as a  single accented french characters. Similar in my Ubuntu 32-bit...

However, in RPI, with all en_GB, I get the same multi-byte extended ASCII display as Windows! Really do not understand why it is **different**? What have I somehow enabled in Ubuntu that I have not done here in Raspbian, another Debian derivative I understand?

And it is even stranger in my old Windows XP (32-bit)! It correctly displays the multi-byte utf-8 as a **single** character, but it is not the correct french accented character. Quite weird...

But as advised, I have some editors in Windows that also correctly display the utf-8, so this is sufficient for me, for now... Even dumb `notepad.exe` will correctly display utf-8, sometimes!

I have rebase my `fr.po` branch to your merged `master`, and will get around to another round of `french` tests... but think this issue has been solved...

**Comment by geoffmcl** [comment]
After another round of french tests, have now merged the `fr.po` branch into `master`, see #388, and deleted that branch...

Remember to do `$ git checkout master && git fetch --prune` to remove deleted branches...

Of course the pushed `language_fr.po` is a WIP, with only about 40% of the text translated... And have not yet done the `$ ruby poconvert.rb msgfmt translations/language_fr.po`, in windows, to put all the latest into the source, but...

But when I run that command I get -

````
E, [2016-03-30 17:55:05#5960] ERROR -- : header_template?: Did someone tamper with the header template? If you
E, [2016-03-30 17:55:05#5960] ERROR -- : header_template?: meant to change the template and know what you're doing,
E, [2016-03-30 17:55:05#5960] ERROR -- : header_template?: then the new digest is:
E, [2016-03-30 17:55:05#5960] ERROR -- : header_template?: cc4a9fbfb7cb9d8e686d92d3dc9e9ef06ecbafb75d18ccf61ada0acbc7b787db
````

Now I can **fix** this by changing the `@@header_digest = ` value to the above, but is this what I am supposed to do?

And of course git then advises of a modified file. Am I supposed to commit and push this? Will this change all the time?

I don't **think** I changed the `template` but maybe... What is happening here? There seems no mention of this in any of the README* files as far as I can see...

The error message is **interesting** in that it sort of asks `do I know what I'm doing?`... Hell, **no**! I am **lost** ;=))

As usual seek **help** in understanding why I get this error!

**Comment by balthisar** [comment]
I'll have a look at it this weekend, I hope, @geoffmcl. It's working now (I regen'd all the POs and pushed them) with no issue. I could remove the `@@header_digest`; it's mostly meant to keep people from breaking the template. Since it's working for me now, I'm guessing that Windows line breaks are probably causing the issue for you.

**Comment by geoffmcl** [comment]
While this still needs work, but we are to shortly do a release 5.4, thus am moving this to `next` 5.5...

**Comment by geoffmcl** [comment]
@balthisar on re-reading this I can see nothing really **open**... so will close...

It was my attempt to understand the **language** process, and `play` with a French translation, but will leave it to a native speaker to continue that effort...
