### ISSUE TITLE
Wrapping within unpaired tags

### ISSUE THREAD

**Issue by tyson-nw** [htacg/tidy-html5#386]
I have a list of unpaired tags that I feed through tidy and instead of wrapping them before the tag it is wrapping them within the tag

```
<html>
  <head>
    <title></title>
  </head>
  <body>
    <form>
      <input id="$nodeid[0]" /><input id=
      "$nodeid[1]" /><input id="$nodeid[2]" /><input id=
      "$nodeid[3]" />
    </form>
  </body>
</html>
```

Is there a configuration option that would produce code more like

```
<html>
  <head>
    <title></title>
  </head>
  <body>
    <form>
	  <input id="$nodeid[0]" />
	  <input id="$nodeid[1]" />
	  <input id="$nodeid[2]" />
	  <input id="$nodeid[3]" />
    </form>
  </body>
</html>
```

**Comment by geoffmcl** [comment]
@tyson-nw I am not sure I fully understand your comment... but the fact that you use ` />` in your expected output suggests that you are talking about xhtml?

When I use the options `-i -xml` I seems to get exactly what you expect from your sample -

````
F:\Projects\tidy-test\test>tidy -v
HTML Tidy for Windows version 5.1.47

F:\Projects\tidy-test\test>tidy -i -xml --show-info no input5\in_386.html
No warnings or errors were found.

<html>
  <head>
    <title>Issue #386</title>
  </head>
  <body>
    <form>
      <input id="$nodeid[0]" />
      <input id="$nodeid[1]" />
      <input id="$nodeid[2]" />
      <input id="$nodeid[3]" />
    </form>
  </body>
</html>
````

Am I missunderstandong something here? Or is that what you were looking for?

**Comment by tyson-nw** [comment]
That did it.  I was outputting html not xml.  Thanks!
