### ISSUE TITLE
In unix given a directory, tidy will generate a document!

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#391]
In combing through, and closing all the **old** SF bugs as `out-of-date`, came across [Bug 744](https://sourceforge.net/p/tidy/bugs/744/), created: 2005-12-06 by Jeff Pohlmeyer, and he even offered a simple solution...

Problem: only in linux

```
$ tidy /usr/bin
line 1 column 1 - Warning: inserting missing 'title' element
Info: Document content looks like HTML5
Tidy found 1 warning and 0 errors!

<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Linux version 5.1.50">
<title></title>
</head>
<body>
</body>
</html>
...
```

While that might be `funny`! Ha, ha, it is a bug in my book. 

And also do not like the simple `Error: Can't open "dir-name"` in Windows. It is not just `can not open`, it is a **directory**, and should say so!

Patch or PR welcome... thanks...

**Comment by geoffmcl** [comment]
Since we about to release a 5.4, and no work has been done on this, am moving it to `next` 5.5... thanks...

**Comment by balthisar** [comment]
@geoffmcl, I'd suggest the expedient fix would be the console application... should be an easy check. A more robust solution would be to implement this is the library and add a new message, because `TY_(FileError)` is used all over the place.

**Comment by balthisar** [comment]
I ended up with a simple fix in the library, including a new message. Tested on macOS and Windows.

**Comment by balthisar** [comment]
Thanks for the fix, @geoffmcl. I've merged it, so will close this.
