### ISSUE TITLE
Creeping indent of php script

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#392]
If you have a simple php block -

```
<!DOCTYPE html>
<html>
<head>
<title>php indent creep</title>
</head>
<body>
<?php
 $file = 'file.txt'
?>
</body>
</html>
```

The first time you run tidy, with `-i`, you get, in part -

```
<body>
  <?php
   $file = 'file.txt'
  ?>
</body>
```

That's fine, but if you run tidy on that output, again with `-i`, you get -

```
<body>
  <?php
     $file = 'file.txt'
    ?>
</body>
```

And so on... creepy creeping identing ;=))

Back in 2007, when I first reported this [Bug #854](https://sourceforge.net/p/tidy/bugs/854/) I attached a zip, again here, which I think included a **patch**. Now while that patch may not be applied directly to the current source, maybe the principle would still apply?

It would be really appreciated if someone could pick this up, and maybe offer a current **tested** patch, or a PR... if I do not get to it first... thanks...

[php-01.zip](https://github.com/htacg/tidy-html5/files/200980/php-01.zip)

**Comment by geoffmcl** [comment]
This seems to continue as an ongoing **bug**, but as we are to shortly do a 5.4 release, and no work has been done on this, am moving it to `next` 5.5... thanks...

**Comment by geoffmcl** [comment]
Hmmm, seems I **nearly** fixed this when fixing #133. That was for the `AspTag`...

But as **noted** at the time, perhaps this would also apply to **other** text like nodes...

It seems this could now be extended to `PhpTag` with the small patch -

```diff
diff --git a/src/pprint.c b/src/pprint.c
index 9106396..68e8d44 100644
--- a/src/pprint.c
+++ b/src/pprint.c
@@ -1935,6 +1935,8 @@ static Bool TY_(nodeIsTextLike)( Node *node )
         return yes;
     if ( node->type == AspTag )
         return yes;
+    if (node->type == PhpTag)
+        return yes; /* Issue #392 */
     /* add other text like nodes... */
     return no;
 }
```

But then taking a look at my **old** patch, maybe a **better** answer would be to extend this `nodeIsTextLike(node)` service to something like done back in 2007 -

```diff
diff -ur C:\FGCVS\tidy\src\tags.c tidycvs\src\tags.c
--- C:\FGCVS\tidy\src\tags.c	Fri Dec 29 17:31:08 2006
+++ tidycvs\src\tags.c	Mon Sep 03 14:10:53 2007
@@ -870,6 +870,22 @@
   return no;
 }
+
+/* new 20070818 - tags that normally contain text */
+Bool TY_(nodeIsTextLike)( Node * node )
+{
+   switch ( node->type )
+   {
+   case TextNode:	  /* yes for sure */
+   case CDATATag:   /* maybe??? */
+   case SectionTag: /* maybe??? */
+   case AspTag:     /* yes? */
+   case JsteTag:    /* yes? */
+   case PhpTag:     /* yes for sure */
+      return yes;
+   }
+   return no;
+}
+
 Bool TY_(nodeIsElement)( Node* node )
 {
   return ( node && 
```

You will note that includes `CDATATag`, `SectionTag`, `JsteTag`, and moves the service to `tags.c`, which is maybe where it belongs... but no real problem with it remaining in `pprint.c`, which is the only place it is used...

Appreciated if others could cut in the small patch, and test this [in_392.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_392.html) sample...

Remember the test is to run tidy with `-i -o temp1.html in_392.html`, then run tidy again on that output, `-i -o temp2.html temp1.html` and make sure it is **not** changed again, `diff temp1.html temp2.html`... that is **no creeping indent**...

Look forward to further comments... thanks...

**Comment by geoffmcl** [comment]
Maybe incomplete, but have pushed a branch `issue-392`, with the simple fix...

Feedback very welcome,, thanks...

**Comment by balthisar** [comment]
@geoffmcl, the fix is working for me. Go ahead and merge it at your leisure.
