### ISSUE TITLE
Re. Automated test cases 

### ISSUE THREAD

**Issue by Shanmuganandh** [htacg/tidy-html5#400]
I found this github repo from the following link http://tidy.sourceforge.net/#test . It is mentioned that there is a test directory in the source code. Could someone point me to the test cases folder?

**Comment by geoffmcl** [comment]
@Shanmuganandh the test cases can be found in their own https://github.com/htacg/tidy-html5-tests repo...

You need to checkout the `refactor` branch... be aware it is WIP... specifically [Issue 5](https://github.com/htacg/tidy-html5-tests/issues/5) needs some work...

Must make a note to update that SF link [here](https://github.com/htacg/tidy.sf.net.legacy) -  another repo, just for those legacy pages - please use -

 - main page - http://www.html-tidy.org/
 - api docs - http://api.html-tidy.org/
 - bin - http://binaries.html-tidy.org/, etc... 

Patches and PR appreciated on all htacg repos... thanks...

**Comment by Shanmuganandh** [comment]
Thanks @geoffmcl
