### ISSUE TITLE
Now available via chocolatey

### ISSUE THREAD

**Issue by majkinetor** [htacg/tidy-html5#401]
I created automated package and now tudy will be available via repository. See

https://chocolatey.org/packages/html-tidy

New packages are available few days after they appear on github releases.
Package source is at https://github.com/majkinetor/chocolatey/tree/master/html-tidy

**Comment by balthisar** [comment]
Awesome. Thanks!

**Comment by geoffmcl** [comment]
@majkinetor **absolutely** great... thanks...

And yes, **must** be added to the Windows section of [get-tidy](http://www.html-tidy.org/#get-tidy) web page... and will try to get to trying it soon...

As previously muttered, it would be great to have a list known distros, and the version they offered. Sort of - get on the list type - encouragement to distro project maintaners... or not... maybe, how can we, htacg, help those **channels**?

Every step in distribution **really** helps... thanks...

**Comment by majkinetor** [comment]
You аre welcome. 

Windows developers still don't have that in the culture - to push to repositories. 

BTW, the source code for the package is [here](https://github.com/majkinetor/chocolatey/tree/master/html-tidy) if you ever want to integrate this into your build procedure. 

Windows installation is as simple as: `cinst html-tidy`. 

Thanks.

**Comment by geoffmcl** [comment]
Since we are to shortly release a 5.4, and there seems no particular Tidy issue here, am closing this for now...

Please feel free to reopen, or post a new issue... thanks for your tidy support...

**Comment by majkinetor** [comment]
I don't see a license anywhere here ? Can I embed zip archives for x32 and x64 versions in the package (unchanged). Currently the package downloads installers from here ? 

This will reduce eventual network problems on install.

If there is a license anywhere that allows redistribution, please point me to it.

**Comment by balthisar** [comment]
README/LICENSE.md, or tidy.h.

**Comment by majkinetor** [comment]
Thanks, I must be blind. ;)
