### ISSUE TITLE
In config file, "Markup" must be yes for Quote-Marks to be substituted

### ISSUE THREAD

**Issue by TomTrottier** [htacg/tidy-html5#402]
When I had markup:no, quote-marks:yes did not cause the apostrophe ' to be substituted by &#39;

**Comment by TomTrottier** [comment]
Hmmm the second apostrophe should  be, spaces omitted, & # 3 9 ;

**Comment by geoffmcl** [comment]
@TomTrottier I think I get the idea... you want a `&#39;` entity output... is that it?

Could you please add -

   - version of tidy `$ tidy -v`
   - small sample html
   - config used
   - current output
   - expected output

This will help move this along,,, thanks...

**Comment by balthisar** [comment]
@TomTrottier, since no feedback I will close this. Please feel free to re-open the issue if you're still around.
