### ISSUE TITLE
Tidy HTML fragments

### ISSUE THREAD

**Issue by GingkoFr** [htacg/tidy-html5#404]
Hello,

I would like to know if it could be possible to add an option for **preventing** addition of any required tags like &lt;html&gt;, &lt;head&gt;, &lt;body&gt;, &lt;title&gt;, &lt;meta&gt;, &lt;style&gt;, etc, if they are missing, along with anything which could enclose the submitted contents.

I ask this because:
1. I sometimes want to tidy only HTML **fragments** intended to be included later in a larger document.
2. I commonly use **[server side includes](https://httpd.apache.org/docs/current/en/howto/ssi.html)**, meaning that I include HTML fragments in a main document using special declarations (actually HTML pseudo comments). These includes are very often the heading and the bottom of the page, leaving only the main contents in the main file, which sometimes needs to be tidied.
3. **PHP** scripts (or sometimes Javascript) can also very often contain HTML fragments which may need to be tidied.

I like to use HTML Tidy as an external filter for my preferred text editor (that is, [Editplus](https://www.editplus.com/)), which gives me the ability to select a part of the text that I am editing, and submitting only that part to the external filter. But the fact that HTML Tidy can add missing tags is a problem in that case, if I don't submit the whole document to it.

Some precisions about what that I think it should be expected if every you follow my suggestion:

About HTML fragments, I usually expect to submit them containing all closing tags corresponding to each opening tag included. If ever it is not the case, however, it may be needed to have the missing closing tags added, and only these ones.

These fragments can be also sometimes already indented relatively to the document expected to contain them, so in that case I think that all indentations added by HTML Tidy in a fragment should be made relative to the existing indentation of the first opening tag.

Regards,

Gingko

**Comment by balthisar** [comment]
Does [show-body-only](http://api.html-tidy.org/tidy/quickref_5.2.0.html#show-body-only) not work for you?

**Comment by geoffmcl** [comment]
@GingkoFr that is add `--show-body-only yes` on the command line, or if placed in a config file `show-body-only: yes`.

Does this not do what you want?

**Comment by balthisar** [comment]
Will close due to age and lack of feedback from the poster.

**Comment by GingkoFr** [comment]
Hello. Sorry for forgetting to answer.

“**--show-body-only**”  does what I wanted.

The only improvement I could suggest to add to it is about its eventual ability to keep previously existing indentation, for example relatively to the initial indentation of the first opening tag.

Gingko
