### ISSUE TITLE
Browserify , Cannot find module 'utf-8-validate' 

### ISSUE THREAD

**Issue by obonyojimmy** [htacg/tidy-html5#405]
Kindly fix node compilation errors , 
`Browserify Failed!: Cannot find module 'utf-8-validate' from '/node_modules/ws/lib'`

**Comment by geoffmcl** [comment]
@obonyojimmy thank you for the report...

But I am **not** familar with **Browserify**, and have no understanding why it can not find a module `utf-8-validate`...

In the source of HTML Tidy I too can **not** find a `module` utf-8-validate???

Please explain more... thanks...

**Comment by benkasminbullock** [comment]
This bug has nothing to do with tidy-html5, it is something to do with node.js (JavaScript), whereas tidy-html5 is written in C.

**Comment by balthisar** [comment]
Closing due to age and non-relevance.
