### ISSUE TITLE
Console app build fails using debuild

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#406]
@Ludovic has reported this debian case -

Relined -
````
[...]
[ 51%] Linking C executable tidy
/usr/bin/cmake -E cmake_link_script CMakeFiles/tidy.dir/link.txt --verbose=1
/usr/bin/cc   -Wall -g -O2 -Wextra -pipe -funsigned-char -fstrict-aliasing 
-Wchar-subscripts -Wundef -Wshadow -Wcast-align -Wwrite-strings -Wunused 
-Wuninitialized -Wpointer-arith -Wredundant-decls -Winline -Wformat 
-Wformat-security -Wswitch-enum -Winit-self -Wmissing-include-dirs 
-Wempty-body -fdiagnostics-color=auto -Wmissing-prototypes -Wstrict-prototypes 
-Wold-style-definition -Wbad-function-cast -Wnested-externs  -Wmissing-declarations 
-Wdate-time -D_FORTIFY_SOURCE=2  
  -Wall  -D_REENTRANT   -fPIE -pie -Wl,-z,relro -Wl,-z,now  
 CMakeFiles/tidy.dir/console/tidy.c.o  -o tidy -rdynamic libtidys.a
/usr/bin/ld: CMakeFiles/tidy.dir/console/tidy.c.o: relocation R_X86_64_32 
 against `.rodata.str1.1' can not be used when making a shared object; 
 recompile with -fPIC
CMakeFiles/tidy.dir/console/tidy.c.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/tidy.dir/build.make:98: recipe for target 'tidy' failed
make[3]: *** [tidy] Error 1
make[3]: Leaving directory '/home/rousseau/Debian/tidy/work/tidy-5.2.0/obj-x86_64-linux-gnu'
````

Something does not make sense here... particulary because 
this is a static link of tidy.c with libtidys.lib, as we want,
so should have no `relocation` problems...

Maybe someone with more `debuild` experience can try, and 
comment... I have already asked for the pebuild options, config, 
etc details...

But meantime, any help appreciated... thanks...

**Comment by geoffmcl** [comment]
Got an update -

````
On 08/05/16 21:31, Ludovic Rousseau wrote:
> - extract the .orig.tar.gz
> - copy the debian/ directory inside
> - run "debuild"
````

Tried to follow that to a T ;=))

````
# in the repo directory...
tidy-packaging $ md temp
$ cd temp
$ tar -xvf ../tidy_20160407.orig.tar.gz
$ cd tidy-5.2.0
$ copy ../../../debian/* .
$ debuild > bldlog-1.txt 2>&1
````

After waiting quite a while I get -

````
This package has a Debian revision number but there does not seem to be
an appropriate original tar file or .orig directory in the parent directory;
(expected one of tidy_20160407.orig.tar.gz, tidy_20160407.orig.tar.bz2,
tidy_20160407.orig.tar.lzma,  tidy_20160407.orig.tar.xz or tidy-5.2.0.orig)
continue anyway? (y/n)  dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: source package tidy
dpkg-buildpackage: source version 20160407-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Daniel James <daniel@64studio.com>
 dpkg-source --before-build tidy-5.2.0
dpkg-buildpackage: host architecture amd64
dpkg-checkbuilddeps: Unmet build dependencies: dh-autoreconf
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc failed
````

Still a mystery... anyone who can help... thanks...

Regards,
Geoff.

PS: copy is aliased to `cp -A` IIRC...

**Comment by danielhjames** [comment]
Hi Geoff, 

There are two different issues here. First is that the whole of the debian directory needs to be copied into the source intact, not just the files from that directory. So in the tidy-5.2.0 directory you would end up with:

```
build
debian
localize
README
version.txt
CMakeLists.txt
experimental
man
README.md
console
include
obj-x86_64-linux-gnu
src
```
Second issue is that the 'unmet build dependencies' error means your test machine is not set up for building this package. If you look at the debian/control file you'll see a list of packages that you would need to install:

`Build-Depends: debhelper (>= 9), libtool, perl, xsltproc, dh-autoreconf, cmake`

**Comment by danielhjames** [comment]
Please see http://stackoverflow.com/questions/13812185/how-to-recompile-with-fpic#13812368
for a possible fix to the original issue.

**Comment by geoffmcl** [comment]
@danielhjames thanks for that additional depends information...

Have installed dh-autoreconf, and will try again... and ensure the copy includes all subdirectories, but I think it did...

Thanks for the link to fpic... but as suggested the standard build for tidy.c, the console app that uses libtidys.lib (static library), does not need relocation... I do not understand that warning...

Maybe something in the **MANY** extra flags added causes the need for relocation... maybe someone can try adding -fPIC and see if tidy.c compiles, links...

This is still a mystery to me...

**Comment by geoffmcl** [comment]
@danielhjames yay, thanks, it all compiles... 

Well I get an error on the gdp signing...

This is an extract from my deblog-1.txt log file...
full : http://geoffair.org/tmp/deblog-1.txt

````
[skip]
Now running lintian...
E: tidy changes: bad-distribution-in-changes-file unstable
W: tidy source: newer-standards-version 3.9.8 (current is 3.9.5)
N: 2 tags overridden (2 info)
Finished running lintian.
Now signing changes and any dsc files...
 signfile tidy_20160407-1.dsc Daniel James <daniel@64studio.com>
gpg: skipped "Daniel James <daniel@64studio.com>": secret key not available
gpg: /tmp/debsign.emNssAQc/tidy_20160407-1.dsc: clearsign failed: secret key not available
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1283:
running debsign failed
build-me.sh: debuild failed... in 36 secs... 
````

When I build a DEB for our own binary distribution -
 http://binaries.html-tidy.org/
it would be great if I could sign them on behalf of HTACG.

Can you help with some pointers, like how to gen the 
'secret' key? Is this like a .ssh key?

But that is not too important, it generated some great 
stuff...

````
libtidy-0.99-0_20160407-1_amd64.deb
libtidy-dev_20160407-1_amd64.deb
tidy_20160407-1_amd64.build
tidy_20160407-1_amd64.changes
tidy_20160407-1_amd64.deb
tidy_20160407-1.debian.tar.gz
tidy_20160407-1.dsc

````

I was surprised by the tidy-0.99-0 deb, but assume 
this deals with the deletion of the tidy-0.99? It 
just contains 3 files, and the important link 
change - ./usr/lib/libtidy.so -> libtidy.so.5

And I can see now how you separate the -dev, which 
basically just contains headers, and the main 
tidy_20160407-1_amd64.deb
contains the binaries...

But wait you seem missing the LIBRARIES! To me, the 
-dev package should contain all the components to use 
the Tidy API... You have them all generated in 
the obj-x86_64-linux-gnu folder... and install in 
the debian/tmp directory...

For example our tidy-5.2.0-64bit.deb, contains -

````
/usr/bin/tidy
/usr/lib/libtidys.a
/usr/lib/libtidy.so -> libtidy.so.5
/usr/lib/libtidy.so.5 -> libtidy.so.5.2.0
/usr/lib/libtidy.so.5.2.0
/usr/include/tidy.h
/usr/include/tidyenum.h
/usr/include/tidyplatform.h
/usr/include/tidybuffio.h
/usr/share/man/man1/tidy.1
````

Everything need to install both the console app,
tidy, and libraries, and headers, for development
using tidy... although maybe we should gzip tidy.1...

But maybe I do not understand something about 
your package building...

And I am puzzled about the `.dsc` file content? 
Why does it mention 0.99, and not 5.2.0, like -
Binary: tidy, libtidy-0.99-0, libtidy-dev

And nowhere can I find this is the 5.2.0 release... 
is has -
Version: 20160407-1

But ok, it is your 'description' file and can contain 
what you need...

Also note from my log, I had no problem with compiling,
and linking tidy.c with libtidys.lib... no -fPIC required...

````
[ 50%] Building C object CMakeFiles/tidy.dir/console/tidy.c.o
/usr/bin/x86_64-linux-gnu-gcc  -DHAVE_CONFIG_H -DLIBTIDY_VERSION=\"5.2.0\" -DRELEASE_DATE=\"2016/04/07\" -DSUPPORT_ACCESSIBILITY_CHECKS=1 -DSUPPORT_ASIAN_ENCODINGS=1 -DSUPPORT_LOCALIZATIONS=1 -DSUPPORT_UTF16_ENCODINGS=1 -g -O2 -fPIE -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -Wall  -D_REENTRANT -I/home/geoff/projects/html_tidy/tidy-packaging/temp/tidy-5.2.0/include -I/home/geoff/projects/html_tidy/tidy-packaging/temp/tidy-5.2.0/src    -DTIDY_STATIC -o CMakeFiles/tidy.dir/console/tidy.c.o   -c /home/geoff/projects/html_tidy/tidy-packaging/temp/tidy-5.2.0/console/tidy.c
Linking C executable tidy
/usr/bin/cmake -E cmake_link_script CMakeFiles/tidy.dir/link.txt --verbose=1
/usr/bin/x86_64-linux-gnu-gcc  -g -O2 -fPIE -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -Wall  -D_REENTRANT   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now  CMakeFiles/tidy.dir/console/tidy.c.o  -o tidy -rdynamic libtidys.a 
make[3]: Leaving directory `/home/geoff/projects/html_tidy/tidy-packaging/temp/tidy-5.2.0/obj-x86_64-linux-gnu'
````

I will now try this in other architectures... like on an 
x86, and an arm7... and I like it that your deb contains an 
`arch`, like **amd64**... We discussed that a little, but 
the conversation petered out, before we reached a conclusion...

Anyway, thanks again for your help on this...

I used a script, which I think would be a good addition
to your repo - http://geoffair.org/tmp/build-deb.sh.txt

Regards,
Geoff.

**Comment by danielhjames** [comment]
Hi Geoff, there are a bunch of issues here :-)

1. To make a signed package, you need to put your own identity into the debian/control file on the Maintainer: line. Otherwise you'd have to make an unsigned package, which would be a bad idea for a public release.

2. The secret key is like an SSH private key, but it might be from a particular key pair that you reserve for signing packages. See https://wiki.debian.org/Keysigning

3. The -0.99 on the library packages is an indicator for ABI compatibility. I don't know why -0.99 was chosen previously, but the implication is that any package built against libtidy-0.99 will carry on working as long as that suffix doesn't change.

4. Nothing gets installed to debian/tmp on the target system, this is just a convenience for package building. If you want to check where stuff gets installed, open up the .deb package as a file archive. For this purpose you can ignore the DEBIAN directory as that contains files used by the package installation tool.

5. Libraries should not be missing, they should be in the libtidy-0.99* package. Imagine you had an application linked against libtidy which did not require /usr/bin/tidy to be present. Splitting the packages this way allows for smaller target systems.

6. The .dsc file is a checklist for the source package. It only mentions -0.99 because that is the current library suffix. It will say the version is 1:5.2.0 when we move to a new epoch.

7. The binary debs are built explicity for an arch, in this case amd64, but the source package is meant to be arch neutral. If it fails to build on any particular arch supported by Debian, we will need to fix whatever is causing that.

Cheers!

Daniel

**Comment by geoffmcl** [comment]
Hi Daniel,

Yeah, sorry about the many questions.

Thanks for the information on debian keysigning -
 https://wiki.debian.org/Keysigning

I will jump through those hoops when needed ;=))

But for now I will assume they will be getting 
correctly signed by you, so we can leave this 
issue... forget it for now...

It seems the important issue is -

**DEB Contents**

So now I see 3 deb files built -

  1. libtidy-0.99-0_5.2.0-1_amd64.deb
  2. libtidy-dev_5.2.0-1_amd64.deb
  3. tidy_5.2.0-1_amd64.deb

But nowhere can I find libtidy.so.5.2.0!

The deb 1. contains just one link -
 ./usr/lib/libtidy.so -> libtidy.so.5

The deb 2. contains the headers, and the 3. just the tidy console
app, and its man page...

In the previous /OLD/ 2009 release, we had -

  1. libtidy-0.99-0_20091223cvs-1.2ubuntu1.1_amd64.deb  
  2. tidy_20091223cvs-1.2ubuntu1.1_amd64.deb
  3. libtidy-dev_20091223cvs-1.2ubuntu1.1_amd64.deb

And as you point out, it is the first that has the 
library, and the associated links were, folders only excluded -

````
-rw-r--r-- root/root    379384 2015-07-23 19:30 ./usr/lib/libtidy-0.99.so.0.0.0
-rw-r--r-- root/root      2131 2015-07-23 19:29 ./usr/share/doc/libtidy-0.99-0/copyright
-rw-r--r-- root/root      1964 2015-07-23 19:30 ./usr/share/doc/libtidy-0.99-0/changelog.Debian.gz
lrwxrwxrwx root/root         0 2015-07-23 19:30 ./usr/lib/libtidy-0.99.so.0 -> libtidy-0.99.so.0.0.0
lrwxrwxrwx root/root         0 2015-07-23 19:30 ./usr/lib/libtidy.so -> libtidy-0.99.so.0.0.0
````

Now, I have no idea why `-0.99` was chosen... but it was,
and that is history... and if we must, I suppose we must 
put up with that...

I think it was a mistake, back 7 years ago, or the committer 
did not know, or understand the ABI significance, and it is 
a shame we seem unable to correct the situation now...

I would like to just see -

  1. tidy_5.2.0-1_amd64.deb - just want the tidy console app.
  2. libtidy-dev_5.2.0-1_amd64.deb - need lib and headers for development

But as stated, at the moment the new `libtidy-0.99-0_5.2.0-1_amd64.deb`
does not contain any **shared** library?

What am I missing here?

**Comment by danielhjames** [comment]
Hi Geoff, you are right, in my test package the libtidy.so.5 is missing, I'll look into the cause of that.

**Comment by danielhjames** [comment]
Please also suggest any updates you would like in the Description or other fields in https://github.com/danielhjames/tidy-packaging/blob/master/debian/control

**Comment by danielhjames** [comment]
Hi Geoff, I found two issues here...

1. The libtidy package did not mention the shared library in its install file, so it was not getting copied in. That's easily fixed.

2. The /usr/bin/tidy binary was being built standalone so it did not make use of the shared library. I'll have to find out how to enable that.

**Comment by danielhjames** [comment]
Hi Geoff, shared library is now properly installed in the libtidy5 package. Please take a look at https://github.com/danielhjames/tidy-packaging/blob/master/debs/sid/libtidy5_5.2.0-1_amd64.deb

**Comment by geoffmcl** [comment]
Hi Daniel,

OOF, lots of issues here...

The primary aim of tidy is to offer a very 
flexible API for tidying html documents...

That is, it offers libtidy.so, and libtidys.lib 
you can use in your application... cross ported...

Now, in addition to that fruit cake, we offer a 
console app, tidy.c, that adds a command line UI,
but then uses `libtidy`...

More a sample app, but its usage has spread... 
and in some minds 'tidy' just means that, without 
libtidy... in all its forms...

Now we have made a conscious choice to link that 
executable to the static version of the library. 
Exe bloat acceptable...

If you want, need, to go beyond the wishes of the 
tidy maintainers, then I suppose a tidy console app 
can be built using the shared library... I think you 
can find the cmake parameters for that...

But I would hope a distribution does not impose its 
own rules on a FOSS project... but at the same time 
would like to be part of every major distribution...

Advise it you can not build 'tidy' in what ever form 
you think appropriate...

Anyway, I will schedule another test shortly...

Really, thank you for your efforts here... we seem 
to be headed forward...

Regards,
Geoff.

Ref: tidy-194-debian-build.txt

**Comment by geoffmcl** [comment]
Hi, 

I guess I prefer libtidy5, rather than libtidy1... but 
maybe we should get some more input on this?

The linking of the sample tidy.c with the static library,
is our choice for distribution of that binary.

But no problem if you prefer it otherwise. I think the 
cmake option is -DTIDY_CONSOLE_SHARED:BOOL=YES... advise 
if you have troubles with this...

Concerning seeking further comment I will share this on -

 https://github.com/htacg/tidy-html5/issues/406

And I will schedule another build test shortly...

Thanks,
Geoff.

On 17/05/16 12:05, Daniel James wrote:
> Hi Ludovic,
>
>> The Debian/Ubuntu package would be named "tidy". Is that confusing?
>
> I think that binary package will be the one most people are looking for.
>
>> The _source_ would be named "tidy-html5". But only people rebuilding the
>> binary would (need to) know that.
>
> That's true. It would mean a change of package name in the changelog
> too, but perhaps that's no bad thing for a new epoch.
>
> Cheers!
>
> Daniel

*AND*

On 17/05/16 12:17, Daniel James wrote:
> Hi Geoff,
>
>> However, a new app, that contains this additional
>> API call, can **NOT** be backwards linked to the old
>> libtidy-0.99.
>
> If additional API calls are added, it is possible for other applications
> to set minimum library versions without changing the package name.
>
> However, the -0.99 is rather unusual in a library name, and this could
> be a good chance to put it right.
>
> Originally the library was libtidy0 in Debian, i.e. the first version.
> I'm guessing the -0.99 meant 'not quite ready to be version 1'.
>
> So I'd be fine with either libtidy1, or libtidy5 to reflect the upstream
> numbering.
>
> Cheers!
>
> Daniel

*AND*

On 17/05/16 16:43, Daniel James wrote:
> Hi Ludovic, hi Geoff,
>
>> So I'd be fine with either libtidy1, or libtidy5 to reflect the upstream
>> numbering.
>
> The lintian output indicated that libtidy5 is preferred, to match the
> SONAME of libtidy.so.5
>
> I've updated https://github.com/danielhjames/tidy-packaging for this,
> and also fixed the issue with the shared library being missing from the
> libtidy* package.
>
> A remaining issue is that the /usr/bin/tidy binary works, but is built
> without using this shared library. I tested this using the sid amd64
> package with:
>
> dpkg -x tidy_5.2.0-1_amd64.deb /tmp/sid-tidy5
>
> objdump -p /tmp/sid-tidy5/usr/bin/tidy
>
> This shows the output:
>
> Dynamic Section:
>   NEEDED               libc.so.6
>
> It looks like libtidy5 is not being linked against, making the binary
> bigger than it should be (given that the package already has a
> dependency on the libtidy5 package).
>
> According to:
>
> https://github.com/htacg/tidy-html5/blob/master/README/README.md
>
> "If you do not need the tidy library built as a 'shared' (DLL) library,
> then in 2. add the command -DBUILD_SHARED_LIB:BOOL=OFF. This option is
> ON by default."
>
> It looks like CMake when used with debhelper builds the shared library
> but does not link against it. Any ideas?
>
> I'm also wondering if we should be running ldconfig in the postinst,
> given that we're installing a library.
>
> Cheers!
>
> Daniel

*EOF Ref: tidy-196-debian-build.txt *

**Comment by danielhjames** [comment]
Hi Geoff, the name libtidy5 is suggested by the lintian output that the library name should match the SONAME, so I'm fine with that. I've updated https://github.com/danielhjames/tidy-packaging/tree/master/debs/ to suit this.

As for the /usr/bin/tidy binary building in the library, if that is what the upstream project prefers I am also fine with that, personally speaking. The practical difference is that the tidy package would no longer have a dependency on the libtidy* package. This would only cause bloat on the target system in the scenario where the user wishes to have both /usr/bin/tidy and another program which relies on libtidy installed.

**Comment by geoffmcl** [comment]
Hi,

Daniel, thanks for the repo update...

I have just run a new test with the latest and it 
produced 3 DEB packages, without problems -

 1. libtidy5_5.2.0-1_amd64.deb
 2. libtidy-dev_5.2.0-1_amd64.deb
 3. tidy_5.2.0-1_amd64.deb
 
Aside from the fact that I could not find the static 
library, libtidys.a, in any of them, that looks quite
confusing, with the varied naming conventions...

We have `libtidy5_`, `libtidy-dev_` and `tidy_`???

But, ok, I guess a developer wanting `tidy` would know 
to select all three, but then they are still missing the 
static library! Where will this be included?

I guess I would really prefer everything just be included 
in **one** DEB, for such a small package...

Concerning static versus shared linkage, for the tidy 
console app, this is very convenient in Windows, which 
has lots of hoops to jump through to distribute such 
small command line utilities with private DLL dependency.

As it is now, tidy.exe can be distributed alone... very 
user friendly... perhaps when, if we have a TidyGUI2,
we would certainly consider a Windows installer, which 
can then also take care of DLL dependency... until then 
we use static linkage... in all...

But as stated, distribute it as needed... but I hardly 
think any bloat argument really applies ;=))

But let's distribute the **whole** package, including 
the static library, across ever how many DEB files as you 
think fit... thanks...

Regards,
Geoff.

On 19/05/16 11:30, Daniel James wrote:
> Hi Geoff, hi Ludovic,
>
>> I guess I prefer libtidy5, rather than libtidy1... but maybe we
>> should get some more input on this?
>
> The name libtidy5 is suggested by the lintian output that the library
> name should match the SONAME, so I'm fine with that. I've updated the
> test packages in
> https://github.com/danielhjames/tidy-packaging/tree/master/debs/ to suit.
>
>> The linking of the sample tidy.c with the static library, is our
>> choice for distribution of that binary.
>
> As for the /usr/bin/tidy binary building in the library, if that is what
> the upstream project prefers I am also fine with that, personally
> speaking.
>
> The practical difference is that the tidy package would no
> longer have a dependency on the libtidy* package. This would only cause
> bloat on the target system in the scenario where the user wishes to have
> both /usr/bin/tidy and another program which relies on libtidy installed.
>
> However the Debian project seeks to avoid bloat whenever possible and
> may prefer that /usr/bin/tidy does not build in the library.
>
>> But no problem if you prefer it otherwise. I think the cmake option
>> is -DTIDY_CONSOLE_SHARED:BOOL=YES... advise if you have troubles with
>> this...
>
> I think we would have to create an override for cmake in the
> debian/rules file. Perhaps Ludovic has some ideas about that.
>
> Cheers!
>
> Daniel

*AND*

On 19/05/16 13:30, Ludovic Rousseau wrote:
> Hello,
>
> 2016-05-19 11:30 GMT+02:00 Daniel James <daniel@64studio.com>:
>
>     Hi Geoff, hi Ludovic,
>
>     > I guess I prefer libtidy5, rather than libtidy1... but maybe we
>     > should get some more input on this?
>
>     The name libtidy5 is suggested by the lintian output that the library
>     name should match the SONAME, so I'm fine with that. I've updated the
>     test packages in
>     https://github.com/danielhjames/tidy-packaging/tree/master/debs/ to suit.
>
>
> Good choice.
> https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#s-sharedlibs-runtime
> "Normally, the run-time shared library and its SONAME symlink should be placed in a package named librarynamesoversion, where soversion is the version number in the SONAME of the shared library."
>
>
>     > The linking of the sample tidy.c with the static library, is our
>     > choice for distribution of that binary.
>
>     As for the /usr/bin/tidy binary building in the library, if that is what
>     the upstream project prefers I am also fine with that, personally
>     speaking.
>
>     The practical difference is that the tidy package would no
>     longer have a dependency on the libtidy* package. This would only cause
>     bloat on the target system in the scenario where the user wishes to have
>     both /usr/bin/tidy and another program which relies on libtidy installed.
>
>     However the Debian project seeks to avoid bloat whenever possible and
>     may prefer that /usr/bin/tidy does not build in the library.
>
>
> I found the footnote https://www.debian.org/doc/debian-policy/footnotes.html#f30 from https://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles "4.13 Convenience copies of code"
>
> I think we should use a dynamic link if possible.
>
>
>     > But no problem if you prefer it otherwise. I think the cmake option
>     > is -DTIDY_CONSOLE_SHARED:BOOL=YES... advise if you have troubles with
>     > this...
>
>     I think we would have to create an override for cmake in the
>     debian/rules file. Perhaps Ludovic has some ideas about that.
>
>
> That should be the way to go.
>
> Bye
>
> -- 
>  Dr. Ludovic Rousseau

*EOF - tidy-197-debian-build.txt*

**Comment by danielhjames** [comment]
Hi Geoff, According to https://www.debian.org/doc/debian-policy/ch-sharedlibs.html section 8.3, the static library should be in the development package. I'll look into how that is enabled.

Debian is concerned with small target systems, so for example an embedded system which never builds from source does not need headers or static libraries from the -dev packages.

Cheers!

Daniel

**Comment by danielhjames** [comment]
Hi Geoff, the libtidy-dev package now contains the static libtidys.a file for people that need it.

I used the cmake option you suggested and the tidy package is now much smaller, from 176KB down to 41KB on Debian jessie.

New test packages in https://github.com/danielhjames/tidy-packaging/tree/master/debs/jessie
work for me, please ask the tidy community to give them a try. The libtidy5 package will need to be installed before the tidy package on the target system.

**Comment by geoffmcl** [comment]
Hi, 

This all looks good to me... noted new content... seems
everything included... across multiple DEBs?, ok... some 
usual questions on use case for a static library...
but includes all required by `tidy` maintainers...
thanks...

Yup, let's distribute this soonest...

What is next step? How can I help in that? 

Regards,
Geoff.

On 20/05/16 12:54, Daniel James wrote:
> Hi Geoff,
>> Aside from the fact that I could not find the static
>> library, libtidys.a, in any of them
>
> According to https://www.debian.org/doc/debian-policy/ch-sharedlibs.html
> section 8.3, the static library should be in the development package.
> I'll look into how that is enabled.
>
>> that looks quite
>> confusing, with the varied naming conventions...
>>
>> We have `libtidy5_`, `libtidy-dev_` and `tidy_`???
>
> That's standard for Debian.
>
>> But, ok, I guess a developer wanting `tidy` would know
>> to select all three
>
> The idea is that a developer building against libtidy would need
> libtidy5 and libtidy-dev, not the tidy package.
>
>> I guess I would really prefer everything just be included
>> in **one** DEB, for such a small package...
>
> Debian is concerned with small target systems, so for example an
> embedded system which never builds from source does not need headers or
> static libraries from the -dev packages.
>
> Cheers!
>
> Daniel

*AND*

On 20/05/16 13:12, Ludovic Rousseau wrote:
> 2016-05-20 12:54 GMT+02:00 Daniel James <daniel@64studio.com>:
>
>     Hi Geoff,
>     > Aside from the fact that I could not find the static
>     > library, libtidys.a, in any of them
>
>     According to https://www.debian.org/doc/debian-policy/ch-sharedlibs.html
>     section 8.3, the static library should be in the development package.
>     I'll look into how that is enabled.
>
>
> You do not _have_ to provide the static library in a Debian package.
> But if you do it is in the -dev package.
>
> Why would you need the static library if you can use the dynamic one (and have security fixes and other upgrades for free)?
>
> Bye
>
> -- 
>  Dr. Ludovic Rousseau

*AND*

On 20/05/16 13:36, Daniel James wrote:
> Hi Ludovic,
>
>> Why would you need the static library if you can use the dynamic one
>> (and have security fixes and other upgrades for free)?
>
> I was wondering that. I guess it is for specialised use cases, such as
> guaranteeing binary compatibility at build time.
>
> There is a /usr/lib/libtidys.a file, so I will put that in the -dev
> package for now.
>
> Cheers!
>
> Daniel

*AND*

On 20/05/16 16:37, Daniel James wrote:
> Hi Ludovic,
>
>>     I think we would have to create an override for cmake in the
>>     debian/rules file.
>>
>> That should be the way to go.
>
> Thanks, I used in debian/rules:
>
> override_dh_auto_configure:
>         dh_auto_configure -- -DTIDY_CONSOLE_SHARED:BOOL=YES
>
> This seems to have worked because the tidy package is now much smaller,
> from 176KB down to 41KB on jessie. Also objdump reports the dependency:
>
> Dynamic Section:
>   NEEDED               libtidy.so.5
>   NEEDED               libc.so.6
>
> New test packages in
> https://github.com/danielhjames/tidy-packaging/tree/master/debs/jessie
> work for me. If it's OK with you, perhaps the package could go on to
> collab-maint now.
>
> I found the libtidy5 package does not need an explicit postinst hook for
> ldconfig in the packaging sources because this is now taken care of by
> an auto generated option in the DEBIAN/triggers file of the sid package:
>
> activate-noawait ldconfig
>
> or in the jessie package by this auto addition to the postinst:
>
> # Automatically added by dh_makeshlibs
> if [ "$1" = "configure" ]; then
> 	ldconfig
> fi
>
> Cheers!
>
> Daniel

; eof ref: tidy-198-debian-build.txt

**Comment by geoffmcl** [comment]
See all #354, and specifically https://github.com/htacg/tidy-html5/issues/354#issuecomment-224635444 - for an update...

I have now done successful package builds in Ubuntu 14.04 LTS 64-bits, and Raspbian arm7, so am closing this...

Please feel free to re-open, or add a new issue... thanks...
