### ISSUE TITLE
Self closing on non-void HTML

### ISSUE THREAD

**Issue by zanona** [htacg/tidy-html5#407]
Hey guys, I have noticed that tidy is self closing non-void HTML elements?

So the following seems to be completely valid whilst it's not?

``` html
<!doctype html>
<title>foo</title>
<div class=bar />
<script src=baz.js />
```

``` bash
$ tidy --version
HTML Tidy for Mac OS X version 5.2.0
```

``` bash
$ tidy test.html -
line 3 column 1 - Warning: inserting implicit <body>
Info: Document content looks like HTML5
Tidy found 1 warning and 0 errors!

<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Mac OS X version 5.2.0">
<title>foo</title>
</head>
<body>
<div class="bar"></div><script src="baz.js"></script>
</body>
</html>
```

Please refer to [the results using  W3C validator](https://validator.w3.org/nu/?showsource=yes&doc=data%3Atext%2Fhtml%2C%3C%21doctype%2520html%3E%3Ctitle%3Efoo%3C%2Ftitle%3E%3Cdiv%2520class%3Dbar%2520%2F%3E%3Cscript%2520src%3Dbaz.js%2520%2F%3E) for more details about the errors.

**Comment by geoffmcl** [comment]
@zanona thanks for the report...

I do not know the exact definition of `non-void HTML elements`, so not sure if ` tidy is self closing` them, what ever they are? Please explain a little more...

But maybe you are suggesting tidy should output all those warnings, like the W3C validator? As errors, or warnings? Is that it? 

Not just a benign, hey, I added a body element for you... (to your truncated and mixed up mess ;=))

Without checking deeply, it seems tidy's output is ok, given the messy input... Where is the issue?

Maybe you could add one more panel - Expected output! ... thanks...

**Comment by zanona** [comment]
thanks for your reply @geoffmcl,

the problem here is with:

```html
<div class=bar />
<script src=baz.js />
```
That apparently are not allowed on HTML 5?

In fact if I try to do this, browser will in fact interpret in crazy ways like:

```html
<div class=bar>
   <script src=baz.js></script>
</div>
```

So in this case there's no expected output since it's basically an error?
I believe they refer to self closing elements are just the ones like the ones below perhaps we can manage to find an official list of those?

```html
<area />
<base />
<br />
<col />
<command />
<embed />
<hr />
<img />
<input />
<keygen />
<link />
<meta />
<param />
<source />
<track />
<wbr />
```


If you check the output on W3C Validator you can see it's printed out as error since it's not valid HTML5 as per the spec apparently?

**Comment by geoffmcl** [comment]
@zanona ok, `<br />` is not allowed in html, and `<br>` is not allowed in xhtml... have I got that right?

Again, what output do you expect?

````
I Expect: fill this in
````

**Comment by zanona** [comment]
Sorry Geoff, perhaps I wasn't too clear before.

I believe the current output is pro-actively correct already, so I don't expect anything on the output generation to change.
However, tidy should point it as an error in the source (not warning), considering that at the moment it just passes through it as it was valid markup.

So:

_I expect tidy to output the same document as it is a the moment, but alerting of an error in the markup._

Does this clarify you question?

Also, self closing is completely valid in HTML on void elements, however it's optional. So both `<br/>` and `<br>` are valid as well as `<img>` or `<img/>`.

The error here is when there's an attempt to self closing non-void elements (the ones that require content) such as `div, p, section, article` or any other that's not in the list I mentioned before.

For more info please see: http://www.w3.org/TR/html5/syntax.html#void-elements

**Comment by geoffmcl** [comment]
@zanona, ok, I think I understand you would like to see the html `errors` clearly stated...

> I believe the current output is pro-actively correct already, 
> so I don't expect anything on the output generation to change.

Tidy has two outputs, which can be re-directed to files, so when I ask for `expected` output it is either, or both, these outputs... So, you accept the html output, but...

> I expect "..., but alerting of an error in the markup."

So I think that means you would like the message output something like - a la validator - 

````
Error: The character encoding was not declared. Proceeding using windows-1252.
Error: Self-closing syntax (/>) used on a non-void HTML element. Ignoring the slash and treating as a start tag.
From line 3, column 1; to line 3, column 17
o</title>?<div class=bar />?<scri
Error: Self-closing syntax (/>) used on a non-void HTML element. Ignoring the slash and treating as a start tag.
From line 4, column 1; to line 4, column 21
ss=bar />?<script src=baz.js />?
Error: End of file seen when expecting text or an end tag.
At line 4, column 22
=baz.js />?
Error: Unclosed element script.
From line 4, column 1; to line 4, column 21
ss=bar />?<script src=baz.js />?
Error: Unclosed element div.
From line 3, column 1; to line 3, column 17
o</title>?<div class=bar />?<scri
Error: End of file seen and there were open elements.
At line 4, column 22
=baz.js />?
````

Wow, such an amount of noise...

I am sure tidy could do **some** of that... but instead it chooses to try to **fix** the document... very quietly... 

So, are we now on the same page ;=))

Maybe I agree, tidy should be more aggressive with html errors, but maybe not... not decided...

But now, perhaps this `Feature Request` is clear, others would care to comment...

And thanks for the clarification... I just hope I got the idea right.

**Comment by zanona** [comment]
@geoffmcl Thanks so much, that was exactly what I meant.
Thanks for the explanation about tidy as well, hopefully next time I will get it right when opening a new issue.

**Comment by geoffmcl** [comment]
Since there has been no further comments, in nearly a year, and it remains unclear exactly what is required of tidy, closing this issue for now....

Please feel free to re-open, or file a new issue... thanks...
