### ISSUE TITLE
Feature request: "sort-elements" configuration option

### ISSUE THREAD

**Issue by john-black-3k** [htacg/tidy-html5#408]
Hello,

I can see that there already is a "sort-attributes" configuration option.

It would also be nice to have a "sort-elements" option. It is not very useful for HTML files, but it can be very useful for XML files. The elements in 2 similar XML files can thus be sorted for comparison purposes (using WinDiff, TortoiseDiff etc). Of course, in some XML files the element order is important, but in others it is not.

This option could be of type "Integer", representing the depth in the tree of the elements that will be affected by the sorting operation:
- -1 (all the elements in the file will be sorted recursively)
- 0 (sorting disabled, no sorting occurs)
- 1 (1st level only; only elements directly under the root node will be sorted)
- 2 (2nd level sorting; only elements directly under the root node and children of those elements will be sorted)
- etc...

The algorithm would be an ascending alphabetic sort, as for "sort-attributes". 

Another feature could be a "sort-elements-attr" configuration option which would allow sorting after the value of a specific attribute. But then again, this is another feature... :-)

Regards,
John

**Comment by geoffmcl** [comment]
@john-black-3k, thanks for the feature request... sorry for the brief delay, but was hoping we would get some other comments first... oh, well...

Hmmmm, a `sort-elements` option... as you point out not much use for html, but **may** have a use case for XML, but even then...

One small point, at present the tidy `integer` type does not support `-1`, but that means either adjusting the above sorting operations, or a small `libtidy` change in the integer parsing... something I have thought about before...

And this is just to **compare** two files? With some `diff` program??

In a way this seems outside what console tidy [tidy.c](https://github.com/htacg/tidy-html5/blob/master/console/tidy.c) is all about... that is tidy up a html file, and pretty print the results...

But it would be a breeze to write say a `tidy-diff.cxx`. It could use **`libtidy`** to load the two files into its DOM like tree of nodes, and then you get each node from file1, and really compare it to every node in file2, flag same/different/differences/etc, maybe adding the results in say a vector... or whatever... not a big task...

If you, or anyone else would like to write such a `tidy-diff` utility, then we would certainly help with technical support, even new library API functions if you need something not already available...

But without further explanation... maybe I misuderstood something... I can not see this option added to tidy directly... but await further comments... thanks...
