### ISSUE TITLE
Easier handling of opaque types

### ISSUE THREAD

**Issue by gagern** [htacg/tidy-html5#409]
Tidy takes an imho pretty strange approach to opaque types. Publicly it declares them as pointers to some bogus structure, and internally it casts them between those and the actual types using a bunch of macros (and a bunch of functions in code conditioned by the `NEVER` preprocessor macro, so I'd consider this dead code).

Most other projects simply declare the structures globally but leave out their implementation. Applied to Tidy you'd get these in `tidy.h` (similar to what's currently in `forward.h`):

``` c
struct _TidyDocImpl;
typedef struct _TidyDocImpl *TidyDoc;
```

Then later in `tidy_int.h` you have the actual definition of `struct _TidyDocImpl { … };`, but that's invisible to library users. You could drop all those type converting calls, and operate on the non-opaque structures internally while keeping the internal layout out of the public API.

I'm willing to write a patch to this effect, but before I do so, I'd like to know whether there are any reasons against this approach.

**Comment by geoffmcl** [comment]
@gagern you raise a very valid point, one I have had for a long time...

Why does tidy use an opaque structure? It does stop libtidy 
users messing with that structure... But is that needed?

And then you have to also ask about the TY(function)( params ) 
macro. Why 'hide' these functions? Some are static, but some 
are public...

So I guess part of it is being able to publish a very 
flexible API, and keep it documented, without the need 
to publish the meaning of every tidy doc member... every 
non-static internal C function...

I know tidy quite well, but that documentation would be the 
tip of an iceberg regarding some very neat C technologies 
in the code, which I hope one day **are** published...

Now, I am not in any way defending that as perhaps being a 
 "... pretty strange approach ..."? It has been well done, 
and reasonably documented... would always like to see more 
here, but where are the writers when you need them?

As you point out, a few minor changes could expose everything, 
but do we want that? At this time? To what gain?

And what additional doxygen needs to be added, to where, etc, 
such that that an extended API change can be `published`... 
and maybe install some additional 'tidy' headers, to expose 
more... add page to API documentation...

And there is the question of backward compatibility, if 
that is needed, or desired... Is this 5.6?

But I suppose, at present a documented API that gives you, 
to varying degrees, access to the structure, through API functions 
is what tidy presently does, in a C++ way, and that works too...

Anyway, @gagern this is my 2 bits on this ;=)) a good question!

**Comment by gagern** [comment]
> Why does tidy use an opaque structure? It does stop libtidy users messing with that structure... But is that needed?

I'd say yes. It's easy to choose new function names for the public API by appending some number, but changing the representation of data structures is much harder unless you can control all access to said data structures.

> And then you have to also ask about the `TY_(function)( params )` macro. Why ‘hide’ these functions? Some are static, but some are public…

Not including the functions in the public header would be enough to prevent people from messing with them. But there might still be unintentional function name conflics with other libraries. As [the header comment says](https://github.com/htacg/tidy-html5/blob/60c1dd1744914335f787148b4b31024ae56a9685/src/forward.h#L21-L23). In C++ this would be solved using namespaces, in C you have to do namespaces yourself, and the `TY_` macro makes the sources somewhat shorter than spelling out all those names. This should not be needed for static functions. And in general it would be a good idea to at some point introduce a linker script to hide all those symbols from the dynamic library on *nix systems, just the way they are hidden on Windows by default. But that's a different issue.

> As you point out, a few minor changes could expose everything, but do we want that? At this time? To what gain?

No, I'd definitely *not* expose any additional internals unless there is good reason to. And even then I'd rather add new methods than exposing the structures themselves. So this question is really just about the internal representation, and would not touch the public API. It wouldn't even require a version bump.

My main motivation for this question is because I'd like to add another opaque type, to represent errors (with code, arguments, the possibility of querying argument types, string representations, position information and so on), so that a fourth message filter could hopefully be the last since all future extensions could be extensions to the error object without touching the signature of the callback function. And I'd like to write this without unneccessary type casting overhead. (The `va_list` argument is nice for `vprintf`-style C functions, but ill suited when presenting the arguments to e.g. JavaScript as I'd like to do in node-libtidy. And conversion needs more information than any single error handler can currently provide.)

> But I suppose, at present a documented API that gives you, to varying degrees, access to the structure, through API functions is what tidy presently does, in a C++ way, and that works too...

I don't see anything C++ about this, unless you refer to the general concept of encapsulation. But yes, what tidy does works well, my point is just that it could be written more easily in the internal code without affecting behavior.

**Comment by balthisar** [comment]
> My main motivation for this question is because I'd like to add another opaque type, to represent errors (with code, arguments, the possibility of querying argument types, string representations, position information and so on), so that a fourth message filter could hopefully be the last since all future extensions could be extensions to the error object without touching the signature of the callback function.

@gagern, I realize that this particular issue hasn't advanced, but I plan to tackle messaging in 5.5, and of the things I've been considering is "one filter to rule them all." There's considerable additional information passing that I would need to accommodate, and so I wonder what you have in mind. All of the filter additions have been to tailored to my needs as a library user, and I'm glad to see other library users out there, so I'd love to arrive at a "forever" solution.

**Comment by gagern** [comment]
@balthisar: The API I had in mind was something like this:

```c
// Callback interface, similar to existing filters
struct _TidyErrorImpl; // incomplete type
typedef struct _TidyErrorImpl *TidyError; // opaque pointer
typedef Bool (TIDY_CALL *TidyReportFilter4)( TidyError error ); // callback function
Bool TIDY_CALL tidySetReportFilter4( TidyDoc tdoc, TidyReportFilter4 filt ); // registration

// Query interface, based on TidyError and therefore extensible
TidyDoc tidyErrorGetDoc( TidyError error );
TidyReportLevel tidyErrorGetLevel( TidyError error );
uint tidyErrorGetLine( TidyError error );
uint tidyErrorGetColumn( TidyError error );
ctmbstr tidyErrorGetCode( TidyError error );
uint tidyErrorGetArgumentCount( TidyError error );
TidyOptionType tidyErrorGetArgumentType( TidyError error, uint index ); // or other type
ctmbstr tidyErrorGetStringArgument( TidyError error, uint index ); // auto-coerces other types
ulong tidyErrorGetUintArgument( TidyError error, uint index ); // or signed?
ctmbstr tidyErrorGetMessageTemplateEnglish( TidyError error );
ctmbstr tidyErrorGetMessageTemplateLocal( TidyError error );
ctmbstr tidyErrorFormatMessage( TidyError error, ctmbstr format );
```

The idea is that you would have that *single* opaque error object, and then an extensible bunch of API functions to query its data. If we add more data, we add more functions, but don't touch existing code. It would be important to communicate that all the query functions are only valid when called from the `TidyReportFilter4` callback. Storing a `TidyError` for later processing is invalid. We might want to enforce this by clearing the data structure after the callback returned.

While the `va_list` concept is nice in the C world of things, it is poorly suited to other languages, e.g. the JavaScript I'm dealing with. With the API outlined above, I could iterate over the arguments one at a time, without having to parse the template string myself. I could extract all arguments of known types and translate them into their JavaScript equivalent, and I could fall back to string representation for unknown types to future-proof my code. Then the user of my JavaScript library could use these arguments to do whatever they like.

Actually you could use the type casts used by libtidy instead of the incomplete type I was requesting here. So the two concepts do not strongly depend on one another. While I still maintain that doing opaque types my way would be preferable, feel free to use a Tidy-like renamed type instead of my incomplete type when implementing something like the above.

**Comment by balthisar** [comment]
@gagern, thanks for the above. It inspired me a lot to fix up a lot of the junk I've added to the library before tackling this, but I think have a good start: check out the `more_messages` branch for a VERY early preview. Note that this builds on a couple of earlier PR's that I have active awaiting review (including the aforementioned junk cleanup), so don't be alarmed at the diff.

Right now the only "API" replicates what LibTidy already does, and it's implemented in the console application as a demonstration.

I might add some more bits and pieces before you pull it, so the previous sentence might be inaccurate. I'm kind of liking where this is going, and the flexibility in error reporting it might offer in the future.

I like your proposed API. I've started trying to steer away from "error" to "message," and classify the messages as "reports" and "dialogue," the latter of which will also encompass *anything* that LibTidy outputs. So the result is a `TidyMessage` object, and `tidyMessageGetLocalizedMessage` instead of referring specifically to errors.

In the longer term, having an internal message type that's extensible can probably go a **long** way towards simplifying Tidy's plethora of output routines, and maybe make some of the message reporting more inclusive of available data.

Right now that's a chicken and egg problem: I could fully flesh out a public API, or I could generalize the current internals. In the interest of backwards compatibility, I might prefer the latter. I'm thinking that at points in Tidy where errors are currently raised a TidyMessage is created instead of calling any one of the numerous functions with different signatures. Let me try my hand at that...

**Comment by geoffmcl** [comment]
Since @balthisar has planned to **tackle messaging in 5.5** moving the milestone out to `next` **5.5**... thanks...

**Comment by balthisar** [comment]
@gagern, when you have a chance please have a look at #507. It adds a new API in addition to the cleanup I mentioned upthread. It's highly inspired by your sample API above, other than indexing not being used in favor of the "Tidy way" of using a TidyIterator. This is a lot more safe in that we can only return values with meaning, and not values with no meaning, such as if your index were out of bounds. Using TidyIterator avoids that danger.

**Comment by balthisar** [comment]
Well, this **major** gutting of Tidy's messaging system and addition of an API per the request is merged and now in `next`, so I'll close this.

@gagern, please file a new bug if something doesn't work as expected. I plan to trial it in a live application myself, soon.
