### ISSUE TITLE
tidyParseBuffer strip the <style> tag in the body, how to keep it?

### ISSUE THREAD

**Issue by xktproject** [htacg/tidy-html5#413]
When i use "tidyParseBuffer" function to parse a html, it remove the "style"  tag in the body, usually the "style" tag  should be in the head, but i need the contents in the body, what should i do to remain the "style" tag in the body?

**Comment by geoffmcl** [comment]
@xktproject thanks for the report, but I not think I understand... a `<style>` tag should be in the `<head>`, not the `<body>`... how come you want it to remain in `<body>`?

But could you give a small sample html case, the output you get, what config, tidy version, and exactly what you expect the output to be... makes for easy testing, and understanding,,, thanks...

**Comment by xktproject** [comment]
@geoffmcl  Thanks for your reply! Actually i am now out the company, so i can just describe the problem, sorry for making you confused.
The parsed url is [http://proxylist.hidemyass.com/](url), there are some tags "style" like below, when parse the html, below tag `style>.xnyt{display:none}.I76W{display:inline}.iwkZ{display:none}.Z4Ol{display:inline}.T7gL{display:none}.zDtB{display:inline}.B2Xc{display:none}.UeLJ{display:inline}</style>` will be removed from the html body.
`<span><style>.xnyt{display:none}.I76W{display:inline}.iwkZ{display:none}.Z4Ol{display:inline}.T7gL{display:none}.zDtB{display:inline}.B2Xc{display:none}.UeLJ{display:inline}</style><span class="T7gL">92</span><div style="display:none">92</div>101<span class="T7gL">156</span><span class="129">.</span><span style="display:none">27</span><span class="iwkZ">27</span><div style="display:none">27</div><span style="display:none">51</span><div style="display:none">51</div><span style="display: inline">96</span><div style="display:none">115</div><span style="display: inline">.</span><span></span><span style="display:none">7</span><div style="display:none">7</div><span style="display:none">8</span><span class="T7gL">8</span><span></span><span class="UeLJ">11</span><span style="display:none">175</span><span class="B2Xc">175</span><span></span><span style="display:none">181</span><div style="display:none">181</div><span style="display:none">202</span><div style="display:none">202</div><span style="display: inline">.</span><span class="212">30</span></span>`
 I tried with version "5.2.0", but i think it is not related to version,I did not use function like "tidyOptSetBool", actualy i tried to set some configuration, but can not fix it. Usually before html5, tag "style" appearing in "body" tag will be considered as error, because it usually appear in "head" tag, maybe is it the reason?

**Comment by geoffmcl** [comment]
@xktproject thanks for the more information, but sorry, now I am getting even more confused!

I constructed a simple html sample -

````html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Issue #413</title>
</head>
<body>
<style>
p.one { color: red; }
p.two { color: blue; }
</style>
<p class="one">
Red para 1
</p>
<p class="two">
Blue para 2
</p>
</body>
</html>
````

This will pass the validator test, except it wants an attribute added to the `<script>` tag...

Using tidy on this file I get -

````html
Info: Document content looks like HTML5
No warnings or errors were found.

<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Windows version 5.3.0">
<meta charset="utf-8">
<title>Issue #413</title>
</head>
<body>
<style>
p.one { color: red; }
p.two { color: blue; }
</style>
<p class="one">Red para 1</p>
<p class="two">Blue para 2</p>
</body>
</html>
````

So tidy has done nothing about moving the `<style>` tag... it seems to leave it in the `<body>`...

Just to make sure console tidy is not acting any different to tidy tidyParseBuffer, but it uses the same parsing services, added a small tidy-buf-test to https://github.com/geoffmcl/tidy-test and output the tidy node tree. But do not see the `<script>` tag moved...

Its output when loading the above file -

````
F:\Projects\tidy-test\build>Release\tidy-buf-test F:\Projects\tidy-test\test\input5\in_413.html
tidy-buf-test: Loading file 'F:\Projects\tidy-test\test\input5\in_413.html' into a tidy buffer...
tidy-buf-test: Loaded 237 characters into the tidy buffer to pass to 'tidyParseBuffer'...
tidy-buf-test: Showing nodes of 'F:\Projects\tidy-test\test\input5\in_413.html'
tidy-buf-test: Got 13 nodes in tidy tree...
Node:1: DOCTYPE (19) <!DOCTYPE html>^M^J^M^J
Node:2: html
  Node:3: head
    Node:4: meta charset="utf-8"
    Node:5: title
      Node:6: Text (12) Issue #413^M^J
  Node:7: body
    Node:8: style
      Node:9: Text (49) p.one { color: red; }^M^Jp.two { color: blue; }^M^J^M^J
    Node:10: p class="one"
      Node:11: Text (12) Red para 1^M^J
    Node:12: p class="two"
      Node:13: Text (13) Blue para 2^M^J
tidy-buf-test: Done 13 nodes from tidy tree...
````


So at this moment, can not repeat this problem... maybe you can re-test, or explain more... what code are you using, etc... thanks...

**Comment by xktproject** [comment]
@geoffmcl  Thanks very much for your patience!
I use tidyParseString in place of tidyParseBuffer, and test the site: http://proxylist.hidemyass.com/ , and in the codes when debug to the` tidyNodeGetText(tdoc, node_tbody, &tmpbuf);`, you will see that the `<style> </style>` in the initial strings have been removed, i can't figure out the reason.
codes:

```
TidyNode FindNodeByName(TidyDoc &doc, TidyNode tnod, string & strNodeName)
{
	TidyNode child;
	for (child = tidyGetChild(tnod); child; child = tidyGetNext(child))
	{
		ctmbstr name = tidyNodeGetName(child);
		if (name && strNodeName == name)
				return child;

		TidyNode tmp = FindNodeByName(doc, child, strNodeName); /* recursive */
		if (tmp != 0)
			return tmp;
	}
	return 0;
}

void parseSite(string &strResp)
{
	///initialize
	TidyDoc tdoc;
	TidyBuffer docbuf = { 0 };
	TidyBuffer tmpbuf = { 0 };
	int err;

	tdoc = tidyCreate();
	tidyOptSetBool(tdoc, TidyBodyOnly, yes); 
	tidyOptSetBool(tdoc, TidyForceOutput, yes);

	tidyBufInit(&tmpbuf);

	err = tidyParseString(tdoc,  strResp.c_str()); 
	if (err >= 0)
	{
		string strName("tbody");
		TidyNode node_tbody = FindNodeByName(tdoc, tidyGetBody(tdoc), strName);
		tidyNodeGetText(tdoc, node_tbody, &tmpbuf);
	}
}
```

for instance the initial string is:

```
 <tbody>

                        <tr class=""  rel="28555078">
    <td class="leftborder timestamp" rel="1464578342">
        <span class="updatets ">
            22secs        </span>
    </td>
    <td>
        <span>
          <style>
.sXNP{display:none}
.gLTS{display:inline}
.uWY_{display:none}
.Htm4{display:inline}
</style><span class="gLTS">101</span>.<span class="uWY_">48</span><span></span>96<span class="sXNP">150</span><span></span><span class="gLTS">.</span><span style="display: inline">10</span><span style="display:none">27</span><div style="display:none">27</div><span class="uWY_">88</span><div style="display:none">88</div><span style="display:none">118</span><div style="display:none">118</div><span class="uWY_">198</span><div style="display:none">223</div>.30<span style="display:none">39</span><div style="display:none">39</div><span class="sXNP">116</span><div style="display:none">116</div><div style="display:none">159</div><span style="display:none">180</span><span class="uWY_">180</span><div style="display:none">180</div><span class="uWY_">243</span><div style="display:none">243</div>        </span>
    </td>	
```

will change to below and the` <style>
.sXNP{display:none}
.gLTS{display:inline}
.uWY_{display:none}
.Htm4{display:inline}
</style>` tag is removed.
```
<tbody>
<tr class="" rel="28555078">
<td class="leftborder timestamp" rel="1464578342"><span class=
"updatets">22secs</span></td>
<td><span class="gLTS">101</span>.<span class=
"uWY_">48</span>96<span class="sXNP">150</span><span class=
"gLTS">.</span><span style="display: inline">10</span><span style=
"display:none">27</span>
<div style="display:none">27</div>
<span class="uWY_">88</span>
<div style="display:none">88</div>
<span style="display:none">118</span>
<div style="display:none">118</div>
<span class="uWY_">198</span>
<div style="display:none">223</div>
.30<span style="display:none">39</span>
<div style="display:none">39</div>
<span class="sXNP">116</span>
<div style="display:none">116</div>
<div style="display:none">159</div>
<span style="display:none">180</span><span class="uWY_">180</span>
<div style="display:none">180</div>
<span class="uWY_">243</span>
<div style="display:none">243</div>
</td>
```

**Comment by xktproject** [comment]
Hi @geoffmcl , i think i also find a bug, you can try to parse below html 
```
<tr class=""  rel="28595742">
    <td class="leftborder timestamp" rel="1464601922">
        <span class="updatets ">
            14secs        </span>
    </td>
    <td>
        <span>
          <style>
.Yl7C{display:none}
.LeKC{display:inline}
.f8kl{display:none}
.ODLH{display:inline}
.Y_zF{display:none}
.zXVA{display:inline}
</style><div style="display:none">30</div>101<span style="display:none">150</span><div style="display:none">150</div><span style="display:none">187</span><div style="display:none">193</div><span class="f8kl">245</span><span class="zXVA">.</span><span style="display:none">18</span><span></span><span style="display:none">56</span><span class="f8kl">56</span><div style="display:none">56</div><span class="45">96</span><span class="zXVA">.</span><span class="ODLH">10</span><span></span><span style="display:none">37</span><div style="display:none">37</div><span></span><span style="display:none">149</span><span class="Y_zF">149</span><span class="Y_zF">254</span><span style="display: inline">.</span><span style="display: inline">29</span><span style="display:none">38</span><div style="display:none">38</div><span class="Yl7C">41</span><span style="display:none">43</span><div style="display:none">43</div><div style="display:none">81</div><span style="display:none">87</span><div style="display:none">87</div><span style="display:none">107</span><span class="Yl7C">107</span><div style="display:none">107</div><span style="display:none">131</span><div style="display:none">131</div><div style="display:none">146</div><div style="display:none">148</div><div style="display:none">208</div><span class="f8kl">214</span><div style="display:none">214</div><span style="display:none">217</span><span class="Yl7C">217</span><div style="display:none">217</div><span style="display:none">241</span><span class="f8kl">241</span><div style="display:none">241</div><span class="f8kl">244</span>        </span>
    </td>	
    <td>
        96    </td>
        <td style="text-align:left" class="country" rel="vn">
        <span  style="white-space:nowrap;">
            <img src="/images/1x1.png" style="width: 16px; height: 11px; margin-right: 5px;" class="flags-vn" alt="flag "/>
            Viet Nam        </span>
    </td>
    <td>
        <div class="progress-indicator response_time" style="width: 114px" value="5427" levels="speed" rel="5427">
                    <div class="indicator" style="width: 46%; background-color: rgb(255, 204, 0)"></div>
        </div>
    </td>
    <td> 
        <div class="progress-indicator connection_time" style="width: 114px" title="" rel="358" value="358" levels="speed">
                   <div class="indicator" style="width: 93%; background-color: rgb(0, 173, 173)"></div>
              
       </div>
    </td>
    <td>
        HTTP    </td>
    <td nowrap>
        High +KA    </td>
</tr>
```

and the result will be like below which has error.
```
<td>
<div style="display:none"><span>30</span></div>
<span>101<span style="display:none">150</span></span>
<div style="display:none">150</div>
<span style="display:none">187</span>
<div style="display:none">193</div>
<span class="f8kl">245</span><span class=
"zXVA">.</span><span style="display:none">18</span><span style=
"display:none">56</span><span class="f8kl">56</span>
<div style="display:none">56</div>
<span class="45">96</span><span class="zXVA">.</span><span class=
"ODLH">10</span><span style="display:none">37</span>
<div style="display:none">37</div>
<span style="display:none">149</span><span class=
"Y_zF">149</span><span class="Y_zF">254</span><span style=
"display: inline">.</span><span style=
"display: inline">29</span><span style="display:none">38</span>
<div style="display:none">38</div>
<span class="Yl7C">41</span><span style="display:none">43</span>
<div style="display:none">43</div>
<div style="display:none">81</div>
<span style="display:none">87</span>
<div style="display:none">87</div>
<span style="display:none">107</span><span class="Yl7C">107</span>
<div style="display:none">107</div>
<span style="display:none">131</span>
<div style="display:none">131</div>
<div style="display:none">146</div>
<div style="display:none">148</div>
<div style="display:none">208</div>
<span class="f8kl">214</span>
<div style="display:none">214</div>
<span style="display:none">217</span><span class="Yl7C">217</span>
<div style="display:none">217</div>
<span style="display:none">241</span><span class="f8kl">241</span>
<div style="display:none">241</div>
<span class="f8kl">244</span></td>

```

**Comment by geoffmcl** [comment]
@xktproject thanks for the further examples... I have not found the `error` you suggested in your second comment yet, but to deal first with the `<style>` being moved...

First, I do not think it matters whether you use `tidyParseString` in place of `tidyParseBuffer`. Internally, whether the input is a file, a string, or a buffer, **all** go through the **same** internal tidy parsing services to build a node tree... should be no difference...

When I pass your first html fragment to tidy I note it emits 4 warnings, among others -

````
line 9 column 9 - Warning: missing </span> before <style>
line 10 column 11 - Warning: <style> isn't allowed in <td> elements
line 8 column 5 - Info: <td> previously mentioned
line 15 column 803 - Warning: discarding unexpected </span>
````

So tidy is parsing the sequence `<td><span><style>`. On reaching the `<style>` it has to close the open `<span>`. This will create an empty span, which it will later remove, but gives us the 4th warning when it reaches the eventual later `</span>`, now with no open span...

But the 2nd tidy warning is **very** clear. `<style>` is **not** allowed in a `<td>` element. And far from discarding the `<style>` block, it simply moved it into the implied `<head>`.

Now, I am sure this **was** true in legacy `html4--` documents, but maybe the `html5` spec is more liberal in this regard. If you, or others, could find some W3C references that -

 1. shows that a `<span>` can be around a block element like `<style>`, and
 2. shows that a `<td>` element can now contain a `<style>` block...
 
Then then one or both could be marked as a html5 parsing **bug**, and we can attempt a `fix`.

But looking at your code fragments I can not quite work out the overall purpose. If you wanted to get the text html output, why are you just getting the body node? Why not get the root to get all the text? But as I say, do not really know the purpose? Simply, what are you trying to do?

I have added some of your code to the `tidy-buf-test` in the `test-tidy` repo mentioned earlier, so I could study this case more. Will push it shortly. It could be used to get all the **text** in a document, without html markup, if that is part of the purpose...

Concerning your second, it is hard to spot the error. Could you point it out exactly, maybe reduce the html input to a minimal case that shows the error, and maybe it can be a new issue... thanks...

But meantime, look forward to your further comments in this `<style>` issue... thanks...

**Comment by geoffmcl** [comment]
Given the fact that we are about to `release` **5.4**, and there has been no further comments in some 9 months, **and** it remains unclear what the actual problem with libtidy is, closing this...

Please feel free to re-open, or file a new issue... thanks...
