### ISSUE TITLE
How to convert things like &#x00E3; to utf-8?

### ISSUE THREAD

**Issue by pengyu** [htacg/tidy-html5#415]
For the following xml, I want to convert things like `&#x00E3;` to utf-8.

http://ieeexplore.ieee.org/gateway/ipsSearch.jsp?sortfield=py&hc=1000&sortorder=desc&an=6706948

But I still see things like `&#x00E3;` with the following command. Does
anybody know what is the correct command to do the conversion? Thanks.

```
~$ curl "http://ieeexplore.ieee.org/gateway/ipsSearch.jsp?sortfield=py&hc=1000&sortorder=desc&an=6706948" > tmp1.xml
~$ tidy -q -xml --preserve-entities no --output-encoding utf8 tmp1.xml > tmp2.xml
~$ grep Bilz tmp2.xml
<![CDATA[Bilz&#x00E3;  Ara&#x00FA; jo;  Liang Zhao]]>
```

**Comment by geoffmcl** [comment]
@pengyu thank you for the issue... it took some time to do the steps in a debug session... sometimes you can speed that up by just supplying a minimal example... but ok, downloaded the indicated file and constructed a small input5\in_415-1.xml example...

In tracing the code, I find that if the node is CDATA then there will be no entity translations...

````
    /* comment characters are passed raw */
    if ( mode & (COMMENT | CDATA) )
    {
        AddChar( pprint, c );
        return;
    }
````

And there seems **no** option to override this at present... I thought `--escape-cdata yes` might help, but it converts the `&` to `&amp;`, and other things, so was of **no** help...

It seems to do the desired translation to UTF-8 if you remove the `<![CDATA[ ... ]]>`...

Input: 

````xml
<?xml version="1.0" encoding="utf-8"?>
<root>
<authors>
Bilz&#x00E3;  Ara&#x00FA; jo;  Liang Zhao
</authors>
<org>
<![CDATA[Bilz&#x00E3; Ara&#x00FA; jo; Liang Zhao]]>
</org>
</root>
````

Output:

````xml
<?xml version="1.0" encoding="utf-8"?>
<root>
<authors>Bilzã Araú jo; Liang Zhao</authors>
<org>
<![CDATA[Bilz&#x00E3; Ara&#x00FA; jo; Liang Zhao]]>
</org>
</root>
````

So if there is a big use case, perhaps there could be a **new** option to change this CDATA output behavior? Maybe `--encode-cdata yes`, def `no`, ... or something...

Await your further comments... thanks...

**Comment by geoffmcl** [comment]
Since we are about to `release` **5.4**, and it remains unclear what is required of tidy, and no further feedback, for abt 8 months, closing this...

Please feel free to re-open, or file a new issue... thanks...
