### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by AdamMajer** [htacg/tidy-html5#416]
Old tidy used to contain Doxygen configuration file to generate documentation from the source code. This documentation comes in handy when trying to use libtidy.

Please re-add generated documentation.

**Comment by geoffmcl** [comment]
@AdamMajer, oops, maybe I miss your question here, but thanks for bring this up ... maybe the info has not been published enough...

We have moved the `Doxygen` document generation to its own repo [html-tidy.org.api](https://github.com/htacg/html-tidy.org.api)... I have not personally generated the API site documentation in a while, but if you have some problems with it then we would certainly appreciate an [issue](https://github.com/htacg/html-tidy.org.api/issues) filed... We need all the help we can get to improve this API document generation... much appreciated... patch or PR welcome... thanks...

At the moment, the current **Doxygen** generation exists on [API 5.2.0](http://api.html-tidy.org/tidy/tidylib_api_5.2.0/). 

Me, I would like to also publish the latest development, like `5.3.1, 2, 3, ... 100, ... NNNN`, without really polluting the above release site... but somewhere I would always like the **latest** available API docs, for pre-view, comment, suggestions, help, etc... but seek a way to implement this... Maybe a special `version`, on that page, say **Development**... only ever 1, and after each version update, is re-gen'ed...

This is the sort of thing that could be done by say a Travis CI, ..., to automate its update on each version.txt change pushed...

But at this moment, we have published the latest release 5.2.0 `Doxygen` API docs, and offer a way anybody can contribute to the doc gen, improvements, change, fixes, etc... 

So yes, old tidy, and current tidy include API doc generation... it certainly comes in **handy** as you say... I use it regularly when addressing **`libtidy`** API issues, and even though I think I `know` the API, sometimes the current docs make me jump through hoops to find what I want, and often when I find it, it does **not** tell me enough...

I sort of wish we had some wiki pages with more programmer information, or some FAQ pages, that could be searched... I would certainly try to contribute to that, with maybe some **HOW TO** ideas, test, use **`libtidy`**, etc... 

But at the moment, these are only dreams I have... really if you can help in any way improve **`libtidy`** documentation, then we are all ears... 

After you check out the separate API doc gen repo, I hope this solves this issue... thanks...

**Comment by AdamMajer** [comment]
Opps, sorry, somehow I didn't see this other repository. Thank you!

Closing it, since clearly invalid bug report on my part.
