### ISSUE TITLE
<section> is not recognized

### ISSUE THREAD

**Issue by kmaradona** [htacg/tidy-html5#417]
the tidy html dose not recognize some html attributes like section , article

**Comment by geoffmcl** [comment]
@kmaradona thanks for the report...

Can you add a minimal sample html, tidy version, config used, output seen, and output expected... thanks...

**Comment by kmaradona** [comment]
@geoffmcl 

Thank you for replying , i upgraded my tidy-html5 in my mac and it fixed the problem.

the other problem um having hear is that on any .php page um still seeing html warnings like missing <DOCTYPE> , inserting missing 'title' 

I added the ignore_match below , but without any luck , if u can help in that , it will be great 
Thanks

  "ignore_match": [
        "missing <!DOCTYPE> declaration",
        "inserting implicit <body>",
        "inserting missing 'title' element"
    ]

**Comment by geoffmcl** [comment]
@kmaradona ok, an upgrade has fixed the first problem - **great**!

And I am sorry, I do not understand the new issue?

How did you add this `ignore_match`? Does not look like a tidy option...

Again, can you add a minimal sample html/php/..., app used, tidy version, config used, output seen, and output expected... thanks...

**Comment by kmaradona** [comment]
php sample 
https://monosnap.com/file/JtegWoSiQM8PTXhE13kIP2wt2xA3da
===========================================
tidy version
HTML Tidy for Mac OS X released on 25 March 2009
===========================================
Config file 
https://monosnap.com/file/cMYVcym8x5fgeT0a8D21yOtBc4KVr5

the output expected is to not have html warnings on a php file

**Comment by geoffmcl** [comment]
@kmaradona oops, your upgrade **FAILED** `badly` ;=((

That `2009` version is exactly that, year 2009... old, dead, out-of-date, etc...

Commencing with release 5.0.0 in 2015, we have had several releases since then, the last is `5.2.0`, Apr 2016... Where did you get your upgrade from?

We publish binaries here - http://binaries.html-tidy.org/ - but there are other ways to upgrade and install modern tidy...

Only when you are using a current version can we hope to address any problems... thanks...

**Comment by kmaradona** [comment]
@geoffmcl  Thanks for ur replay

**Comment by balthisar** [comment]
@kmaradona, did you get this resolved? I know it's now half a year later, but if you're still having trouble getting the newer version of Tidy running on your Mac, then please feel free to re-open this issue.

**Comment by danodan** [comment]
I had the same issue.. I'am on a Mac me too, when I ran tidy -v the older version was still there even after the download and installation of the new one.
For me the solution was rename the old tidy executable on bin folders and put a symbolic link in place to redirect to the newer version installation folder:

sudo ln -s /usr/local/Cellar/tidy-html5/5.4.0/bin/tidy /usr/local/bin/tidy
and
sudo ln -s /usr/local/Cellar/tidy-html5/5.4.0/bin/tidy /usr/bin/tidy

hope this helps

**Comment by azhuchkov** [comment]
On macOS it may be necessary to run `rehash` after tidy-html5 installation. Or just restart shell session.
The reason of that is the shell caches previously found Tidy location and executes it instead of new one.
