### ISSUE TITLE
incorrectly moving svg <title> to html <head>

### ISSUE THREAD

**Issue by maxstarkenburg** [htacg/tidy-html5#419]
When I tidy (granted, I'm using Tidy2 via Notepad++, but I get the same results with an online tidier) a document like the following:
```
<!DOCTYPE html>
<html>
  <head>
    <title>The page's title</title>
  </head>
  <body>
    <br>
    <svg width="40" height="40" viewBox="0 0 9 9">
      <title>The SVG's title</title>
      <polygon points="3,0 0.5,0 0,0 0,0.5 0,3 0.5,3 0.5,0.5 3,0.5" />
    </svg>
  </body>
</html>
```
It ends up putting the [SVG `<title>` element](https://developer.mozilla.org/en/docs/Web/SVG/Element/title) inside the HTML `<head>` tag, right after its own title, like so:
```
  <head>
    <meta name="generator" content="HTML Tidy for HTML5 (experimental) for Windows https://github.com/w3c/tidy-html5/tree/c63cc39" />
    <title>
      The page's title
    </title>
    <title>
      The SVG's title
    </title>
  </head>
``` 
and strips it out of the `<svg>`. I tried variations of the `output-...` options, but that didn't seem to change the problem (and my input doc apparently doesn't like `input-xml`). My configuration looks like this, in case it's relevant:
```
indent: yes
indent-spaces: 2
wrap: 0
clean: no
markup: yes
vertical-space: yes
output-html: yes
preserve-entities: yes
quote-marks: no
new-inline-tags: title
new-blocklevel-tags: svg, title
new-empty-tags: polygon
```
Finally, here's [my StackOverflow question](http://stackoverflow.com/questions/37779009/) that ended up bringing me here. Let me know if more info is needed. Thanks!

**Comment by geoffmcl** [comment]
@maxstarkenburg, thanks for the issue...

Hmmm, looking at that commit c63cc39, in the meta, that was July 2012. We can do nothing about that old tidy version... It seems you should upgrade the tidy version used by Notepad++.

Running current tidy, with **default** configuration, does not seem to have this problem, using your above input sample!

Output:

````html
F:\Projects\tidy-test\test>tidy5 input5\in_419.html
Info: Document content looks like HTML5
No warnings or errors were found.

<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Windows version 5.3.0">
<title>The page's title</title>
</head>
<body>
<br>
<svg width="40" height="40" viewbox="0 0 9 9">
<title>The SVG's title</title>
<polygon points=
"3,0 0.5,0 0,0 0,0.5 0,3 0.5,3 0.5,0.5 3,0.5"></polygon></svg>
</body>
</html>

etc...
````

So maybe all the problems have been fixed...

Maybe if we can find who built the `Tidy2.dll` plugin, we could quickly update that to use the latest `Tidy` library... I have found https://github.com/bruderstein/NppTidy2? Ah, Ha I have been here before ;=))

I had created a [fork](https://github.com/geoffmcl/NppTidy2), and had updated my Notepad++ installation with a new Tidy2.dll, using tidy verion 4.9.33, circa June 2015, and just trying a `clean`, using the first config, of your sample, and everything  worked fine...

So in that fork, I pulled the latest 5.3.1 in the tidy-html5 submodule folder, and built a new Tidy2.dll, copied it to the Notepad++/plugins, stop and start NotePad++, and **bingo** I was using 5.3.1... an easy update...

So the path is there for you to update, if you want to get into building it yourself... I have added a binary to the repo [Tidy2.dll](https://github.com/geoffmcl/NppTidy2/blob/master/dll/Tidy2.dll), if that helps...

Please advise how I can help more to get your Notepad++ plugin installation updated, and maybe explore where I could publish this `Tidy2.dll` to make it appear in say plugin updates... thanks...

**Comment by maxstarkenburg** [comment]
> I have added a binary to the repo Tidy2.dll, if that helps...

Immensely! I have no experience building .dll files, so I would have been lost. Followed your instructions and it worked (I also looked at the online editor I was using -- https://infohound.net/tidy/ -- and since it's pointing to SourceForge, which I understand to be the old home, I'm assuming it's out of date too). 

I will answer my own StackOverflow question in case people find the same issue there. I don't know where else to point people to your new Tiny2.dll (and don't know anything about Notepad++ dev, or if a pull request at bruderstein/NppTidy2 is appropriate in these cases), but I will link to your fork/dll from S.O. Thanks again!

**Comment by geoffmcl** [comment]
@maxstarkenburg glad it all worked ;=))

I have actually removed the single `Tidy2.dll`, and put it in a `Tidy2-5.3.1.zip`, with some other files, particularly the `quickref.html` so you get matching help... The README.md I added should explain more...

The best way to refer to this 'release' is through this URL - `https://github.com/geoffmcl/NppTidy2/releases/tag/5.3.1` - where the zip is available for download...

This would be the best link to use if you add anything to StcakOverflow...

I do not know what version of tidy is used at - https:/infohound.net/tidy/ - but if you are in touch with the owner then it should be fairly easy to update the site to use the latest and best...

**Comment by maxstarkenburg** [comment]
S.O. answer updated and site owner e-mailed. Thanks!
