### ISSUE TITLE
TidyMergeClean merges <font> into <p>

### ISSUE THREAD

**Issue by ralfjunker** [htacg/tidy-html5#42]
TidyMergeClean merges &lt;font&gt; into &lt;p&gt;, for example:

    <p style="background-color: #00ffff;"><font style="background-color: #ffff00">Text</font></p>

and

    <P><FONT style="BACKGROUND-COLOR: #00ff00">Green Text</FONT></P>

As a result, the paragraph takes the font's color, which is wrong.

**Comment by balthisar** [comment]
Fixed and in develop-500. I'll close this, but feel free to re-open if there continues to be an issue.
