### ISSUE TITLE
Allow allow all "flow content" in body and don't warn for html5

### ISSUE THREAD

**Issue by rtack** [htacg/tidy-html5#428]
See https://www.w3.org/TR/html5/single-page.html#the-body-element 
and https://www.w3.org/TR/html5/single-page.html#flow-content-1

The below is valid html5
```
<!DOCTYPE html>
<html>
<head>
<title>Test</title>
</head>
<body>

<input type="submit" class="button button--primary" value="Submit">

</body>
</html>
```

However tidy built from master complains and says it's invalid html.

```
➜  tests tidy --version                       
HTML Tidy for Linux version 5.3.3
```

```
➜  tests tidy --doctype html5 input-html5.html
line 8 column 1 - Warning: <input> isn't allowed in <body> elements
line 6 column 1 - Info: <body> previously mentioned
line 8 column 1 - Warning: inserting implicit <form>
line 8 column 1 - Warning: missing </form>
Info: Document content looks like HTML5
Tidy found 3 warnings and 0 errors!

<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Linux version 5.3.3">
<title>Test</title>
</head>
<body>
<form><input type="submit" class="button button--primary" value=
"Submit"></form>
</body>
</html>

About HTML Tidy: https://github.com/htacg/tidy-html5
Bug reports and comments: https://github.com/htacg/tidy-html5/issues
Official mailing list: https://lists.w3.org/Archives/Public/public-htacg/
Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
Validate your HTML documents: http://validator.w3.org/nu/
Lobby your company to join the W3C: http://www.w3.org/Consortium

Do you speak a language other than English, or a different variant of 
English? Consider helping us to localize HTML Tidy. For details please see 
https://github.com/htacg/tidy-html5/blob/master/README/LOCALIZE.md
```

**Comment by geoffmcl** [comment]
@rtack thank you for this issue...

From your html sample I certainly agree tidy should not emit these warnings, if running in `html5` mode...

Now, for this specific case, I experimented with the following patch -

````
diff --git a/src/parser.c b/src/parser.c
index ae773aa..4fb7a8c 100644
--- a/src/parser.c
+++ b/src/parser.c
@@ -4022,9 +4022,9 @@ void TY_(ParseBody)(TidyDocImpl* doc, Node *body, GetTokenMode mode)
         */
         lexer->excludeBlocks = no;
         
-        if ( nodeIsINPUT(node) ||
+        if (( nodeIsINPUT(node) ||
              (!TY_(nodeHasCM)(node, CM_BLOCK) && !TY_(nodeHasCM)(node, CM_INLINE))
-           )
+           ) && !TY_(IsHTML5Mode)(doc) )
         {
             /* avoid this error message being issued twice */
             if (!(node->tag->model & CM_HEAD))
diff --git a/version.txt b/version.txt
index 5075da1..abfc04f 100644
--- a/version.txt
+++ b/version.txt
@@ -1,2 +1,2 @@
-5.3.5
+5.3.5-Issue-428
 2016.07.01
````

And maybe this is wrong, and the test for html5 mode should only be for the `input` node, ie to the left of the `||` and thus **not** include skipping other nodes without `CM_BLOCK && CM_INLINE`... have to research and test what they might be...

But that little `fix`, which ever way it is best implemented, in **no** way addresses the bigger question - to allow all "flow content" in body and don't warn for html5

We do have some 21 bits - content model shortcut encoding - lexer.h, from CM_EMPTY to CM_OMITST - but it seems no `bit` for say `CM_FLOW`, that we could use to mark the elements listed in your second link, which would lead to an easy `flow content` test, but maybe we should have one...

Anyway, hope you get the chance to try the above patch, or modifications of it, to see how far that leads us down the road... 

You should certainly update to version 5.3.5 plus... that 5.3.3, well 5.3.2 to 5.3.4, had an enumeration flaw... see #418

I have done this patch in an `issue-428` branch, which I will consider pushing after some more tests... this feels like a **bug**... thanks...

**Comment by geoffmcl** [comment]
@rtack have pushed my `issue-428` branch for testing...

Just pull and checkout issue-428... thanks...

**Comment by geoffmcl** [comment]
@rtack have now merged `issue-428` and this should close this issue... can you confirm... thanks...
