### ISSUE TITLE
Avoid crash in tidyCleanAndRepair if no doc, thus no lexer

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#429]
@nijel I have moved this here, since investigation shows the PR #426 as **not** the correct fix for this...

As suspected `doc->lexer` is **null** if no document loaded... this causes the crash...

Of course I would remind you that what you are doing, namely calling `tidyCleanAndRepair` with no document loaded, is **not** correct libtidy API procedure... 

As can be seen in tidy.c, and the API docs, that clean and repair should only be called if there is a successful load, like -

````
    status = tidyParseFile( tdoc, htmlfil );
    if ( status >= 0 )
        status = tidyCleanAndRepair( tdoc );
````

But **OTOH**, it should not cause a **crash**, even if done...

The simple patch I see is as follows -

````diff
diff --git a/src/tidylib.c b/src/tidylib.c
index 28ebbb2..69ccf9b 100755
--- a/src/tidylib.c
+++ b/src/tidylib.c
@@ -1908,7 +1908,7 @@ int         tidyDocCleanAndRepair( TidyDocImpl* doc )
        it can ever be, so we can start detecting things that shouldn't
        be in this version of HTML
      */
-    if (doc->lexer->versionEmitted & VERS_HTML5)
+    if (doc->lexer && (doc->lexer->versionEmitted & VERS_HTML5))
          TY_(CheckHTML5)( doc, &doc->root );
     TY_(CheckHTMLTagsAttribsVersions)( doc, &doc->root );
 
````

Just check if there is a `lexer` before checking if `versionEmitted` still contains the `VER_HTML5` bits...

Hope you will get a chance to test this, after you rebase your fork to `master`, and remove your current patch from the log, and report... thanks...

**Comment by nijel** [comment]
With your patch I still get a crash:

```
#0  0x00007ffff507829c in prvTidyCheckHTMLTagsAttribsVersions (doc=0x273f560, node=0x273f560) at /home/nijel/work/tidy-html5/src/tidylib.c:1587
#1  0x00007ffff5078a37 in tidyDocCleanAndRepair (doc=0x273f560) at /home/nijel/work/tidy-html5/src/tidylib.c:1913
#2  0x00007ffff5077805 in tidyCleanAndRepair (tdoc=0x273f560) at /home/nijel/work/tidy-html5/src/tidylib.c:1179
```

**Comment by geoffmcl** [comment]
@nijel thanks... you are **absolutely** correct... CheckHTMLTagsAttribsVersions also can **not** be called with **no** document... should have checked...

Have created a **new** patch, which in fact is very close to your PR #426 ... different entry test, but could be persuaded on this... and some comments added...

````
diff --git a/src/tidylib.c b/src/tidylib.c
index 28ebbb2..4787336 100755
--- a/src/tidylib.c
+++ b/src/tidylib.c
@@ -1908,9 +1908,18 @@ int         tidyDocCleanAndRepair( TidyDocImpl* doc )
        it can ever be, so we can start detecting things that shouldn't
        be in this version of HTML
      */
-    if (doc->lexer->versionEmitted & VERS_HTML5)
-         TY_(CheckHTML5)( doc, &doc->root );
-    TY_(CheckHTMLTagsAttribsVersions)( doc, &doc->root );
+    if (doc->lexer) 
+    {
+        /*\ 
+         *  Issue #429 #426 - These services can only be used
+         *  when there is a document loaded, ie a lexer created.
+         *  But really should not be calling a Clean and Repair
+         *  service with no doc!
+        \*/
+        if (doc->lexer->versionEmitted & VERS_HTML5)
+            TY_(CheckHTML5)( doc, &doc->root );
+        TY_(CheckHTMLTagsAttribsVersions)( doc, &doc->root );
+    }
 
 #if !defined(NDEBUG) && defined(_MSC_VER)
     SPRTF("All nodes AFTER clean and repair\n");
````

May take me a few days to push something... But if you get a chance to try it, that would be great... or even present it in a PR...

Like your nijel/utidylib patch as well... avoids a wasted call if nothing loaded...

Thanks for the further testing...

**Comment by nijel** [comment]
Thanks, this works fine! The PR with your patch is here: https://github.com/htacg/tidy-html5/pull/433

**Comment by TPS** [comment]
Since #433 supersedes this & is already merged, shouldn't this be closed?

**Comment by geoffmcl** [comment]
@TPS agreed ;=))
