### ISSUE TITLE
Need a tidyVersion() function

### ISSUE THREAD

**Issue by petdance** [htacg/tidy-html5#43]
For my Perl code that wraps tidy-html5, I'm going to need a function that returns a version number of the library.  This is so my Perl code can know that it's calling an underlying library of some minimum version.

The constant `TY_(release_date)[]` in src/version.h doesn't help because I can't tell any sequence from that.

**Comment by geoffmcl** [comment]
In the develop-500 branch added a -
ctmbstr tidyLibraryVersion(void)
which will return a string "5.0.0"
Is this ok for your use case?

**Comment by balthisar** [comment]
Working in develop-500. Will close.
