### ISSUE TITLE
No (x)html to plain text?

### ISSUE THREAD

**Issue by zhenjie** [htacg/tidy-html5#430]
Hi all, would it be possible to add a function to convert the (x)html document to plain text? Similar to `BeautifulSoup::get_text` function, [BeaufitulSoup 4](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#get-text)

**Comment by geoffmcl** [comment]
@zhenjie thanks for the request...

Given that the role of **`tidy`** is the parse, fix, and beautify **html**, it would be unlikely to have such an option...

But such a `text extractor` tool could easily be written using **`libtidy`**.

In fact my [tidy-test](https://github.com/geoffmcl/tidy-test) repo has such a sample, called [url2text](https://github.com/geoffmcl/tidy-test/blob/master/src/url2text.cxx). It uses the **CURL** library to fetch a URL, and output just the text nodes from the libtidy `tree`...

Of course that CURL fetching could be replaced with a simple file read, and would do more or less what you request...

I do not know anything about `BeaufitulSoup 4`, but it looks like a python library... so the above extraction function could be added as part of the python bindings for tidy...

Hope this helps...

**Comment by geoffmcl** [comment]
Since we are headed for a 5.4 release, and there have been no further comments on this for quite a while, am closing it...

Please feel free to reopen, or post a new issue... thanks...
