### ISSUE TITLE
Feature request: sort-attributes options

### ISSUE THREAD

**Issue by PlNG** [htacg/tidy-html5#434]
I have been looking for a solution to normalize html attribute order to assist HTTP compression routines with compressing my document as well as producing some very organized markup.  Alphabetical is a good step but it makes some critical information a little harder to find within a tag.  I am proposing new sort options:  
"TagFirst": places tag specific attributes first, then global attributes.  
"GlobalFirst": places global specific attributes first, then tag specific attributes.  
"IDClassTagFirst": places ID, Class, then tag specific attributes first, then global attributes.  
"IDClassGlobalFirst": places ID, Class, global specific attributes first, then tag specific attributes.  
"Custom": Where users can define their own order.

**Comment by geoffmcl** [comment]
@PING, thank you for the feature request... looks interesting...

Your sorting options brings up the idea of `global attributes`... I understand that, a term used frequently in W3C docs, **but does tidy**? Have we arranged the attribute tables with the **global** flag in mind? Maybe... need to check deeper...

But other than that, just expanding the enum types, and write a `ptAttValComparator ptComparator`
to compare `p,q`...

The difficult one would be `Custom`... How do you let the user define the `comparitor` to use?

Certainly look forward to more discussion, and even some code to determine if an attribute belongs to **global**... 

And I hope you can explain more the use case... why do we need this sorting... thanks...

**Comment by balthisar** [comment]
It's trivial to add a new attribute globally in `attrdict.h` which was reorganized last year to _massively_ reduce the file size (and allowed the strict-tags-attributes option). However there's no metadata assigned to attributes other than the tags that they apply to, meaning that implementing such sorting would be non-trivial.

**Comment by da2x** [comment]
Before spending any time on this, someone needs to spend time crawling the web to build a large sample site of documents to test which attribute sorting strategy would yield the best compression ratio with both brotli and gzip.

If you really want to improve compression, you’d also need to look at the attribute contents. If two attributes contain similar contents, like the same value for `id` and `class` then those should be sorted together.

However, simply changing from alphanumerical sorting to to frequency sorting should yield good results. Whichever attributes is used on the most number of elements should be listed first followed by decreasingly frequently occurring attributions. This should produce patterns that compressors can do great things with.

**Comment by balthisar** [comment]
If we decide to tackle something like this, I'd suggest that a more feasible/useful approach would be simply to specify a new configuration option that takes a list of attributes, in the order specified, and outputs them that way, i.e., "custom" as described in the original feature request. "Custom" would satisfy all of the other cases.

The only other alternative is to massively refactor Tidy internally, so that it has knowledge of which attributes are global vs. tag specific, and although PR's are welcome, I don't think it's something that's high on our own development radar right now.

This approach would also leave it to individual users to do all of the sampling work indicating what gives them the best compression ratio, as it should.

**Comment by balthisar** [comment]
Created #613 which doesn't really do _everything_ that @PING asked for, but gives everyone the opportunity to do their own thing. When not used, current Tidy behavior is not affected, however when `priority-attributes` is populated with a list of attributes, then those attributes will be printed before any other attributes, in the order that they are specified. Any other attributes are written afterward according to the normal `sort-attributes` setting.

This is kind of a cool change, and I welcome the opportunity to always ensure that my `id` attributes are first, for example.

**Comment by balthisar** [comment]
@PING, @da2x, the new `priority-attributes` can be leveraged to address the original feature request. Sorry it took so long. Granted, it doesn't provide _all_ of the auto-magic features asked, but `priority-attributes` _does_ let you figure out on your own which attributes you wish to prioritize.

Future contributions might be able to enable the auto-magic via the use of the comparator mechanism, and expand the use of the `sort-attributes` configuration option, but a well-crafted config file should make all of this possible now, so I will close this issue.
