### ISSUE TITLE
clarify strict-tags-attributes default value on man page

### ISSUE THREAD

**Issue by jidanni** [htacg/tidy-html5#436]
The man page says

```
   strict-tags-attributes

          Type:    Boolean
          **Default: no**
          Example: y/n, yes/no, t/f, true/false, 1/0

          This options ensures that tags and attributes are applicable for
          the version of HTML that Tidy outputs. When set to **yes (the
          default)**
```

Please pick one, no or yes.

**Comment by geoffmcl** [comment]
@jidanni thanks for this issue... Yes, the description is **wrong**...

Suggest a small patch -

````
diff --git a/src/language_en.h b/src/language_en.h
index 7a8d1de..a895b31 100644
--- a/src/language_en.h
+++ b/src/language_en.h
@@ -2058,8 +2058,8 @@ static languageDefinition language_en = { whichPluralForm_en, {
           be translated. */
       TidyStrictTagsAttr,           0,
         "This options ensures that tags and attributes are applicable for the "
-        "version of HTML that Tidy outputs. When set to <var>yes</var> (the "
-        "default) and the output document type is a strict doctype, then Tidy "
+        "version of HTML that Tidy outputs. When set to <var>yes</var> "
+        "and the output document type is a strict doctype, then Tidy "
         "will report errors. If the output document type is a loose or "
         "transitional doctype, then Tidy will report warnings. "
         "<br/>"
````

Will get to this, unless someone has a better wording... thanks...

**Comment by jidanni** [comment]
By the way,
```
$ tidy --drop-proprietary-attributes yes --strict-tags-attributes yes file.html
line 17 column 7 - Warning: <a> proprietary attribute "ajaxify"
```
Why not also mention "stripped", e.g.,
```
line 17 column 7 - Warning: <a> proprietary attribute "ajaxify"...stripped
```
or
```
line 17 column 7 - Stripping: <a> proprietary attribute "ajaxify"
```
Else the user wonders why the same message appears when you do, or
don't do, anything about it.

HTML Tidy for Linux/x86 version 5.2.0

**Comment by balthisar** [comment]
The intention was to make `strict-tags-attributes` the default, which is probably how it got into the documentation that way. We wanted to clean up all of the output tests, first, based on the new default behavior, but then I got sidetracked into a transpacific move, so... thanks for the catch!

There are several documentation issues on the tracker now. I'll try to take a stab at them as I migrate back to the online world.

**Comment by geoffmcl** [comment]
@jidanni, as we are about to `release` **5.4**, can only move this out to `next` **5.5**...

@balthisar note you mentioned this `strict-tags-attributes` option in a direct email, and certainly look forward to your **stab** at the `several`, maybe even **many**, documentation issues in **5.5**... thanks...
