### ISSUE TITLE
where are my blank lines?

### ISSUE THREAD

**Issue by Claghorn** [htacg/tidy-html5#440]
The purpose of indenting is to make the html human readable. In old tidy, I got blank lines between things like paragraphs, now all the blank lines have disappeared. I read through the config flags and options and none of them sounded like they would have anything to do with blank lines. How do I get my blank lines back?

If it can't provide them now, consider this a request for a new config parameter. I can't read what it generates now even with indenting.

**Comment by geoffmcl** [comment]
@Claghorn have you tried `--vertical-space yes`?

As the docs state "This option specifies if Tidy should add some extra empty lines for readability."

Look forward to your further comment...

**Comment by Claghorn** [comment]
Thank you, I guess I couldn't see that option for all the others. (Of course, now there seems to be too much vertical space with two lines between each paragraph, but it is still much more readable, two blank lines is no big deal).
