### ISSUE TITLE
Feature request: Support Subresource Integrity

### ISSUE THREAD

**Issue by dengeist** [htacg/tidy-html5#441]
SRI  was recently published as a [W3C Recommendation](https://www.w3.org/TR/2016/REC-SRI-20160623/) and it would be great to see Tidy support it in the future. 

In the meantime, Tidy warns that  SRI attributes `integrity` and `crossorigin` are proprietary. Is there a way to teach Tidy new tag attributes? Turning off all warnings to suppress messages about SRI is undesirable.

**Comment by geoffmcl** [comment]
@dengeist thanks for the issue... quickly reviewing your link it certainly looks like tidy should not warn about SRI attributes...

I remember something recently at least about `crossorigin` - yes, can you look at #418... Is this related? That has been merged... Did we miss some cases?

If yes, can you give a brief sample html, config used, output, and expected output... thanks...

Or is this completely different? Separate...

Look forward to your further comments... including tidy library version tested, etc...

**Comment by dengeist** [comment]
Hi @geoffmcl!

The original problem tag is directly from jQuery's CDN:

```
<script src="https://code.jquery.com/jquery-3.1.0.min.js"
        integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="
        crossorigin="anonymous"></script>
```

Tidy warns 'proprietary' attribute on both `crossorigin` and `integrity`. After reading #418, I saw comments about the tags you were explicitly considering while adding crossorigin support, so I tried:

`<img src="http://placehold.it/350x150" alt="placeholder" crossorigin="anonymous">`

and `crossorigin` is again warned as proprietary. I expected no warnings from the file in either case because there are no other issues. Again, these can be suppressed by changing `show-warnings` but that is not ideal.

Some background info:

```
OS X 10.11.3

$ tidy -v
HTML Tidy for Mac OS X version 5.2.0

$ which tidy 
/usr/local/bin/tidy 
# this should be the Brew one, right? OSX's default Tidy is in usr/bin

Tidy config: default
```

Let me know if you need something else!

**Comment by dengeist** [comment]
Okay, so I just realized the problem is that I got Tidy from Brew. I see that the actual current library is newer. Apologies!

**Comment by geoffmcl** [comment]
Hi @dengeist, thanks for the further information, especially the version and the source... that makes a **lot** of difference...

Yes, the release 5.2.0, available by `Brew`, does not have this **fix**, or **enhancement**... 

I am sorry that normally, distributions like `Brew`, and others, do not offer you the latest development version, but perhaps they could/should... but that is up to each distribution to choose...

But this is an additional **new** feature, as tidy moves on, and is **not** a critical **bug**, so this enhancement of tidy is very unlikely to be pushed back to release version 5.2, creating say a 5.2.1, which `Brew` might pick up, so the only solution is to move forward... 

It **will** be in the next tidy release, `5.4`, but there is no definite date on that yet... hopefully, in a few months, at most...

BUT, your issue also now points out, we seemed to have **missed** the `integrity` attribute... in my book, this is a **bug**... and should be addressed...

You know, `Brew` is actually a simple script for cloning the tidy repo, and building the project... You should be able to achieve the same by directly cloning the latest, building and installing the project... without `Brew`...

But, this points out an issue, that the `integrity` attribute is not yet accepted by tidy version 5.3.7 plus... and that needs to be addressed... PR very welcome...

Again, thanks for showing this up...

**Comment by dengeist** [comment]
I don't know why I didn't think to use Brew to build the latest Tidy! Thanks for the suggestion, and I'm very glad I could help raise the `integrity` issue. Sorry again for not realizing I was outdated.

**Comment by geoffmcl** [comment]
@dengeist, that is interesting, that Brew can build the **latest** tidy... maybe you could share with us how to do that... that is good to know...

So thanks to @bdesham, #442, have now merged this 'integrity' support... and that merge marked this as closed...

So to get this support you need to build the **latest** `master` branch, version 5.3.8, plus... 

Would appreciate you testing, and reporting... if you get a chance... thanks...
