### ISSUE TITLE
src/parser.c:4661]: (style) Redundant condition

### ISSUE THREAD

**Issue by dcb314** [htacg/tidy-html5#444]
src/parser.c:4661]: (style) Redundant condition: node.line==1. 'node.line!=1 || (node.line==1 && node.column!=1)' is equivalent to 'node.line!=1 || node.column!=1'

Source code is

```
if (node->line != 1 || (node->line == 1 && node->column != 1))
```

**Comment by geoffmcl** [comment]
@dcb314 thanks for the issue...

Assume you are talking about line https://github.com/htacg/tidy-html5/blob/master/src/parser.c#L4740 ?

Certainly agree the same switch logic is achieved by -

````
    if (node->line != 1 || node->column != 1)
````

Maybe others care to comment...

It is quite minor, but will consider it... thanks for spotting it, and reporting...

**Comment by balthisar** [comment]
I'll close this as it's not actually a bug and no support is needed. If it's submitted in a PR, will he happy to accept. Thanks for reporting.
