### ISSUE TITLE
Suggested edit to source-code documentation (comments)

### ISSUE THREAD

**Issue by AthanasiusOfAlex** [htacg/tidy-html5#452]
This took me two days to figure out, and I discovered the solution by chance, so I am suggesting adding a note in the source-code comments.

According to the comments in `tidy.h`, the function`tidyOptParseValue()`’s purpose is to “Set named Option value as a string.  Good if not sure of type.”

I suggesting adding the following annotation to that comment: The argument `optnam` should be the name given in the API, not the name of the corresponding enum given in the source code. For instance, one should use `error-file`, not `TidyErrFile`.

On a related note, after some testing, it seems that the function `tidyOptGetValue()` _only_ works when the given value is a string. It will _not_ convert, say, an integer-valued option into a string. In fact, if one attempts to read such a value, the function returns, not a null pointer (which could be tested for), but a garbage pointer that crashes the program when dereferenced. I suggest adding a suitable warning in the comments.

For instance, in C++, the following code produces a crash even if I check for null pointers:

``` c++
tidyDoc = tidyCreate();
auto showErrors = tidyOptGetValue(tidyDoc, TidyShowErrors);

if (showErrors!=nullptr) {
    cout << showErrors << endl;
}
```

**Comment by geoffmcl** [comment]
@AthanasiusOfAlex thanks for the issue... it seems you bring up two good **documentation** points -

 1. Bool tidyOptParseValue( TidyDoc tdoc, ctmbstr optnam, ctmbstr val );
    - Set named Option value as a string.  Good if not sure of type.
 2. ctmbstr tidyOptGetValue( TidyDoc tdoc, TidyOptionId optId );
    - Get current Option value as a string
    
It certainly seems the code comments in `tidy.h`, for these two functions, which are then put in the API documentation, leave a **lot** to be desired! ;=))

I certainly agree, the first, `tidyOptParseValue` should make it clear that the `optnam` is a `string`, and **not** an enumerated `TidyOptionId`. Of course here we can see in `tidy.h` that the 2nd parameter is a `ctmbstr`, but agreed, the documentation could/should make that much clearer.

And yes, the second, `tidyOptGetValue` does sort of imply it will return the option as a string, when in fact it will **only** return an option that is a `string`. In fact, the DEBUG build of libtidy has an `assert( opt && opt->type == TidyString );` which will abort the program if it is **not** a `string` type. 

In the release it just returns the `.p` value of the particular `config.value[id]`, which may not be zero, so a `nullptr` test will **not** work, and who know what passing that returned value to `cout` will do...

But I am **not** too familiar to how `doxygen` converts these `tidy.h` code comments to API documentation, so hope you, or others can make very **specific** suggestions on how to change this/these... 

That is a patch or PR would be great... thanks...

**Comment by AthanasiusOfAlex** [comment]
> I certainly agree, the first, tidyOptParseValue should make it clear that the optnam is a string, and not an enumerated TidyOptionId

... and that the string that should go there is to be found in the API. (I thought naively that I was supposed to put in the TidyOptionId as a string.)

**Comment by geoffmcl** [comment]
@AthanasiusOfAlex I have started to `experiment` with this API documentation change... and now can do more...

I do **not** yet want to push it to the main API url, since we are **not** yet at the next release point, so I am using a `temporary` free rhcloud/openshift API URL...

Check out - http://tidy5docs-htacg.rhcloud.com/group__Configuration.html#ga0fbe23ab1e4ec374fa38e6f514617e4d - you may need to do a **refresh** to get the latest...

But please let me know what you think...

As I say, the actual `wording` of the API may need more massaging... and really **welcome** more thought on that, but it is a start of a change... and for other API items... thanks...

Of course, such API documentation changes will only appear on the next `official` http://api.html-tidy.org/ when we make the **next** release, 5.4.0, but would really appreciate further feedback before that... thanks...

**Comment by geoffmcl** [comment]
As we are about to issue a `release` **5.4**, and no change has yet been presented, can only move the milestone to `next` **5.5**.

In **5.5** we are expecting quite a number of documentation changes, and hopefully this will be included... thanks...

**Comment by balthisar** [comment]
Made the API documentation more explicit for the first item, and the second concern as already addressed during a documentation spree a bit earlier this year.

@AthanasiusOfAlex, thanks for the report.
