### ISSUE TITLE
Compiling with tidy-html5 static library in my own project

### ISSUE THREAD

**Issue by zen0x90** [htacg/tidy-html5#453]
I tried to add tidy-html5 library in my projects. To start I just create a file named "clean.c" with only two includes :

>#include \<tidy.h\>
>#include \<tidybuffio.h\>

I used libtidys.a file and I copied it into libs directory in my project.

So I compiled the file that way :

>$ gcc -ansi -pedantic -std=c99 -c -W -Wall -O -I/foo/bar/inc -I/usr/include/libxml2 -I/foo/bar/dependencies/tidy-html5/include -L/foo/bar/libs -ltidys clean.c -o clean.o

And here is the results :

>In file included from /foo/bar/dependencies/tidy-html5/include/tidy.h:65:0,
>             from clean.c:1:
>/foo/bar/dependencies/tidy-html5/include/tidyplatform.h:547:9: error: unknown type name 'uint'
> typedef uint tchar;         /* single, full character */
>         ^
>In file included from clean.c:1:0:
>/foo/bar/dependencies/tidy-html5/include/tidy.h:368:13: error: unknown type name 'uint'
> TIDY_EXPORT uint TIDY_CALL        tidyErrorCount( TidyDoc tdoc );
>             ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:371:13: error: unknown type name 'uint'
> TIDY_EXPORT uint TIDY_CALL        tidyWarningCount( TidyDoc tdoc );
>             ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:374:13: error: unknown type name 'uint'
> TIDY_EXPORT uint TIDY_CALL        tidyAccessWarningCount( TidyDoc tdoc );
>             ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:377:13: error: unknown type name 'uint'
> TIDY_EXPORT uint TIDY_CALL        tidyConfigErrorCount( TidyDoc tdoc );
>             ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:469:13: error: unknown type name 'ulong'
> TIDY_EXPORT ulong TIDY_CALL         tidyOptGetDefaultInt( TidyOption opt );
>            ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:487:13: error: unknown type name 'ulong'
> TIDY_EXPORT ulong TIDY_CALL         tidyOptGetInt( TidyDoc tdoc, TidyOptionId optId );
>             ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:489:86: error: unknown type name 'ulong'
> TIDY_EXPORT Bool TIDY_CALL          tidyOptSetInt( TidyDoc tdoc, TidyOptionId optId, ulong val );
>                                                                                      ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:594:13: error: unknown type name 'uint'
> TIDY_EXPORT uint TIDY_CALL tidyGetByte( TidyInputSource* source );
>             ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:597:68: error: unknown type name 'uint'
> TIDY_EXPORT void TIDY_CALL tidyUngetByte( TidyInputSource* source, uint byteValue );
>                                                                ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:631:63: error: unknown type name 'uint'
> TIDY_EXPORT void TIDY_CALL tidyPutByte( TidyOutputSink* sink, uint byteValue );
>                                                           ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:643:44: error: unknown type name 'uint'
>   uint line, uint col, ctmbstr mssg );
>   ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:643:55: error: unknown type name 'uint'
>   uint line, uint col, ctmbstr mssg );
>   ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:646:44: error: unknown type name 'uint'
>    uint line, uint col, ctmbstr mssg, va_list args );
>    ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:646:55: error: unknown type name 'uint'
>   uint line, uint col, ctmbstr mssg, va_list args );
>   ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:649:49: error: unknown type name 'uint'
>    uint line, uint col, ctmbstr code, va_list args );
>    ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:649:60: error: unknown type name 'uint'
>   uint line, uint col, ctmbstr code, va_list args );
>   ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:653:51: error: unknown type name 'TidyReportFilter'
>   TidyReportFilter filtCallback );
>   ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:656:51: error: unknown type name 'TidyReportFilter2'
>   TidyReportFilter2 filtCallback );
>   ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:659:56: error: unknown type name 'TidyReportFilter3'
>   TidyReportFilter3 filtCallback );
>   ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:675:57: error: unknown type name 'uint'
>  typedef void (TIDY_CALL *TidyPPProgress)( TidyDoc tdoc, uint line, uint col, uint destLine );
>                                                          ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:675:68: error: unknown type name 'uint'
>  typedef void (TIDY_CALL *TidyPPProgress)( TidyDoc tdoc, uint line, uint col, uint destLine );
>                                                           ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:675:78: error: unknown type name 'uint'
>  typedef void (TIDY_CALL *TidyPPProgress)( TidyDoc tdoc, uint line, uint col, uint destLine );
                                                          ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:678:51: error: unknown type name 'TidyPPProgress'
>TidyPPProgress callback );
>^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:756:65: error: unknown type name 'uint'
>tmbstr buffer, uint* buflen );
>               ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:908:13: error: unknown type name 'uint'
>  TIDY_EXPORT uint TIDY_CALL tidyNodeLine( TidyNode tnod );
>              ^
>/foo/bar/dependencies/tidy-html5/include/tidy.h:909:13: error: unknown type name 'uint'
>  TIDY_EXPORT uint TIDY_CALL tidyNodeColumn( TidyNode tnod );
>              ^
>In file included from clean.c:2:0:
>/foo/bar/dependencies/tidy-html5/include/tidybuffio.h:27:5: error: unknown type name 'uint'
> uint  size;         /**< # bytes currently in use */
> ^
>/foo/bar/dependencies/tidy-html5/include/tidybuffio.h:28:5: error: unknown type name 'uint'
> uint  allocated;    /**< # bytes allocated */ 
> ^
>/foo/bar/dependencies/tidy-html5/include/tidybuffio.h:29:5: error: unknown type name 'uint'
> uint  next;         /**< Offset of current input position */
> ^
>/foo/bar/dependencies/tidy-html5/include/tidybuffio.h:40:59: error: unknown type name 'uint'
> TIDY_EXPORT void TIDY_CALL tidyBufAlloc( TidyBuffer* buf, uint allocSize );
>                                                           ^
>/foo/bar/dependencies/tidy-html5/include/tidybuffio.h:46:55: error: unknown type name 'uint'
> uint allocSize );
> ^
>/foo/bar/dependencies/tidy-html5/include/tidybuffio.h:52:47: error: unknown type name 'uint'
> uint allocSize, uint chunkSize );
> ^
>/foo/bar/dependencies/tidy-html5/include/tidybuffio.h:52:63: error: unknown type name 'uint'
> uint allocSize, uint chunkSize );
> ^
>/foo/bar/dependencies/tidy-html5/include/tidybuffio.h:61:70: error: unknown type name 'uint'
>TIDY_EXPORT void TIDY_CALL tidyBufAttach( TidyBuffer* buf, byte* bp, uint size );
>^
>/foo/bar/dependencies/tidy-html5/include/tidybuffio.h:68:70: error: unknown type name 'uint'
> TIDY_EXPORT void TIDY_CALL tidyBufAppend( TidyBuffer* buf, void* vp, uint size );
>                                                                      ^
>Makefile:16: recipe for target 'clean.o' failed
>make[1]: *** [clean.o] Error 1
>Makefile:26: recipe for target 'all' failed
>make: *** [all] Error 1

I'm on GNU/Linux. So I think I can fix that by adding "defined(LINUX_OS)" in the first preprocessor instructions (I didn't try). But, thats strange because this library is heavily used so...did I miss something ?

Cheers

**Comment by geoffmcl** [comment]
@zen0x90 yes, I too seem to remember having run into this problem in linux of a **missing** `uint`...

Will look back over my stuff to find out what I did to solve it... 

Maybe some others will have a quick, better idea...

On another topic, but maybe related, why are you using `-std=C99`? Do you use `C99` declarations in your `clean.c`? Why do you not name it `clean.cxx`, then you should not need `C99(C11)` C extensions, which by the way are **not** supported in Windows MSVC compilers until the latest MSVC 2015...

But I am sure there is a simple explanation of this missing `uint` case... it has been in Tidy since its beginning... quite puzzling...

**Comment by zen0x90** [comment]
>/* hack for gnu sys/types.h file which defines uint and ulong */
>
>#if defined(BE_OS) || defined(SOLARIS_OS) || defined(BSD_BASED_OS) || defined(OSF_OS) || defined(IRIX_OS) || defined(AIX_OS)
>#include \<sys/types.h\>
>#endif
>#if !defined(HPUX_OS) && !defined(CYGWIN_OS) && !defined(MAC_OS_X) && !defined(BE_OS) && !defined(SOLARIS_OS) && !defined(BSD_BASED_OS) && !defined(OSF_OS) && !defined(IRIX_OS) && !defined(AIX_OS) && !defined(LINUX_OS)
>\# undef uint
>typedef unsigned int uint;
>#endif
>#if defined(HPUX_OS) || defined(CYGWIN_OS) || defined(MAC_OS) || defined(BSD_BASED_OS) || defined(_WIN32)
>\# undef ulong
>typedef unsigned long ulong;
>#endif


Hmm...I'm not sure but did they forget this : 
>defined(LINUX_OS)

>On another topic, but maybe related, why are you using -std=C99? Do you use C99 declarations in >your clean.c? Why do you not name it clean.cxx, then you should not need C99(C11) C extensions, >which by the way are not supported in Windows MSVC compilers until the latest MSVC 2015...

Well actually, I have no code for "clean.c" but my project use C99. I'm not concerning by Windows as I'm on GNU/Linux.

**Comment by zen0x90** [comment]
Still in platform.h :

>#elif defined(linux) && (defined(__i386__) || defined(__i486__) || defined(__i586__) || defined(__i686__))
>/* Linux on x86 - gcc compiler */
>#define LINUX_OS
>#ifndef PLATFORM_NAME
>#define PLATFORM_NAME "Linux/x86"
>#endif

Nothing for GNU/Linux 64 bits...So LINUX_OS macro is not defined.

**Comment by geoffmcl** [comment]
@zen0x90 thank you for your continued research, time and testing... this is good...

Yes, you seem to have found a **hole** in the `tidyplatform.h`, in that is does **not** correctly address certain `linux` 64-bit builds, and look forward to a patch or PR to address this...

I am sure you will have noted the comment in there -

````
/* hack for gnu sys/types.h file which defines uint and ulong */
````

My builds, of projects using `libtidy` in Ubuntu 14.04 LTS 64 bit linux do **not** have this problem...

As you can understand, it is very difficult to keep this tidy `platform` header up-to-date, and would really seek ways to avoid this continual update of that tidy `header`... it should not be necessary... to discover, and account for, every possible OS `type`...

When you run `tidy -v`, what does it show?

Maybe it could be included in a cmake configuration... that is search for a `<sys/types.h>` and set a variable `HAVE_SYS_TYPES_H`, and on this find/not found, include that file... or something...

Concerning `C99`, I am sad that you do not seem to include `Windows` cross porting compatibility in your projects... Yes, you are in GNU/Linux 64 bits, but do you **not** want your code to be compileable in Windows? No problem... that is for sure, your choice...

But back to the **missing** `uint`, we **do** want tidy to be compileable in **ALL** systems, so what do you suggest? thanks...

**Comment by zen0x90** [comment]
I identified precisely the problem now. This is because "uint" type has been removed from c99. In <sys/types.h> the macro "__USE_MISC" must be defined to use "uint" type. And "__USE_MISC" macro is defined only if "_BSD_SOURCE || _SVID_SOURCE". But both are deprecated.

Because of that, just checking sys/types.h is not enough. I think the better solution is to declare (check the types existence first if needed) "uint" and "ulong" in "tidyplatform.h".

Otherwise, it works fine (with c99) if you compile with "_GNU_SOURCE" (this define "__USE_MISC").

> $  tidy -v                                                                    
> HTML Tidy for Linux version 5.2.0

Concerning Windows, c99 is not implemented (in Windows compiler). So, I don't want to fight with preprocessor instruction to make it compile on Windows. But in case, I need my project to be able to compiler on Windows I'll do it.

So, I resolve the issue by compiling with "-D__GNU_SOURCE".

**Comment by geoffmcl** [comment]
@zen0x90 glad you found the solution, and as I thought, it is tied to this quasi `C99(C11)` standard?, absolutely **not** yet agreed for massive cross-porting of code...

Why some `gcc` developers think that it is a good idea to port some `C++` conventions, namely you can declare a new variable in certain contexts at any time, is quite beyond me ;=)) and do not quite see how this got mixed up with the declaration of a `uint` and `ulong`... that too is quite beyond me... but `c'est la vie`...

All declared function variables **must** be allocated off the stack of the function, whether they are declared at the top of the function, as in the K&R C standard, before any actual function code, or when ever the developer just thinks they needs them... 

It is just a question of whether the compiler is willing to over look this late declaration or not... all variable just become an ASM offset into the stack... It **is** the agreed `standard` in C++...

And as you understand, MS Windows compilers have been **very** late coming to this, what `laziness`? party ;=))

But very glad you found yet another **GNU** define, that puts things back to where they were a little, even when you choose `C99`... for what ever reason...

I will try to find a place in our Tidy documentations to add the obscure `-D__GNU_SOURCE`, if you want to declare `C99`, and still use **`libTidy's`** C headers... 

And certainly hope you will consider a MS Windows port, probably still upwards of `40% plus` of the desktop market share in some stats, for your great app...

Really, thank you for this issue, time. exploration, solution and close...

**Comment by zen0x90** [comment]
>glad you found the solution, and as I thought, it is tied to this quasi C99(C11) standard?, absolutely >not yet agreed for massive cross-porting of code...

God !! You're right I don't know why I used C99...Well, I'm switching to C11 now.

>And as you understand, MS Windows compilers have been very late coming to this, what laziness? >party ;=))

>But very glad you found yet another GNU define, that puts things back to where they were a little, >even when you choose C99... for what ever reason...

>I will try to find a place in our Tidy documentations to add the obscure -D__GNU_SOURCE, if you >want to declare C99, and still use libTidy's C headers...

>And certainly hope you will consider a MS Windows port, probably still upwards of 40% plus of the >desktop market share in some stats, for your great app...

>Really, thank you for this issue, time. exploration, solution and close...

\o/    ;)
