### ISSUE TITLE
Ignoring close elements

### ISSUE THREAD

**Issue by MartinPerry** [htacg/tidy-html5#457]
I have a HTML page (`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">`) 

Problem is with this:
`<script type="text/javascript" src="../lib.js"><!--some comment --></script>`

The closing `</script>` element is not found. Comment section is correctly found. 

I have tried to step code, but it seems that the node is not in the hierarchy at all.

My code:

```
void IterateNode(TidyDoc doc, TidyNode tnod)
{
    TidyNode child;
    for (child = tidyGetChild(tnod); child; child = tidyGetNext(child))
    {
        ctmbstr name = tidyNodeGetName(child);
        if (name)
        {
            TidyNodeType nodeType = tidyNodeGetType(child);

            // if it has a name, then it's an HTML tag ...
            TidyAttr attr;
            printf("<%s ", name);
            // walk the attribute list
            for (attr = tidyAttrFirst(child); attr; attr = tidyAttrNext(attr))
            {
                printf(tidyAttrName(attr));
                tidyAttrValue(attr) ? printf("=\"%s\" ", tidyAttrValue(attr)) : printf(" ");
            }
            printf(">\n");          
        }
        else
        {
            /* if it doesn't have a name, then it's probably text, cdata, etc... */
            TidyBuffer buf;
            tidyBufInit(&buf);
            tidyNodeGetText(doc, child, &buf);
            printf("%s\n", buf.bp ? (char *)buf.bp : "");
            tidyBufFree(&buf);          
        }
        IterateNode(doc, child); /* recursive */
    }
}
```

**Comment by geoffmcl** [comment]
@MartinPerry thanks for the issue. I started looking at this before you edited the post, but ok you have remove the `random` loss of a `<TD>` node, but still think tidy somehow misses the closing `</script>` tag... Is that it?

I constructed an `in_457-1.html` sample -

[in_457-1.html.txt](https://github.com/htacg/tidy-html5/files/504993/in_457-1.html.txt)

Cut your code into my [tidy-tree.cxx](https://github.com/geoffmcl/tidy-test/blob/master/src/tidy-tree.cxx) test sample code, and can not find any problem using the latest `5.3.11 (2016.09.11)` master branch code...

Running `tidy-tree` on my sample there does not seem a problem...

My `dumpNode` reports 49 nodes, and so does your `IterateNode` seems to be doing the same... log output -

[temptree.txt](https://github.com/htacg/tidy-html5/files/504994/temptree.txt)

Specifically note -
````
R=5 C=1: Returning starttag node <script type="text/javascript" src="../lib.js"> stream
R=5 C=48: Returning lex-cdata TextNode [<!--some...ment -->]20 lexer
R=5 C=68: Returning endtag node <script> stream
````

Sorry, can not seem to duplicate the problem. Am I missing something here? Please advise...

**Comment by MartinPerry** [comment]
Thank you for your reply. The "random" loss of elements was caused by cURL. It sometimes downloaded the page incorrectly and I did not notice - it was just one missing block from raw downloaded data.

As for `<script>`, I can see it in "dump", but  there is no "close" node from within IterateNode .... even in your example, there is no output of </....> in the second half of text:

Eg., what I expected
```
   StartTag script   type="text/javascript" src="../lib.js"
    Text   (20) '<!--some comment -->'
  <THIS IS MISSING (?) EndTag script .....>
  StartTag body
```
(However, this is not just <script> issue, I don't see "end tags" anywhere.)

**Comment by geoffmcl** [comment]
@MartinPerry yes, that is correct. **NO** `end tags` are kept in the internal tidy node tree... none... they are **all** discarded...

They can only be **implied** by the fact that there are no more children on a node... if you see what I mean...

So after dealing say with the `<script>` tag, with one child, text, it ends, as you can see, by the loss of the `indent` in my log, which is where the end tag, if needed for that tag, needs to be added... before the StartTag body...

And look at say nodes 9 to 14, like -

````
  Node:9: body 
    Node:10: table 
      Node:11: tr 
        Node:12: td 
          Node:13: font 
            Node:14: Text (6) 
````

So at this point in the iteration of the node tree, if that was the end of data, we would need to close 5 open tags, well actually 6, so in this case would need to add -

````
          </font>
        </td>
      </tr>
    </table> 
  </body>
</html>  
````

Tidy has an option `--hide-endtags`, Boolean, def no, and some `optional` implied end tags would not be output...

Of course, some tags, like `meta`,... do not have an end tag, and if correct output is expected from a tidy node iterator, you have to know those... see the quite complicated code in `pprint.c`...

Hope this make the situation clear ;=)) but understand this may not be what you expected...

But it depends on exactly what you are trying to achieve with your code... feel free to ask more question, and I will help if I can...

**Comment by MartinPerry** [comment]
@geoffmcl 
Ok.. thank you for your help. I will do the checks manually using recursion depths.

**Comment by geoffmcl** [comment]
As we are about to `release` **5.4**, and there has been no further feedback in 4 months or so, am closing this...

Please feel free to -re-open, or file a new issue... thanks...
