### ISSUE TITLE
Write design goals

### ISSUE THREAD

**Issue by petdance** [htacg/tidy-html5#47]
Create a design document that states the high-level design decisions.  Things like "We only validate HTML 5, and not HTML 4 or XHTML", or "We will only run on these compilers: gcc 4.x or above, Visual C whatever," etc etc.

**Comment by geoffmcl** [comment]
Well at this time 'tidy5' is intended to validate, tidy, clean everything, unless we run into a real road block that forces a separation... And at present know no restrictions on which compiler, at least as far as Visual C is concerned... but agree would be good to state this somewhere... Maybe start something and I will help fill it in...

**Comment by balthisar** [comment]
Agreed. I'm mostly here to organize the milestones. Probably not on track for 5.0.0, but don't want to leave this empty.

**Comment by balthisar** [comment]
Added placeholder to /htacg/community. I will close this. Don't hesitate to work on the draft documents. :-)
