### ISSUE TITLE
Question: Merge sibling tags ?

### ISSUE THREAD

**Issue by ctjhoa** [htacg/tidy-html5#474]
Hi,

I would like to know if `tidy` can merge identical sibling tags.
For example, turn this:
```html
<p>
<span style="color:red">A</span>
<span style="color:red">B</span>
</p>
```

into this:
```html
<p>
<span style="color:red">AB</span>
</p>
```

All merge options I see (`merge-divs`, `merge-spans`, ...) works with nested tags but not siblings according to [the doc](http://api.html-tidy.org/tidy/quickref_5.0.0.html)
Thanks

**Comment by geoffmcl** [comment]
@ctjhoa thanks for your question, but I know of **no** option to merge siblings...

And take care with your example... you have put a newline between the two `spans`... that would become a space... so you would get `A B`... that is the `A` and `B` text elements would be separated by the space,` ` text element... which would not have the same rendering options...

So if you remove that newline/space, I suppose it would be possible, in post processing, to find say touching text element, in the node tree, review the `span` around them, and if the same merge the two text elements, and extending the `span` around them both...

Even as I write that, I can see some quite difficult code decisions, that the human eye can see quite easily... so even if there was a convincing use case for such a merging, which I am not yet convinced of, I personally would not be prepared to work on such an `option`...

But given a substantial use case, maybe you, or others may, and I would consider it, and help where I can...

Will leave this Feature Request open for a while for further comments... thanks... but no definite milestone yet...

**Comment by ctjhoa** [comment]
@geoffmcl Thanks for your answer.
To establish a little bit of context, my company manage a lot of MS Word files turned into HTML by `Aspose Word` (similar to google docs export). Those documents are often complex and very long. My first goal was to optimize the generated HTML to get a smaller HTML and faster rendering.

I totally forgot the messy behavior on whitespace in HTML/CSS.
Out of curiosity how `tidy-html` handle this case with `merge-divs: auto`?

```html
<div>
<div style="whitespace: pre">AAAA</div>




</div>
```

Is this not a similar issue? According to the doc ` If set to "auto", the attributes of the inner <div> are moved to the outer one.`, so EOL are revealed after optimization if I'm right.

Thanks for your time.

**Comment by geoffmcl** [comment]
@ctjhoa no, unfortunately, do not see this as a similar issue...

And as the [merge-divs](http://api.html-tidy.org/tidy/quickref_5.2.0.html#merge-divs) documentation stated, this **only** effects the [clean](http://api.html-tidy.org/tidy/quickref_5.2.0.html#clean) option... and will do the same for `--merge-divs auto` and `--merge-divs on`, and will leave the outer `<div>` if `--merge-divs no`...

So, with `clean` on all tidy is effectively doing is removing the outer `<div>` which has no attributes...

You mentioned MS Word files, turned into html, and assume you have experimented with the [word-2000](http://api.html-tidy.org/tidy/quickref_5.2.0.html#word-2000) option...

But back to the question `merge sibling tags`, at present Tidy has no such option...

In the absence of further comment, and a use case for trying to implement such an option, I am closing this issue...

Please feel free to re-open, or file a new issue... thanks...
