### ISSUE TITLE
<svg> proprietary attribute "xmlns:xlink"

### ISSUE THREAD

**Issue by onnimonni** [htacg/tidy-html5#478]
Hey!

I'm getting this error  from inline svg elements in WordPress twentyseventeen theme:
```bash
Warning: <svg> proprietary attribute "xmlns:xlink"
```

The error happens because of this element:
```html
<svg style="position: absolute; width: 0; height: 0; overflow: hidden;"
  version="1.1"
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">
... <!-- Insert the element svg nodes here -->
</svg>
```

I think this is false positive because https://validator.w3.org doesn't give any warnings from the same input.

I'm getting this error from quite new build from master commit: fd0ccb2bbf3f907e5425d5849409fbf1558197bc

**Comment by geoffmcl** [comment]
@onnimonni thanks for the issue...

And thanks for the small sample. Always speeds up the investigation, and in this case a solution...

If `xmlns:xlink` is a valid `<svg>` attribute, and its value is a url, then this could be added to tidy in just 3 steps...

 1. Define attribute: `TidyAttr_XMLNSXLINK, /**< svg xmls:xlink="url" */`, in tidyenum.h, just before `N_TIDY_ATTRIBS`
 2. Add to attribute_defs [] like `{ TidyAttr_XMLNSXLINK, "xmlns:xlink", CH_URL }, /* for <svg> */`, just before `N_TIDY_ATTRIBS`,
 3. Pass attr to W3CAttrsFor_SVG[] - `{ TidyAttr_XMLNSXLINK, xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|XH11|xxxx|HT50|XH50 }, /* svg xmln:xlink=uri */`

Re-build, and that should do it...
 
Can you give some W3C reference links? I do not think just relying on what the validator.nu does should be the sole criteria, but it is certainly sometimes a very good indication that tidy may have something wrong...

Maybe these steps to **add an attribute** could be put in say a `README/NEWATTRIBUTE.md`, as others may come along, not yet built into tidy's tables...

Comments, patches, PR, ... very welcome...

**Comment by onnimonni** [comment]
Thanks for such an fast answer!

I Found out these:

This is an example that Mozilla is using when they are talking about xml namespaces with SVG elements:
> ```
> <svg xmlns="http://www.w3.org/2000/svg"
>     xmlns:xlink="http://www.w3.org/1999/xlink">
>  <script xlink:href="cool-script.js" type="text/ecmascript"/>
></svg>
>```
> Source: https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course

Then there's this brief notice how the `xmlns:xlinx` is optional for inlined `<svg>` elements.

> The xmlns:xlink="http://www.w3.org/1999/xlink" attribute is:
> * **Required** for image/svg+xml files with xlink: attributes.
> * **Optional** for inlined <svg> with xlink: attributes.
>
> source: http://stackoverflow.com/questions/18467982/are-svg-parameters-such-as-xmlns-and-version-needed#answer-34249810

The latter had links into https://www.w3.org/TR/html5/ but honestly couldn't find any information in the spec how to use xml elements.

**Comment by geoffmcl** [comment]
@onnimonni thanks for the links... 

I, like you, did not really find `xmlns:xlink` except the W3C REC - https://www.w3.org/TR/SVG/linking.html - contains an elipse sample, which contains this...

```html
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="5cm" height="3cm" viewBox="0 0 5 3" version="1.1"
     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <desc>Example link01 - a link on an ellipse
  </desc>
  <rect x=".01" y=".01" width="4.98" height="2.98" 
        fill="none" stroke="blue"  stroke-width=".03"/>
  <a xlink:href="http://www.w3.org">
    <ellipse cx="2.5" cy="1.5" rx="2" ry="1"
             fill="red" />
  </a>
</svg>
```

Assuming this was thought of as a valid document, while not totally conclusive in itself, with this evidence, I think I would be for adding this attribute...

As stated, comments, patches, PR, ... very welcome...

**Comment by onnimonni** [comment]
I try to get familiar with the code base and  commit a PR next week

**Comment by geoffmcl** [comment]
@onnimonni wow, is it next week already? ;=))

Since this was only opened a day ago, is just a warning, will leave it at least few days... for others to comment... maybe even pull and test your fork...

I have some other tidy items to catch up on first, and you may need to rebase your fork, now and then, since one of them involves quite a number of files... 

Please **remind** me if I forget for too long... thanks for the quick work...

**Comment by onnimonni** [comment]
You're welcome :)! I will.
