### ISSUE TITLE
Option for ignoring regex

### ISSUE THREAD

**Issue by MaVo159** [htacg/tidy-html5#482]
A common issue is that tidy is fundamentally incompatible with most template engines.
It would be convenient if tidy could treat strings that match a particular regular expression the same way it treats comments.

Alternatively just preventing the addition of completely new pairs of tags would go a long way.

Small example to illustrate a typical case where not adding new tags or ignoring `{{[^}]+}}` would help:
```
<ul>
{{range .Models}}
<li>{{.Name}}</li>
{{end}}
</ul>
```
should not change at all, but is at the moment replaced by
```
<ul>
<li style="list-style: none">{{range .Models}}</li>
<li>{{.Name}}</li>
<li style="list-style: none">{{end}}</li>
</ul>
```

**Comment by geoffmcl** [comment]
@MaVo159 thanks for the issue. 

What version of tidy are you using? With your input, and `--show-body-only yes --show-info no` I get, with current tidy 5.3.14 -

```
No warnings or errors were found.

Info: Document content looks like HTML5
<ul>{{range .Models}}
<li>{{.Name}}</li>
{{end}}</ul>
```

Yes, there has been some re-lining of the code, but no additional `<li style="list-style: none">` added?

There has been some previous discussion on something like this... see #282, #310, #396, #447, and maybe others...

Look forward to further comments... thanks...

**Comment by MaVo159** [comment]
Thanks. Nice to see that this particular case is not an issue anymore. I am using 5.2.0. (debian testing)
I'll leave this open since I think the proposal may still have merit. Even if you keep fixing issues like this for new templating engines, many users are years behind the current development version, so offering a general solution may be worthwhile.

I think this is all I can contribute to the discussion, since I don't know the project very well. Feel free to close.

**Comment by balthisar** [comment]
Closed by request of @MaVo159.

**Comment by lyda** [comment]
This is still an issue I think. This snippet generates two warnings:

1. On the `{{range .}}` line: `plain text isn't allowed in <tr> elements`
2. On the `<img` line: `<img> attribute "width" has invalid value "{{.ThumbX}}"`

A regex to ignore these would just be `{{[^}]*}}` which would get most of the template cruft and allow the remaining html to be sanity checked.

```html
<table summary="Stuff">
  <tr>
  {{range .}}
    <td valign="top">
      <img src="{{.Thumb}}" height="{{.ThumbY}}" width="{{.ThumbX}}" alt="{{.Alt}}">
    </td>
  {{end}}
  </tr>
</table>
```
