### ISSUE TITLE
Generation of the man page should be done in two phases

### ISSUE THREAD

**Issue by eric-brechemier** [htacg/tidy-html5#484]
Currently, the XSLT stylesheet `tidy1.xsl.in` mixes two responsibilities: transforming the XML options structures to the [man page](https://en.wikipedia.org/wiki/Man_page) structure (grammatical level) and formatting of text using [troff](https://en.wikipedia.org/wiki/Troff) commands (lexical level).

The transformation should be done in two phases:

1. convert options XML to 'man XML' (custom XML tags that represent the structure of a man page)
2. convert 'man XML' to man text format

For example:

### Before

```xslt
<xsl:template name="seealso">
  <xsl:if test="seealso">
    <xsl:text>
</xsl:text>
See also: <xsl:text />
    <xsl:for-each select="seealso">
      <xsl:text />\fB--<xsl:value-of select="." />\fR<xsl:text />
      <xsl:if test="position() != last()">
        <xsl:text>, </xsl:text>
      </xsl:if>
    </xsl:for-each>
  </xsl:if>
</xsl:template>
```

#### Phase 1

```xslt
<xsl:template name="seealso">
  <xsl:if test="seealso">
    <br />
    <span>See also: </span>
    <xsl:for-each select="seealso">
      <bold><xsl:value-of select="." /></bold>
      <xsl:if test="position() != last()">
        <span>, </span>
      </xsl:if>
    </xsl:for-each>
  </xsl:if>
</xsl:template>
```

#### Phase 2

```xslt
<xsl:template match="br">
  <xsl:text>&#xA;</xsl:text>
</xsl:template>

<xsl:template match="span">
  <xsl:value-of select="." />
</xsl:template>

<xsl:template match="bold">
  <bold><xsl:value-of select="." /></bold>
</xsl:template>
```

**Comment by balthisar** [comment]
A PR would be welcome!

**Comment by eric-brechemier** [comment]
@balthisar that's the plan ;)

**Comment by balthisar** [comment]
Since we're awaiting a PR, and there's no actual bug or support request here, I'll clear this from the stack.
