### ISSUE TITLE
White space should not be added to `<var>` tags 

### ISSUE THREAD

**Issue by marcoscaceres** [htacg/tidy-html5#496]
Sometimes:

```HTML
<ul>
    <li>The <var>foo</var></li>
</ul>
```

Becomes:

```HTML
<ul>
    <li>The <var>
         foo</var></li>
</ul>
```

Expected `var` to not have whitespace added to it.

**Comment by geoffmcl** [comment]
@marcoscaceres thank you for your comment, and html sample...

You say `sometimes`... 

I experimented with your sample, with many different configs, but in the latest master 5.3.20, I can **not** get the `<var>` newline split you show...

What tidy version, and what config did you use to get this? Thanks...

**Comment by marcoscaceres** [comment]
ah, sorry @geoffmcl - I'm on 5.2.0. I guess as a different issue, any idea when the OS X brew formula for this will get updated?

**Comment by marcoscaceres** [comment]
I can send a PR there, btw: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tidy-html5.rb

**Comment by balthisar** [comment]
@marcoscaceres, typically they follow "releases"; we're getting ready to pull the trigger on 5.4 in the next few days, and they usually jump on releases.

Any reason you don't want to build your own in the mean time? Homebrew has a cmake formula, and as long as Xcode is installed, that's all you need.

**Comment by marcoscaceres** [comment]
Problem is that I work as part of a distributed team, and we all rely on latest stable. I couldn't ask everyone who contributes to our project to build tidy from scratch (sometimes we also get random contributions, so it would be a hurdle for those folks too). We ask everyone to tidy before they send pull requests. 

Happy and really excited to wait for 5.4!!!

**Comment by balthisar** [comment]
Ok, got it. 5.4 will be released soon, but in the future if you need a developer-signed macOS installer for non-release versions, I can periodically post them. Usually I only go through that trouble for official releases, though, because no one bothers to ask. ;-)

**Comment by geoffmcl** [comment]
As we are headed for the 5.4 release, hopefully in just days, am closing this for now...

And yes, when 5.4 is out, posting a PR to [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tidy-html5.rb) would be great... we always need help in pushing other distributions to update...

Please feel free to re-open or post a new issue... thanks...
