### ISSUE TITLE
Structure of the Errors/Warnings file: Can I rely on finding an INFO line directly following the LINE x COLUMN z lines?

### ISSUE THREAD

**Issue by LWillms** [htacg/tidy-html5#501]
I'm working on converting hundreds of HTML files to HTML 5, most of which are still marked in their DOCTYPE as DTD HTML 3.2. 

To easy that task, I am working on a procedure speeding up the inspection of TIDY output, looking up the WARNINGS and ERRORS which TIDY writes with line and column numbers of the input file into the ERROR list (I give them the extension ERR). 

I have a VBScript which loops thru the ERR files in the directory of the input files, and starts UltraEdit with the ERR file, the input HTM file and the TIDY HTM output file. That works. It is somewhat awkward, because I have to terminate UEdit and start it anew for each triple of files, but I have found no other way. 

Now to the question posed in the header of this question: 

Inside UltraEdit, I want to write a script using UE's Javascript engine, which should fist sort the WARNING/ERROR lines by the line number, and then jump to the position in Tidy's input file indicated by the line/colum numbers in that WARNING/ERROR list, where I can possibly make some changes in the Tidy input, so that a next Tidy run produces better results. 

If I could rely on finding a line beginning with "INFO" just following the last line of WARNING/ERROR lines, it would be easier to limit the area of the file to be sorted. 

It is easier to find the first occurence of a line beginning with "INFO" than looping thru all lines beginnign with "line" until the line begins with something else.

**Comment by geoffmcl** [comment]
@LWillms, hmmm, a **tricky** question ;=))

AFAIK lines that `begin` with `Info:` **should** follow all the lines that begin with `line `... and what I remember of the code the `Info: ` output is after all the parsing and cleaning stages, so should be after...

I just checked some over 200 what I call `message` files, and could not find an exception... see the https://github.com/htacg/tidy-html5-tests/tree/master/testbase repo - files beginning with `msg_`...

But also **note** there are presently 3 types of lines beginning with `line nn column nn -` output, namely - `Error:`, `Warning:` **and** `Info:`...

Also, note there is an option `--gnu-emacs yes`, which will change those lines to begin with `filename.html:row:col:` which is another way to correctly position an editor, like emacs... but never used this myself...

Certainly the parsing should stop at `Tidy found %u %s and %u %s!` **or** `No warnings or errors were found.`...

And the option `--show-info no`, to **not** show all the usual babble at the end of these `msg` files, would reduce the parsing effort...

HTH! Geoff.

**Comment by balthisar** [comment]
Can you use LibTidy directly? There area couple of callbacks that will provide *just* the warnings and errors, and you can capture them into your own structures without having to parse anything.

**Comment by LWillms** [comment]
Thanks for the reassuring reply from geoffmcl, and thanks to balthisar for his question. 

[Ultraedit ](http://www.ultraedit.com) version 24, to which I just upgraded (because of the promise of 100% UTF-8 support) seems to have integrated LibTidy, but would then apply to individual files, whereas I am doing bulk operations on whole directories, and UltraEdit's LibTidy would be upgraded only with major updates of UltraEdit itself, making me dependent on that. And the UltraEdit upgrade would have to be paid for. So I prefer to use the free and freestanding Tidy 5. 

Let me present the workflow which I am currently developing, to deal with the sheer mass of of HTML files which are still marked as HTML 3.2 (but are actually already more or less HTML 4). Currently I am working on three directories with the HTML representations of a three volume book, with 40, 27 and 57 files respectively. 

The **first step** is done by a VBscript programm which applies a series of Regular Expression search-and-replace pairs to all HTML files in a directory, to prepare them for being input to Tidy. Those RegExp search/replace terms are being loaded from a file. Since I know what the orignal HTML encoders have meant, and I have the orginal printed books as reference, I can make knowlegeable changes where Tidy can only guess what is meant. E.g. Chapter, sub-chapter and section headers are not marked up by H1..H6, but are recognizeable by the anchor and the form of the NAME parameter, or other typical forms, and my VBscript adresses that. The files contain hyperlink marks for the page numbers of the printed book, which are enhanced with hyperlinks to the previous and next pages, including those in the previous or next HTML file. The result is then checked with [Xenu's Link Sleuth 
](http://home.snafu.de/tilman/xenulink.html), whose diagnostic output is used to correct errors in the orginal file (copies of the orignal files in a separate directory). 

There are strange things in the old files e.g. the anchor for a page number or a footnote might be spread over a `</p>` Yesterday, on a test run for the script(s) which prompted me to open this 'Issue', I found a strange sequence:  `<SUP><FONT SIZE="2"></P>1</SUP>/2` - Tidy's solution was to finally discard the `<SUP>`, which is not a good move, since this breaks what is meant as the markup of a fraction (there are lots of fractions in that book, and I have decided to normalize them with my VBscript to the form of <SUP>n</SUP>/<SUB>m</SUB>, which I can later change to MathML or replacing the slash with the Unicode fraction slash - I leave that to the work to be done after Tidy. There also very strange things like preceding any text in a table cell by a `<P>` which is not terminated by a `</P>`. Tidy generates a closing `</P>` before the `</TD>`, but that would complicate the cleaning up, so I remove all those` <P>`. The script also removes all inline formatting as much as possible. 

The **second step** is to apply Tidy in a batch run to all results of the first step (this is done by another VBScript). And here comes the Ultraedit Javascript which I am working on currently, and for which I had opened this issue. I let Tidy write the ERROR/WARNINGS list (the -f parameter) as files with the ERR extension into the directory with the files produced by the previous step, since the line/column numbers refer to the input file).  Tidy is instructed by the config file to produce HTML5 with UTF-8 encoding and to write the output with a BOM. 

Now comes the verification of the Tidy output, and possibly changes in the input files. 

To ease this task, I have written a VBscript which goes thru the directory with the Tidy input and the ERR files and for each ERR file the script starts UltraEdit with the Tidy input, HTML5 output and the ERR file, plus the Javascript which brought me to open this issue, and which is started by Ultraedit on load (preceding the file name of the script with a "/s=" causes the immediate execution - Ultraedit has a bult in Javascript engine). This is not yet complete. 

It already does throw out the "About Tidy" paragraph, the option paragraph giving general advice on TABLE formatting, and I have yet to see the paragraph recommenting CSS instead of inline formatting so that I know how to identify its first words (anyway, most inline formatting is already being removed by the script in the first step). Are there more of those general hints? The script also removes lines like these

> Info: Doctype given is "-//W3C//DTD HTML 3.2//EN"
> Info: Document content looks like HTML 4.01 Transitional
> Tidy found 8 warnings and 0 errors!
and display this in a message box to the user. 

Then the script should sort the remaining lines beginning with "line x column y" by line number (and column), and store them somehow in the nine user clipboards provided by UltraEdit, where they are to be found by another Ultraedit Javascript. Sort, because the same position is often being referenced by Tidy, first by a "inserting x before z", and later by a "removing empy x". 

This second script is to be called by the user with a hotkey, and jumps the cursor in the Tidy input file to the line/column position indicated by Tidy and displays Tidy's message concerning that position. 

I can then make changes there so that the next batch run with Tidy produces better results. 

The **third step** comes when I have an Tidy output with all errors and warnings resolved. 

This involves replacing the quotes from classic greek writers like Aristotle by proper Unicode UTF-8 encodings, which in the orignal files had been marked up as `<FONT FACE="SYMBOL">` which in the first step has already been replaced by `<SPAN LANG="GRC">`. I had already done that, but then found problems which caused me to go back to stage one. Then replacing mathematical formulas represented by complicated TABLE constructions or oven just images by proper MathML, and formatting the many tables with proper CSS. Also replacing the inline CSS style sheets created by Tidy and the references to it by references to my own external CSS style sheet(s). BTW, the script in the first step introduces references to a CSS style sheet and a Javascript in the header. 

This is a lot of tedious work coming up...  But it is made easier by the script which I develop today and the friendly help which you grant me here in this forum and the friendly peers in the UltraEdit forum. I am grateful for all that. Thank you.

**Comment by balthisar** [comment]
If you can relate the file name in your script to the tidied file, then I think @geoffmcl's solution to use `--gnu-emacs yes` will make parsing so much easier.

Barring that, it would be fairly trivial to add something like `--delimit-reports` or something to Tidy. This could fence off the error report table with <<<<<<<<<<<< and >>>>>>>>> or ++++++ and ===== or something. Actually, this would probably be better as a CLI switch than a Tidy config option proper.

**Comment by LWillms** [comment]
Thanks to all, all now works fine for me. The outer VBScript gets to load the two HTML files, the ERR file (that's my extension for the file written by the -f option) and the Javascript to decode the ERR file. The Javascript is executed by UltraEdit right away, I am only interested in the list of Tidy's remarks with line and column number. 

First the general recommendations at the end beginning with "About HTML Tidy:", "The table summary" and "You are recommended to use CSS" are being deleted. Those messages are hard coded in the Tidy.exe file. As said above, Tidy's summary is displayed to the user and eliminated from the file. 

The line and column numbers are normalized to 5 digit numbers with leading zeroes, and the whole list is sorted numerically by line and column number. The sort is wanted, because Tidy often refers to the same line and column number twice, and by sorting the script brings them together. 

Unfortunately the sort does not yet work, as seen by this snippet: 

```
> line 00227 column 00030 - Warning: missing </a> before </p>
> line 00228 column 00004 - Warning: inserting implicit <a>
> line 00228 column 00004 - Warning: missing </b> before </a>
> line 00228 column 00021 - Warning: discarding unexpected </b>
> line 00229 column 00001 - Warning: missing </i> before <h4>
> line 00229 column 00021 - Warning: inserting implicit <i>
> line 00230 column 00001 - Warning: discarding unexpected </i>
> line 00236 column 01369 - Warning: discarding unexpected </b>
> line 00254 column 00008 - Warning: inserting implicit <p>
> line 00144 column 00004 - Warning: <table> lacks "summary" attribute
> line 00195 column 00004 - Warning: <table> lacks "summary" attribute
> line 00228 column 00004 - Warning: <a> anchor "S85" already defined
> line 00013 column 00175 - Warning: trimming empty <p>

```
All four remarks regarding the position in line 228 column 4 have to be considered together, and they are caused all by the same problem which is visible in this snippet of lines 227 and the beginning of 228: 
```
<P>20 Ellen Leinwand = 2 Pfd.<A NAME="S85">St.</P>
<P><B>&lt;85&gt;</A></B> Die Schwierigkeit im Begriff
``` 
the anchor named S85 is spanning from one paragraph into the next. The "St." between `"S85">` and `</P>`  belongs to the "Pfd." as Pfd.St. or "Pfund Sterling" in Germany i.e. "Pound Sterling" in english, and the `<A NAME="S85">` belongs behind the next `<P>`, or even better behind the `<B>` succeding the `<P>` . 

Tidy made this out of it: 
```
  <p>
     20 Ellen Leinwand = 2 Pfd.<a name="S85" id="S85">St.</a>
   </p>
   <p>
      <a class="c3" name="S85" id="S85">&lt;85&gt;</a> Die Schwierigkeit im Begriff 
```
  simply duplicating the anchor for page ("Seite" in German) 85 (of the printed book whose text is reproduced here in HTML). Not better, or even worse. 

   Maybe I should also load the input to my VBscript with its RegularExpressions, since that one should have expanded this anchor to this for page 94: 

`<a class="SeiteZurueck" href="#S93">&lt;</a><a class="Seitenzahl" id="S94">94</a><a class="SeiteVor" href="#S95">&gt;</a>
`
i.e. with anchors to jump to the previous or next pages (of the printed book), and adding the CLASS for the CSS.  

You see how this workflow could help to inspect and correct the problems and problemitas by relieving the user of the tedious task of loading three or four files, and then searching the locations of those problems, and unloading that onto a robot. 

For that, the Javascript started by loading the three (or four) corresponding files sets up a sorted table of the line and column numbers which is to be used by another Javascript (still to be written) which moves the cursor in the input file to Tidy to those positions, allowing the user, i.e. me, to look at what Tidy did no like so much, and possibly apply corrections, so that a repetition of the Tidy run creates the proper result (see above in my previous reply). These changes are all done using Regular Expressions -- no problem with the parsing, so no gnu-emacs format, no further changes to Tidy needed. 

Thank you very much.

**Comment by LWillms** [comment]
To make that clear: this was just a query for information, absolutely no changes requested from my part.

**Comment by geoffmcl** [comment]
@LWillms thanks for the clarification... so am closing this...

That does not mean you can not post further comments, which we will get and read, or indeed open a new issue... thanks...
