### ISSUE TITLE
option to ignore attribute-errors if attribute contains pseudo-elements

### ISSUE THREAD

**Issue by HoffmannP** [htacg/tidy-html5#505]
html:

    <a href="<# jsteLink #>">Link</a>
    <a href="<% aspLink %>">Link</a>
    <a href="<?php echo $phpLink ?>">Link</a>
    <a href="<?= $phpLink ?>">Link</a>

using

    tidy -q --show-body-only true test.html

gives me always (handlebars templates using `{ }` seem to work) an error like:

    Warning: <a> escaping malformed URI reference

So is it possible to stop checking for malformed attributes if they contain any pseudo elements? Is there any workaround that anyone is using in their routine?

**Comment by geoffmcl** [comment]
@HoffmannP thanks for the issue...

First there is the option `--fix-uri no`, it defaults to `yes`. This will stop some of the escaping, but not all, and the warning message is still output. Maybe this could be fixed, at least for those it outputs exactly as the input, 2 and 3 in this case...

Some of this has been discussed at length in earlier issues...

#310 - Jinja - As you say some attempt has been made to allow `handlebars`, or `curly bracket`, ie `{ ... }` syntax, but sometimes the warning message remains...

#352 - href illegal characters - Where also the W3C validator will flag an illegal `|` character in the href...

#378 - accented chars - This href contains a utf-8 character, which **is** accepted by the W3C validator... maybe tidy should also...

#485 - while not specifically on an anchor href attribute, is also about escaping characters, especially `<` and `>`...

Now here again you are asking tidy to **not** check or change the URI, even though the URI has not yet been really formed. As indicated in other comments, while it might be possible to code tidy to skip over such `pseudo` attributes is this really the purpose of tidy?

I **can** see Tidy being extended to accept 1, `"<# ... #>"`, and 4, `"<?= ... ?>"`, like it does for 2, `"<% ... %>"`, and 3, `"<?php ... ?>"`, and patches, or a PR would be considered for these...

But what do others think? Look forward to further comments... thanks...

**Comment by HoffmannP** [comment]
I absolutely see your point. It can be considered out of tidy's scope to "know" (other) (templating) languages, so a probably better option would be to use some kind of preprocessor that 1. removes code blocks and 2. replaces variable output blocks with some innocente content. That way tidy would never be in the position to have to discuss the addition of another "templating symbol".
Just throwing as many switches as needed on your html template file doesn't seem to do the trick. Should such a preprocessor be part of tidy or should one use well known tools as `sed` or should languages deliver such filter. Mengeling languages is always making a mess…

**Comment by geoffmcl** [comment]
No comments for a **long** time... maybe question asked and answered... so closing this...

Feel free to re-open, or file a **new** issue... thanks...

**Comment by balthisar** [comment]
Actually, I'd like to have figured out a solution to this. I'll leave it closed for tidiness, but might consider adding it to a personal to-do list, given that we support other types like this. Like so many things, this would raise a lot of questions related to behavior that I don't quite have time to discuss right now.
