### ISSUE TITLE
Request: binaries for 5.1.4

### ISSUE THREAD

**Issue by tuanmh** [htacg/tidy-html5#511]
Hi team, since 5.1.4 binaries is crucial for our system' major functionalities, would you be able to put them back to your website or github again? We're just noticed that it has been deleted from your website. To make it worst, 5.1.25 is having problem when installing https://github.com/htacg/tidy-html5/issues/364. We have no plan so far to upgrade 5.2.0 or 5.4 since it would take us quite substantial effort.  

Thank you so much.

**Comment by balthisar** [comment]
@tuanmh, I've added 5.1.4 as a pre-release under Github releases, and updated the binaries site with them again.

**Comment by aidanlane** [comment]
Champion, thanks @balthisar!

**Comment by tuanmh** [comment]
Thank you greatly @balthisar!
