### ISSUE TITLE
Win32 tidy.exe v5.4.0 binary build missing DLL file

### ISSUE THREAD

**Issue by AlbertWiersch** [htacg/tidy-html5#515]
I get messages about VCRUNTIME140.dll missing when I run tidy.exe v5.4.0 on some Windows systems.

**Comment by geoffmcl** [comment]
@AlbertWiersch well it will fail to run on **all** Windows systems that do **not** have the [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed.

You need to match the vc_redit.[x64|x86]. depending whether you are using the 64 or 32 bit exe, resp.

Of course they will also be installed if you install Visual Studio 2015 (msvc140)...

Since these components are a free download from Microsoft, we do **not** include them in the distribution package...

Advise if you have any trouble... thanks...

**Comment by AlbertWiersch** [comment]
Can you build the EXE so that it does not require that DLL? I don't recall ever having any missing DLL issues with the 5.2.0 build.

**Comment by geoffmcl** [comment]
@AlbertWiersch yes we could... but that gets us into a lot of messy `zip/exe` naming conventions...

Like I could build a Windows EXE with say MSVC10, but that still needs the vc10 re-dist dlls... I would have to check back, but maybe the 5.2.0 build used that...

And could maybe build using a `static` version of some of these DLLs... that is using `/MT` versus `/MD`... Maybe that is worth exploring...

We could also build with say MinGW and MinGW-x64, which avoids the later MSVC DLLs... and  there are **other** Windows build systems that can be used... but **who** is going to take over, and supply these **each** release time...

It's also possible to generate a Windows **msi** installer, which would probably include such dlls... will check this... but this installs in `C:\Program Files\tidy` by default...

But the easiest way is for you to clone the source and build it yourself... You only need some minimum build tools, depending on the `make` files you ask CMake to **generate** for you... `cmake -help` will list all the `generators` it supports... quite a list..

Lots of **food** for thought here... will explore... thanks...

HTH

**Comment by geoffmcl** [comment]
Ok, some parts of the puzzle solved ;=))

Tidy.exe, **5.2.0**, 64-bit, has a dependence on msvc100, `MSVCR100.dll` to be exact... Tidy.exe, **5.4.0**, 64-bit, has a dependence on `VCRUNTIME140.dll`, plus a **dozen** or so others... MS is certainly making it harder to distribute binaries...

The `msi` package **failed** to build for 5.5.10, the latest in `next` branch... not sure what is going wrong... I can still build the Windows installer EXE, **but** it does **not** include the dependent run-time DLLs...  so adds nothing at this time...

I note a recent `GeographicLib 1.47` installed the `VCRUNTIME140.dll`, and some others... need to look at what they did in `CMakeLists.txt` to get this to happen... in my case I would like to understand, and maybe `undo` it...

Still to explore some other options...

**Comment by AlbertWiersch** [comment]
It seems really strange that an statically linked tidy.exe file can't be made with a compiler/linker setting adjustment. Is this possible? Are you sure it can't be linked statically? If not then I may just go back to distributing 5.2.0 if not, at least for the time being.

Or maybe redistribute the needed DLLs if I have to... it seems it is allowed:
http://stackoverflow.com/questions/35097193/can-i-bundle-the-visual-studio-2015-c-redistributable-dlls-with-my-applicatio

But I'd much rather have a statically linked EXE file.

**Comment by geoffmcl** [comment]
@AlbertWiersch just about of time tonight, but I have experimented with CPack, and **have** been able to **included** the MSVC DLLs in the **zip**... but this was just in a **test** package...

I was also able to build both the **msi** and Windows **exe** installer, but still to check if the DLLs were included...

If I can then move this additional CPack stuff into Tidy's `CMakeLists.txt`, and build these there, I could certainly add them to our binary distribution...

And as stated, still to find time to experiment with using the `static` link to some of these system libraries, to see what DLL dependence is removed... 

Tidy.exe already links with the tidys.lib - the static library - removing the need for the Tidy.dll...

Will do some of that over the coming days... hang in there... thanks...

**Comment by AlbertWiersch** [comment]
Thank you. I hope you are able to get everything statically linked so I can just distribute tidy.exe like I could with 5.2.0. I'm distributing the 32-bit version, by the way... because that runs on more systems.

**Comment by geoffmcl** [comment]
ok, have built a **zip**, `tidy-5.5.10-win32.zip`, which contains the system runtime DLLs... could publish it shortly, if I **need** to...

Have published the CMake/CPack source changes to the `cpack-test` branch...

But meantime have uploaded - http://geoffair.org/tmp/tidy-5.5.10-win32.zip - (SHA1 ACEDEA2280AF62B81B560A4A2BBA63962BB3F121) ...

If you could download that zip, and test, that would be a great help... thanks...

**Comment by AlbertWiersch** [comment]
Thank you. I will test tomorrow. Are you still experimenting with a static link to avoid the need for any and all DLLs?

**Comment by AlbertWiersch** [comment]
OK. I tried it on the computer that it didn't work on and it came up with a message about another missing DLL. I think the only way to make this work well is to statically link everything. I don't want to distribute a bunch of extra DLL's with tidy.exe and I didn't have to with the 5.2.0 binary... so there must be way to get this to work without extra DLLs. I think I will go back to 5.2.0 until this is resolved.

UPDATE: 5.2.0 (32-bit) didn't work on my old Windows 7 notebook either - MSVCR100.dll missing. Ug.... but I never received any complaints about it.... perhaps because more people already have this DLL on their systems and/or most people don't use the HTML Tidy functionality.

**Comment by geoffmcl** [comment]
@AlbertWiersc I suppose they do not call it **dll hell** for nothing ;=))

But with the free distribution of Visual Studio, and as it moves on, each active windows user, **must** keep up with distributions. Now we could ship the 14,572,000 vc_redist.x64.exe and 13,767,776 vc_redist.x86.exe packages, **with** our package... but they are **big**, and can be [downloaded](https://www.microsoft.com/en-us/download/details.aspx?id=48145) by anyone, any time... and installed, and all done...

I am glad you now realize that the `tidy.exe` we distribute has always had dependence on a `MSVCR100.dll` up to 5.2.0, and thereafter on msvc140 re-distrib DLLs. And ok, it seems CMake/CPack missed adding a DLL, or 2 - **What DLL did it report missing?**

That ZIP contained `msvcp140.dll` and `vcruntime140.dll`, **but** I note my msvc140 redist folder contains 4, adding `concrt140.dll` and `vccorlib140.dll`. And other folders... Was the missing DLL one of these? Now, I do not know why CPack missed these two...

Accordingly have added these two(2) to a [tidy-5.5.10-win32-2.zip]()http://geoffair.org/tmp/tidy-5.5.10-win32-2.zip). Actually it is a little smaller than the original, in that I removed the **debug** DLLS... no need for those... Would be good if you could download and test this... thanks...

As to adding the ability to build an **all** `static` version, I have already tested this in another project, and it works fine. You just need to add "-DUSE_STATIC_RUNTIME:BOOL=YES" to the running of cmake, and bingo, an exe with no msvc DLL dependence... it will, of course, still have some dependence on systetms DLLs, like KERNEL32.dll,... as always. But the little test example jumped from 25K, /MD, to 158K, /MT, static... quite a leap in size...

After a little more testing, will move this `option` into Tidy...

Then we could add say a `tidy-5.4.0-win32-mt.zip`, or something to the distribution... that will take some time...

Meantime, I hope you can report Tidy 5.5.10-cpack-test runs without problems... thanks...

**Comment by AlbertWiersch** [comment]
Yes, DLL hell for sure.

I want something I can distribute with my app that just works and doesn't require users to download a bunch of extra DLLs or do any extra "work".

The DLL reported missing by 5.5.10 (the first ZIP) was api-ms-win-crt-runtime-l1-1-0.dll.

I tried the *-win32-2.zip and got the same message about api-ms-win-crt-runtime-l1-1-0.dll missing.

YES!!! Please make an all static version of tidy.exe. Can you do this? I don't have a build environment setup on my system to do it and I'm sure it would take me a lot longer to figure it all out than it would take you. :)

The increase in size is well worth the "price" for not having to deal with DLL hell if you ask me.

**Comment by geoffmcl** [comment]
@AlbertWiersch argh, that `api-ms-win-crt-runtime-l1-1-0.dll` can **only** be installed through running the `vc_redist.[x64|x86].exe`! Searching the web you can find **plenty** of people with this problem, as more and more s/w gets built with msvc140 (2015), and shortly there is a msvc 2017 version to come out, so this will get even worse... For most sites read, installing the vc redist exe cleared up the problem...

As a first cut, a WIP, have uploaded [tidy-5.5.10-win32-ms.zip](http://geoffair.org/tmp/tidy-5.5.10-win32-ms.zip), containing a tidy.exe with, where possible, **all** static links... I think it should depend on only KERNEL32.dll... it will emit a version `5.5.10-cpack-test2`...

Have not had a chance yet to push this change to the source, but will get to that soonest, so others can built and test it...

After a suitable testing period, can probably backport this to release 5.4... but do you need this? Why not go forward with the latest stable 5.5.10 version?

Anyway, I hope you get a chance to test it and report... thanks...

**Comment by AlbertWiersch** [comment]
Great! Unfortunately the link doesn't work so I can't try it but will try it as soon as I can get it. Do you think it will be suitable and stable enough to distribute with my application?

I don't need a backport to 5.4. The latest stable version should be fine.

**Comment by geoffmcl** [comment]
Yes, something went wrong with the upload... will try to come back after dinner to fix this... maybe I could attach it to a direct email... maybe try it here ...

[tidy-5.5.10-win32-mt.zip](https://github.com/htacg/tidy-html5/files/862760/tidy-5.5.10-win32-mt.zip)

Ok, maybe that worked... advise...

**Comment by AlbertWiersch** [comment]
Thanks. Got it and will try it soon.

**Comment by AlbertWiersch** [comment]
Yes! Looks like it works:
```
Q:\temp\tidy-5.5.10-win32-mt\bin>tidy.exe -v
HTML Tidy for Windows version 5.5.10.cpack-test2
```

Is the tidy.exe file safe to distribute with my application?

**Comment by geoffmcl** [comment]
@AlbertWiersch, yes sadly, running `virustotal.com` on the `tidy.exe` repeats that **malware** report... UGH!

But reading up on the `Qihoo-360` I know `tidy,exe` does **not** contain this... so it is, for sure, a **false** report... very **SAD**...

But moving forward, I have created a `Pull Request`, #516, to include this building of an **all** static version of **`Tidy`**, and hope to merge this soon...

> Is the tidy.exe file safe to distribute with my application?

Absolutely! Yes, all of the `next` branch is considered very stable, and a good improvement on the last official `release`...

You should consider updating your build environment, so you could generate the **latest** tidy.exe, from source, to ship that with your app...

I am sorry MS has created this **big** distribution problem...

OT: You should also consider directly using **`tidys.lib`** in your app, rather than running the **sample** tidy.exe... it would give you better ongoing control... In a way `console/tidy.c` is just the current example of using **libtidy**...

Anyway, moving forward, I hope we can soon close this issue... thanks...

**Comment by AlbertWiersch** [comment]
Thanks! I'll just distribute the statically linked tidy.exe file that you provided.

I'm going to stick with the EXE instead of the LIB because I don't think too many users use it and because of the advantages of keeping them as separate/independent programs.

I'll go ahead and close this issue.
