### ISSUE TITLE
Add tidy package to Alpine repository

### ISSUE THREAD

**Issue by iamfreee** [htacg/tidy-html5#520]
Hi,

Is possible to add this lib to:
https://pkgs.alpinelinux.org/packages

Thanks

**Comment by geoffmcl** [comment]
@iamfreee thanks for the issue...

Have no problem with that, but **how** to do it? 

Can you, or @thorade, or others, help?

We certainly want tidy distributed as much as possible... thanks...

**Comment by iamfreee** [comment]
Hi,

I found this wiki:
https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package

**Comment by geoffmcl** [comment]
@iamfreee good, that **looks** fairly straight forward...

Assume you have `Alpine` installed, and running, so you are more than halfway there ;=)) 

Advise if you have any problems building `tidy`... I am sure they can be addressed and quickly **fixed**...

Then you, or anyone else with `Alpine` installed, could present a PR to - https://github.com/alpinelinux/aports/pulls - through say a `main/tidy/APKBUILD`, or `testing/`, ... package...

I could not specifically find it, but feel sure they would support the `Makefile` generation using **cmake**... after that it is just standard unix `make`... tidy, the console app, and libtidy, static and/or shared, have no particularly **special** dependencies...

**Go for it**... will help where we can... thanks...

**Comment by thorade** [comment]
I think not too many people have Alpine installe don their computer, the reason that makes it an interesting distro ist that it is one of the smallest docker base images available:
https://wiki.alpinelinux.org/wiki/Docker
https://blog.bitbucket.org/2017/03/13/bitbucket-pipelines-adds-support-alpine-linux/

**Comment by balthisar** [comment]
Closed as stale, and not directly related to Tidy. Hopefully @clandmeter or @ jirutka accept the PR.
