### ISSUE TITLE
version 5.2.0 missing from verhist.log

### ISSUE THREAD

**Issue by cjerdonek** [htacg/tidy-html5#522]
I noticed that version 5.2.0 is missing from [`README/verhist.log`](https://github.com/htacg/tidy-html5/blob/17354ff927b4183bdfc757f311ec359638df2cb6/README/verhist.log#L25). Was that intentional?

**Comment by geoffmcl** [comment]
Thanks for the issue...

Yes, I too had noted that, but it is more or less there as `5.3.0`... or even `5.1.52`... There is a `5.2.0` tag, and a `release/5.2` branch

It was just the order in which I did the tagging... and how and when that `verhist.log` is generated by a script...

And you will note I corrected that order when doing the `5.4.0` release...

We learn more each time ;=))

**Comment by geoffmcl** [comment]
Question asked and answered, so closing this...

Please feel free to re-open, or file another issue... thanks...
