### ISSUE TITLE
Suggested removal of TEXT_WINDOWS_CHARS from language_en.h

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#524]
I was working on a test file, to output **all** the `badChars` messages... recently more discussed in Issue #519, PR #518... to more carefully review this suggested `message wrap` change...

As far as I can see this was added in `message.c` from the first commit d505869910b01, but there is an `#if 0` around the `if ( doc->badChars & WINDOWS_CHARS )` from that beginning, circa Jan 15 2016, so the message string in `language_en.h` of ` TEXT_WINDOWS_CHARS` is no longer needed... i.e is a **DEPRECIATED** string...

It further seems `tidyenum.h` does **not** contains a `WINDOWS_CHAR` bit... in the `/* badchar bit field */`...

And this bit, `WINDOWS_CHARS` was also commented out in the **old** CVS source of `localize.c`... circa 2001, so not sure why it continued...

But maybe I am mistaken, and the `#if 0` define should also removed, and maybe rename to the current convention of `BC_xxxx!\`...  and maybe there is a case to restore it...

But I can **not** find anywhere in the current tidy library code that adds this undefined bit, `WINDOWS_CHARS` to `doc->badChars`, so at this moment, the message is redundant... never used...

Suggest removal...

**Comment by balthisar** [comment]
Agreed. And conditional in source.

**Comment by geoffmcl** [comment]
Done... of course this must now ripple through the other languages, and eventually a re-run of the auto-gen files...

**Comment by geoffmcl** [comment]
@balthisar I was looking at closing this, but it seems I have left the enumeration there in [tidyenum.h](https://github.com/htacg/tidy-html5/blob/next/include/tidyenum.h#L157)! Oops...

I am pretty sure this should **also** be removed... correct?

Then it also shows up in [language_fr.h](https://github.com/htacg/tidy-html5/blob/next/src/language_fr.h#L203), and again assume it should be removed... that should entirely remove the enumeration...

But then I find the `text` in this case, "TEXT_WINDOWS_CHARS", in **several** PO files, and in **`tidy.pot`**? How do I get rid of these? 

Do I have to remove it from the master `template` **tidy.pot**, I assume by say running `./poconvert.rb xgettext`? And then regenerate the PO files? ... or something...

I am sorry I have not fully kept up with your great `localize` efforts, and while [localize/README.md](https://github.com/htacg/tidy-html5/blob/next/localize/README.md) seems clear on how to add another language, it does **not** seem to enumerate the process required to **delete**, completely **eliminate** a particular previous message...

It would seem the process is -

 - eliminate it from `tidyenum.h`
 - eliminate it from **each** `language_XX.h`... for as many as there are...
 - regen master template `tidy.pot`... but how?
 - regen each `language_XX.po`... but how?

Your help appreciated... thanks...

**Comment by balthisar** [comment]
@geoffmcl, yes, eliminate it from `tidyenum.h`, and make sure it's not present in the base English header. Then all you have to do is `./poconvert.rb rebase`, and you will have fresh POT, PO's, and headers in the other languages without the extra string.

I'm not sure if it's in the present code, but for future reference, we can probably start using the option `rebase {git_hash}` which will mark things as fuzzy in the PO's, meaning that if we change a string in English, the other languages will have that string marked as "fuzzy" so that translators know that something changed. Not needed for string deletes and new strings, though.

**Comment by balthisar** [comment]
This was merged, so closing.
