### ISSUE TITLE
`&` in url getting converted to &amp;

### ISSUE THREAD

**Issue by jckdrpr** [htacg/tidy-html5#526]
Input:
```<img src="http://abc.com/?action=a&bction=b">```

Output:
```
                <html>
                <head>
                  <meta name="generator" content=
                  "HTML Tidy for HTML5 for Mac OS X version 5.4.0">
                  <title></title>
                </head>
                <body>
                  <img src="http://abc.com/?action=a&amp;bction=b">
                </body>
                </html>
```
The `&` got converted to `&amp;` which in my opinion should not happen.
(NOTE: Tested on `release/5.4`)

**Comment by geoffmcl** [comment]
@jckdrpr thanks for the issue...

Have you tried the option `--quote-ampersand no`?

Running current tidy, 5.5.14, on your sample, with a config of `--quote-ampersand no --show-body-only yes --show-info no input5\in_526.html` you will still get two warnings, and an `alt` message, and this should be the same in `release/5.4.0`, except for an additional `Info:` message, which has now been suppressed -

```html
line 1 column 35 - Warning: unescaped & or unknown entity "&bction"
line 1 column 1 - Warning: <img> lacks "alt" attribute
Tidy found 2 warnings and 0 errors!

<img src="http://abc.com/?action=a&bction=b">

The alt attribute should be used to give a short description
of an image; longer descriptions should be given with the
longdesc attribute which takes a URL linked to the description.
These measures are needed for people using non-graphical browsers.

For further advice on how to make your pages accessible
see http://www.w3.org/WAI/GL.
```

But the `&bction` is **not** converted...

Does this solve the problem?

**Comment by jckdrpr** [comment]
I tried it with `--quote-ampersand no` but I am still getting &amp;
```
<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Mac OS X version 5.5.14">
<title></title>
</head>
<body>
<img src="http://abc.com/?action=a&amp;bction=b">
</body>
</html>
```

**Comment by geoffmcl** [comment]
@jckdrpr wow, that seems **impossible**!!!

I just re-tested in Windows 10, Ubuntu 14.04, and RPi Rasbian 8.0, with various versions of tidy, back as far as release 5.0.0, and before, like a dev version Jan 2012, even the last cvs release, Mar 2009, ... and in **every** case using the option `--quote-ampersand no` changed the output...

Can you check again? Can others do the test, and report... Or am I going **mad**? ... thanks...

**Comment by jckdrpr** [comment]
@geoffmcl You are not going mad. *It's me.* So I had a wrapper around libtidy written in `go`. Which led to this weird behaviour. 
```
...
	tidy := exec.Command("/bin/tidy", <array of tidy options>)
	tidy.Stdout = &stdOut
	tidy.Stderr = &stdErr
	tidy.Stdin = bytes.NewBuffer(input)
	err := tidy.Run()
        .... // go's error handling
	logger.Info(string(stdOut.Bytes()))
..
```

It looked straightforward to me so I did not bother to remove this layer when doing my test (second time).

This outputs (in log) `...<img src=\"http://abc.com/?action=a&amp;bction=b\">...`
but running tidy from the terminal results in valid output `...<img src="http://abc.com/?action=a&amp;bction=b">...`

I apologise for wasting your time and thanks for all the help. Feel free to close this issue.

PS: I hope you you tried your hands on `haskell` :) .

**Comment by geoffmcl** [comment]
@jckdrpr thanks for re-testing and reporting... glad it worked out... so closing this...

PS: No, have **not** got around to `haskell` yet... Quite some time ago did some experiments in `go` but also abandoned that... I guess I like standard C/C++ **too** much to change, and find it **easy** ;=)) I do continue to write a lot of **perl** when I want to test something...
