### ISSUE TITLE
Dot net version?

### ISSUE THREAD

**Issue by gidmeister2** [htacg/tidy-html5#535]
I am working with webpages that are unbalanced in a program written in Vb.net.  Is there an easy way to incorporate tiny-html5, which is written in C?

**Comment by geoffmcl** [comment]
@gidmeister2 yes, a long time back now, **Charles** built **COM/ATL/.NET** wrappers - see http://users.rcn.com/creitzel/tidy.html#dotnet - that would be suitable for use in Vb.net...

Several times, over recent years, I have tried to update that, from his original source, those zips are still available... but lack the skills required to complete it... I make some steps forward, but ultimately fail...

If you, or others, want to take this on, then I will certain **help** where I can... thanks...

**Comment by balthisar** [comment]
I'll close this, as it's not a Tidy issue. We're happy to keep support threads open if there's active participation, but this has gone stale.
