### ISSUE TITLE
Indent of CDATA markers in xml mode

### ISSUE THREAD

**Issue by jcubic** [htacg/tidy-html5#538]
I have xml rss feed and I have html with html entities in CDATA block and after run tidy (`tidy -xml -utf8 -indent -wrap 200 -modify -quiet "$file"`) I got this:
```xml
      <description>
<![CDATA[
        &lt;p&gt;Biblioteka jQuery, mimo wzrastającej popularności takich frameworków jak &lt;a href=&quot;https://pl.wikipedia.org/wiki/AngularJS&quot;&gt;Angular&lt;/a&gt; czy &lt;a href=&quot;https://en.wikipedia.org/wiki/React_(JavaScript_library)&quot;&gt;React&lt;/a&gt;, które umożliwiają tworzenie skomplikowanych aplikacji typu &lt;a href=&quot;https://en.wikipedia.org/wiki/Single-page_application&quot;&gt;&lt;abbr title=&quot;Single Page Application&quot;&gt;SPA&lt;/abbr&gt;&lt;/a&gt;, nadal jest najczęściej wykorzystywaną biblioteką JavaScript na stronach internetowych. Warto więc wiedzieć jak jej używać. W tym poście przedstawię jak korzystać z biblioteki jQuery.&lt;/p&gt;


        &lt;br/&gt;
        *** To tylko fragment wpisu! Kliknij na tytuł aby przeczytać całość.
        ]]>
      </description>
```

is it possible to have:

```xml
      <description><![CDATA[
        &lt;p&gt;Biblioteka jQuery, mimo wzrastającej popularności takich frameworków jak &lt;a href=&quot;https://pl.wikipedia.org/wiki/AngularJS&quot;&gt;Angular&lt;/a&gt; czy &lt;a href=&quot;https://en.wikipedia.org/wiki/React_(JavaScript_library)&quot;&gt;React&lt;/a&gt;, które umożliwiają tworzenie skomplikowanych aplikacji typu &lt;a href=&quot;https://en.wikipedia.org/wiki/Single-page_application&quot;&gt;&lt;abbr title=&quot;Single Page Application&quot;&gt;SPA&lt;/abbr&gt;&lt;/a&gt;, nadal jest najczęściej wykorzystywaną biblioteką JavaScript na stronach internetowych. Warto więc wiedzieć jak jej używać. W tym poście przedstawię jak korzystać z biblioteki jQuery.&lt;/p&gt;


        &lt;br/&gt;
        *** To tylko fragment wpisu! Kliknij na tytuł aby przeczytać całość.
      ]]></description>
```

or

```xml
      <description>
        <![CDATA[
        &lt;p&gt;Biblioteka jQuery, mimo wzrastającej popularności takich frameworków jak &lt;a href=&quot;https://pl.wikipedia.org/wiki/AngularJS&quot;&gt;Angular&lt;/a&gt; czy &lt;a href=&quot;https://en.wikipedia.org/wiki/React_(JavaScript_library)&quot;&gt;React&lt;/a&gt;, które umożliwiają tworzenie skomplikowanych aplikacji typu &lt;a href=&quot;https://en.wikipedia.org/wiki/Single-page_application&quot;&gt;&lt;abbr title=&quot;Single Page Application&quot;&gt;SPA&lt;/abbr&gt;&lt;/a&gt;, nadal jest najczęściej wykorzystywaną biblioteką JavaScript na stronach internetowych. Warto więc wiedzieć jak jej używać. W tym poście przedstawię jak korzystać z biblioteki jQuery.&lt;/p&gt;


        &lt;br/&gt;
        *** To tylko fragment wpisu! Kliknij na tytuł aby przeczytać całość.
        ]]>
      </description>
```

I can fix that using sed but was wondering if that's not a bug.

**Comment by geoffmcl** [comment]
@jcubic while I do not think it rises to the level of a **bug**, it is certainly a valid Pretty Printing Feature Request...

For quick testing could you please add a very minimal complete xml document? It should be minimal but include some indenting... thanks...

Patches, or a PR very welcome... thanks...

**Comment by jcubic** [comment]
I've narrowed the issue to this xml (two different cdata):
```xml
<?xml version="1.0" encoding="utf-8"?>
<root>
  <tag><![CDATA[
    Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet
       ]]></tag>
  <tag>
  <![CDATA[
    Hello from CDATA
  ]]>
  </tag>
</root>
```

using command `tidy -xml -utf8 -indent -wrap 200 -modify -quiet test.xml` I've got this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<root>
  <tag>
<![CDATA[
    Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet
       ]]>
  </tag>
  <tag>
<![CDATA[
    Hello from CDATA
  ]]>
  </tag>
</root>
```
it simply remove indent from before `<![CDATA[` (it keep it in newline) and everything after it is left intact and indent tag after  `]]>` normally.

**Comment by geoffmcl** [comment]
@jcubic thanks for the simple sample... this made testing quick and easy...

While it might not be exactly what you want, in running a debug session I note that there is an `--indent-cdata yes` option - it defaults to **no**.

Thus in the service `static void PPrintCDATA( TidyDocImpl* doc, uint indent, Node *node )` there is the code -

```
    Bool indentCData = cfgBool( doc, TidyIndentCdata );
    if ( !indentCData )
        indent = 0;
```

Notice the indent is set zero if this option is off...

With this **on** Tidy not only indents the `<![CDATA[`, but the text as well...

Is this ok?

**Comment by geoffmcl** [comment]
@jcubic another thing noted during the debug concerning xml pretty printing `<![CDATA[`, and that is the `text` content is **never** wrapped... as you can see in the code below, wrapping is **always** disabled in this `PPrintCDATA` text...

```
    PCondFlushLineSmart( doc, indent );
    saveWrap = WrapOff( doc );        /* disable wrapping */

    AddString( pprint, "<![CDATA[" );
    PPrintText( doc, COMMENT, indent, node );
    AddString( pprint, "]]>" );

    PCondFlushLineSmart( doc, indent );
    WrapOn( doc, saveWrap );          /* restore wrapping */
```

In fact such `CDATA` also preserves any newline chars, so -

```xml
  <tag><![CDATA[
    Lorem Ipsum Dolor Sit Amet 
    Lorem Ipsum Dolor Sit Amet 
    Lorem Ipsum Dolor Sit Amet 
    Lorem Ipsum Dolor Sit Amet 
    Lorem Ipsum Dolor Sit Amet
       ]]></tag>
```

will be output as - of course with `-xml -i --indent-cdata yes` -

```xml
  <tag>
    <![CDATA[
        Lorem Ipsum Dolor Sit Amet
        Lorem Ipsum Dolor Sit Amet
        Lorem Ipsum Dolor Sit Amet
        Lorem Ipsum Dolor Sit Amet
        Lorem Ipsum Dolor Sit Amet
           ]]>
  </tag>
```

So, unless you have other `text` nodes, outside `CDATA` then the option you showed of `-wrap 200` would **not** do anything...

Also Tidy `defaults` to `-utf8` so you do not need to add that...

HTH.

**Comment by jcubic** [comment]
It would be great if it don't indent `]]>` I've got this when I call on my feed.xml file (Wrapping is great):

```xml
      <description>
        <![CDATA[
                &lt;p&gt;Jest to pierwszy post na blogu Głównie JavaScript. Od czasu do czasu
        będę zamieszczał wpisy na tematy związane głównie z Front-Endem, czyli CSS, HTML i
        JavaScript, ale mogą pojawić się także posty na inne tematy. Treścią bloga będzie głównie
        JavaScript i na nim postarm się skupić. Będę omawiał podstawowe jak i zaawansowane
        aspekty tworzenia aplikacji internetowych, skupiając się na warstwie Front-End.&lt;/p&gt;


                &lt;br/&gt;
                *** To tylko fragment wpisu! Kliknij na tytuł aby przeczytać całość.
                ]]>
      </description>
```
Also is indent of first line of the paragraph a feature? Shouldn't it be the same as next line?

**Comment by jcubic** [comment]
OK, I know the reason if indentation, the input was (it was also already wrapped):
```xml
        <description><![CDATA[
        &lt;p&gt;Jest to pierwszy post na blogu Głównie JavaScript. Od czasu do czasu
będę zamieszczał wpisy na tematy związane głównie z Front-Endem, czyli CSS, HTML i
JavaScript, ale mogą pojawić się także posty na inne tematy. Treścią bloga będzie głównie
JavaScript i na nim postarm się skupić. Będę omawiał podstawowe jak i zaawansowane
aspekty tworzenia aplikacji internetowych, skupiając się na warstwie Front-End.&lt;/p&gt;


        &lt;br/&gt;
        *** To tylko fragment wpisu! Kliknij na tytuł aby przeczytać całość.
        ]]></description>
```
so it already had indent, but tidy is adding indent blindly and don't check if it already have any indent.

I think it should get current indent and replace it with correct one.

**Comment by geoffmcl** [comment]
@jcubic sorry, this is what I would call a `Creeping Feature Request` (CFR) ;=))

You initially asked why is `<![CDATA[` **not** indented. I spent time, research, debug, ... and find **AH HA**, you need to add option `--indent-cdata yes`... seems issue **closed**?

You bounce back with, sort of `well yes...`, but do **not** actually say to that, and go on with, `but...` now I want **more** ;=))

No problem, but at the very least what you want **more** should be **new** issues to be consider... close this and move on...

But to try to address the 2 new features I perceive here - maybe I missed something...

 1. The closing `]]>` should **not** be indented again - perhaps fair enough - another, different, FR!
 2. tidy is adding indent blindly - **NO**! CDATA is collected as the user input, and if indent requested, then what the user gave will be `indented`
 
On the 2nd item, consider an input of -

```xml
  <tag><![CDATA[
    Lorem Ipsum Dolor Sit Amet 
    Lorem Ipsum Dolor Sit Amet 
        Lorem Ipsum Dolor Sit Amet 
        Lorem Ipsum Dolor Sit Amet 
Lorem Ipsum Dolor Sit Amet
       ]]></tag>
```

Tidy will honor the **user** xml input, and if **indent** requested, will **keep** all the leading space... **as I think it should**...

So yes, it is good to have more **expectations**... and some of them could be a **new** FR to be considered, like 1. ... but some, like 2. are very unlikely to be worked on... even considered...

Have I missed something important here?

Sorry to be so blunt... thanks for your interest in Tidy...

**Comment by jcubic** [comment]
Sorry about that request, I can leave with sed to add space before `<![CDATA[` and not use that option.

Should I add another issue that will allow to format CDATA like normal text (with another option)? Or maybe you don't want you not implement such feature?

And many thanks for tidy it's awesome tool.

**Comment by geoffmcl** [comment]
@jcubic I guess we have quite a different understanding of what an xml `<![CDATA[ ... ]]>` section is...

The best quote I could find was "Everything inside a CDATA section is ignored by the parser". And that is what Tidy does - ignores it... until the ending `]]>`... just stores what ever is exactly there, and outputs it **as is**... except it will always place the section open and close on a new line...

Now Tidy has an option, deliberately **off** by default, which when turned **on**, Tidy will add measured indent space (or tab) characters to the beginning of each line of the **as is** data... it can **not** look upon it as ordinary text, and somehow **merge** its indent addition with any pre-existing leading space characters...

I just do **not** see an option to `allow to format CDATA like normal text` would fly... sorry...

So I think question asked and answered, so closing this... Please feel free to re-open, or file another issue... thanks...
