### ISSUE TITLE
Some html5 coding has drifted into legacy documents

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#539]
While working on an alternate patch for #461, now in the `issue-461` branch, found a **bug** in Tidy.

This is in code I added quite some time back, in `TY_(AdjustTags)` and `TY_(ResetTags)`... The latter correctly sets `doc->HTML5Mode = yes;   /* set HTML5 mode */`, but the former, used when a doctype indicates a legacy document type does **not** do `doc->HTML5Mode = no;`...

That means the service `TY_(IsHTML5Mode)`, used in a few places to control code, flow always returns **yes**. That is html5 mode! UGH!

The effects of this can best be seen in the `regression` tests, and have opened as [Issue 15](https://github.com/htacg/tidy-html5-tests/issues/15) there to deal with this, once the above correction to Tidy is made...

**Comment by balthisar** [comment]
#461 merged, so closing this.
