### ISSUE TITLE
Compile in Windows XP/Vista, with MSVC8 2005 and MSVC10 2010

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#550]
This is **not** a **bug**, and **not** really a `Feature Request` so am labeling is just `Technical Support`!

While I am **not** suggesting we should **always** try to support the MSVC compilers back to 2005, on the other hand Tidy C code is **not** complicated, and while such support involves only a few changes, and some small code re-arrangement, one has to ask **why not**?!

Like GCC, for a long time now, MSVC14 2015, allows some minimal breaks to what I understand is **pure** K&R C, these older MS compilers did **not**! In essence that means **all** variables, in any given context, **must** be declared **before** any code statements... Not a very difficult thing to do, but is easily forgotten, given that no warning or error is issued by modern compilers...

I have searched for a GCC option to put back this warning... have tried things like `-pedantic` and/or `-std=x99`, and while this generated other warnings, nothing about say the following in tidy.c - 

```
    tmbstr locale = NULL;
    tidySetMessageCallback( tdoc, reportCallback); /* experimental group */

    uint contentErrors = 0;
    uint contentWarnings = 0;
    uint accessWarnings = 0;
```

This will cause an error in MSVC8 and MSVC10, **but** it only needs to be re-arranged to - 

```
    tmbstr locale = NULL;
    uint contentErrors = 0;
    uint contentWarnings = 0;
    uint accessWarnings = 0;
    
    tidySetMessageCallback( tdoc, reportCallback); /* experimental group */
```

and all is well, which to me looks neater code anyway...

A second **stupid** thing is whether a standard library type function should **have** a leading underscore, or **not**. And in this case it seems MS can be optional in some cases, **not** in others... example, again in `tidy.c` -

```
        snprintf(buffer, sizeBuffer, "%s:", tidyOptGetName( topt ));
```

MSVC14 has **no** problem with this, but again MSVC8/10 will first warns that it is undefined, but assumes it is external, but then when we come to the link, will report it as missing external **error**... the fix is sloppy, but works -

#if (defined(_MSC_VER) && (_MSC_VER < 1900))
#define snprintf _snprintf
#endif

Anyway, I am preparing a small set of patches to address each of these small issues, and will present them shortly... 

Some can be overcome by suppressing the MSVC warnings, and we already do that for 4996 4090 4244 4267, and will continue to add more, if need be, so this really **only** addresses those that generate an **error**, and thus stop the compile/link!

As stated, I have found **no** gcc option to provide these warnings, and seek help on that? And can not ask other developers to have even a VM running these old systems, but to at least keep in mind the K&R C rule - in any given context, all variables must be declared before code... not hard to remember... thanks...

So again, while I agree we should **not** have to keep this backward MSVC compatibility going forever, I see no harm while it is easy... and offers some Windows users with these still working **old** systems, even though no longer updated by MS, a chance to build Tidy from source...

Comments and feedback welcome... thanks...

**Comment by geoffmcl** [comment]
When I started this I had only lit up the respective **old** systems, pulled and compiled, and saw there were **many** errors, some of which I looked at... but still did not seem too big...

Now it turns out that the **many** was just the cascading effect in the compiler... failing to create a variable can generate **many** more errors... thankfully the compiler sort of gives up about 100+

But now that I look at it closely, the actual patch, given below is quite small and very limited. 

This does not address one `#pragma execution_character_set("utf-8")` that did not exist back in MSVC8 2005, but is only a warning... so left it... 

The minimal patch is -

```diff
diff --git a/console/tidy.c b/console/tidy.c
index 4a9fe0a..4614052 100644
--- a/console/tidy.c
+++ b/console/tidy.c
@@ -24,6 +24,9 @@
 #include "locale.h"     /* for determing and setting locale */
 #if defined(_WIN32)
 #include <windows.h>    /* Force console to UTF8. */
+#if (defined(_MSC_VER) && _MSC_VER < 1900)
+#define snprintf _snprintf
+#endif
 #endif
 #if !defined(NDEBUG) && defined(_MSC_VER)
 #include "sprtf.h"
@@ -1547,8 +1550,8 @@ static void printXMLCrossRefEqConsole(TidyDoc tdoc,   /**< The Tidy document. */
 
     if ( hit )
     {
-        localHit = *hit;
         tmbstr localName;
+        localHit = *hit;
         localize_option_names( &localHit );
         printf("  <eqconsole>%s</eqconsole>\n", localName = get_escaped_name(localHit.name1));
         free((tmbstr)localHit.name1);
@@ -1900,12 +1903,12 @@ int main( int argc, char** argv )
     TidyDoc tdoc = tidyCreate();
     int status = 0;
     tmbstr locale = NULL;
-    tidySetMessageCallback( tdoc, reportCallback); /* experimental group */
-
     uint contentErrors = 0;
     uint contentWarnings = 0;
     uint accessWarnings = 0;
 
+    tidySetMessageCallback( tdoc, reportCallback); /* experimental group */
+
     errout = stderr;  /* initialize to stderr */
 
     /* Set an atexit handler. */
diff --git a/src/message.c b/src/message.c
index 2c5587e..f2556ad 100755
--- a/src/message.c
+++ b/src/message.c
@@ -567,9 +567,9 @@ void TY_(ReportAttrError)(TidyDocImpl* doc, Node *node, AttVal *av, uint code)
 /* lexer is not defined when this is called */
 void TY_(ReportBadArgument)( TidyDocImpl* doc, ctmbstr option )
 {
+    TidyMessageImpl *message;
     assert( option != NULL );
-
-    TidyMessageImpl *message = TY_(tidyMessageCreate)( doc, STRING_MISSING_MALFORMED, TidyConfig, option );
+    message = TY_(tidyMessageCreate)( doc, STRING_MISSING_MALFORMED, TidyConfig, option );
     messageOut( message );
 }
 
```

Just 4 little blocks, in just 2 files, and as seen 3 are just moving the code position only...

So I will shortly get around to cutting this in... thanks...

**Comment by geoffmcl** [comment]
Oops, just noted the above `-std=x99` should probably be `-std=c89`, or something... will get to trying that in linux... just looking for a way to show these K&R C warnings using gcc... any help appreciated... thanks...

**Comment by balthisar** [comment]
Looks like a reasonable patch. I'm probably the guilty party; I do try to keep declarations at the top of contexts, but sometimes they slip by as I'm experimenting. Still, this particular case goes back more than a year.

I have Clang set up for C89, and it, too, fails to warn when declarations fall below execution in the context. given how closely Clang maintains gcc compatibility, I'm not sure if there's a flag available.

I've been compiling in Windows a bit lately, and I've got to say, I've not noticed that particular warning mentioned. However on Windows, I usually build "release" per the project README, as the default `cmake ..\..` and `make` don't work for me.

Given that I don't debug but only test on Windows, should I be using a different `cmake` configuration on the CLI to see additional warnings pop up?

**Comment by LWillms** [comment]
More important than build in XP is building for XP etc. 

This can be done with MS Visual C++ 2015. See https://msdn.microsoft.com/en-us/library/ms235435.aspx and the links to further information on what to do when targeting XP.
