### ISSUE TITLE
gcc warning in message.c:249:21

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#552]
This is a very small issue, but I do like it when tidy compiles in linux without any warnings ;=))

The warning is `[-Wmaybe-uninitialized]`, when it detects `switch ( cfg( doc, TidyUseCustomTags ) )` has no `case default:`! 

Now **we** know `TidyUseCustomTags` is set by tidy, so it is **extremely** unlikely, probably impossible, to be other than one of the `cased` values... but what is the **best** way to avoid this warning? Of course, other than `-Wno-maybe-uninitialized`, which I do **not** want to add...

I have generated a **giant** patch ;=))

```diff
diff --git a/src/message.c b/src/message.c
index 48c300f..cd61fde 100755
--- a/src/message.c
+++ b/src/message.c
@@ -245,6 +245,10 @@ void TY_(ReportNotice)(TidyDocImpl* doc, Node *element, Node *node, uint code)
                 case TidyCustomPre:
                     tagtype = tidyLocalizedString( TIDYCUSTOMPRE_STRING );
                     break;
+                default:    /* of course should **never** be here - just to suppress gcc warning 
+                               maybe it should be an 'assert', or something else? */
+                    tagtype = tidyLocalizedString( TIDYCUSTOMPRE_STRING );
+                    break;
             }
             message = TY_(tidyMessageCreateWithNode)(doc, element, code, TidyInfo, elemdesc, tagtype );
             break;
```

But the real question is in the **comment**... what to do in the **exceptional** case?

**Or** maybe we should have say a `TIDY_UNKNOWN_STRING`, like "Error: Unknown string **FIX ME**!", or something... maybe there are other cases where this could be useful... but maybe not...

**Or** get really serious and call the Tidy `panic` vtbl member, which unless set by the libTidy user app to other than the default, would **exit** Tidy, especially if we think it will **never** happen. This is the function presently **only** called if a memory allocation/reallocation fails...

**Or** maybe we could just patch it as follows and **forget** it -

```diff
diff --git a/src/message.c b/src/message.c
index 48c300f..9321c9d 100755
--- a/src/message.c
+++ b/src/message.c
@@ -243,6 +243,7 @@ void TY_(ReportNotice)(TidyDocImpl* doc, Node *element, Node *node, uint code)
                     tagtype = tidyLocalizedString( TIDYCUSTOMINLINE_STRING );
                     break;
                 case TidyCustomPre:
+                default:
                     tagtype = tidyLocalizedString( TIDYCUSTOMPRE_STRING );
                     break;
             }
```

Wow, so much said, and so many options, for such a **little** thing ;=)) but I do like to try to cover all the bases...

Would appreciate some ideas to decide, but I hope we can do **something** about this annoying single warning... thanks...

**Comment by balthisar** [comment]
Hmmm... not seeing that warning in Ubuntu myself with gcc, but odd that Clang isn't giving me that warning either, since it's obviously missing the default case, and Clang is always shouting at me about those.

**Comment by geoffmcl** [comment]
@balthisar wow, that seems very **strange** indeed... what gcc version?

I see it with -

 - Ubuntu 16.04 - 32-bit - gcc 5.4.0 - Intel Pentium 4 LE
 - Ubuntu 14.04 - 64-bit - gcc 4.8.4 - Intel Core2 Quad Q5500 LE
 - Rasbian 8.0  - 32-bit - gcc 4.9.2 - arm71 LE
 
You must be the **luckiest** guy on the planet ;=))

**Comment by balthisar** [comment]
@geoffmcl, I usually look out for those on Ubuntu, too, because I tend to catch and patch things that crop up when it happens. Since we were talking about MinGW in another thread, I might throw that back into the testing mix, too, now that you have me thinking about it.

**Comment by geoffmcl** [comment]
@balthisar you did not mention the gcc version...

Anyway, suggest the last patch shown - just drop in a `default:`? Agreed?

Yes, I too am surprised how good MinGW 32-bit, and MinGW.x64 does... Never had any particular problem with it, but then again I do **not** test with it that much..

Certainly seems we should maybe consider add one or the other, or both on the **next** release... but I think it includes a runtime dll dependency, which always causes more distribution bother, but certainly no more than MSVC...

Off for dinner, and not sure will make it back tonight... we will see..

**Comment by balthisar** [comment]
@geoffmcl, not at my Linux machine right now, so no version. 

I wouldn't bother to publish MinGW bins, only to ensure we don't lose build compatibility. Some FOSS purists might not want to use MSVC.

Enjoy your dinner!

**Comment by geoffmcl** [comment]
@balthisar since we added the MinGW topic, now I can report one **more** gcc version that reports this warning, but I can also report **one** that does **not**!!!

 - Windows 10 - 64-bit - MinGW 32-bit - gcc 4.8.1 - WARNING
 - Windows 10 - 64-bit - MinGW-w64 64-bit - gcc 5.3.0 - NO WARNING

But whether a compiler **does** or **does not** report a potential uninitialized `tagtype` variable, we can see there is **no** `case default:`, so the potential is there!

Can we at least agree on the following **one line** patch -

```diff
diff --git a/src/message.c b/src/message.c
index 48c300f..9321c9d 100755
--- a/src/message.c
+++ b/src/message.c
@@ -243,6 +243,7 @@ void TY_(ReportNotice)(TidyDocImpl* doc, Node *element, Node *node, uint code)
                     tagtype = tidyLocalizedString( TIDYCUSTOMINLINE_STRING );
                     break;
                 case TidyCustomPre:
+                default:
                     tagtype = tidyLocalizedString( TIDYCUSTOMPRE_STRING );
                     break;
             }
```

I  hope you get the chance to cut this in, just make sure this does **not** cause any other warning... it works fine for me in the above 2 MinGW builds... thanks...

Yes, whether we publish the MinGW binaries is an open question, but adding them would ensure we do always maintain MinGW comptibilitiy going forward... I note my MinGW install is a few years old, and my mingw-w64 last year, so maybe I need to do some updates at some time, if the respective projects have continued to move forward...

**Comment by balthisar** [comment]
@geoffmcl, I can agree to the patch. I've had not much time on a development machine. If you're available, feel free to push it. Something like this doesn't need a PR, even.
