### ISSUE TITLE
link problems in win32

### ISSUE THREAD

**Issue by chomse** [htacg/tidy-html5#560]
The provided win32 DLL has the wrong calling convention. All tidy* exports are mangled and a leading
underscore is added. Thus any attempt to link to these DLLs from Freepascal fails.

_tidyAttrDiscard@12	0x10023a00	0x00023a00	19 (0x13)	tidy.dll	J:\Lazarus Projects\AsgHtmlTidy\bin\i386-win32\tidy.dll	Exported Function

The provided win64 DLL allows linking but the available freepascal wrappers are  32 bit only.

tidyAttrDiscard	0x00000001800275b0	0x000275b0	19 (0x13)	tidy.dll	J:\Lazarus Projects\AsgHtmlTidy\bin\x86_64-win64\tidy.dll	Exported Function

**Comment by geoffmcl** [comment]
@chomse thanks for the issue...

That is certainly a **shame** the link of Tidy DLLs with `Freepascal` **failed**... and assume it also fails with the Tidy `static` libraries... 

I do **not** know or use Freepascal... so am paddling in deep water here ;=))

As you can see in the following Tidy code, from [tidyplatform.h](https://github.com/htacg/tidy-html5/blob/next/include/tidyplatform.h#L513) WIN54 uses `__fastcall`, and 32-bits `__stdcall` -

```
#ifndef TIDY_CALL
#ifdef _WIN64
#  define TIDY_CALL __fastcall
#else
#  define TIDY_CALL __stdcall
#endif
#endif
```

And just above that block the `export` convention is also defined... DLL vs STATIC...

But as can also be seen, it allows `TIDY_CALL` to be defined externally... so could potentially generate a DLL/Static library with any valid calling convention... 

There is a caveat I read, that some calling conventions do **not** support variadic arguments, say like in  `printf()`... need to check if we have any APIs like that... a quick search yielded none...

So the question becomes, **What calling convention does FreePascal use?**

So again, quickly reading around, I read that `__pascal` is now obsolete, but seems replaced with `__stdcall`... but **not** sure...

You need to do some **deep** research, and come back with a specific request, and maybe we can generate, and publish suitable DLL/Static libraries... or indeed help you build one from Tidy source... thanks...

**Comment by chomse** [comment]
I need  real extern "C" which means that the function names are the same as used in the include file, not
mangled to include the type of parameters as in C++. I can adjust to cdecl, stdcall etc. but I need
the pure method names.

As you can see in my first message the methodname has been changed with a leading underscore and
a @12 postfix whitch is a code for the number and type of the parameters which indicates a C++ convention.

I have started the conversion from 32 to 64 bit and I'm able to link to the Win64 dll, but at the moment
I'm triggering exception due to a wrong translation from the *.h files to Pascal.

**Comment by chomse** [comment]
sorry, pressed wrong button

**Comment by balthisar** [comment]
@chomse, what do you mean by the "provided" DLL's? Are you building from source? Or taking the DLL's directly from a pre-built package? 

According to [MSDN](https://msdn.microsoft.com/en-us/library/3y1sfaz2.aspx):

> dllexport of a function exposes the function with its decorated name. For C++ functions, this includes name mangling. For C functions or functions that are declared as extern "C", this includes platform-specific decoration that's based on the calling convention. For information on name decoration in C/C++ code, see Decorated Names. No name decoration is applied to exported C functions or C++ extern "C" functions using the __cdecl calling convention.

I think, though, that you probably want to leave the decorated name intact. You should be able to activate the `dllimport` in our header file, I would think. Unfortunately I'm not sure how Lazarus links to C code, and if I _did_ figure it out, it would apply to macOS, I'm sure.

**Comment by geoffmcl** [comment]
@chomse thanks for the further comment... I can read what you **want**, and it becomes a question of **how** to achieve that...

As @balthisar asked, the first question is which binaries are you using? pre-built **or** your build from source?

Then for sure there is a **big** difference between 32-bit (x86) and 64-bit (x64/AMD64/x86_64)! chaulk and cheese... 

x64 really simplified things, passing some variable in registers, the so called FASTCALL... The caller cleans up the stack, if used, so no addition of `@NN` to the name... for sure this is the best way forward...

Can the same be done for x86 (32-bits)? Not sure... I experimented a bit with setting TIDY_CALL, but this seemed to make things worse... that is could **not** get rid of the leading `_`, or the trailing `@`, like `_tidyCreate@0`, or your example `_tidyAttrDiscard@12`! 

BTW, this is **not** name mangling as I understand it... and `tidy.h` does use `extern "C"`...

Will keep trying if I get another idea... there **must** be a way...

**Comment by geoffmcl** [comment]
@chomse ok, had not got around to trying the obvious ;=))

Added to CMakeLists.txt

```
if(WIN32 AND MSVC)
    set(WARNING_FLAGS "${WARNING_FLAGS} -DTIDY_CALL=__cdecl")
```

This gave me, in the Tidy.dll -

```
  Entry Pt  Ordn  Name
  00021A90    29  tidyAttrDiscard
  00021B60    54  tidyCreate
```

In the static tidys.lib, the underscore remains...

```
  00092BC0  _tidyAttrDiscard
```

Is this it?

**Comment by chomse** [comment]
yes. I can't use the lib file anyhow. With the above exports I can link to the methods and deal with
the other conventions call by call. So If you could send me the DLL I can contine with my FreePascal
wrapper

At the moment I'm using the DLLs downloaded from http://binaries.html-tidy.org/ as part of the
binary package.

**Comment by balthisar** [comment]
@chomse, I recommend that you simply build the DLL to your requirements. MSVC is free of charge, and MinGW (uses gcc) is free open source, and is a nice alternative to MSVC if avoiding proprietary software.

**Comment by geoffmcl** [comment]
@chomse well, my build is using the latest 5.5.24 source, so I can **not** add that to the `release` [binaries](http://binaries.html-tidy.org/) at this time...

This also raises another issue, touched on in #515, and that is RUNTIME DLL dependency... now you have **not** raised this yet, so maybe you have already installed the MSVC14 redistributables?

So I have uploaded two zips, to my `tmp` site location -

  - http://geoffair.org/tmp/tidy-5.5.24-win32-vc14-md-cdecl.zip - 728,629 - SHA1: EEA1A307ABA28386D5261A35B955ACB84ABC8B57
  - http://geoffair.org/tmp/tidy-5.5.24-win32-vc14-mt-cdecl.zip - 903,702 - SHA1: 9DD9D820DB9379FA489C73A024271C40E96BFD9D
  
The first is built using the default `/MD` - dynamic runtimes, and the second, using the cmake option `-DUSE_STATIC_RUNTIME:BOOL=ON`, uses `/MT` - static runtimes, at a cost of a few hundred K in size... and both using `-DTIDY_CALL=__cdecl`

But as @balthisar points out, you could simply get into building your own custom Tidy.DLL, and the runtimes would already be handled... 

And further as he points out, you could also build the Tidy DLL using MinGW... which I quickly tried, with the same `-DTIDY_CALL=__cdecl` set for the mingw-gcc compiler, and it built a `libtidy.dll`, again with clean exports like `tidyWarningCount`, so this too looks a viable possibility for Win32... 

As with the MSVC static tidy library, all exports in `libtidys.a` have a leading `_`... so this seems **normal** for a static library... and feel you **should** be able to also link with such a **static** library... Did not have time to try MinGW.x64...

Good luck. Let us know how things turn out... thanks...

**Comment by chomse** [comment]
I have no problems in finding missing Windows DLLs.

Thanks for the DLL. It works:

Release Date    : 2017/05/13
Library Version : 5.5.24
Tidying         : "<title>Foo</title><p>Foo!"

tidyOptSetBool: TRUE
tidySetErrorFile: 3328112
tidyParseString: 1

Node: html
    Node: head
        Node: title
            Node: Text
    Node: body
        Node: p
            Node: Text

tidyCleanAndRepair: 1
tidyRunDiagnostics: 1

Node: DOCTYPE
Node: html
    Node: head
        Node: meta
        Node: title
            Node: Text
    Node: body
        Node: p
            Node: Text

tidySaveStdOut: -1
A severe error (-1) occurred.\n
Press any key to continue

**Comment by geoffmcl** [comment]
@chomse glad one **or** the other Tidy.dll (md **or** mt) worked out for you - you did not say which - and the closing of this...

And just to document it for next time, if there is one, below is the patch I used in CMakeLists.txt -

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d3a7f0f..3e0891b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -81,6 +81,7 @@ if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
 endif() 
 
 if(WIN32 AND MSVC)
+    set(WARNING_FLAGS "${WARNING_FLAGS} -DTIDY_CALL=__cdecl")
     # turn off various warnings
     set(WARNING_FLAGS "${WARNING_FLAGS} /wd4996")
     # C4090: 'function' : different 'const' qualifiers
@@ -99,6 +100,7 @@ if(WIN32 AND MSVC)
     set( CMAKE_DEBUG_POSTFIX "d" ) # little effect in unix
 else()
     # add any gcc flags
+    set(WARNING_FLAGS "${WARNING_FLAGS} -DTIDY_CALL=__cdecl")
 endif()
 
 set( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${WARNING_FLAGS} ${MSVC_FLAGS} -D_REENTRANT" )
```

The first `set` was for WIN32 MSVC, and the second was for `MinGw` gcc 32-bit... since they are only for a special **custom** dll builds, of course the changes have **not** been pushed to `next`... but if this comes up again, maybe an option, like say `TIDY_CALL_CDECL`, or something, could be added to make it easy and flexible...

And I really wondered what `output` we were reading... but no problem...

Now you have a GitHub account, it is very **easy** to make your work into a GitHub repository... that is **share** your `FreePascal` code... it's a long, **LONG** time since I looked at any `Pascal` coding... anyway, just an idea...

Thanks for your interest in HTML Tidy...

**Comment by zedalaye** [comment]
> And just to document it for next time, if there is one, below is the patch I used in CMakeLists.txt -
> 
> ```diff
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index d3a7f0f..3e0891b 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -81,6 +81,7 @@ if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
>  endif() 
>  
>  if(WIN32 AND MSVC)
> +    set(WARNING_FLAGS "${WARNING_FLAGS} -DTIDY_CALL=__cdecl")
>      # turn off various warnings
>      set(WARNING_FLAGS "${WARNING_FLAGS} /wd4996")
>      # C4090: 'function' : different 'const' qualifiers
> @@ -99,6 +100,7 @@ if(WIN32 AND MSVC)
>      set( CMAKE_DEBUG_POSTFIX "d" ) # little effect in unix
>  else()
>      # add any gcc flags
> +    set(WARNING_FLAGS "${WARNING_FLAGS} -DTIDY_CALL=__cdecl")
>  endif()
>  
>  set( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${WARNING_FLAGS} ${MSVC_FLAGS} -D_REENTRANT" )
> ```

This seems to work for me. I'm using tidy (since libtidy) with Delphi for ages to reformat XML files. I just switched to current master of tidy-html5 but mangled exports cannot be used in Delphi.
