### ISSUE TITLE
Windows 32-bit XP Release

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#568]
As covered in #566 the current Windows release zips are **incompatible**, read will not run, in Windows **`XP`**, nor `Server 2003`, which is very **sad**... 

Through the testing by @LWillms and myself, we seem to have found a reliable way to generate the appropriate `Tidy.EXE`... 

Should also read other relevant points made in #515, #550, #560, and maybe others..

It seems to effect only builds by MSVC14 2015, and maybe later... all the earlier releases built with **trusty** MSVC10 2010 seem ok...

As time permits, will try to add **new** zips to the current `5.4` release...

For sure the **lessons learned** will be applied to the next `5.6` release...

**Comment by geoffmcl** [comment]
@LWillms have just added a `tidy-5.4.0-w32-mt-XP.zip` to the [binaries](http://binaries.html-tidy.org/)

It runs fine in my **old** XP machine...

It would be most appreciated if you could download and test it in `XP` and `Server 2003`... thanks...

**Comment by LWillms** [comment]
I just saw that you added a new 32-bit Windows build. Thanks -- adding instead of replacing is OK with me. 

But I am sure that not only the 32-bit version needs one which runs also on XP-level OSes, but also the 64 bit version. As we established in the other thread, the issue is not 32 bit vs. 64 bit, but Windows XP vs. later Windows versions. OK, I could not test that because I don't have a 64 bit Windows XP or Server 2003. 

I was intitially confused because I had only XP on 32 bit and Win7 on 64 bit, so this led me to the wrong assumption that the issue was 32 bit vs. 64 bit, but it turned out to be Windows XP and Server 2003 vs. Windows 7 and later (I don't know about Vista).

**Comment by geoffmcl** [comment]
@LWillms glad you found the **new** `32-bit XP Windows` build...

Now I am unsure if we **need** a `64-bit XP Windows` build? Since neither of us have `64-bit XP` we can't test it anyway... I will wait until I get a **specific request**, from a **64-bit XP owner**, so they can test it **first**... I did build it, just not uploaded anywhere yet...

As I mentioned in the other thread, I think the Tidy `32-bit XP Windows` build will **run** in a `64-bit XP OS` through what MS call `Windows-on-Windows`, or **WoW64**, as they call it in later OSES...

The reverse, a `64-bit` application will **never** run in a `32-bit` OS!

There are **some** `32-bit` applications that will **not** run in a `64-bit` OS! That is if they include `32-bit` kernel mode device drivers, or that plug into the process space of components that are implemented purely as 64-bit processes (e.g. Windows Explorer) - they cannot be executed on a `64-bit` platform. See [Wow64](https://en.wikipedia.org/wiki/WoW64), and probably many others, for more details...

But Tidy is a very simple `32-bit` **service** application, only in `user` mode, and should have no problems in `64-bit` OSES, with `WoW64`, like in my `Windows 10 64-bit`... All the 32-bit Tidy apps I build run in it fine... and this should be the same for your `Windows 7 64-bit`...

I guess we will have to wait-and-see... thanks...

**Comment by LWillms** [comment]
OK with me.

**Comment by geoffmcl** [comment]
WARNING WARNING WARNING
-----------------------

See Windows [binary](http://binaries.html-tidy.org/) `tidy-5.4.0-w32-mt-XP.zip`, added recently.

**WARNING**: While some strong effort has been made to provide a `5.4` Windows **`XP`** version of `tidy.exe`, using MSVC14 2015, this has **not** proved completely successful in **all** cases. We do **not** know exactly why!

**Regrettably**, if you have an **`XP`** like system, which seems to include `Windows Server 2003`, and this `tidy.exe` fails to run correctly, for any reason, then you have no other options but to upgrade the system to a later version of Windows, and/or, if you have the capability and tools, maybe build tidy from source in that system...

**Alternatively**, apparently some **older** versions of **`Tidy.exe`**, `5.2` and before, may still run... these were built using the MSVC10 2010 tool...

If you have this **problem**, then we can only state `HTML Tidy` no longer supports such **old** systems, and will **not accept any issue on the subject! Sorry**!

On the other hand, we would **love** to hear from you if it does successfully run in **old** systems, as it does in my ancient **`XP`** system... but **not** in the even older `Windows 98`!

Some thought will be given to this for the next `5.6`, and later, releases, and the above positive feedback would help in this, but be **sternly** warned, release `tidy.exe` may not be **compatible** with Windows **`XP`**, and earlier systems!

Maybe this **compatibility** problem should be added to the Tidy website somewhere... suggestions welcome... thanks...

**Comment by balthisar** [comment]
Windows XP is officially out of support, so I'd have no problem dropping Tidy support for it. It's highly likely that Tidy doesn't work on Mac System 7 anymore, either!

On the other hand, @geoffmcl, you were pretty vociferous about continuing Win XP support last time, I seem to recall.

**Comment by geoffmcl** [comment]
With release **5.6** out-the-door, and have included a 32-bit version built with MSVC10, hope this can be closed...

If not please feel free to re-open, or perhaps file a **new** issue... thanks...
