### ISSUE TITLE
<script> inside <script>

### ISSUE THREAD

**Issue by ogolovanov** [htacg/tidy-html5#580]
Hello!

Tidy v5.4.

Input html:

`<html>`
`<body>`
`<script>`
`<!-- <script>`		
`</script> -->` 
`</script>`
`</body>`
`</html>`

Config:

`$config = array(`
    `'drop-empty-elements' => false,`
    `'drop-empty-paras' => false,`
    `'fix-backslash' => false,`
    `'fix-uri' => false,`
    `'input-encoding' => 'raw',`
    `'output-encoding' => 'raw',`
    `'merge-divs' => false,`
    `'merge-emphasis' => false,`
    `'merge-spans' => false,`
    `'output-xhtml' => true,`
    `'preserve-entities' => true,`
    `'wrap' => 0`
`);`

Result:

`<!DOCTYPE html>`
`<html xmlns="http://www.w3.org/1999/xhtml">`
`<head>`
`<title></title>`
`</head>`
`<body>`
`<script>`
`<![CDATA[`
`<!-- <script>`          
`]]>`
`</script> --&gt;` 
`</body>`
`</html>`

Is it possible somehow to fix it?
I expect body content not to be modified at all.

Thanks.

**Comment by geoffmcl** [comment]
@ogolovanov thank you for your issue, but do not understand what you expect tidy to do?

As far as I know, a `<script>`, within a `<script>` is **not** valid javascript, and probably **not** valid html...

Certainly, when tidy enters a `<script>`, it suspends any html decoding, and is only searching for the close, namely `</script>`, which it found... then it found a second one, so it gives a warning...

Really, what else would you expect tidy to do in this case?

It can **not** see the `<!--` as the beginning of a comment! It is in reading a **script**, only searching for the close, `</script>`. 

And I am very sure the javascript interpreter would also see `<!-- <script>..` as an error... certainly not valid javascript... a comment in javascript is preceded by `//` or `/* ... */` block, but those are also **not** seen by tidy...

Given this **invalid** input, it seems tidy has done the **best** it can, so sorry, I do not see anything to **fix** here...

You indicate v5.4, but this is the same in the latest 5.5.31 version. This is the output given your sample, and the default configuration -

```html
F:\Projects\tidy-test\test>tidy5 input5\in_580.html
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
line 6 column 1 - Warning: discarding unexpected </script>
line 2 column 1 - Warning: inserting missing 'title' element
Tidy found 3 warnings and 0 errors!

<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Windows version 5.5.31">
<title></title>
</head>
<body>
<script>
<!-- <script>
</script> --&gt;
</body>
</html>
```

As indicated, please maybe explain more if you think the output should be different, but understand tidy does **not** read javascript... it treats all as transparent text until a `</script>`, is found... thanks...

**Comment by balthisar** [comment]
I'm going to close this as no response from @ogolovanov. Back in the early Netscape/Mosaic days, there may have been a case for this, but comments in scripts are a bad idea, and not even allowing in XHTML documents. For consistency, Tidy's behavior should not parse comments within scripts.
