### ISSUE TITLE
(bug) Empty elements are forced to separate line

### ISSUE THREAD

**Issue by shentino** [htacg/tidy-html5#585]
Compare

&lt;td&gt;
&lt;/td&gt;

vs

&lt;td&gt;foo&lt;/td&gt;

**Comment by shentino** [comment]
Similiar misformatting observation noted with:

```<p><a href="foo.html">bar</a>
```</p>

vs

```<p><a href="foo.html">bar</a>baz</p>

**Comment by shentino** [comment]
I wish to add that this apparently only happens when vertical-space = yes

Without vertical-space, it formats properly

**Comment by shentino** [comment]
issue 582 might be related

**Comment by geoffmcl** [comment]
@shentino as you have pointed out this wrapping empty elements to a new line is what is call tidy's `classic` behaviour... 

The original founders of tidy were in **love** with adding a **lot** of vertical space to the pretty print output... so in respect for this we have kept `--vertical-space yes` to signal this is what you want, expect and **like**... extra vertical space in the output...

And no, issue #582, now fixed, merged, was where `classic` mode even added a **3rd** newline in some circumstance, a **bug**, so is not really related... except in the vertical space sense...

It has to be understood, the `pretty print output` comes down to a **lot** of **different** personal preferences, and tidy could **never** please everybody! But it does have a lot of options to try as best it can to be **acceptable** to all...

So this is certainly **not** a **bug**. It is designed behaviour. But thanks for pointing it out...

So closing this, but feel free to re-open, or add a new issue... thanks...

**Comment by shentino** [comment]
is there an option I can use to avoid line-splitting an empty tag?

**Comment by geoffmcl** [comment]
@shentino have you tried `--vertical-space no`? This is in fact the default value...

An even more interesting one, to avoid line-splitting just about every tag, try `--vertical-space auto`... sometimes combined with `-w 0`...

HTH...

**Comment by shentino** [comment]
What I would like is both:

* Empty tags don't get split
* Block level elements at the same depth still get separated by blank lines.

vertical-space yes handled the second one but messed up the first one
