### ISSUE TITLE
Supporting new tags

### ISSUE THREAD

**Issue by GauthamBanasandra** [htacg/tidy-html5#586]
Hi all,

Is it possible to format the HTML that has new custom tags in it. I'm referring to the custom tags that we could create using AngularJS.
Unfortunately tidy considers custom tags (not part of HTML standard) as errors and won't format the file. Is there any way to override this?

Thanks,
--Gautham

**Comment by balthisar** [comment]
@GauthamBanasandra, did you try the `custom-tags` configuration option?

**Comment by balthisar** [comment]
No response, and Tidy clearly has the ability to support custom tags via multiple options, so I will close this.
