### ISSUE TITLE
<span lang="EN-US"><!--?xml:namespace prefix = o /--><o:p></o:p></span>

### ISSUE THREAD

**Issue by dry11orange** [htacg/tidy-html5#592]
the html file has a line like this
<span lang="EN-US"><o:p></o:p></span>

and tidy work with it,report an error like this
Error: <o:p> is not recognized!

**Comment by balthisar** [comment]
@dry11orange, that's not valid HTML, but since Microsoft insists on exporting files containing that kind of junk, you can activate the `word-2000` option so that Tidy will recognize them.

Feel free to re-open this if that doesn't work for you.
