### ISSUE TITLE
XML element name supports subset of valid NameStartChars

### ISSUE THREAD

**Issue by ablackton** [htacg/tidy-html5#594]
Tidy only recognizes xml elements whose names begin with a letter character.

Sample input
```
<?xml version="1.0" encoding="UTF-8"?><form><_a></_a><:b></:b></form>
```

Current output
```
<?xml version="1.0" encoding="utf-8"?>
<form>&lt;_a&gt;&lt;/_a&gt;&lt;:b&gt;&lt;/:b&gt;</form>
```

Expected output
```
<?xml version="1.0" encoding="utf-8"?>
<form>
<_a></_a>
<:b></:b>
</form>
```

Tidy config
```
input-xml: yes
output-xml: yes
```

Tidy version
```
tidy --version
HTML Tidy for Windows version 5.4.0
```

**Comment by geoffmcl** [comment]
@ablackton have not had a chance to fully test this yet, but just reading the patch in your PR #595 this looks good... thanks...

Will merge this if someone else can find the time to test it fully, and run the compatibility tests... thanks...

**Comment by balthisar** [comment]
This was merged, and should have been closed! Doing so...
