### ISSUE TITLE
<a> with "download" attribute misidentified as proprietary

### ISSUE THREAD

**Issue by ReubenM** [htacg/tidy-html5#598]
Warning: <a> proprietary attribute "download"

This is using release 5.4.0

**Comment by geoffmcl** [comment]
@ReubenM thank you for the issue...

Could you please add a simple `html` sample, to facilitate easy, quick testing... giving say -

 - configuration
 - sample html
 - current tidy ouput
 - expected tidy output

And maybe you could point us to some supporting W3C documentation... thanks...

**Comment by ReubenM** [comment]
I run into this when using vim via syntastic. When using tidy directly (no arguments) on the following html page:
```
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
        <head>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <meta name="language" content="English" />
                <title>Download attribute demo</title>
        </head>
        <body>
                <a href="/path/to/file.ext" download="file.ext" type="application/octet-stream">Download file here</a>
        </body>
</html>
```
the first three lines from tidy is:
```
line 9 column 17 - Warning: <a> proprietary attribute "download"
Info: Document content looks like HTML5
Tidy found 1 warning and 0 errors!
```

As for the w3c documentation, you can reference here:
https://www.w3.org/TR/html5/links.html
with specific reference to sections 4.8.1 and 4.8.3

**Comment by balthisar** [comment]
Added candidate #621, which now allows the download attribute to the anchor tag.

**Comment by balthisar** [comment]
Fixed and live. @ReubenM, thanks for the report.
