### ISSUE TITLE
Eliminate legacy conditionals

### ISSUE THREAD

**Issue by balthisar** [htacg/tidy-html5#602]
At some point, experimental features were added into Tidy that have been stable for years and years and years, and so I see no need to continue to support compiler macros capable of disabling them.

I propose that we remove `SUPPORT_UTF16_ENCODINGS`, `SUPPORT_ASIAN_ENCODINGS`, and `SUPPORT_ACCESSIBILITY_CHECKS`.

I can't fathom a use case that requires the ability to turn these off any more.

**Comment by geoffmcl** [comment]
> I can't fathom a use case that requires the ability to turn these off any more.

@balthisar me neither... they should be removed...

You might also consider `TIDY_STORE_ORIGINAL_TEXT`. 

Although I used it for some diangostic reasons years and years ago, it needed quite a number of patches to make it work, which never made it into the base code, and would be difficult for me to recover now... Even Björn, who I understand introduced the compile option, thought it a bad idea that I try to use it... 

I think it too can go...

There may be others... will look around... thanks...

**Comment by balthisar** [comment]
Proposal #624 available.
