### ISSUE TITLE
Configuration Options "cleanup"

### ISSUE THREAD

**Issue by balthisar** [htacg/tidy-html5#609]
I've been auditing all of the configuration options, and there are a few key changes I'd like to sneak in while we're still in `next`. The goals are to simplify the number of configuration options, preserve backward compatibility for a time, communicate changes to users, and offering better documentation.

## Change `TidyShowMarkup`
Propose changing this to an enum with values `no`, `yes`, `force-output`. This would allow us to eliminate `TidyForceOutput`.

## Change `TidyHtmlOut`

Propose changing this to an emum with values `html`, `xhtml`, and `xml`, allowing us to retire `TidyXhtmlOut` and `TidyXmlOut`. 

Aside from trimming options, this removes all doubt about which configuration option "wins" if someone sets multiple options.

## Retire `TidyShowMetaChange` and `TidyWarnPropAttrs`

Consistent with #629, these wouldn't be needed any more. The question, then, would be whether or not we maintain these using the deprecation mechanism (good practice), or drop them completely because they've only ever been in the `next` branch.

## Handle the above deprecations in a backward compatible way

There's now a mechanism in place to accept "legacy" options while eliminating them from Tidy, but allowing them to still work (with a notice to the user).

**Updated**: 2017-October-08

**Comment by balthisar** [comment]
Proposal #627 implements the categories. _None_ of the option names have changed; no new options. This simply takes care of the category aspects of this request in line with table above.

**Comment by balthisar** [comment]
#629 would allow the "retirement" behavior with a config option (`squelch`).

**Comment by geoffmcl** [comment]
20210409: Review, years later...

It seems some issues, ideas, here have been subsequently merged...

I was recently searching for a backward compatible, `depreciation` mechanism, in issue #933, but did not find it...

Are there any open, **active** issues here???

Closing this for now... thanks...
