### ISSUE TITLE
Makefile build doesn't support DESTDIR convention

### ISSUE THREAD

**Issue by craigbarnes** [htacg/tidy-html5#61]
The gmake build currently doesn't allow the common convention of `make install DESTDIR=mybuildroot`.

**Comment by geoffmcl** [comment]
As you may know the latest development branch is develop-500...
$ git checkout develop-500
This uses cmake and the install directory can be set by -
$ cd build/cmake
$ cmake ../.. -DCMAKE_INSTALL_PREFIX:PATH=/install/path
$ make install
so I hope this can be closed?
