### ISSUE TITLE
bdi tag should be marked as inline, not block

### ISSUE THREAD

**Issue by behnam** [htacg/tidy-html5#616]
Current Config: https://github.com/htacg/tidy-html5/blob/0016e0083505ccee25a5c76dcf64cfe336765128/src/tags.c#L300

From [the spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-bdi-element):
> The `bdi` element represents a span of text that is to be isolated from its surroundings for the purposes of bidirectional text formatting.

The language and example clearly show that `bdi` is an inline element and not a block element.

Is there any reason this tag is being treated as block element in tidy?

**Comment by balthisar** [comment]
Confirmed.

**Comment by balthisar** [comment]
Added candidate #620. This is a simple change, and so will merge in a day or so unless objections are raised.

**Comment by balthisar** [comment]
@behnam, confirming that this is merged and live now, so closing this issue.
