### ISSUE TITLE
ISO-8859-1 special characters not translated correctly

### ISSUE THREAD

**Issue by jh2858** [htacg/tidy-html5#62]
When I first tried this fork of tidy, I noticed that the following html code

```
<!DOCTYPE html>
<html><head><title></title></head>
<body>
  <p>It costs 15&cent;.</p>
</body>
</html>
```

is translate by tidy into the following:

```
<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 (experimental) for Mac OS X https://github.com/w3c/tidy-html5/tree/c63cc39">
<title></title>
</head>
<body>
<p>It costs 15Â¢.</p>
</body>
</html>
```
Note that ```&cent;``` doesn't appear in the output... it has been replaced by an escape sequence.  If this is intended behavior, how do I revert to the behavior in the original fork of tidy?  Thank you.

**Comment by geoffmcl** [comment]
The latest development branch is develop-500
$ git checkout develop-500
And as you now understand the default output-encoding used to be ascii, but is now utf8, as can be seen here -
http://www.html-tidy.org/quickref.html#output-encoding
If you add the config of --output-encoding ascii you will get &cent; as before...
Hope you can get a chance to test, confirm, and hopefully close this issue...

**Comment by geoffmcl** [comment]
Oops, seems in these issue the `&cent;` is translated if not quoted ;=))
