### ISSUE TITLE
Feature request: option to replace inline styles with classes + `<style>` tag styles

### ISSUE THREAD

**Issue by bpj** [htacg/tidy-html5#638]
I really miss an option to replace inline styles with classes + `<style>` tag styles

**Comment by geoffmcl** [comment]
@bpj have you tried the `-c`, `-clean`, or `--clean yes` option? These are all the same...

This will convert -

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>head</title>
</head>
<body>
<p>I am normal</p>
<p style="color:red;">I am red</p>
<p style="color:blue;">I am blue</p>
<p style="font-size:36px;">I am big</p>
</body>
</html>
```

to 

```html
<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Windows version 5.5.76">
<meta charset="utf-8">
<title>head</title>

<style type="text/css">
 p.c3 {font-size:36px;}
 p.c2 {color:blue;}
 p.c1 {color:red;}
</style>
</head>
<body>
<p>I am normal</p>
<p class="c1">I am red</p>
<p class="c2">I am blue</p>
<p class="c3">I am big</p>
</body>
</html>
```

If that is **not** what you meant, or have some other question, then you will need to **explain** more...

Including tidy **version**, giving some **sample** input code, what **config** used, what **current** output, and what you **expect** as output... thanks...

**Comment by geoffmcl** [comment]
@bpj as asked, does the above **answer** your question... can this be **closed**? Thanks...

**Comment by geoffmcl** [comment]
No response, so assume can close this...

**Comment by bpj** [comment]
Sorry for not getting back.  Much happening IRL!

It seems --clean is adequate, but its documentation doesn't mention `style` tags.
