### ISSUE TITLE
Question: in which case will a Tidy{Doc,Node,Attribute} be mutated?

### ISSUE THREAD

**Issue by jokester** [htacg/tidy-html5#642]
Is it safe to assume that libtidy does not mutate nodes/attributes in a cleared document, except in `tidyDiscardElement` / `tidyAttrDiscard` ? (I couldn't find other mutating calls, just wanted to be sure. Thanks in advance.)

**Comment by geoffmcl** [comment]
@jokester well concerning the **`LibTidy`** public API, I think those are the only two which allow `elements` to be deleted from the tidy DOM like tree of nodes...

The **public** API is very light on services to manipulate, mutate, change, add to, etc, the **opaque** tree of nodes... I guess the tidy founders never saw `libtidy` as a builder of a document other than by reading html...

Of course **internally** there are quite a number of functions which create, add, place `nodes` into the tree, including a `coerce` function, the word it uses, to mutate a node from one type to another... these will either be `static` - ie only available in that module, or encased in the `TY_(<name>)` macro, which is libtidy's way of saying - only for use within the library...

In the main, the module `clean.c` has many of these `manipulators`, but they can be anywhere... 

And as far as I can see those two public API functions are **not** used in the library... but `tidyDiscardElement` is converted to the internal function, `TY_(DiscardElement)`, and `tidyAttrDiscard` to `TY_(RemoveAttribute)`, which may be used internally...

This points out the interesting way public API functions only use **opaque** structures, which are `cast` to a visible structure internally, and vice versa passing out of the library...

It is hard to know what to add, cover, without exactly knowing the reasons behind the question...

Does that answer your question? If not, ask or explain more... thanks...

**Comment by jokester** [comment]
Thanks @geoffmcl , I wanted to ask about the public APIs. That answered my question perfectly 👍 .
