### ISSUE TITLE
Why is libtidy complaining <data> isn’t approved by W3C?

### ISSUE THREAD

**Issue by jonnybarnes** [htacg/tidy-html5#649]
It is: https://www.w3.org/TR/html5/text-level-semantics.html#the-data-element

What does “approved by W3C” mean?

**Comment by geoffmcl** [comment]
@jonnybarnes thanks for the issue... 

It is usually better, and certainly faster testing, if you supply a minimal sample html, which should pass the W3C validator... but I was able to construct one quite quickly using the sample code given [here](https://html.spec.whatwg.org/#the-data-element)...

> Why is libtidy complaining `<data>` ...

In a quick read of the [TR](https://www.w3.org/TR/html5/text-level-semantics.html#the-data-element) given, and others found, can only say just an **oversight**! 

It seems that element should be supported... but there is presently **no** `TidyTag_DATA` enumerated, and defined in `tags.c`... so libtidy will **bark** loudly ;=))

Will get to it, if no one beats me to it, but meantime look forward to a `patch`, or `PR`... thanks...

**Comment by balthisar** [comment]
On that note, I wonder if we should update that message per se, given that the (WHATWG)[https://whatwg.org/] essentially define what HTML5 (and beyond) is. Not long ago, I was trying to understand, "why voyager?" (or XHTML flag), and it took me down a rabbit hole of who defines the specification these days.

WHATWG _is_ affiliated with the W3C (currently), and they only apply to HTML5, so leaving things alone is certainly the easiest...

**Comment by geoffmcl** [comment]
@balthisar not sure I understand your comment... maybe you can clarify...

If you run default tidy, my 5.5.84, on my sample, [in_649.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_649.html), you will get -

```
line 12 column 23 - Error: <data> is not recognized!
line 12 column 23 - Warning: discarding unexpected <data>
line 12 column 44 - Warning: discarding unexpected </data>
etc
```

If you run that tidy adding `--new-blocklevel-tags data` you will get -

```
line 12 column 23 - Warning: <data> is not approved by W3C
...repeated...
```

I **assumed** @jonnybarnes was referring to the **second** message... if **not**, hope he too will clarify... and supply some **sample** code...

Which message do you refer to in `I wonder if we should update that message per se`? Update it to **what** exactly...

And then why do you add `leaving things alone` as an option? 

That sample `in_649.html` validates without a problem, and per the `TR` and `WHATWG` pages, `<data value="123">` is **valid** HTML 5... How can we `leave things alone`?

Anyway, given that nothing has been done on this yet, that I know of, am moving the milestone out to the next release... 

But certainly feel tidy should support this `<data value="123">` element... thanks...

**Comment by jonnybarnes** [comment]
Yes, I was referring to the second message.

**Comment by AntoniosHadji** [comment]
I edited tags.c and tags.h to include the `<data>` tag but it does not compile on my machine.  I would like to submit a PR if I can get it working.  

the changes I made to the code are just three lines.  
```
diff --git a/src/tags.c b/src/tags.c
+#define VERS_ELEM_DATA       (xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|xxxx|HT50|XH50)

+  { TidyTag_DATA,        "data",         VERS_ELEM_DATA,        &TY_(W3CAttrsFor_DATA)[0],        (CM_INLINE),                   TY_(ParseInline),    NULL           },
   
diff --git a/src/tags.h b/src/tags.h
+#define nodeIsDATA( node )       TagIsId( node, TidyTag_DATA )
```

When I compile, I'm getting these errors:
```
[  8%] Building C object CMakeFiles/tidy-share.dir/src/tags.c.o
/mnt/projects/oss-contrib/tidy-html5/src/tags.c:306:5: error: ‘TidyTag_DATA’ undeclared here (not in a function); did you mean ‘TidyTag_META’?
   { TidyTag_DATA,        "data",         VERS_ELEM_DATA,        &TY_(W3CAttrsFor_DATA)[0],        (CM_INLINE),                   TY_(ParseInline),    NULL           },
     ^~~~~~~~~~~~
     TidyTag_META
In file included from /mnt/projects/oss-contrib/tidy-html5/src/config.h:35:0,
                 from /mnt/projects/oss-contrib/tidy-html5/src/tidy-int.h:12,
                 from /mnt/projects/oss-contrib/tidy-html5/src/tags.c:11:
/mnt/projects/oss-contrib/tidy-html5/src/forward.h:23:29: error: ‘prvTidyW3CAttrsFor_DATA’ undeclared here (not in a function); did you mean ‘prvTidyW3CAttrsFor_META’?
 #define TY_(str) TYDYAPPEND(prvTidy,str)
                             ^
/mnt/projects/oss-contrib/tidy-html5/src/forward.h:22:31: note: in definition of macro ‘TYDYAPPEND’
 #define TYDYAPPEND(str1,str2) str1##str2
                               ^~~~
/mnt/projects/oss-contrib/tidy-html5/src/tags.c:306:66: note: in expansion of macro ‘TY_’
   { TidyTag_DATA,        "data",         VERS_ELEM_DATA,        &TY_(W3CAttrsFor_DATA)[0],        (CM_INLINE),                   TY_(ParseInline),    NULL           },
                                                                  ^~~
CMakeFiles/tidy-share.dir/build.make:158: recipe for target 'CMakeFiles/tidy-share.dir/src/tags.c.o' failed
make[2]: *** [CMakeFiles/tidy-share.dir/src/tags.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tidy-share.dir/all' failed
make[1]: *** [CMakeFiles/tidy-share.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

I can't figure out why I'm getting message `‘TidyTag_DATA’ undeclared here (not in function)`
it seems to be declared the same as the other tags in `tags.h`.

**Comment by geoffmcl** [comment]
@AntoniosHadji thanks for looking at this...

A brief look at the 3 lines of code added, these are good but some **more** things are required... 

The README [TAGS](https://github.com/htacg/tidy-html5/blob/next/README/TAGS.md) may help a bit, but it too could/should be expanded... I will think about doc additions, but maybe there are not too many more to add...

As it suggests, the **first** thing to create a **new** HTML tag, is to add an item to `tidyenum.h`, in the following enumeration -

```C
/** Known HTML element types
 */
typedef enum
{
  TidyTag_UNKNOWN,       /**< Unknown tag! Must be first */
  TidyTag_A,             /**< A */
  /* skip to bottom */
  TidyTag_DATA,          /**< DATA */
  
  N_TIDY_TAGS            /**< Must be last */
} TidyTagId;
```

Note, I do not think this list need be kept in alphabetical order... it is a unseen enumeration value...

Then your addition to `tag_defs[]` table in `tags.c` will be ok, nearly...

You will also need to define a set of attributes allowed on the **NEW** element, in `attrdict.h/c`, namely a `const AttrVersion TY_(W3CAttrsFor_DATA)[] = { };` array of attributes, which **must** be terminated with `{ TidyAttr_UNKNOWN, 0 }`... the [Content Attributes:](https://www.w3.org/TR/html5/text-level-semantics.html#the-data-element) gives a clue to what must be added... 

Maybe see [W3CAttrsFor_DATALIST](https://github.com/htacg/tidy-html5/blob/next/src/attrdict.c#L884), and all the others as examples...

Then it should compile... you have made a good start... but there may be some question about the `tag_defs` entries... hope this helps in the continuation... thanks...

**Comment by AntoniosHadji** [comment]
Thank you, @geoffmcl Your comments were most helpful.  I have added  the tag and compiled successfully on ubuntu 18.04.  I have tested on an html page with data elements and received no warnings or errors.  I have created a [pull request][1]

I realized that I need to look at the ATTRIBUTES.md as well as TAGS.md for the full picture of what was required.

[1]: https://github.com/htacg/tidy-html5/pull/769

**Comment by geoffmcl** [comment]
@AntoniosHadji  Added a `lang` attribute to my test sample [in_649.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_649.html), and now it **fully** passes the `nu` W3C validator...

Now to patch tidy per #769, and it too should issue a **clean report**, ie exit 0... onwards in testing...

Also need to run the [regression](https://github.com/htacg/tidy-html5-tests), to check for any **change**... any help appreciated... thanks...

**Comment by geoffmcl** [comment]
@AntoniosHadji thanks - now added this new `data` element, but not yet run regression tests... any help appreciated... thanks...
