### ISSUE TITLE
Tidy dumped on my html!

### ISSUE THREAD

**Issue by kennyhendrick** [htacg/tidy-html5#650]
I hope I'm not in the wrong room or asking a question that nobody knows the answer to....DOES ANYBODY KNOW HOW TO CLEAN THIS unTIDY header tag out of my html ? I would prefer a cli script to do it recursively since I accidentally trusted the stupid untidy program under the assumption that it would simply double-check my work....instead it crapped on it and then had the audacity to inject a link in the header back to its site with a snippet of strange code I'd rather not have.

There are over 5 T H O U S A N D pages I need to remove this bad unethical injection from (in fact it's way more if you are counting the online bible I host).

This is a shame....backup, I tell my customers that all the time, backup before you mess with corporate crap...uggghhh.....dammit man.

**Comment by geoffmcl** [comment]
@kennyhendrick really sorry to hear about your **unTidy** problem...

This is **Tidy**!

Or are you talking about some other **stupid `untidy` program**?

With **Tidy**, unless you use the option `--tidy-mark no` tidy **will** add a **meta** tag in the head, of the form -

```html
<meta name="generator" content="HTML Tidy for HTML5 for Windows version 5.5.76">
```

where `Windows` and `Version` will change appropriately...

This is certainly **not** `a link ... to its site`, and definitely **no** strange code... so do not think you can be talking about this **Tidy**...

While you give yourself an answer, **backup**, also it would always be prudent to try a **new** program, presumably downloaded from the web, on one or two documents **first**, before you unleash it on thousands...

As I say, sorry about your problem, and really hope it was not our **Tidy** you are talking about...

**Comment by balthisar** [comment]
@kennyhendrick, if there's a link that something is inserting into your HTML, where does that link lead to? You might want to take up the issue with them.

**Comment by kennyhendrick** [comment]
thanks Jim....my finger has arthritis otherwise I'd write more (issue solved) Visit our website at: http://springfield-repair.com 2803 Troy Road in Springfield, Ohio(937) 718-3586   17.11.2017, 11:00, "Jim Derry" <notifications@github.com>:@kennyhendrick, if there's a link that something is inserting into your HTML, where does that link lead to? You might want to take up the issue with them.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by balthisar** [comment]
Thanks for getting back @kennyhendrick. Yeah, that's definitely **not** HTML Tidy doing that. You might want to report the incident to whomever provided that tool to you.

**Comment by kennyhendrick** [comment]
Hello, Can I get your input/opinion about appearances?  No need to read any of it, I'm just needing a heads-up about its appearance.  The site is: https://springfield-ohio-post.com     I am mainly looking to remedy any distortions, jumbled words or words on top of each other (or any other anomaly). *I already know it doesn't look so good in a mobile phone.  Thanks   ";-) Kenny Hendrick2803 Troy Road in Springfield, Ohio(937) 718-3586VisitSpringfield Ohio Jump Page
