### ISSUE TITLE
Consecutive insertion and trimming at non-location.

### ISSUE THREAD

**Issue by funkyfuture** [htacg/tidy-html5#653]
as the summary may suggest, i'm quiet confused about a result i get when i use tidy 5.2.0 via pytidylib.

when processing a document that looks okay to me, i get this message:

    line 41 column 41 - Warning: inserting implicit <p>
    line 41 column 41 - Warning: trimming empty <p>

while the data i feed in has a line 41 that is 10 characters long:

```
40					</table>
41					</p>
42					<p>
```

is that something that may happen or should i investigate this further?

**Comment by balthisar** [comment]
@funkyfuture, can you try this with a current version? And post a complete, working sample file and configuration that reproduces the problem. Thanks!

**Comment by funkyfuture** [comment]
okay, i realised it was caused by flow control elements inside `<p>`, eg:

```html
<!DOCTYPE html>
<title/>
<body>
	<p>Lorem ipsum...
		<ul>
			<li>foo</li>
		</ul>
	</p>
</body>

```

`cat test.xml | tidy 1> /dev/null` yielding:

```
line 8 column 9 - Warning: inserting implicit <p>
line 8 column 9 - Warning: trimming empty <p>
Info: Document content looks like HTML5
Tidy found 2 warnings and 0 errors!
```

so, the messages make sense, yet the first message could be clearer why it does so. shouldn't there also be a message regarding the implicit closing of the `<p>` element in line 4?

**Comment by balthisar** [comment]
@funkyfuture, thanks for getting back.

Tidy doesn't warn on "optional" end tags, and that's considered optional (see omit-optional-tags).

And when Tidy finds the closing tag, later, it does two things: adds the "missing" opening tag (and warns), and then realizes that it's an empty tag, so deletes it (and warns). Perhaps there's some logic that can detect and avoid this in the future, but for now, that's the explanation of how Tidy works!
