### ISSUE TITLE
tidylib.c fails to compile on Visual Studio 2010

### ISSUE THREAD

**Issue by dconnet** [htacg/tidy-html5#665]
VS2010's C compiler is old. The declaration of bomEnc at line 1440 causes a syntax error. Moving it to the top of the function fixes it.

**Comment by geoffmcl** [comment]
@dconnet thank you for pointing this out...

However this **fix** is already included in PR #664, Issue #663... commit 7f9e02b2fbf ... seems the old `Haiku` gcc2 2.95 compiler has the same problem as MSVC10...

So this will be done as soon as that PR is merged... and hopefully will soon get around to that... thanks...

**Comment by dconnet** [comment]
Ah, Missed that since I didn't look at the pull request queue...
