### ISSUE TITLE
Tidy deletes empty tags

### ISSUE THREAD

**Issue by Jeremiah-B** [htacg/tidy-html5#669]
When running tidy with html containing empty tags, many empty tags are simply removed.   For example i, span and li elements.   This is a problem as many of these elements are in fact significant, as can be seen in my example.

My version string: "HTML Tidy for Linux version 5.4.0"

A minimal, verifiable example:

```
<!doctype html>
<html lang="en">
  <head>
    <link href="vendors/css/ionicons.min.css" rel="stylesheet"/>
  </head>
  <body>
    <span class="ion-bug"></span>
  </body>
</html>
```

```
$  cat test.html | tidy > test1.html
```

produces

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Linux version 5.4.0">
<link href="vendors/css/ionicons.min.css" rel="stylesheet">
<title></title>
</head>
<body>
</body>
</html>
```

**Comment by geoffmcl** [comment]
@Jeremiah-B, yes, that is the **default** action of `tidy`...

See [drop-empty-elements](http://api.html-tidy.org/tidy/quickref_5.6.0.html#drop-empty-elements)... the **default** is `yes`... and that is the same in release `5.4.0` that you show you are using...

Try adding a config `--drop-empty-elements no` on the command line, or add `drop-empty-elements: no` to a config file, then add `-config /path/to/tidy.conf`... and advise... thanks...

It is normal to set up a default config file, like say `$HOME/tidy-def.conf`, with the options you like, and add, `export HTML_TIDY=$HOME/tidy-def.conf` before running `tidy`... and there are other ways to do this... we all have very different preferences when running `tidy`...

**Comment by geoffmcl** [comment]
@Jeremiah-B since there has been no further feedback in months, assume this is question asked and answered, so closing this...

Feel free to re-open, or post a **new** issue... thanks...
