### ISSUE TITLE
--fix-uri no does not turn off check

### ISSUE THREAD

**Issue by jidanni** [htacg/tidy-html5#675]
fix-uri:
> This option specifies if Tidy should check attribute values
> that carry URIs for illegal characters and if such are found, escape
> them as HTML4 recommends.

OK  but ```--fix-uri no``` still gives
```
/tmp/v.html:86:113: Warning: <a> improperly escaped URI reference
```
on e.g.,
```
<a href="https://zh.wikipedia.org/wiki/台灣積體電路製造">台積電</a>
```

**Comment by geoffmcl** [comment]
@jidanni if you refer to the **warning**, then then I think from about `tidy` version **5.5.23**, circa May 13, 2017, with a `--fix-uri no` config, it is no longer issued...

See issue #378 for the discussion and PR #556 for the merge... 

Upgrade to **any** later tidy version, if it is the **warning** you refer to... if not please explain more... thanks...

**Comment by jidanni** [comment]
OK I will tell http://bugs.debian.org/888839 .
