### ISSUE TITLE
Use tidy with json  custom attributes on  custom components

### ISSUE THREAD

**Issue by saulzini** [htacg/tidy-html5#677]
Hello @geoffmcl, I want to know if  there is a way to tell tidy to ignore custom attributes on  custom components ?

Notice the ':' before the attribute.

 Something like this using json_encode,htmlspecialchars or not:
`<order-details-table    :element=" {&quot;test&quot;:&quot;test&quot;} " ></order-details-table>`

or like this
`<order-details-table    :element=" {"test":"test"} "></order-details-table>`

Because tidy is giving this result 
`<order-details-table  ></order-details-table>`
In advance, thank you :)

**Comment by geoffmcl** [comment]
@saulzini unfortunately I know of no way to "tell tidy to ignore custom attributes on custom components"...

HTML Tidy is a **HTML/XHTML** parser, certainly **not** a `json` parser. 

Given the current tidy html `attribute="value"` parsing, things like you suggest `:element=" {"test":"test"} "`, **escaped** or **not**, will always be **invalid**...

In other words there are some things HTML Tidy can **not** do, and is unlikely to ever do... sorry...

**Comment by geoffmcl** [comment]
20201007:

@saulzini feel question asked, and answered, so closing this...

Please feel free to re-open, with discussion, or open a new issue... thanks...
