### ISSUE TITLE
Tidy does not strip leading and trailing spaces in HTML href

### ISSUE THREAD

**Issue by zneak** [htacg/tidy-html5#678]
The href attribute in HTML5 is [allowed to be surrounded by whitespace characters](https://www.w3.org/TR/2014/REC-html5-20141028/infrastructure.html#valid-url-potentially-surrounded-by-spaces), which user agents have to discard. However, when tidy encounters whitespace in href attributes, it percent-encodes them, making them part of the URL.

**Comment by geoffmcl** [comment]
@zneak thanks for your issue, and the W3C **REC** reference - this is good...

As always it would be very much appreciated if you advised the tidy **version** you are using, and provided a simple, small sample html **input**, the output **received**, and the output **expected**... thanks...

At this moment I can **not** duplicate the problem with tidy versions including and after release `5.4.0`...

Even `5.2.0` removed the spaces, but output a warning... version `5.0.0` did escape leading spaces, but removed trailing... but maybe I misunderstand the problem...

**Comment by zneak** [comment]
You're right, there is missing information here. If people frequently forget the version, you could use a [GitHub issue template](https://github.com/blog/2111-issue-and-pull-request-templates).

```
$ tidy --version
HTML Tidy for Apple macOS version 5.6.0
```

I incorrectly assessed the issue, as well. I'm trying to clean up documents generated by the (almost certainly ancient) `xsltproc` distribution for macOS. The XSLT markup looks like this:

```xml
<a>
	<xsl:attribute name="href">
		./
		<xsl:for-each select="../x86:mnemonic">
			<xsl:value-of select="@name"/>
			<xsl:if test="position() != last()">:</xsl:if>
		</xsl:for-each>
		.html
	</xsl:attribute>
	<xsl:value-of select="@name"/>
</a>
```

I get links that look like that:

```html
<html>
<head>
 <title>Foo</title>
</head>
<body>
<a href="
	./
	AAA
	.html
">AAA</a>
</body>
</html>
```

Safari and Firefox (and Chrome, I'm told) all render that as ./AAA.html. Tidy renders it as "./%20AAA%20.html", correctly stripping out the whitespace before, and keeping the ones in the middle.

With this out, I'm not sure about the spec that governs parsing URLs, unfortunately. It would still be somewhat surprising that all three implemented the same non-standard URL parsing quirk.

**Comment by geoffmcl** [comment]
@zneak for sure what **browsers** do, or do **not** do, is up to them **and** does **not** neccessarily make **VALID**, or **even** correct HTML...

Throw your `sample` at the W3C [validator](https://validator.w3.org/#validate_by_upload), and I think you will see what I mean -

```
Error: Bad value ↩	./↩	AAA↩	.html↩ for attribute href on element a: Tab, new line or carriage return found.
From line 8, column 1; to line 12, column 2
d>↩<body>↩<a href="↩	./↩	AAA↩	.html↩">AAA</a
```

The purpose of `tidy` is to try to **fix** this... but of course it can only **guess** at what the html author **intended**... It is **good** at some, and really **sucks** on others...

What is a **valid** `href` is certainly one of the **more** difficult ones... 

And there have been quite a number of issues on this... we do have the option `--fix-uri no` to stop the `escaping`, but there seems no way to just strip **all** spacey chars, given that there are valid URI's with `spaces`, just like you can have a `path` and/or `filename` that does include spaces...

I do not think `tidy` can do more at this time... but always open to suggestions, patches, PR for review... thanks...

And yes, thanks for the github `template` pointer... this is possible, but most of the time commenters do remember to add sufficient information, so probably will not implement this at this time... thanks...

**Comment by geoffmcl** [comment]
@zneak no `Feature Request` emerging here... sorry, closing this...

Look forward to any further discussion, new issue, etc.... thanks...
