### ISSUE TITLE
Adopt Cygwin tidy package

### ISSUE THREAD

**Issue by AnrDaemon** [htacg/tidy-html5#680]
The HTML Tidy package in Cygwin is extremely old and seems abandoned.
It would be wonderful, if somebody could take care of it.

#### What is Cygwin?
Cygwin is a POSIX API implementation for Windows (["newlib"](https://sourceware.org/newlib/), the "Cygwin DLL" itself) and a [package distribution system](http://cygwin.com/install.html) with a "rolling release" approach to update packages.

While the Cygwin DLL is maintained by a core development team, the project as a whole receive contributions from many people - package maintainers - devoting their time to update and support numerous packages provided through the single package manager.

#### But there's a Windows builds for Tidy already?
Cygwin is not "Windows", Cygwin is "sort of Linux".
While it is possible to pipe data in and out of tools from different environments with little care, directly working with files across operating environment borders requires wrappers.
Nothing that can't be solved with relative ease, but a native build would be greatly appreciated.

**Comment by geoffmcl** [comment]
@AnrDaemon thanks for your comment. I am **well** aware of **Cygwin**, and have built projects in the past using it...

I am not sure I fully understand what you are suggesting here... as far as I am aware current `tidy`, that is a **console** app `tidy.exe`, and **libtidy**, static and shared, can be built using **Cygwin**... 

Have you, or others, tried it? What results? I am sure we can address any problems, if there are any...

I am **not** personally interested in **adopting** a `Cygwin` HTML Tidy package, but **may** consider adding it to our **binary** distributions if someone else supplied and looked after it, solidly and regularly... 

And naturally such a package could be added to the `Cygwin` **packages**, but I am **not** familiar with what that entails, or exactly what that offers...

So who is the **champion** that's going to stand up, and own this? Suggestions are fine, but who will do the **work**?

**Comment by AnrDaemon** [comment]
I'm aware that it can be built (in fact, I'm working towards setting up build environment for Cygwin to test some stuff I'm interested in).
But Cygwin is not a "build it yourself" kind of project, it is distributing actual binaries, and you don't have to be a code guru to use it.
The proposition is to take the hat of the [package maintainer for Cygwin](https://cygwin.com/packages.html) and upload the packages directly to the Cygwin repository.

Assuming it is building cleanly, I could probably help with initial setup. But I'm not a C/C++ programmer and unable to support the builds if anything goes down the rabbit hole.

**Comment by geoffmcl** [comment]
@AnrDaemon well that is what these `issues` are about... If there is a `cygwin` build issue, then I am **sure** it can be addressed here...

In general `Tidy` is a **simple** C project, and tends towards the original K&R C... It does nothing particularly special in this regard, so should be easily built by a `gcc` windows port... I have for instance successfuly built `tidy` using `MinGW` and `MinGW-w64` which also has a windows `gcc` port...

As stated, I personally am very unlikely to setup the `cygwin` environment, but am sure there may be others interested... 

So **go for it**, rabbits and all... ;=))

I am sure we can find a place like [get-tidy](http://www.html-tidy.org/#homepage19700601get_tidy) to mention it on our web site... keep us informed... thanks...

**Comment by geoffmcl** [comment]
@AnrDaemon so is anything happening on this? It has been several months...

I just noticed there was a previous closed #362 on this topic...

Searching around noted http://cygwin.1069669.n5.nabble.com/State-of-HTML-Tidy-package-td134148.html where this was discussed... 

But searching say https://cygwin.com/packages/package_list.html, I could only find the 2009 `libtidy0_99_0`, which is very **sad**...

Anyway, due to the fact that this is **not** really a `tidy` issue, but a `cygwin` issue, and no further comments, closing this... 

But would still like to know if there is any `cygwin` update to add to our web site...

Feel free to reopen, or post a new issue... thanks...

**Comment by AnrDaemon** [comment]
This is not a "cygwin issue", as there's no active tidy package maintaner for Cygwin.
Cygwin itself provide installer and core library, the rest is provided by maintainers of individual packages.
And #362 is not related in any way, so to say.

**Comment by geoffmcl** [comment]
@AnrDaemon thanks for the further feedback...

> there's no active tidy package maintaner (sic) for Cygwin.

That I understood, and thought that was what **you** were going to do... oh, well...

As advised, I am personally **not** interested, and more or less left this open a while hoping **someone** would step up...

> And #362 is not related in any way, so to say.

That was about building `tidy` from source, with-in the `cygwin` quasi unix environment, which I took the time to do, test and report, and can **not** see how it is **unrelated**. 

That seems what a `tidy package maintainer for Cygwin` would have to do, to have the binaries to upload, but **no** problem... Maybe I am wrong...

What more do you want from `tidy`? Thanks...

**Comment by AnrDaemon** [comment]
I do not **want** anything specifically, I was suggesting that somebody with skill and knowledge could step up to support one more distribution channel.
But if not, then not.
