### ISSUE TITLE
feature request(safari): Pinned Tab Icons support

### ISSUE THREAD

**Issue by Kristinita** [htacg/tidy-html5#686]
### 1. Summary

If user have in HTML constructions as:

```html
<link rel="mask-icon" href="SashaSVG.svg" color="red">
```

It would be nice, if user don't get a warning:

```shell
line 6 column 9 - Warning: <link> proprietary attribute "color"
```

### 2. Argumentation

See [**Creating Pinned Tab Icons page**](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html) on official Apple site.

Another validation tools already support `color` attribute, see related issues:

+ [**mask-icon is not a registered keyword**](https://github.com/validator/validator/issues/174),
+ [**HTML validation fails**](https://github.com/RealFaviconGenerator/realfavicongenerator/issues/218).

Thanks.

**Comment by balthisar** [comment]
See the option [`warn-proprietary-attributes`](http://api.html-tidy.org/tidy/quickref_next.html#warn-proprietary-attributes) for instant resolution.

**Comment by geoffmcl** [comment]
@Kristinita thanks for the issue...

Have **not** read any W3C documentation on this, but like the `nu` validator, @sideshowbarker, have added `TidyAttr_COLOR` to the `W3CAttrsFor_LINK` that governs attributes allowed for `TidyTag_LINK`... and pushed the change db02d45 to the `issue-686` branch... this seems to remove the **warning**...

Have run our [Regression Tests](https://github.com/htacg/tidy-html5-tests) and no problem, but this may just mean there is no existing test for this...

Look forward to futher feedback on whether this should be merged to `next`... thanks...

**Comment by geoffmcl** [comment]
Now PR #701 merged so closing this... thanks @Kristinita ...

**Comment by Kristinita** [comment]
@geoffmcl , when 5.7 version will released?

Thanks.

**Comment by Kristinita** [comment]
5.6.0 is [**latest release**](https://github.com/htacg/tidy-html5/releases) for February 2019. We wait a new release.

Thanks.

**Comment by Kristinita** [comment]
@geoffmcl , in September 2020 we are waiting for version 5.8.

Thanks.
