### ISSUE TITLE
Is there any way to remove inline styles?

### ISSUE THREAD

**Issue by i-give-up** [htacg/tidy-html5#689]
[Feature request] One workaround is to use `--clean yes` and then remove the `<style>` tag manually. But a built-in way for `tidy` to remove inline styles would be quicker and would result in a smaller file size.

Use case: when exporting a spreadsheet as HTML, the program tries to preserve the original appearance using a lot of style information resulting in an odd-looking HTML table.

## Input

``` html
<!DOCTYPE html>
<html>
  <title>Testing</title>
<body>
<table>
  <tr>
    <td style="font-weight:bold">Hello whirl!</td>
    <td style="color:red">Goodbye!</td>
  </tr>
</table>
</body>
</html>
```

## Desired output 

``` html
<!DOCTYPE html>
<html>
  <title>Testing</title>
<body>
<table>
  <tr>
    <td>Hello whirl!</td>
    <td>Goodbye!</td>
  </tr>
</table>
</body>
</html>
```

**Comment by geoffmcl** [comment]
@i-give-up thought about this but certainly at the moment there is no `option` to just delete **style**, as you are requesting...

While one of tidy's actions is to **clean** a document, but in doing so considerable care has been taken to try to keep the rendering in a browser unchanged. 

Such an option is asking `tidy` to deliberately mess up the rendering...

So at this moment do not see this as a suitable option for `tidy`, but would try to listen to other feedback and ideas... thanks...

**Comment by geoffmcl** [comment]
@i-give-up for the reasons mentioned marking this `Won't Fix`, and closing it... thanks...
