### ISSUE TITLE
"Too many title elements in <title>" should say "Too many title elements in <head>"

### ISSUE THREAD

**Issue by petdance** [htacg/tidy-html5#692]
There are no title elements in <title>.  They're in <head>.

```
$ cat titles.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <HEAD>
        <TITLE>Test stuff</TITLE>
        <TITLE>As if one title isn't enough</TITLE>
    </HEAD>
    <BODY>
        <P>This is my paragraph</P>
    </BODY>
</HTML>
```
```
$ tidy -q -e titles.html
line 2 column 5 - Warning: too many title elements in <title>
```

**Comment by petdance** [comment]
In `src/message.c`, this seems to be the problem:

```
        case COERCE_TO_ENDTAG:
        case NON_MATCHING_ENDTAG:
        case TOO_MANY_ELEMENTS_IN:
            return TY_(tidyMessageCreateWithNode)(doc, rpt, code, level, node->element, node->element );
```

I would think that the second `node->element` should be something else.  But I don't know enough about tidy internals to say for sure.

**Comment by geoffmcl** [comment]
@petdance Pushed the above simple message fix to `branch` **issue-692** for consideration...

But seek further feedback on whether this should also include deleting such multiple `<title>` elements, and as suggested maybe trying to keep the last, if possible, but at least all after the first... to ensure tidy outputs valid html... thanks...

**Comment by geoffmcl** [comment]
@petdance Have done further testing on this, and in the case of multiple `<title>` elements it seems in the 4 browsers I tested, I was surprised to find that they only showed the **first**. Others seem to just be dropped...

That makes deleting subsequent `<title>` elements relatively easy in `tidy`...

So will work on extending the `issue-692` branch to do this...

As always further feedback very welcome... thanks...

**Comment by geoffmcl** [comment]
@petdance have now pushed a further fix to the `issue-692` branch to delete any subsequent `<title>` tags...

In this case it was not so `easy`. It was not possible to delete the additional `<title>` node in the `parser.c` module where the first message comes from. So I created a new service `TY_(CleanHead)(doc)` in `clean.c`, called during the post parsing, in `tidyDocCleanAndRepair` phase.

At this moment now we get two warnings, the original, during the parsing phase, and the second during the post clean-up phase, and on your sample get -

```html
line 2 column 5 - Warning: too many title elements in <head>
line 2 column 5 - Info: <head> previously mentioned
line 4 column 9 - Warning: discarding unexpected <title>
```

Maybe we could delete the warning during the parsing, and only leave the clean-up phase. Or leave them both? What do you or others think? Thanks...

And this seems to show up another possible item, and that is the line numbers. 

In the actual document the second `<title>` is actually on `line 4 column 9`, as the second warning correctly states. The first warning shows the location of the `<head>` tag, which is technically **correct** in that the message mentions the `<head>`, but now seems less informative. 

Maybe this is an additional reason to to drop the first warning...

Also, I used a message that already existed. Maybe we need to have a more specific message like say `discard duplicate <title> tag`, or something, but that could be a separate issue...

Look forward to further feedback and testing on this `issue-692` branch... thanks...

**Comment by petdance** [comment]
Is there something specific you want me to look at?  My time right now is being spent on the HTML::Tidy5 Perl wrapper around it.

**Comment by balthisar** [comment]
Closing due to merging of the PR.
