### ISSUE TITLE
tidy-html5 does not understand SVG

### ISSUE THREAD

**Issue by danvk** [htacg/tidy-html5#70]
I cloned the most-recent version of tidy and ran it against a simple html file:

$ ./bin/tidy workbench.html
line 7 column 5 - Error: <svg> is not recognized!
line 7 column 5 - Warning: discarding unexpected <svg>
line 9 column 5 - Warning: discarding unexpected </svg>
Info: Document content looks like HTML5
2 warnings, 1 error were found!

This document has errors that must be fixed before
using HTML Tidy to generate a tidied up version.

About this fork of Tidy: http://w3c.github.com/tidy-html5/
Bug reports and comments: https://github.com/w3c/tidy-html5/issues/
Or send questions and comments to html-tidy@w3.org
Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
HTML language reference: http://dev.w3.org/html5/markup/
Validate your HTML5 documents: http://validator.w3.org/nu/
Lobby your company to join the W3C: http://www.w3.org/Consortium

$ cat workbench.html
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Micro chart workbench</title>
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" version="1.1" id="svgID"
        height="100%" width="100%">
    </svg>
  </body>
</html>
```

The <svg> tag is mentioned in the "Latest HTML specification" that tidy refers to, so it would be nice to see support in tidy-html5.

**Comment by geoffmcl** [comment]
Thanks for the report... Sorry for the delay in response...
As you may know the latest devlopment branch is develop-500
$ git checkout develop-500
But in checking the latest code, this 'bug' is still present, while after building a input test sample based on yours above with the added head item -
 '<meta charset=utf-8>'
the sample passes the validators... and then found w3.org documentaions supporting 'svg', so will work on adding svg support, and advise when done.

**Comment by geoffmcl** [comment]
Basic support for svg tag added in version 4.9.7 in the develop-500 branch...

A big thank you to Ger Hobbelt who had implemented this in his htmltidy fork with some attribute table additions, and some parsing services, which needed only minimal changes to cut into tidy5.

Still to review the supported attribute table, and perhaps extend, fix the list...

After this table review and testing this should be closed...

**Comment by balthisar** [comment]
Confirmed working fix in develop-500. Please feel free to reopen this if you disagree.

**Comment by PierBover** [comment]
I'm using 5.6.0 and SVG still isn't recognized...

```
line 20 column 17 - Error: <svg> is not recognized!
line 20 column 17 - Warning: discarding unexpected <svg>
line 19 column 9 - Warning: missing </a> before <style>
line 19 column 9 - Warning: <style> isn't allowed in <a> elements
line 20 column 154 - Error: <path> is not recognized!
line 20 column 154 - Warning: discarding unexpected <path>
line 20 column 5011 - Error: <path> is not recognized!
line 20 column 5011 - Warning: discarding unexpected <path>
line 20 column 7439 - Error: <g> is not recognized!
line 20 column 7439 - Warning: discarding unexpected <g>
line 20 column 7444 - Error: <path> is not recognized!
line 20 column 7444 - Warning: discarding unexpected <path>
line 20 column 13722 - Warning: discarding unexpected </g>
line 20 column 13727 - Warning: discarding unexpected </svg>
```
