### ISSUE TITLE
Get plain text data

### ISSUE THREAD

**Issue by daurnimator** [htacg/tidy-html5#71]
I'm using `tidyNodeGetText`, I was hoping to get the plain text (that is, without escape sequences).

As far as I can figure out, `PPrintText` can just be called with different (non-zero) mode parameter.
But there is no way to change the mode parameter with the public interface...

**Comment by balthisar** [comment]
@daurnimator, sorry for the very late response. Can you be more specific? Or better yet, can you create a PR against the develop-500 branch? We wouldn't want to modify existing API, but are open to new API if it provides features you require.

I will close this due to age, but you are free to reopen this if you're still around and still interested in applying Tidy.

**Comment by daurnimator** [comment]
I still believe this fix needs to happen.

but the next time I go near my html tidy-ing code I imagine I might just port over to [gumbo](https://github.com/google/gumbo-parser) instead... tidy doesn't seem to be maintained :(

**Comment by balthisar** [comment]
@daurnimator, you can still reopen this ticket, but I don't understand exactly what functionality you want from the library. Can you provide an example?

You're right, Tidy hasn't been maintained in a long time. It's been three weeks since HTACG got involved, and I think things are changing. :)

**Comment by daurnimator** [comment]
> I don't understand exactly what functionality you want from the library. Can you provide an example?

I am using tidy to (in realtime) transform mildly malformed HTML to valid XHTML. From there, I traverse the XML tree and use fields inside my application.

The issue is, `tidyNodeGetText` returns text that is xml escaped: I have to manually unescape it to get the actually text content.

Reading the source, `tidyNodeGetText` only does the escaping on output, so the request is that an alternative is added that does not escape on output, only for me to unescape again....

**Comment by geoffmcl** [comment]
Just to understand more exactly what you are asking for here can you give a few samples of what you get from `tidyNodeGetText`, and then show what you expect...

**Comment by daurnimator** [comment]
```C
#include "buffio.h"
#include "tidy.h"
#include <stdio.h>

int main() {
	TidyDoc tdoc = tidyCreate();
	TidyBuffer buff;
	tidyBufInit(&buff);
	tidyBufAppend(&buff, "<body>something &amp; escaped</body>", 36);
	tidyParseBuffer(tdoc, &buff);
	TidyNode body = tidyGetBody(tdoc);
	TidyNode text_node = tidyGetChild(body);
	TidyBuffer buff2;
	tidyBufInit(&buff2);
	tidyNodeGetText(tdoc, text_node, &buff2);
	fwrite(buff2.bp, buff2.size, 1, stdout);
	return 0;
}
```
output is:
```
something &amp; escaped
```

I expect:
```
something & escaped
```

**Comment by geoffmcl** [comment]
Hi daurnimator,

Thanks for the quick reply, and the code to boot ;=))

And if I get a chance I will test your code, and perhaps add it as a simple sample of the use of libtidy, if you have no objection.

Now I understand what you want very clearly, but at present Tidy has no such API service ;=((.

But it would not be difficult to write/add... Look in entities.c. At present all services there are 'private' library services... including the static entities table...

So perhaps add to the API with something like, remembering libtidy is C, NOT C++ - CODE NOT TESTED!

tidy.h
````
/** Get entity code point from name */
TIDY_EXPORT Bool TIDY_CALL tidyGetEntityCode( ctmbstr name, Bool isXml, uint* code, uint* versions );
````

entities.c
````
/** Get entity code point from name */
Bool TIDY_CALL tidyGetEntityCode( ctmbstr name, Bool isXml, uint* code, uint* versions )
{
    /* little bit of versification - avoid an assert */
    if ( !name || name[0] != '&' )
        return no; /* failed */
    if ( !code )    
        return no; /* failed */
    if ( !version )
        return no; /* failed */
    /* see what we get */    
    return TY_(EntityInfo)( name, isXml, code, version );
}
````

Now, in your 'main' you could process the text buffer, replacing the entities with their code...

After coding and testing you could do this as a Pull Request, or even just a simple diff patch file, and I would add it...

In this way we would BOTH gain a new service ;=)) at least for entities 'known' by libtidy...

Regards,
Geoff.

**Comment by daurnimator** [comment]
I have no problem processing the entities myself.
But the thing is, tidy stores them unencoded internally, and only creates them on output (i.e. the `tidyNodeGetText` call).
To encode and then decode immediately after is a silly API.

**Comment by geoffmcl** [comment]
Didn't look that deep... maybe you are right...

But if you are right, then would still need an API extension, something like tidyNodeGetRawText or something... since the current API is intended that the text be placed in a html file, thus needs to be encoded... will get around to checking further...

**Comment by daurnimator** [comment]
> need an API extension, something like tidyNodeGetRawText or something

Yes, a new function will probably need to be added.
Unless no one was using the old API.... It was quite unexpected when I ran into this.

> since the current API is intended that the text be placed in a html file,

Is it? the C API doesn't seem to be: see GetName, GetAttr, etc.

> thus needs to be encoded... will get around to checking further...


-------------------------------

Herp..... half way through typing this email I was reading the source and ran into `tidyNodeGetValue`.
This seems to be what I need.

Sorry for the noise!

**Comment by geoffmcl** [comment]
@daurnimator no problem... shows I do not know the API as well as perhaps I should ;=))

Yes `tidyNodeGetValue` returns the data exactly as in the lexer - straight strcpy to the buffer.

Have added a little to your sample API usage, tested, and pushed it in the hope it will help others... Thanks.
