### ISSUE TITLE
tidy converts '&' in query parameters (&aen=true => &amp;aen=true) in relative paths

### ISSUE THREAD

**Issue by JESii** [htacg/tidy-html5#710]
### Input HTML
`<a class="m-j-cm-link" href="/shop/womens-clothing?id=118&edge=hybrid&aen=true&cm_sp=mew_us_homepage-_-slot1-_-Women">`

### Output tidied HTML
`          "/shop/womens-clothing?id=118&amp;edge=hybrid&amp;aen=true&amp;cm_sp=mew_us_homepage-_-slot1-_-Women">`

I couldn't see an option to turn off this behavior...

**Comment by geoffmcl** [comment]
@JESii I do **not** think there is a `tidy` option to turn this off...

We do have an option `--fix-uri no`, but this **only** effects the escaping of `illegal` characters, and does **not** effect an ampersand...

But why would you want it turned off?

If you view the link as tidy has escaped it, in a browser, it should appear without the `&amp;`, just with the `&`, so the link will function correctly...

Maybe I misunderstand the case... need further feedback... thanks...

**Comment by mc0e** [comment]
Tidy's behavior here is turning incorrect html into correct html.  I'd have to say though that I've never liked the readability of those `&amp;` character entities, and I much prefer the use of `;`, which is blessed by the CGI spec as an alternative to the ampersand in query strings.

**Comment by mc0e** [comment]
`&` is correct in the query string, but to represent an `&` in html, you write it as a character entity.  With html, an unescaped `&` is usually not the start of something that looks like a defined character entity, and browsers deal with that.  In XHTML though it violates the requirement of being well formed XML, and the browser is required to reject it.

**Comment by JESii** [comment]
OK... got it. thanks!
