### ISSUE TITLE
feature_request(validation): “preserve-entities yes” by default

### ISSUE THREAD

**Issue by Kristinita** [htacg/tidy-html5#732]
### 1. Summary

It would be nice, if value of [**`preserve-entities` option**](http://api.html-tidy.org/tidy/quickref_next.html#preserve-entities) will `yes` by default.

### 2. Argumentation

[**Official W3C validator**](https://stackoverflow.com/q/3493405/5951529) and [**htmllint**](https://github.com/htmllint/htmllint) require escaped `&` symbols.

More details:

+ [**Do I really need to encode '&' as '&amp;'?**](https://stackoverflow.com/q/3493405/5951529)

### 3. Configuration

`SashaEscapeAmpersand.html`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sasha &amp; title</title>
</head>
<body>
</body>
</html>
```

### 4. Expected behavior

If `--preserve-entities yes`:

    tidy -mq --show-errors 0 --show-warnings 0 --wrap 0 --preserve-entities yes SashaEscapeAmpersand.html

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta name="generator" content="HTML Tidy for HTML5 for Windows version 5.6.0">
<meta charset="UTF-8">
<title>Sasha &amp; title</title>
</head>
<body>
</body>
</html>

```

Valid.

### 5. Actual behavior

Else:

    tidy -mq --show-errors 0 --show-warnings 0 --wrap 0 SashaEscapeAmpersand.html

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta name="generator" content="HTML Tidy for HTML5 for Windows version 5.6.0">
<meta charset="UTF-8">
<title>Sasha & title</title>
</head>
<body>
</body>
</html>

```

Not valid.

Thanks.

**Comment by sampablokuper** [comment]
Perhaps this should be doctype-specific, such that it is on by default for doctypes for which a standalone `&` would be invalid? That is probably the most intuitive behaviour, but it would be more complicated to implement than document than simply default on or default off.

**Comment by balthisar** [comment]
I'm going to close this. The reason we have options is to have options.
