### ISSUE TITLE
Summer solstice release 5.8.0

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#741]
I have arbitrarily set the next release to June 24, 2018... in about 3 weeks...

The last release, 5.6.0, was on Nov 25, 2017, after some delays... that would be about 6 months... which seems about right...

At this time we only have about some 40 commits to `next`, but some of those have been very important fixes... like #739 ... in the remaining period maybe more could be added...

The following is a fluid situation, but is sort of a summary of outstanding issues...

There are presently 3 PR's. One requires a `regression` test change. 

Two have had some rude words thrown at them, like ad hoc, confusing, ... and will have to wait for further fixes... 

Then we have about nearly 70 **open** issues...

About a dozen are marked `Bugs`, but as yet **no** fix has been proposed or at least accepted... no PR...

A few are marked `Docs` which always needs improvement. There are some `patch` suggestions, but not yet a PR... 

About 20 are marked `Feature Request`. Some are very **good** ideas, but **no** coding has yet been proposed...

About 20 are marked `Technical Discussion`, where for many, no current **fix** is suggested, or indicated...

So at the very least, many need their `milestone` extended... 

There it is... should there be a release? Or wait longer? feedback welcome... thanks...

**Comment by geoffmcl** [comment]
@ler762, thanks for the +1, and to `all`, but I am not getting any 'younger!' and spend a **lot** less time with my computer, so sadly no longer have the time for `tidy`, that I used to... so this, and other `tidy` matters/things are unlikely to be actioned by me anytime soon... sorry..

So unless this work is undertaken by the other 'admins', I suppose `tidy` should look for **new** `maintainers`... any offers, suggestions, ... ?

I may be able to supply a win64 binary release, after the release is all setup...

**Comment by balthisar** [comment]
I can supply binaries as well. I've got a six-month old, so similar time restraints as @geoffmcl, unfortunately.

My style is to attack something, and spend all of my time on it, which I'm unable to do right now. I can pitch in for smaller maintenance things and releases for now, and see how it works out in the future.

We've _always_ looked for other maintainers, and that invitation is still out there!

@geoffmcl, what help do you need for a 5.8 release, if you think it's ready?

**Comment by ler762** [comment]
@geoffmcl I hope it's something good in your life that's leaving you no time for tidy.

I'm still very uncomfortable with git; I can help with documentation and testing but I'd probably cause more problems than progress trying to help with anything git related.

**Comment by geoffmcl** [comment]
@balthisar, I do not know if we **need** a 5.8 release... a quick review shows some 65 commits since the last, so this is positive... but there are outstanding PRs, some new, which I have not reviewed, but there also remains 70 plus issues, unresolved... so I do not know if it is **ready**... but would support one, with help...

@ler762, yes, the release process is mainly git/github, and it takes time to understand all that is involved... mainly a number of little steps, some of which need to be done in a timely manner, to set the version, the tag, and the branches...

But ok, if we are to proceed with **The Release 5.8.0**, as usual I have prepared a rough list...

#### Preparation:
 
 - Create 5.10 milestone - **Done**
 - Decision on PR's to include, bumping version.txt, accordingly...
 - Change milestone of all excluded this time issues to 5.10, or indefinite...
 
#### The Release:
 
 1. Update version.txt to 5.8.0, and date...
 2. Create git TAG 5.8.0, create branch release/5.8, and push
 3. Update README/vershist.log
 4. Generate release 5.8.0.html
 - Generate release binaries
 - Add binaries
 - Add api docs
 - Update web pages 
 - Other things?

#### Post:

 - Update master branch to release
 - Update next version.txt to 5.9.0
 - Add more binaries...
 
Maybe the list needs to be filled out... I have some scripts for the updating of vershist.log, and gen. of 5.8.0.html release notes, see [rel.sample](http://geoffair.org/tmp/5.8.0.html), as advised... see #334, #394, #471, maybe others..., so could do 1 thru 4, as usual... when/if the release date is definitively decided, and agreed... most dates are ok with me, except tomorrow, 30/8/2018 - will be out all day...

**Comment by ler762** [comment]
@geoffmcl if it's this weekend, does that answer your earlier
> Decision on PR's to include
with 'with whatever is currently in branch next'?

I just did a pull on tidy-html5 & tidy-html5-tests, built tidy & ran the regression tests.
All passed :)

**Comment by balthisar** [comment]
I'll try to support this weekend. It's a long holiday weekend for us on this side of the pond.

**Comment by geoffmcl** [comment]
@ler762 **no**, no decision on PRs, and outstanding issues done by me... that is what I expect feedback on... some sort of review, as a yes/no list...

It is that decision which will begin to decide and agree a **release date**, if there is to be one...

Sorry, if the resetting of the 5.7 milestone confused the issue... forget that...

In my view of the past, the only PR I would include at this time is #731, #726, and note it includes regression test matching merge... but thank you @ler762 for conducting the tests with `next`... good to have confirmation of what I see in Windows for 5.7.16, since April...

I do **not** have time to review the 2 other recent PRs ... extra const #746 PR #747 and snap packaging #748 PR #749... 

And since no current agreed **fixes** are available for many of the issues, in my view they would all be assigned another milestone... that is the release would almost be the current `next`... but I am just one voice... so for me it is just a case of choosing a suitable date...

This weekend turned out bad for me anyway... having a RAM upgrade problems in one of my main machines, which will reach into tomorrow now... so I am for later days/weeks/mth target date suggestions...

**Comment by ler762** [comment]
@geoffmcl  If you pick a date for a release, isn't whatever that's in 'branch next' what goes out in that release?  Or was this weekend supposed to be more of a final push for what all goes in 5.8?

I did a quick look in the docs & didn't see anything about the release process.  Is that documented somewhere?

**Comment by geoffmcl** [comment]
Merged the #753 Fix type in the **new** `RELEASE.md`, but accidentally added with an Is #752 commit message...

As to a target release date, now I would suggest that be after the **interesting** `can of worms` exposed in exploring issue #752 - the `mute` option, and more... full satisfactory solution seems near, else move it to next release...

**Comment by ler762** [comment]
@geoffmcl  My definition of 'full satisfactory solution' would include having command line options processed first :)  But 'satisfactory' would be documenting the current behavior (and less risky), so
- doc update for the man page
- get rid of the ``Loading config file "~/.tidyrc" problems, err = 1`` message
- matching changes for tidy-html5-tests/

and what else before a new release?

I'd leave off improving .tidyrc processing for a later release and continue having stuph like ``malformered input'' be silently ignored.

**Comment by balthisar** [comment]
Released. @geoffmcl, I hope you're well out there!
