### ISSUE TITLE
Can't parse UTF16 html string

### ISSUE THREAD

**Issue by ekalchev** [htacg/tidy-html5#744]
I can't get this code to work. The output is empty html without h1 and p tags. It works for utf8 and ascii but not for UTF16

Am I doing something wrong or this is defect?

                                     int rc = 0;
					TidyDoc tdoc = tidyCreate();
					TidyBuffer output = { 0 };
					TidyBuffer errbuf = { 0 };
					char* test = (char*)u"<html><head><meta name = 'author' content = 'John Doe'></head><body><h1>My First Heading  𠜱 𠝹 𠱓 𠱸</h1><p>My first paragraph.</p></body></html>";
					rc = tidySetInCharEncoding(tdoc, "utf16le");
					rc = tidySetOutCharEncoding(tdoc, "utf16le");
					rc = tidyParseString(tdoc, test);
					rc = tidySaveBuffer(tdoc, &output);

**Comment by cmb69** [comment]
Calling `tidyParseString()` with UTF-16 encoded input does not seem to be supported (under the hood it uses  [`TY_(tmbstrlen)`](https://github.com/htacg/tidy-html5/blob/86b52dc1081ca4b0582c7bad279bf254bad268e1/src/tmbstr.c#L92-L102) which does not report the proper byte length for UTF-16). See, for instance, [PHP's wrapper](https://github.com/php/php-src/blob/php-7.3.0RC3/ext/tidy/tidy.c#L1043-L1044) on how to set up an appropriate input buffer.

**Comment by ekalchev** [comment]
This works. Thanks!

**Comment by geoffmcl** [comment]
@cmb69, thank you for pointing this out... yes the internal `strlen` service will stop at the first 0 `byte`, so can fail with a utf16 string... 

Maybe this is suggested by the [tidyParseString(TidyDoc,ctmbstr)](http://api.html-tidy.org/tidy/tidylib_api_next/group__Parse.html#ga50c02fa244dcd120ae339719c2132ff9) uses a string **type** `ctmbstr`, which is based on a `char`, but could certainly be documented better...

@ekalchev as pointed out, PHP uses `tidyParseBuffer()`, with a `TidyBuffer`, which supplies **length**, is used, and provide the desired character encoding is specified should work as expected with all supported char encoding...

Certainly look forward to feedback on documentation improvements... that is in the `tidy.h` doxygen comments... suggestions, patches, PR, comments very welcome... thanks...

**Comment by balthisar** [comment]
Documentation change pushed to reflect this. Closing.
