### ISSUE TITLE
tidy dies on unexpected character

### ISSUE THREAD

**Issue by geoffleach1** [htacg/tidy-html5#745]
3:	unexpected character decimal 147 (�) in script
3:	Giving up after error\
1221:	To save a full .LOG file rerun with -g

There's no mention of .LOG in the (Linux) man page, and -g has no obvious effect.

**Comment by geoffmcl** [comment]
@geoffleach1 output shown does not look like `tidy`... please explain...

**Comment by geoffleach1** [comment]
Hmmm ... its been a while ...

The file that caused the problem is long gone.

I had a file that contained a non-ASCII byte. Tidy died.

Sorry I can't be more specific.

**Comment by geoffmcl** [comment]
@geoffleach1 well, if you can not now duplicate the problem, then there can be no fix for `tidy` ;=)) no need to be sorry...

Closing this until then... or open a new issue, with full details, sample input, tidy version, config, setup, output, etc... thanks...
