### ISSUE TITLE
Intent-To-Package: Snaps are Universal Linux Packages

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [htacg/tidy-html5#748]
Dear maintainer(s), 

[Snaps are universal Linux packages](https://snapcraft.io) that can be installed and run on multiple GNU+Linux distributions with ease.  I've been following the [Snapcrafters](https://forum.snapcraft.io/t/join-snapcrafters/1325) instructions and [have built a working snap on the Snap Store](https://snapcraft.io/tidy), you may try it by running the following commands after [installing snapd](https://docs.snapcraft.io/core/install):

    # snap install tidy

I'm also looking forward to working with you to make the packaging work upstream (if you're interested).  You may want to check out the current [packaging recipe](https://github.com/Lin-Buo-Ren/tidy-snap), the [documentation](https://forum.snapcraft.io/c/doc), registering a developer account on the [Snap Store](https://snapcraft.io/store), and [get in touch with us](https://forum.snapcraft.io) to transfer the work under your control.

Thanks for your time and attention.

**Comment by geoffmcl** [comment]
@Lin-Buo-Ren, agree with the comments of @balthisar, this should not be in this main tidy repo, but maybe other arrangements could be made... sorry...

Accordingly, closing this PR for now, and the associated issue #748... thanks...
