### ISSUE TITLE
--tidy-mark no inserts blank line

### ISSUE THREAD

**Issue by jcubic** [htacg/tidy-html5#760]
If you use this option to remove meta tag generator (I have it already from Jekyll that I wan to keep) it don't remove newline and you have one blank line in place of generated meta tag.

**Comment by geoffmcl** [comment]
@jcubic I am afraid I do not understand the issue... sorry...

While I do think the API docs [tidy-mark](http://api.html-tidy.org/tidy/quickref_next.html#tidy-mark) leaves a lot to be desired by way of explanation of exactly what will happen in various cases, nowhere can I read it is an option `to remove meta tag generator`... 

That is, it will `never` **remove** a meta tag... 

In a specific circumstance, that it can find an existing meta tag of the exact form `<meta name="generator" content="HTML Tidy[ $version]">` it can **modify** the specific `[$version]`... but **never** remove the tag...

The option `--tidy-mark no` means `libtidy`, in the API `tidyCleanAndRepair( TidyDoc )`, in `tidyDocCleanAndRepair(doc)`, does **not** run the internal service `TY_(AddGenerator)(doc);`... so nothing is added, modified, or removed...

Show the version of tidy in use, provide sample html input, and config used, showing current tidy output, and then the expected output... showing say the `blank line` you mention... thanks...

**Comment by jcubic** [comment]
Sorry, I think I use some old version, I've update the code recently and it now works fine.

It leave some blank lines but not in place of generator meta tag.
