### ISSUE TITLE
Tidy output going to stderr

### ISSUE THREAD

**Issue by phonedog365** [htacg/tidy-html5#763]
HTML Tidy for Apple macOS version 5.6.0 installed via Brew and updated. Output is going to stderr. Ran command `tidy -e [file] | more` and notice output was bypassing `more`. Ran `hilite tidy -e [file]` and it verified all output was going to stderr. Man page indicates:

> --output-file String This option specifies the output file Tidy uses for markup. **Normally markup is written to stdout.**

Thanks!

**Comment by geoffmcl** [comment]
@phonedog365 maybe I completely misunderstand the problem... sorry...

If you use `-e`, or `-errors`, or `--markup no` on the command line, or add `markup: no` to a config file, then there should be **no** `stdout`, that is **no** pretty printed html output, thus **nothing** would be passed to `| more`... 

So given say `tidy -e in_file.html[ | more]`, with or without the `| more`, the **only** output should be warnings, errors, and info, all sent to `stderr`, as documented...

What is the problem you see?

Please clarify... thanks...

**Comment by phonedog365** [comment]
I just now read this (as if for the first time!): 

> If no input file is specified, Tidy reads the standard input.  If no output file is specified, Tidy writes the tidied markup to the standard output.  If no error file is specified, Tidy writes messages to the standard error.

I would have (wrongly?) assumed that any error (stderr) output from Tidy would be a program error and **not** output matching errors found with the source file. To me that seems... wrong. But I'm not a committer and I truly appreciate your efforts in maintaining the software. Thanks!
