### ISSUE TITLE
Tidy needs a changelog

### ISSUE THREAD

**Issue by petdance** [htacg/tidy-html5#776]
There is no documentation in the project that says what changes have been made in each version.  This is crucial for users to know if they should upgrade to a new version, and to know what behavior has changed because of an unexpected problem in an upgrade.

**Comment by geoffmcl** [comment]
@petdance we do add a [Release Notes 5.6](http://binaries.html-tidy.org/release_notes/5.6.0.html) for each release...

But that is just a **massage** of what is available from the git repo, by `$ git log -p`, for all to see, at any time...

At this time, `tidy` does **not** maintain a `changelog`, in the traditional sense...

If someone want to step up and say manually manage a **better** `changelog`, then look forward to ideas on that... thanks...

**Comment by bmix** [comment]
It may be sufficient for the developers to mark their contributions with 'i' for 'internal' and 'u' for 'user-facing', or something like that. This way the changelog could be automated: Only changes would be retrieved (not author and git interna) and only those, which have the 'u' flag set, would be printed to a user facing Release-History file, like change of command-line options, behavior, etc.

**Comment by balthisar** [comment]
I will begin to generate better changelogs with the 5.8 release, which is coming in the next few days. Closing this.

**Comment by petdance** [comment]
Let me know if there's some way I can help.  Thanks.
