### ISSUE TITLE
Redundant blank lines when printing -help

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [htacg/tidy-html5#781]
Refer the following screenshot:

![default](https://user-images.githubusercontent.com/13408130/49209398-539aef80-f3f5-11e8-99e9-26fe2e8e898f.png)

There are two redundant blank lines before the actual -help content (in 5.2.0 there was only one but now there are two), which is not pretty IMO.

I would suggest keep no blank lines at all or only one blank line, if there's any reason to do so.

**Comment by geoffmcl** [comment]
@Lin-Buo-Ren this is certainly your preference, but I wonder whether it is universal... maybe...

Wandering back in history, the original tidy creators certainly **liked** `redundant` blank lines... and I sort of got used to them, even liked them... over the years `some` have been eliminated in the `pretty print` output, but can sometimes be restored by `--vertical-space yes`, referred to as `classic` mode in the code, but not all... but maybe not at all relevant here...

You are just referring to `-h` text... 

Back at `5.2.0`, `5.4.0` there was only 1... and maybe more important, back in `tidy-2000` and `tidy-2009` there were none... 

So this does feel like `redundant` blank line **creep** in `help`... nothing to do with `classic` mode...

So, in general, could go for PR #782, a very limited change...

What do others think? Look forward to further feedback... thank...
