### ISSUE TITLE
NppTidy 5.6.0 quickref.html link broken - please fix

### ISSUE THREAD

**Issue by FredThompsonII** [htacg/tidy-html5#787]
Using Tidy2-2.0.5-vc140-mt-32b, Show Config Help links to https://w3c.github.io/tidy-html5/quickref.html and not a local copy of quickref.html. Would you please fix this link and state where quickref.html should be stored in the NPP folder?

---

With my Tidy2 [release](https://github.com/geoffmcl/NppTidy2/releases), the zip includes a `quickref.html` which can be copied to NPP install, and viewed with `Plugins -> Tidy2 -> Show Config Help`...

_Originally posted by @geoffmcl in https://github.com/htacg/tidy-html5/issues/558#issuecomment-305178385_

**Comment by geoffmcl** [comment]
@FredThompsonII well this is really a request for `NppTidy`, and **not** this `HTACG/tidy-html5`...

But to quickly answer you, while I have experimented with my own fork `NppTidy2`, I am not actively maintaining it... so there is unlikely to be any other releases from there... 

In any case that bad URL is only if `plugins\\doc\\Tidy2\\quickref.html` does not exist, so obviously that zip `quickref.html` needs to be copied to `[NPP_INSTALL_DIR\\]plugins\\doc\\Tidy2\` and then `Show Config Help` should load that local file... 

See the [code](https://github.com/geoffmcl/NppTidy2/blob/next/Tidy2/PluginMain.cpp#L396) ... I guess a **better** fallback URL would be something like `http://api.html-tidy.org/tidy/quickref_next.html`... but even that is not permanent...

So closing this here, as not relevant the HTML Tidy... thanks...
