### ISSUE TITLE
Uninstall & remove

### ISSUE THREAD

**Issue by almadsen** [htacg/tidy-html5#79]
How do I uninstall & remove all tracks of tidy form my system (OS X)?

I want to reinstall it with brew so that it doesn't give me warnings and issues when building other stuff, so I need to first remove all trace of the old install.

**Comment by aristidesfl** [comment]
+1

**Comment by aristidesfl** [comment]
@almadsen how do you install tidyhtml5 with homebrew?

**Comment by balthisar** [comment]
I will close due to age, and new `cmake` build system means that any fixes are no longer relevant. Sorry no one attended to this in a timely manner.

In general, though, the only traces should be the `tidy` command and `tidy.1` man page, plus whatever crud is left over in your build directory.
