### ISSUE TITLE
html conversion to xml leaves many tags unclosed

### ISSUE THREAD

**Issue by davidmichaelkarr** [htacg/tidy-html5#792]
I'm sure I'm doing something wrong, or have some misconception about this, but I'm trying to process html files in the JDK 1.8 javadoc tree with tidy, so I can run "xpath" on them.  So far, tidy is not fully converting them to valid XML. I'm using options "--html --xmlout".  Initially, I see that all the "meta" and "link" elements in the "head" elements are left unchanged.

**Comment by davidmichaelkarr** [comment]
I eventually found the "-axsml" option, and that appears to consistently work, so I think I'm ok for now.

**Comment by geoffmcl** [comment]
@davidmichaelkarr assuming you meant option `-asxml`, or `-asxhtml` - please take care...

That is `--output-xml yes`, or in a cfg file, `output-xml: yes`, and glad to hear you found the output **consistent**... from what ever **version** of tidy you are using...

Just searching around, and there may be other related issues, found open #767, but that is with `-ashtml`... still searching...

So maybe `-asxml` could also have problems... but would appreciate a **new** issue on this/these... 

Meantime closing this... thanks...
