### ISSUE TITLE
Tidy 5.7.20 crashes if allocator replaced

### ISSUE THREAD

**Issue by dd8** [htacg/tidy-html5#797]
attrs.c
DefinePriorityAttribute allocates priorities->list using TidyAlloc(), but re-allocates using realloc() instead of TidyRealloc(), which crashes if TidyAlloc didn't allocate memory via malloc

message.c 
DefineMutedMessage allocates list->list using TidyAlloc(), but re-allocates using realloc() instead of TidyRealloc(), which crashes if TidyAlloc didn't allocate memory via malloc

**Comment by geoffmcl** [comment]
@dd8 thanks for catching this `not very obvious` **bug**... but easy to see, when you know what to look for...

Given that `libTidy` has a memory [TidyAllocator](http://api.html-tidy.org/tidy/tidylib_api_next/group__Memory.html#struct__TidyAllocator), that users can set to what they want, `realloc()` should **not** be used in the **raw**, in those 2 cases...

```
F:\Projects\tidy-html5>find /N ">list" src\*.c
---------- SRC\ATTRS.C
[801]        priorities->list = realloc( priorities->list, sizeof(tmbstr) * priorities->capacity + 1 );
and
---------- SRC\MESSAGE.C
[1353]        list->list = realloc( list->list, sizeof(tidyStrings) * list->capacity + 1 );
```

Will try to include this easy fix somewhere... unless someone beats me to it, with say a `patch`, or `PR`... thanks...

**Comment by dd8** [comment]
I do have a patch which has been tested in production, so I can package that up and attach it to this issue

**Comment by dd8** [comment]
Here's the patch
[patch-realloc.diff.txt](https://github.com/htacg/tidy-html5/files/2807402/patch-realloc.diff.txt)

Compiles in XCode 10 clang on Mac, Visual Studio 2015 on Windows
Tested in production on macOS 10.13, macOS 10.14, Windows 7, Windows 10, Windows Server 2016

Not tested on Linux/gcc

**Comment by geoffmcl** [comment]
@dd8 now applied, version **5.7.22**... thanks...
