### ISSUE TITLE
Publishing in VS2015 - System.DllNotFoundException

### ISSUE THREAD

**Issue by recepogras** [htacg/tidy-html5#804]
Hello People,

i have an iossue i struggle with since days. I nearly tried everything i am able to try but had no success.

I use Tidy in a project to correct some corrupt html from an editor. The software is written in C#, .net 4.6.

I started with TidyHtml5ManagedRepack  and TidyHtml5Managed from nuget. Formerly i compiled 32bit. When i tried to change over to 64bit i was no more able to reinstall TidyHtml5ManagedRepack   from nuget. So i installed it manually (referencing).

On my development machine (Win7 with 64bit) everything is good when i compile 64bit or 32bit. 

TidyHtml5Managed.dll is in "References-folder" and added to References.
tidy.x86.dll and tidy.x64.dll are in the projects root folder and while release they got copied. 

THis works on my development machine AND on windows 7 client machines.

When i try to install it on windows 10 64 bit i get this error for x64 compilation:
System.DllNotFoundException: Die DLL "tidy.x64.dll": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.

The dll exists in the root folder. I also tried to copy it to windows-folder and other folder where it could be loaded from.

Does anyone have an idea or a suggested setup for this issue? I want use my software in 64bit with tidy.

Greetings from Germany.

**Comment by recepogras** [comment]
We discussed this here and found a solution:

https://stackoverflow.com/questions/54804066/dll-not-found-error-after-publishing-in-vs2015-tidy-x64-dll?noredirect=1#comment96385122_54804066

**Comment by geoffmcl** [comment]
@recepogras, note `nuget/TidyHTML5Managed...` is **not** directly related to this [site](http://www.html-tidy.org/)... 

While the `*.nupkg` package zip I [downloaded](https://www.nuget.org/packages/TidyHtml5ManagedRepack/), and explored, does contain a **renamed** `tidy.dll`, in 32 and 64 bit forms, which depend directly only on `KERNEL32.dll` and `MSVCR100.dll` is obviously built from the tidy source in this repo, not sure which version... interesting... but it is not maintained by anyone here, that I know of... and are **not** from our [binaries](http://binaries.html-tidy.org/)...

If you, or someone, has **published** a .NET tidy source, using the above `tidy.dll`, I may find the time to explore this framework more... 

But maybe you have found the solution...

Anyway, closing this here... thanks...
