### ISSUE TITLE
Installs library in /usr/local/lib/lib instead of /usr/local/lib

### ISSUE THREAD

**Issue by simonmeaden** [htacg/tidy-html5#807]
When I built the static and/or shared library on Linux the library was installed in the/usr/local/lib/lib directory. When cmake was run with the -DCMAKE_INSTALL_PREFIX=/usr/local it was installed correctly in /usr/local/lib.

HTML Tidy for Linux version 5.7.22
Fedora 29

**Comment by geoffmcl** [comment]
@simonmeaden sorry, can not seem to duplicate... just did a clean build in Ubuntu 18.04... cmake 3.10.2, and the `cmake_install.cmake` file generated shows it will use `"/usr/local"`, for the install...

What does your `cmake_install.cmake` show? 

Give your full build commands, script contents, etc... need more information, to try to repeat, understand... thanks...

**Comment by simonmeaden** [comment]
Weird I can't seem to repeat it either, this time it worked properly and placed stuff in /usr/local/lib. Sorry must have been something I did that has cleared.

Regards
Simon Meaden

**Comment by geoffmcl** [comment]
Ok, assume we can close this, at least until you can repeat, what could only be a `cmake` error, or something... thanks...
