### ISSUE TITLE
Option to always encode double ampersands

### ISSUE THREAD

**Issue by DaveJarvis** [htacg/tidy-html5#827]
**Replicate**
Create `test.html`:
``` html
<!DOCTYPE html>
<html>
<body>
Hello &amp;&amp; world!
</body>
</html>
```

Run:

    tidy -m -q --wrap 0 --tidy-mark no --vertical-space auto --doctype html5 test.html

**Expected Results**
``` html
<!DOCTYPE html><html><head><title></title></head><body>Hello &amp;&amp; world!</body></html>
```

**Actual Results**
``` html
<!DOCTYPE html><html><head><title></title></head><body>Hello &amp;& world!</body></html>
```

Note the ampersands.

**Discussion**

While this behaviour is correct for HTML5, it would be nice to have an option to always encode them.

**Comment by DaveJarvis** [comment]
Additionally:

```
<!DOCTYPE html>
<html>
<body>
Hello &amp; &amp; world!
</body>
</html>
```

Produces:

``` html
<!DOCTYPE html><html><head><title></title></head><body>Hello & & world!</body></html>
```

Instead of:

``` html
<!DOCTYPE html><html><head><title></title></head><body>Hello &amp; &amp; world!</body></html>
```

**Comment by DaveJarvis** [comment]
Additionally:

```
<!DOCTYPE html>
<html>
<body>
Hello &amp; &amp; world!
</body>
</html>
```

Produces:

``` html
<!DOCTYPE html><html><head><title></title></head><body>Hello & & world!</body></html>
```

Instead of:

``` html
<!DOCTYPE html><html><head><title></title></head><body>Hello &amp; &amp; world!</body></html>
```

**Comment by DaveJarvis** [comment]
Use `--doctype html5` and `--output-xml yes` to ensure ampersands are always encoded.

**Comment by geoffmcl** [comment]
@DaveJarvis thank you for the issue... which you seem to have closed?... with an `--output-xml yes` option... hmmmm...

I think this has nothing to do with `xml/xhtml` output... unless, that is what you want... but what about `html` output... what tidy does best...

The option you are looking for is [--preserve-entities](http://api.html-tidy.org/tidy/quickref_next.html#preserve-entities) **yes**! ... 

Where I hope you will get what you expect...

But this does **not** deal with the default **no**, for this option...

Where say `<p>Hello &amp;&amp; world!</p>`, is output as `<p>Hello &amp;& world!</p>`... UGH! sample [in_827.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_827.html)... default config...

While this is **not** spectacularly **wrong**, but not particularly **good** either... feels a bit like a not very important **bug**...

This maybe started when the W3C introduced the idea of an `ambiguous ampersand` in `HTML5` doc types... and the `libTidy` **fixes** to try to do this... see #207, and maybe others...

Maybe the output `<p>Hello &amp;& world!</p>` should, in fact, be `<p>Hello && world!</p>`?

Note, an option like `--doctype html5`, only effects the output, **not** the parsing of the input... 

Try adding `HTML4` doctype to your input, to see the difference... like say [in_827-1.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_827-1.html)...

Look forward to further feedback... patches, PR, .... thanks...

**Comment by DaveJarvis** [comment]
> Maybe the output `<p>Hello &amp;& world!</p>` should, in fact, be `<p>Hello && world!</p>`?

I believe this makes it ambiguous, or at least not compliant, as per (from #207):

> not followed by another U+0026 AMPERSAND (&) character

It's not a big issue; I'll give `--preserve-entities yes` a whirl, thank you.
