### ISSUE TITLE
Support EJS?

### ISSUE THREAD

**Issue by openbu-owner** [htacg/tidy-html5#842]
Support EJS?
Input:
` <img src="../public/images/default/Logos/Large/1/<%= Logo1 %>.png" width="60" height="60" alt=""/> `
Output:
`<img src="../public/images/default/Logos/Large/1/%3C%=%20Logo2%20%%3E.png" width="60" height="60" alt="">`

**Comment by geoffmcl** [comment]
@openbu-owner, thank you for the issue...

In our case, the first **support** must come from a W3C REC... 

In an initial tests, when I put such a `src` to the W3C validator, I get -

```
Error: Bad value ./<%= Logo1 %>.png for attribute src on element img: Illegal character in path segment: < is not allowed.
From line 9, column 1; to line 9, column 46
body><p><img src="./<%= Logo1 %>.png" alt="EJS #842"/></p>
```

So, closing this for now, but feel free to provide the required W3C REC that supports this...

It could be re-opened for discussion... consideration... etc.... thanks...
