### ISSUE TITLE
<input type="file"> needs name=

### ISSUE THREAD

**Issue by jidanni** [htacg/tidy-html5#845]
REC-html401-19991224 says:
> A successful control must be defined within a FORM element and must have a control name.

Alas, tidy 5.6 allowed me to forget that I needed a name= in
```
<input type="file" multiple>
```
causing it not to append the selected files in the browser. So at
least for type="file", do catch it when people forget a name=.

**Comment by geoffmcl** [comment]
@jidanni thank you for the issue...

Although the spec you gave, [REC-html401-19991224](https://www.w3.org/TR/1999/REC-html401-19991224/) is marked **This version is outdated!**, the follow on spec [html401](https://www.w3.org/TR/html401/) say the same thing about `Successful Controls`...

And given that `Tidy`, in general, aims to help the user produce valid html, **BUT** maybe this is too big of a **stretch**, to ask libtidy to check for `Successful Controls`, within a **FORM**...

In constructing both a legacy [4.01](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_845.html) document, and a [html5](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_845-1.html) document, for testing, both the legacy W3C validator, and `nu` validator do **not** appear to have such a validation check... for a `missing` name attribute... both docs **pass**... 

As they do with current tidy 5.7.28...

The question is - `should tidy do more in this case`?

So this seems to need much more discussion... thanks...

**Comment by geoffmcl** [comment]
2020/10/11
@jidanni no further feedback, no clear feature emerging... so closing this...

Please feel free to reopen, with comments, or open a **new** issue... thanks...
