### ISSUE TITLE
man page missing header causing appending to XML discussion

### ISSUE THREAD

**Issue by jidanni** [htacg/tidy-html5#846]
On tidy 5.6 man page, before
```
       Configuration options can be specified...
```
there is a missing header, causing this to still be part of the XML discussion.

**Comment by geoffmcl** [comment]
@jidanni thank you for the issue...

Yes, it certainly does appear, the `man tidy` page, even with the latest 5.7.28, by indentation alone, the the paragraph with `options can be specified` seems **joined** with the last subheading, namely `XML`... ugh!

After a bit a reading about `xsltproc` stylesheet syntax, (difficult to find)...

... reading the source docs, like how the man page is generated, from [CMakeLists.txt](https://github.com/htacg/tidy-html5/blob/next/CMakeLists.txt#L478)...

... particularly the last `call-template`, in the src  [tidy1.xsl.in](https://github.com/htacg/tidy-html5/blob/next/man/tidy1.xsl.in#L100)...

... showing how the `man page` is generated... through xml transformation... blah, blah, blah,,,

This led me to a simple sub-header addition, and a new line... so a **suggested** patch...

```diff
--- tidy1.org.xsl       2019-07-10 19:48:51.000000000 +0200
+++ tidy1.xsl   2019-11-27 16:21:53.000000000 +0100
@@ -98,6 +98,8 @@
 can be combined; for example '\fB-i\fR', '\fB-m\fR' and '\fB-u\fR'
 may be combined as '\fB-imu\fR'.<xsl:text/>
 <xsl:call-template name="show-cmdline-options" />
+.SS Configuration Options General
+.rs
 .LP
 \fIConfiguration\fR options can be specified
 by preceding each option with \fB--\fR at the command line,
```

But I am entirely **new** to this syntax, and maybe others, who know, understand more... can make the docs better...

Please step in with comments, patches, PR, etc... thanks...

**Comment by geoffmcl** [comment]
2020/10/11
@jidanni thank you for responding with an emoji... way back then... but...

But I need someone, preferably with `xsltproc` stylesheet syntax knowledge, to try the patch, maybe modify... correct... build... and report...

As stated, can someone please step up, with comments, tests, patches, PR, etc... so this issue can move forward... thanks...
