### ISSUE TITLE
<li> tags skipped in tidy result shown on screen

### ISSUE THREAD

**Issue by benThijssen** [htacg/tidy-html5#847]
When using "tidy -i page.txt" I don't see the &lt;li&gt; tags that are defined. Tidy creates an empty &lt;ol&gt; tag without any &lt;li&gt; tags embedded. 
File tidyResult is what tidy made out a the contents of file page.txt (both attached)
This is the first time I use tidy, but I don't see what I'm doing wrong. 

In page.txt the OL tag starts a column 102, there you can also see the LI tags, the first one starts at column 134. 

[tidyResult.txt](https://github.com/htacg/tidy-html5/files/3902497/tidyResult.txt)
[page.txt](https://github.com/htacg/tidy-html5/files/3902499/page.txt)

**Comment by ler762** [comment]
```
$ tidy -iq page.txt
   ...
line 1 column 134 - Warning: trimming empty <li>
line 1 column 198 - Warning: trimming empty <li>
line 1 column 925 - Warning: trimming empty <span>
line 1 column 1113 - Warning: trimming empty <span>
```

``tidy -iq --drop-empty-elements no page.txt`` if you want to keep empty elements like this
``<li data-target="#pietje" data-slide-to="1"></li>``

And you might like the ``-wrap`` option

**Comment by benThijssen** [comment]
Ier762 Thanks you very much for your prompt and helpful reply. This is exactly what I was looking for.  Bootstrap often uses empty tags, just to trigger javascript events on tag attributes only. And that -wrap option also helps a lot.  (FYI: I have a small javascript generator accepting some parameters to  create bootstrap source-code for carousel, accordion, panels, etc..., producing 1 long line of code. Tidy is very helpful to tidy up that long line in indented source code). Thanks you very much again.
