### ISSUE TITLE
Warning: unescaped & or unknown entity "&P" when encoding as utf-8

### ISSUE THREAD

**Issue by TZubiri** [htacg/tidy-html5#861]
sample document

```
<!DOCTYPE html>
<head>
    <meta charset="utf-8"/>
</head>
<body>
  <p>We use the S&P 500 index.</p>
</body>
```

This renders fine in browsers.

**Comment by geoffmcl** [comment]
@TZubiri thank you for the issue... 

As can be seen in issue #207, some work has already been done in this regard... some exceptions were added, if the document is html5... see commit 3a524f1...

The question is should the likes of `<p>the S&P 500 index</p>` also be excepted? 

And what about say `S&P500`? Where does it stop? 

What is the exact criteria? A full spec, a definition, ... 

How does this def. match with, say [ambiguous-ampersand](https://www.w3.org/TR/html50/syntax.html#syntax-ambiguous-ampersand) ... other W3C references...

That seems tough, to decide... but maybe... What do you and others think?

There is a **big** difference between just rendering, as in a browser - just display it as it is, if it is not a valid entity... all done...

And tidy, the html fixer, that finds a string commencing with `&`, invokes its `ParseEntity` service, to collect the string until `;`, or any other non-char, ie `!IsNamechar`, like a space, ` `, or a `<`, etc, tries to match lexer collection to a known entities, and **fails**...

Tidy has to make a choice, and report the problem, as best it can...

Look forward to further feedback, expanding the spec, ideas, patches, etc... thanks...

**Comment by TZubiri** [comment]
I see the conundrum here, the parser can't disambiguate between an escaped character and an intended ampersand. Browsers solve this issue with lots of magic, it's a classic tradeoff between complexity in the interface or the implementation.

It's great to see that "S & P 500" doesn't issue a warning!
I've been experimenting with some implementations and reading the standards, it looks like this section is relevant.
https://html.spec.whatwg.org/multipage/parsing.html#tokenization

The section on [parse errors](https://html.spec.whatwg.org/multipage/parsing.html#parse-errors) includes a list of ambiguous situations that tidy could use to selectively warn about unescaped ampersands. I don't know if this warning should dissapear, it's a hard question, but there's undeniable value in implementing all of these parse errors and issuing a different informative warning for each.

We could keep this warning until all parse errors are implemented, to get the boll ralling, I opened an [issue](https://github.com/htacg/tidy-html5/issues/862) on [the standarized missing-semicolon-after-character-reference error](https://html.spec.whatwg.org/multipage/parsing.html#parse-error-missing-semicolon-after-character-reference). It seems the warning was already implemented, but it doesn't behave exactly as the chromium and firefox implementations.

Regarding ambiguous ampersand, the procedure should be the same as with a missing semicolon, issue a specific warning, so in the future, if we decide to remove the generic warning. This edge case still issues a warning.

**Comment by geoffmcl** [comment]
20210411: Review...

@TZubiri, thank you for the further feedback... but it is still unclear exactly what you think `tidy` should do, in what circumstance(s), etc... and no further feedback in over 6 months... so closing this, for now...

As stated, look forward to further feedback, expanding the spec, ideas, patches, etc... thanks...
