### ISSUE TITLE
http-equiv metas should trigger helpful upgrade messages

### ISSUE THREAD

**Issue by jidanni** [htacg/tidy-html5#868]
When encountering
```
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
```
print
```
 'These days one can just write <meta charset="utf-8">'
```
In fact tidy already prints
```
  line 8 column 2 - Warning: discarding unexpected <meta>
```
about the latter, if it finds both.

Also when encountering
```
 <meta http-equiv="Content-Language" content="zh-tw">
```
print
```
 'These days one can just write ...' etc.
```

**Comment by geoffmcl** [comment]
@jidanni, hmmm, this has the whiff of an **undefined** `feature request`... 

But when, where, what, and why, need to be clearly spelled out, specified, detailed, discussed, ...

Meantime closing this as too sketchy...  

At a minimum, please provide feedback, input samples, config used, current output, and, more important, full `expected` output... to re-open... or open new issue(s)...

Look forward to further feedback, patches, or PR... thanks...

**Comment by jidanni** [comment]
(To create samples just place the above meta lines into a HTML page.

The proposed output is like I gave except you can make it more formal sounding.)

**Comment by geoffmcl** [comment]
@jidanni, your reply does not add anything...

> To create samples just ...

If you have no interest in doing that, giving complete samples, that can be run through the W3C validator, and Tidy, who do you expect to do it for you?

> The proposed output is like I gave ...

But what you **gave** is just not `TRUE`, in all cases, and the second case is `INCOMPLETE` anyway...

That is supply the `when`, `what`, `why`? And pointer to W3C RECS can help... 

Yes I can `assume` this or that, but you, the proposer must make it clear, and not expect others to fill it out, by their guessing...

> about the latter, if it finds both

Yes, but with experimentation I find Tidy discards the second in all cases. That does not seem right, in all cases...

So you have provided nothing **new**! No fleshed out, more complete, proposal, so this remains **CLOSED**... thanks...
