### ISSUE TITLE
Even with -utf8 tidy replaces UTF8 code U+00A0 into numeric entity &#160;

### ISSUE THREAD

**Issue by mcepl** [htacg/tidy-html5#871]
When running ``tidy -i -m -xml -utf8`` to canonicalize XML file I get this diff (among many other things):
```diff
@@ -15389,7 +15389,7 @@ xsi:schemaLocation="http://www.bibletechnologies.net/2003/OSIS/namespace z:/osis
             <verse sID="Lev.11.13" osisID="Lev.11.13" />Toto jsou
             ptáci, jichž se budete štítit. Nesmějí se jíst, jsou
             ohavní: 
-            <note>některé živočišné druhy v následujících
+            <note>některé živočišné druhy v&#160;následujících
             výčtech nelze určit s jistotou</note>orel, orlosup,
             mořský orel, 
             <verse eID="Lev.11.13" />
```
The character after the preposition “v” is the non-breakable space (U+00A0). When I say ``-utf8`` it means in my opinion that both input and output documents are in UTF8 and tidy should keep its dirty paws from changing characters, and *especially* it shouldn’t convert perfect UTF8 characters into numeric entities.

I am using ``tidy-5.6.0-1.7.x86_64`` from the openSUSE package.

**Comment by ler762** [comment]
On 3/14/20, Matěj Cepl <notifications@github.com> wrote:
> When running ``tidy -i -m -xml -utf8`` to canonicalize XML file

try it with the '--quote-nbsp no' option

> The character after the preposition “v” is the non-breakable space (U+00A0).

> When I say ``-utf8`` it means in my opinion that both input and output
> documents are in UTF8 and tidy should keep its dirty paws from changing
> characters, and *especially* it shouldn’t convert perfect UTF8 characters
> into numeric entities.

man tidy
    ...
  --quote-nbsp Boolean (yes if unset)
      This option specifies if Tidy should output non-breaking space characters
      as entities, rather than as the Unicode character value 160 (decimal).

**Comment by mcepl** [comment]
Hmm, so I added ``quote-nbsp`` to my ``~/.tidyrc`` and the result is not persuasive either (and I still hold, that ``quote-nbsp: no`` should be default when ``-utf8`` is in use):
```
~@stitny$ unset HTML_TIDY
~@stitny$ tidy -xml ~/projekty/CzeB21/CzeB21.xml 
Loading config file "~/.tidyrc" failed, err = 1
~@stitny$ strace tidy -xml CzeB21.xml |&grep -C 5 '/home/matej/.tidyrc'
openat(AT_FDCWD, "/usr/lib/locale/cs_CZ.utf8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=340640, ...}) = 0
mmap(NULL, 340640, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f63b18de000
close(3)                                = 0
access("/etc/tidy.conf", F_OK)          = -1 ENOENT (Adresář nebo soubor neexistuje)
access("/home/matej/.tidyrc", F_OK)     = 0
openat(AT_FDCWD, "/home/matej/.tidyrc", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=420, ...}) = 0
mmap(NULL, 420, PROT_READ, MAP_SHARED, 3, 0) = 0x7f63b1e91000
close(3)                                = 0
munmap(0x7f63b1e91000, 420)             = 0
write(2, "Loading config file \"~/.tidyrc\" "..., 47Loading config file "~/.tidyrc" failed, err = 1) = 47
~@stitny$ ls -l ~/.tidyrc
lrwxrwxrwx 1 matej users 23 Mar 14 20:02 /home/matej/.tidyrc -> .config/dotfiles/tidyrc
~@stitny$ ls -l ~/.config/dotfiles/tidyrc
-rw-r--r-- 1 matej users 420 Mar 14 20:02 /home/matej/.config/dotfiles/tidyrc
~@stitny$
```
I don’t see any reason, why tidy shouldn’t read [its config file](https://github.com/htacg/tidy-html5/files/4333228/tidyrc.txt).

**Comment by ler762** [comment]
> Hmm, so I added ``quote-nbsp`` to my ``~/.tidyrc`` and the result is not
> persuasive either (and I still hold, that ``quote-nbsp: no`` should be
> default when ``-utf8`` is in use)

^shrug^ I still hold there should be a command line option to tell
tidy to not read any init files.  But like the old song..  "you can't
always get what you want"

> ~@stitny$ unset HTML_TIDY
> ~@stitny$ tidy -xml ~/projekty/CzeB21/CzeB21.xml
> Loading config file "~/.tidyrc" failed, err = 1

It took me a while to get everything installed to build tidy on linux,
and.. it works for me.  Maybe because you didn't use fully qualified
filenames on the ln command?

> ~@stitny$ ls -l ~/.tidyrc
> lrwxrwxrwx 1 matej users 23 Mar 14 20:02 /home/matej/.tidyrc ->
> .config/dotfiles/tidyrc

does 'cd /tmp; cat ~/.tidyrc' work for you?

$ ls -l ~/.tidyrc
lrwxrwxrwx 1 lee lee 33 Mar 14 18:21 /home/lee/.tidyrc ->
/home/lee/.config/dotfiles/tidyrc

$ cat ~/.tidyrc
indent: yes
quote-nbsp: no
tidy-mark: no
wrap: 120

$ tidy -show-config | grep 'wrap '
punctuation-wrap            Boolean    no
wrap                        Integer    120

**Comment by mcepl** [comment]
> ^shrug^ I still hold there should be a command line option to tell tidy to not read any init files. But like the old song.. "you can't always get what you want"

Wouldn’t ``export HTML_TIDY=/dev/null`` work as well?

> does 'cd /tmp; cat ~/.tidyrc' work for you?
```
~@stitny$ cd /tmp/
tmp@stitny$ cat ~/.tidyrc
char-encoding: utf8
quote-ampersand: yes
break-before-br: no
drop-empty-paras: yes
drop-proprietary-attributes:yes
show-warnings:no
// sort-attributes:alpha
// drop-font-tags: yes
join-classes:yes
replace-color:yes
write-back: yes
quiet: yes
markup: yes
indent: yes
logical-emphasis: yes
hide-endtags: no
clean: yes
xml: yes
tidy-mark: no
quote-nbsp: no
doctype: html5
word-2000: yes
output-xhtml: yes
tmp@stitny$
```
The following command got frozen and I had to finish it with ``Ctrl-C``.
```
tmp@stitny$ tidy --show-config |grep wrap
Loading config file "~/.tidyrc" failed, err = 1
^C
tmp@stitny$
```

**Comment by ler762** [comment]
>> ^shrug^ I still hold there should be a command line option to tell tidy to
>> not read any init files. But like the old song.. "you can't always get
>> what you want"

> Wouldn’t ``export HTML_TIDY=/dev/null`` work as well?

hrmm... maybe?  I'll give it a try.


>> does 'cd /tmp; cat ~/.tidyrc' work for you?

> ~@stitny$ cd /tmp/
> tmp@stitny$ cat ~/.tidyrc
> char-encoding: utf8
   <.. snip ..>

oh well.. so much for that theory

> The following command got frozen and I had to finish it with ``Ctrl-C``.

> tmp@stitny$ tidy --show-config |grep wrap
> Loading config file "~/.tidyrc" failed, err = 1
> ^C

That's different.  I get an error message since show-config needs a
single dash and then it hangs

$ tidy --show-config | grep 'wrap '
Config: unknown option: show-config
^C

What's your OS and tidy version?

$ uname -a
Linux izzy 4.9.0-12-686-pae #1 SMP Debian 4.9.210-1 (2020-01-20) i686 GNU/Linux

$ tidy -version
HTML Tidy for Linux/x86 version 5.7.28.next.2020.03.14
  (in other words, whatever came from
https://github.com/htacg/tidy-html5.git on Mar 14)

**Comment by mcepl** [comment]
> The following command got frozen and I had to finish it with ``Ctrl-C``. ***@***.***$ tidy --show-config |grep wrap Loading config file "~/.tidyrc" failed, err = 1 ^C

The problem was with that double dash, without that tidy works as shown in the updated comment.

**Comment by geoffmcl** [comment]
@mcepl, @ler762 have re-read all this... are there any outstanding issue(s) here?

And @ler762, adding an option to stop reading environmental, or configured, config files, has been considered, and discussed, at length, with you, IIRC, and it was **rejected**... sorry for that... tidy has an easy to understand config file policy, which conforms to many Unix apps... in no need of a change, that I can see...

But is everything else ok, here? Can this be **CLOSED**... thanks...
