### ISSUE TITLE
Convert spaces to non-breaking space

### ISSUE THREAD

**Issue by petko** [htacg/tidy-html5#875]
Is there a way to configure tidy-html5 to convert single spaces to `&nbsp;`? Or at least to point me in an area that I need to change in the code in order to add such an option?

**Comment by geoffmcl** [comment]
@petko I do not think Tidy has an option "to convert single spaces to `&nbsp;`", but why would you want to do that?

And I guess our [OPTIONS.md](https://github.com/htacg/tidy-html5/blob/next/README/OPTIONS.md) should point you in the right code directions...

But while this has a whiff of a `feature request`, you need to add sample html code, and definitively define the `use` case...

Need some feedback, discussion, patches, PR, to move this issue forward... thanks...
