### ISSUE TITLE
Versioning seems a bit off

### ISSUE THREAD

**Issue by noloader** [htacg/tidy-html5#877]
Hi Everyone.

I build HTML Tidy from sources. I performed a `git clone` a couple of years ago. Then on occasion, I perform a `git checkout master -f && git pull` to update the software, rebuild and reinstall to get the latest version of the software.

I performed the update/rebuild/reinstall cycle recently. It looks like version numbers went backwards after tidy'ing up my web pages:

```
$ git diff 7a39d7d..2cb78ca
diff --git a/website/404.html b/website/404.html
index 0cae35f..a560c2f 100644
--- a/website/404.html
+++ b/website/404.html
@@ -2,8 +2,7 @@
 "http://www.w3.org/TR/html4/loose.dtd">
 <html>
 <head>
-  <meta name="generator" content=
-  "HTML Tidy for HTML5 for Linux version 5.7.28">
+  <meta name="generator" content="HTML Tidy for HTML5 for Linux version 5.6.0">^M
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
   <title>Callboot Client Error</title>
   <meta name="description" content=
[...15 additional pages with same change...]
```

Something looks off with the version numbers. I went from version 5.7.28 to version 5.6.0 using the same sources I always have.

I think the relative build dates and versions are/were:

* Build sometime around October or December 2019, version 5.7.28
* Build May 1, 2020, version 5.6.0

I'm using the expected copy of the program in `/usr/local`.

```
$ command -v tidy
/usr/local/bin/tidy
$ tidy --version
HTML Tidy for Linux version 5.6.0
```

Here's my `.git/config`. It is still tracking  htacg/tidy-html5. As far as I know, nothing has changed.

```
$ cat .git/config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/htacg/tidy-html5
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "next"]
        remote = origin
        merge = refs/heads/next
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

I don't have enough history in Bash to look back further in time.

**Comment by ler762** [comment]
You're using the wrong branch?

```
$ git checkout master
Branch 'master' set up to track remote branch 'master' from 'origin'.
Switched to a new branch 'master'

$ cat version.txt
5.6.0
2017.11.25

$ git checkout next
Switched to branch 'next'
Your branch is up to date with 'origin/next'.

$ cat version.txt
5.7.28
2019.07.08
```

**Comment by geoffmcl** [comment]
@noloader, seems answered, by @ler762 ... thanks...

So am closing this...
