### ISSUE TITLE
<img> proprietary attribute "loading"

### ISSUE THREAD

**Issue by JoyceBabu** [htacg/tidy-html5#879]
Native lazyloading is now accepted as part of the HTML standard.

Please support it in tidy.

Is it possible to suppress these warning until it is added to tidy? Maybe create a custom DTD for tidy to validate against?

**Comment by geoffmcl** [comment]
@JoyceBabu, I presume you are talking about `<img loading="lazy" src="...">`... if not please explain...

And it would be nice to add a small sample...

> Native lazyloading is now accepted as part of the HTML standard.

Says who? Need some W3C references for this, links, etc... it is **not** just about browser support...

> Is it possible to suppress these warning until ...

No. Supported attributes of each HTML tag is hard-coded into libTidy... see src `const AttrVersion TY_(W3CAttrsFor_IMG)[] = `... would need to add something like a `TidyAttr_LOADING`... etc...
 
Given that you can find the W3C spec, when this would be considered a `feature request`...

Look forward to feedback, discussion, links, samples, patches, PR, etc... thanks...

**Comment by sidvishnoi** [comment]
Hi! Do these help in furthering the discussion?
https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-loading
https://html.spec.whatwg.org/multipage/iframe-embed-object.html#dom-iframe-loading
https://html.spec.whatwg.org/multipage/urls-and-fetching.html#lazy-loading-attributes

**Comment by JoyceBabu** [comment]
> @JoyceBabu, I presume you are talking about `<img loading="lazy" src="...">`... if not please explain...
> 
> And it would be nice to add a small sample...

Yes, `loading="lazy"` is what I meant. Sorry for not being explicit.

> 
> > Native lazyloading is now accepted as part of the HTML standard.
> 
> Says who? Need some W3C references for this, links, etc... it is **not** just about browser support...

Native lazy loading was merged into WHATWG/html on `February 12`

https://github.com/whatwg/html/pull/3752#issuecomment-585202516

> 
> > Is it possible to suppress these warning until ...
> 
> No. Supported attributes of each HTML tag is hard-coded into libTidy... see src `const AttrVersion TY_(W3CAttrsFor_IMG)[] = `... would need to add something like a `TidyAttr_LOADING`... etc...
> 
> Given that you can find the W3C spec, when this would be considered a `feature request`...

It was merged into WHATWG spec, not W3C spec. Is that not acceptable for HTACG?

> Look forward to feedback, discussion, links, samples, patches, PR, etc... thanks...

**Comment by geoffmcl** [comment]
@sidvishnoi, thank you for the `WHATWG` links...

@JoyceBabu, yes, I do think at this time `WHATWG` **is** acceptable to `HTACG`... you can read around about the agreements between the `WHATWG` and `W3C`, and it is interesting to note that they **share** the same `validator` - https://whatwg.org/validator/ directly links to https://validator.w3.org/nu/ ...

Accordingly, marking this as a `Feature Request`... thanks...

Look forward to samples, patches, PR, etc, to implement this... thanks...

**Comment by sidvishnoi** [comment]
Also, https://www.w3.org/TR/html/ (which is the latest version as per https://www.w3.org/TR/html52/) redirects to the WHATWG spec.
