### ISSUE TITLE
Use with TextPad 8

### ISSUE THREAD

**Issue by Wayne-Ca** [htacg/tidy-html5#882]
I grabbed the original Tidy off of the TextPad site as usable with TextPad as an external tool. I set it up the way the instructions described and ran it on a html 4.01 document. It reported strange results, so I checked the docs. It was last updated in 2000. I searched for a newer version and found this one. I downloaded 5.6.0 and put that in. There were no docs on what to set the settings in TextPad to, so I used the ones from the old version. I got no results at all when I ran it on the same document. I need to know:

a) does it still work as a tool with TextPad
b) if so, what are the parameters I need to set in the TextPad Tool configuration to use it

**Comment by balthisar** [comment]
We have nothing to do with TextPad. You'll have to go ask them for support.
