### ISSUE TITLE
html-tidy site does not work with https

### ISSUE THREAD

**Issue by sgbeal** [htacg/tidy-html5#883]
The site:

http://www.html-tidy.org/

does not work when loaded with an HTTPS schema because it loads it resources explicitly over HTTP, and some browsers do not like switching from secure to insecure connections when loading resources.

The fix is to change all  of the explicit "http://" resource-loading URLs to "//" (removing the http: prefix), which will allow it to work with both http and https.

**Comment by JustAGuyTryingToCodeSomething** [comment]
**I think this bug should be registered against the website project at https://github.com/htacg/html-tidy.org; **

A note to confirm this. Browsing to https://www.html-tidy.org/ fails to display the styles in Chrome. 

Inspecting [tools window] the website shows base.css, sites.css the google fonts, and site.js are all being called over HTTP. It looks like Google is blocking these.

**Comment by sgbeal** [comment]
They're only blocked because of the change in protocol from https to http. i have moved this over to the forum you linked to - i wasn't aware there was a separate repo for that.
