### ISSUE TITLE
how to forbid auto insert tag?

### ISSUE THREAD

**Issue by DieYoungWsn** [htacg/tidy-html5#889]
`
line 115 column 1 - Warning: missing </em> before <ul>

line 116 column 5 - Warning: inserting implicit \<em\>

line 117 column 29 - Warning: inserting implicit \<em\>

line 118 column 5 - Warning: inserting implicit \<em\>

line 126 column 38 - Warning: inserting implicit \<em\>

line 129 column 33 - Warning: inserting implicit \<em\>

line 132 column 1 - Warning: inserting implicit \<em\>
`

how to forbid ?

**Comment by geoffmcl** [comment]
@DieYoungWsn, Tidy is **fixing** your HTML code... you can not tell tidy to **forget it**...

If you gave some sample code, and your config used, could maybe give a better answer...

Look forward to further feedback... thanks...
