### ISSUE TITLE
Help output refers to a non-existent -options option

### ISSUE THREAD

**Issue by dkearns** [htacg/tidy-html5#892]
G'day all,

Under the "Tidy Configuration Options" section of the `tidy -help` output there is a reference to `-options` rather than the correct `-config` option.

```
$ tidy --version
HTML Tidy for Linux version 5.7.28
```

Thanks,
Doug

**Comment by geoffmcl** [comment]
@dkearns , as you can see in #876, a patch is in the works... thanks for pointing this out...

**Comment by geoffmcl** [comment]
@dkearns doc fix now merged... thanks...
