### ISSUE TITLE
Say how to deal with XHTML input

### ISSUE THREAD

**Issue by jidanni** [htacg/tidy-html5#893]
The man page talks about how to specify
- xml and html input
- xml and xhtml and html output

So it also should mention
"For XHTML input, just use -xml"
somewhere on it.

**Comment by geoffmcl** [comment]
@jidanni given that our docs probably can always do with improvement... maybe this `thought` has merit... but...

But this does not rise to the level of being an issue... so closing it... sorry...

You suggest `-xml`, or `--input-xml yes`, will give xhtml input! That does **not** seem right... 

To me `[x]html` is the default... unless you choose `xml`... can someone help on this...

For **where**, you suggest `somewhere`! Huh? Find a place, at least for discussion...

Look forward to your further feedback, comment, patches, PR, etc... maybe there is an issue here... thanks...
