### ISSUE TITLE
tidy-mark option is not working

### ISSUE THREAD

**Issue by iio7** [htacg/tidy-html5#901]
I'm using tidy for Linux version 5.7.16. The `tidy-mark` option is not working. Using:

```
$ tidy --tidy-mark no foo.html
```

Still leaves the generator meta tag:

```
<meta name="generator" content="HTML Tidy for HTML5 for Linux version 5.7.16">
```

**Comment by geoffmcl** [comment]
@iio7 thank you for the issue, but seem **unable** to repeat the problem... tested with `tidy5-5.7.16`, circa 2018/05/03, and `next`...

Tidy can **not** ignore the `--tidy-mark no` option! See [code](https://github.com/htacg/tidy-html5/blob/next/src/tidylib.c#L2134) ... 

If the option is **on**, no `TY_(AddGenerator)(doc);` is done...

Are you sure this option is **not** in one of the config files tidy may use, like through env, `HTML_TIDY`, or the other `config file` options...

And note, tidy will **not** remove any such meta from the input source...

Am I missing something here? You will need to explain more... thanks...

**Comment by iio7** [comment]
Sorry for the delay in my response. I'm sorry, but I can no longer reproduce the error myself.

I don't know exactly what happened, but I can only guess that I must have managed to use tidy the first time without the `--tidy-mark no` option, resulting in all HTML files getting the generator tag inserted without me noticing. Later when I was testing output I used the `--tidy-mark no`. option, but must have been dealing with files that already had the tag inserted.
