### ISSUE TITLE
</select> ending tag missing

### ISSUE THREAD

**Issue by BearOpenSource** [htacg/tidy-html5#904]
if <select> starting tag is missing the</select> ending tag, tidy could not add </select>ending tag.
example:
`<table>
	<select style="width: 64px; height: 24px; border: 1px solid #ddd;" id="year_box" onchange="changeDate();">
		</table>																
`

**Comment by geoffmcl** [comment]
@BearOpenSource thank you for the issue, but unfortunately can **NOT** repeat the problem you suggest...

First, in the sample code you give, you put `<select>` as a child of `<table>`, which is not valid, but if you add a `<tr><td>`, where it is valid, then tidy will still have problems, but will for sure output `Warning: missing </select>`, and add it, to the output...

You do not mention the version of tidy you are using, but I am not sure it matters. As far as I know **ALL** versions of `tidy` will definitely supply the **select** `close` tag, if missing...

Please check again, give further feedback, more examples, etc... or close this... thanks...

**Comment by geoffmcl** [comment]
@BearOpenSource, reviewed, and as stated, unable to **repeat the problem**!

Please supply further information, feedback, more sample html, sample configs, tidy version, etc, etc... thanks...

Meantime closing this... thanks...
