### ISSUE TITLE
tidy hanging

### ISSUE THREAD

**Issue by namedgraph** [htacg/tidy-html5#935]
Why does `tidy` keep hanging after it has produced output? Using a simple `tidy "${id}.html" -asxhtml -utf8` command but cannot script it properly as `tidy` does not exit.

Platform: Ubuntu 18.04 (Windows Subsystem for Linux 2)

**Comment by namedgraph** [comment]
OK, I guess I should reorder the options/filenames :)

**Comment by geoffmcl** [comment]
@namedgraph, yup ;=))

Tidy is **$ tidy [options] file1.html [[options] file2.html ...]** - very __strict__ order...

Glad you caught it ;=))
