### ISSUE TITLE
Lot of config options; but where are the defaults specified

### ISSUE THREAD

**Issue by jpwynn** [htacg/tidy-html5#948]
IMO when you run `tidy -help-config` it ought to indicate not just all the settings, but which of the values is default?

Eg

```
xxxxxxx     Boolean      no, [yes]
```

Or similarly in the docs, where it presents a sample config file, how about one with all the options set to their default?

**Comment by balthisar** [comment]
Which version are you on?

```
./tidy -export-default-config
```

Works for me. Version 5.7.x in the **next** branch.

**Comment by jpwynn** [comment]
Yes, thank you, `tidy -export-default-config` works on this version 5.6.0 for MacOS (from homebrew), I simply missed it since, AFAIK it is discussed nowhere in the how-to documentation, only on the `-h` screen under "miscellaneous".

Specifically, it seems `-export-default-config` probably ought to be mentioned on https://www.html-tidy.org/documentation/ in the section "Tidy Options and Configuration" right after it discusses `tidy -help-config`, especially since the next section discusses how to use a config file.

So guess this ticket ought to be tagged Documentation request?

**Comment by balthisar** [comment]
Not a bad idea. Time crunch right now, but it'd be really, really easy to merge a PR, if you want to have a look here:

https://github.com/htacg/html-tidy.org/tree/gh-pages/documentation/_posts

**Comment by jpwynn** [comment]
If I can make time to figure out the github PR process - something I ought to grok anyway - I will take a whack at adding the 2 sentences.

**Comment by balthisar** [comment]
Fix added. Thanks.
