### ISSUE TITLE
No NPM?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [htacg/tidy-html5#960]
This is useful to add project dependencies to package.json

**Comment by balthisar** [comment]
This is a C project, not Javascript. Beyond that, please don't assume that maintainers of a project not at all related to Node have any  idea what you're talking  about with the very few words that you offered.

**Comment by vitaly-zdanevich** [comment]
I mean that we cannot install it through NPM.

**Comment by balthisar** [comment]
Why would you be able to install it through NPM? This isn't a Javascript module, but a terminal CLI command and C library.

**Comment by vitaly-zdanevich** [comment]
Through NPM you can install many related CLI apps. Right now I found [js-beautify](https://www.npmjs.com/package/js-beautify) - CLI for formatting HTML.

**Comment by balthisar** [comment]
That's a Javascript application. Javascript is a scripting language. It runs everywhere there's a Javascript scripting language interpreter. Tidy is a C library and program. It requires a C compiler, which generates microprocessor-specific machine language, and links dynamically into the operating system where it's running, making it both processor- and os-dependant.

Tidy is available via package managers for operating systems which can deliver either the correct binary, or provide the correct toolchain to compile and link on the target environment. Consider homebrew, apt, or equivalent package manager for your particular operating system.

Other projects are free to write wrappers for native code. If this is something that you'd like to tackle for npm, please feel free, if npm is capable of working with native binaries and supporting clang/gcc toolchains. Consider looking at other projects that use native binaries in Javascript, such as OpenSSL, libpng, etc., if you need inspiration.

**Comment by vitaly-zdanevich** [comment]
I am not about C library, I am about your compiled CLI. This is popular that frontend projects has `package.json` file with dependencies for developers and runtime dependencies. And because `tidy-html5` is not on NPM I included another CLI app that format our HTML.

> It requires a C compiler, which generates microprocessor-specific machine language, and links dynamically into the operating system where it's running, making it both processor- and os-dependant

But I believe that you can compile to generic x64.
