### ISSUE TITLE
Public symbol with prvTidy prefix in tidy 5.8.0

### ISSUE THREAD

**Issue by hosiet** [htacg/tidy-html5#968]
With the released 5.8.0 version, the following symbol is publicly exposed to the user but contains the `prvTidy` prefix:

`prvTidyAdjustConfig@Base`

Looks like it was introduced by #959 . @balthisar was it intentionally introduced or by accident?

**Comment by balthisar** [comment]
Nope, that was by accident. All of @geoffmcl's work to fix the visibility preceded this fix, and it was missed when I merged #959.

Because I release it and bumped the SONAME, I think we're stuck with it until 5.10.

**Comment by balthisar** [comment]
I've fixed it for this branch, and despite the commit message, I think I will NOT replicate it in master (5.8), as that would break the API and require an SO version bump. I'm confident that nothing has rolled out to package managers yet, but this is the safe approach.

If someone wants to use that private symbol in the meantime, then let them have at it. ;-)

**Comment by hosiet** [comment]
Thanks, I believe this should be OK.
