### ISSUE TITLE
Codespell report for "HTML Tidy" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [htacg/tidy-html5#973]
The FOSS server [fossies.org](https://fossies.org) - supporting also the [HTML Tidy](https://fossies.org/tidy-html5) project - offers among others a feature named "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies administrator I have just created for testing purposes such a [codespell](https://github.com/codespell-project/codespell) based analysis for the new "HTML Tidy" release 5.8.0:

&nbsp;https://fossies.org/linux/www/tidy-html5/codespell.html

That version-independent URL should redirect always to the last report (if available), so currently to
https://fossies.org/linux/www/tidy-html5-5.8.0.tar.gz/codespell.html.

By the way, the context type of the spelling errors and typos are marked by a single character (within the sortable column "T"): The less interesting, probably not user visible ones (in "comments") are greyed, while the probably more interesting ones are black-colored. If JavaScript is enabled all table columns are sortable.

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can force a new improved check if applicable.

Just for information there are also three supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/www/tidy-html5/codespell_conf.html), all obvious [false positives](https://fossies.org/linux/www/tidy-html5/codespell_fps.html) and an [misspelling history](https://fossies.org/linux/www/tidy-html5/codespell_hist.html) (log).

By the way, using `tidy` itself I found at the end of the output a typo (`"\tttp://validator.w3.org/nu/\n"` instead of `"\thttp://validator.w3.org/nu/\n"` ) that is located in the both German translation files [src/language_de.h](https://github.com/htacg/tidy-html5/blob/next/src/language_de.h#L2008) and [localize/translations/language_de.po](https://github.com/htacg/tidy-html5/blob/next/localize/translations/language_de.po#L2690).

And generally some of the used HTTP links may be better replaced by HTTPS variants, e.g.
```
http://validator.w3.org/nu/               -> https://validator.w3.org/nu/
http://dev.w3.org/html5/spec-author-view/ -> https://html.spec.whatwg.org/multipage/
http://www.w3.org/Consortium              -> https://www.w3.org/Consortium/
```
Perhaps more meaningful may be a similar and continuously updated codespell report for the "HTML Tidy" GitHub "next" version which could be generated on request within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines.

Although the correction of misspellings and typos has probably not a top priority, I hope that the report can nevertheless be a little bit useful.

**Comment by balthisar** [comment]
@jschleus, thanks for the report. I think I fixed most of them, and it was a good opportunity to move to HTTPS where appropriate.

Feel free submit more of these in the future! Note, you may want to exclude `regression_testing` and `localize`; we won't update the regression tests, and fixes to `localize` will be applied automatically if the corresponding header in `src` is updated.

Again, thanks!

**Comment by jschleus** [comment]
Thanks for the information, just for completeness I have forced a new run with the updated configuration.

Although not directly required I have nevertheless animated by the positive feedback  set up the above mentioned "continuously" codespell testing for the "HTML Tidy" GitHub "next" version:

&nbsp; https://fossies.org/linux/test/tidy-html5-next.tar.gz/codespell.html

That version independent URL hopefully always redirects to the report for the latest "next" version identified by the short GitHub commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The data are residing within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines. The report should be available at least for some weeks and is continuously updated (currently with a half-hourly refresh rate).
By the way, even a mail notification is possible if new misspellings are found but that may be too annoying and probably it's difficult to find an appropriate mail address.

Great, from the codespell point of view it looks almost perfect now. The remaining two typos are in the file `  README/CHANGELOG.md` that may be not editable and are caused by typos in the issue title text. So I will exclude that file shortly.
