### ISSUE TITLE
homebrew install issue

### ISSUE THREAD

**Issue by mainpal1** [htacg/tidy-html5#974]
When I run `brew install tidy-html5` it gives me following error:

```
==> Downloading https://github.com/htacg/tidy-html5/archive/5.8.0.tar.gz
==> Downloading from https://codeload.github.com/htacg/tidy-html5/tar.gz/5.8.0
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 2fc78c4369cde9a80f4ae3961880bd003ac31e8b160f6b9422645bab3be5a6cf
  Actual: 59c86d5b2e452f63c5cdb29c866a12a4c55b1741d7025cf2f3ce0cde99b0660e
    File: /Users/mainpal/Library/Caches/Homebrew/downloads/fcb8f1c75881571d4be82fdb5998114428157f7ab3b3188d8380d100f9e474fb--tidy-html5-5.8.0.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by balthisar** [comment]
It looks like @SMillerDev it maintaining the Homebrew package. Hopefully that mention pings him in.

**Comment by SMillerDev** [comment]
Homebrew packages don't have specific maintainers, but this looks like the code was retagged. If that was intentional and not a sign of a compromised repository you could update the hash in the homebrew-core repo.

The [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do though, so if it was intentional you might want to avoid it next time.

**Comment by balthisar** [comment]
@SMillerDev, thanks; it was an "accidental" intentional error trying to get the automated build system set up. It won't happen again.

**Comment by balthisar** [comment]
Update: the PR is live [here](https://github.com/Homebrew/homebrew-core/pull/81646), and will require manual review from the Homebrew team, since the sha change causes the automatic testing to fail.

**Comment by balthisar** [comment]
Update: PR was merged, and after `brew install tidy-html5`,

`/usr/local/Cellar/tidy-html5/5.8.0/bin/tidy -v`

yields

`HTML Tidy for Apple macOS version 5.8.0`

I'll close this as resolved.
