### ISSUE TITLE
Update "as of 2015-January-15" on Github readme

### ISSUE THREAD

**Issue by matkoniecz** [htacg/tidy-html5#975]
> canonical for HTML Tidy as of 2015-January-15.

Is it still canonical?

https://github.com/htacg/tidy-html5#history

**Comment by balthisar** [comment]
"As of" indicates the starting date, so it's still correct. If we change it to today's date, for example, then we should infer that the project belonged somewhere else until now. Am I misunderstanding?

**Comment by ler762** [comment]
On 7/19/21, Jim Derry wrote:
>
> "As of" indicates the starting date, so it's still correct. If we change it
> to today's date, for example, then we should infer that the project belonged
> somewhere else until now. Am I misunderstanding?

I think you've got it.  Although if you want to quibble about the date
it could be Jan 15 or 16
http://tidy.sourceforge.net/  says
16 January 2015
    The HTML Tidy Advocacy Community Group (HTACG) was founded as an
official W3.org community group for the purpose of assuming
responsibility for HTML Tidy, and the W3 transferred their repository
to HTACG today.

**Comment by balthisar** [comment]
I was an American living in China founding HTACG on a European server back then, so I won't ever quibble about what date a particular event occurred on. ;-)

**Comment by matkoniecz** [comment]
> "As of" indicates the starting date, so it's still correct. If we change it to today's date, for example, then we should infer that the project belonged somewhere else until now. Am I misunderstanding?

It is typically used in documentation to mean "when last checked at $DATE, following was true"

Maybe "starting from" would be better for this intended meaning?

**Comment by balthisar** [comment]
Done.
