### ISSUE TITLE
Installation fails on OS X

### ISSUE THREAD

**Issue by forthrin** [htacg/tidy-html5#99]
~$ sudo make install -C build/gmake/
...
xsltproc -o ../../htmldoc/tidy.1 ../../htmldoc/tidy1.xsl ../../htmldoc/tidy-help.xml
../../htmldoc/tidy-help.xml:1: parser error : Document is empty
../../htmldoc/tidy-help.xml:1: parser error : Start tag expected, '<' not found
unable to parse ../../htmldoc/tidy-help.xml
make: *** [../../htmldoc/tidy.1] Error 6

**Comment by geoffmcl** [comment]
The latest development branch is develop-500
$ git checkout develop-500

At this development stage have left out of the cmake script automated document building... so you should have no problem building and installing now... Please check and advise... and close if ok...

As we move towards a 5.0.0 release perhaps some of this will be restored, in which case this can be re-opened if there remains a problem...

**Comment by forthrin** [comment]
Compiles quickly and perfectly. Ticket may be closed. PS! A Homebrew formula would be appreciated!

**Comment by geoffmcl** [comment]
Glad it compiled ok ;=))

Do not know anything about Homebrew formula...

On reading around seems something to do with an
Apple package manager, or ??? and the formula
is brewed in brew? But no idea really...

Can only leave this to an Apple person to
address... maybe in build\apple or something...
if needed in addition to cmake...

**Comment by geoffmcl** [comment]
Please note the latest code is now in the master branch, the default, as we head towards a 5.0.0 release - `$ git checkout master; $ git pull`
