### ISSUE TITLE
Strange <Data Link Escape> (DLE) character in comments (separator) lines of fiile "src/parser.c"?

### ISSUE THREAD

**Issue by jschleus** [htacg/tidy-html5#991]
I just tried to check for possible new misspellings in the development code of "HTML Tidy" (GitHub "next" version; see issue #973) and unexpectedly found that Fossies didn't displayed the probably by two errors affected file `src/parser.c` correctly. The reason is that this file wasn't detected by the used `file` program as a "text" file but as a "data" file.

Looking nearer into the file `src/parser.c` I found after making a hex dump that currently at least the following lines at number
&nbsp;&nbsp;240 (before ` ** MARK: - Decision Making`),
&nbsp;&nbsp;493 (before ` ** MARK: - Information Accumulation`) and
&nbsp;&nbsp;510 (before ` ** MARK: - Fixes and Touchup`)
are containing a for me strangely looking hexadecimal `0x10` resp. Unicode `(U+0010)` character like  here
```
/*****(U+0010)**********************************************************************//*
 ** MARK: - Decision Making
 ***************************************************************************/
```
Is that `<Data Link Escape> (DLE)` character intentional or a possible bug?

**Comment by balthisar** [comment]
There were a total of three of those character. No idea how they got there. Fixed in source, though. Thanks for the report!

**Comment by jschleus** [comment]
Thanks for the quick fix. But you could have also corrected the two following typos right away;-)

&nbsp;&nbsp;"preverve->preserve" at line [1159](https://fossies.org/linux/test/tidy-html5-next.bde0838.210818.tar.gz/tidy-html5-next/src/parser.c?M=1159#l_1159)
&nbsp;&nbsp;"firt->first" at line  [5876](https://fossies.org/linux/test/tidy-html5-next.bde0838.210818.tar.gz/tidy-html5-next/src/parser.c?M=5876#l_5876)
 
But yes, that isn't really important.
