### ISSUE TITLE
How do I make the output less verbose?

### ISSUE THREAD

**Issue by tddschn** [htacg/tidy-html5#996]
I'm `tidy`ing up hundreds of html files with `fd -e html -x /usr/local/bin/tidy -config tidy.conf -ashtml -m {}` and every time tidy is invoked it shows these text:
```
About HTML Tidy: https://github.com/htacg/tidy-html5
Bug reports and comments: https://github.com/htacg/tidy-html5/issues
Official mailing list: https://lists.w3.org/Archives/Public/public-htacg/
Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
Validate your HTML documents: http://validator.w3.org/nu/
Lobby your company to join the W3C: http://www.w3.org/Consortium

Do you speak a language other than English, or a different variant of 
English? Consider helping us to localize HTML Tidy. For details please see 
https://github.com/htacg/tidy-html5/blob/master/README/LOCALIZE.md
```

Flooding my terminal.

Why is `tidy` showing this when it's not invoked with `-help` or `--version`?
I don't think this behavior is appreciated by the end users.

How do I disable output of these text? Tried several config options but non of them works. TIA.

**Comment by balthisar** [comment]
Does `-q` not make it quiet for you?

**Comment by tddschn** [comment]
It does. 😂 My bad.

**Comment by ghost** [comment]
`-q` does work, and so does `--show-info no`. But both silences far more than just `TEXT_GENERAL_INFO` and `TEXT_GENERAL_INFO_PLEA`. I have tried a variety of options, skimmed the source code, etc. My conclusion at the moment is that there is no clean way to get rid of the `TEXT_GENERAL_INFO` and `TEXT_GENERAL_INFO_PLEA` output without also silencing other potentially helpful output, but I would love to be proven wrong.

**Comment by lindes** [comment]
Yeah, something like a `--show-plea no` or `--no-plea` or similar, along with equivalent persistent config options, would be very nice.  In the mean time, I've set `show-info: no` in my `~/.tidyrc`... A little worried about what I might miss that's an info message, but yeah, that's closer to what I want (though I might graduate to `-q` at some point, we'll see.)
